'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {GoogleBankAuth,EXPECTED_EMAIL,SCOPES}=require('../app/bank-auth.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bank-auth-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let url,account=EXPECTED_EMAIL,requests=[];const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).reverse(),decryptString:b=>Buffer.from(b).reverse().toString()};const auth=new GoogleBankAuth({directory:dir,safeStorage,openExternal:async s=>{url=new URL(s);},fetchImpl:async(u,opts)=>{requests.push({url:u,...opts});return new Response(JSON.stringify(u.includes('/token')?{access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,scope:SCOPES.join(' ')}:{email:account,email_verified:true,sub:'mock-subject'}),{status:200});}});auth.configure({installed:{client_id:'mock.apps.googleusercontent.com',client_secret:'mock-secret'}});t.after(()=>auth.cancel());return {auth,dir,requests,get url(){return url;},set account(v){account=v;}};}
async function started(s){const result=s.auth.connect();result.catch(()=>{});for(let i=0;!s.url&&i<100;i++)await new Promise(r=>setTimeout(r,5));assert.ok(s.url);return {result,callback:new URL(s.url.searchParams.get('redirect_uri'))};}
test('desktop PKCE, loopback, state and verified account; persisted refresh resumes without browser (mock Google)',async t=>{const s=fixture(t),{result,callback}=await started(s);assert.equal(s.url.hostname,'accounts.google.com');assert.equal(s.url.searchParams.get('code_challenge_method'),'S256');assert.equal(callback.hostname,'127.0.0.1');callback.search=new URLSearchParams({code:'one-time-code',state:'wrong'});assert.equal((await fetch(callback)).status,400);assert.equal(s.requests.length,0);callback.searchParams.set('state',s.url.searchParams.get('state'));assert.equal((await fetch(callback)).status,200);await result;assert.equal(s.auth.status().account.email,EXPECTED_EMAIL);const form=s.requests[0].body;assert.equal(crypto.createHash('sha256').update(form.get('code_verifier')).digest('base64url'),s.url.searchParams.get('code_challenge'));assert.equal(await s.auth.token(),'test-access');assert.doesNotMatch(fs.readFileSync(s.auth.file,'utf8'),/test-refresh/);s.auth.invalidate();assert.equal(await s.auth.token(),'test-access');assert.equal(s.requests.filter(r=>r.url.includes('/token')).length,2);s.auth.disconnect();assert.equal(s.auth.status().connected,false);assert.equal(s.auth.read().tokens,undefined);});
test('wrong account is blocked even with correct login hint',async t=>{const s=fixture(t);s.account='someone@example.com';const {result,callback}=await started(s);callback.search=new URLSearchParams({code:'code',state:s.url.searchParams.get('state')});await fetch(callback);await assert.rejects(result,/다른 계정/);assert.equal(s.auth.read().tokens,undefined);await assert.rejects(s.auth.token(),/다른 계정/);});
test('cancellation while Google replies cannot restore credentials',async t=>{const s=fixture(t);let resume,entered=false;s.auth.verify=async()=>{entered=true;await new Promise(r=>resume=r);return {email:EXPECTED_EMAIL,sub:'test'};};const {result,callback}=await started(s);callback.search=new URLSearchParams({code:'code',state:s.url.searchParams.get('state')});const request=fetch(callback).catch(()=>{});for(let i=0;!entered&&i<100;i++)await new Promise(r=>setTimeout(r,5));assert.ok(entered);s.auth.cancel();resume();await assert.rejects(result,/취소/);await request;assert.equal(s.auth.read().tokens,undefined);});
test('unavailable OS encryption and expired refresh require action; no token fallback',async t=>{const s=fixture(t);s.auth.safeStorage.isEncryptionAvailable=()=>false;assert.throws(()=>s.auth.write({tokens:{refresh_token:'secret'}}),/보안 저장소/);s.auth.safeStorage.isEncryptionAvailable=()=>true;s.auth.write({...s.auth.read(),account:{email:EXPECTED_EMAIL},tokens:{refresh_token:'expired',expiresAt:0}});s.auth.fetch=async()=>new Response(JSON.stringify({error:'invalid_grant'}),{status:400});await assert.rejects(s.auth.token(),/다시 연결/);assert.equal(s.auth.status().connected,false);});
