'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {localServer}=require('./shared-bank-local-server.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{ProjectStore}=require('../app/store.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{BankMaintenance}=require('../app/bank-maintenance.cjs'),M=require('../app/bank-model.cjs'),T=require('../app/bank-question-types.cjs');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64');
test('type-only native upload keeps body/solution/scores/files/confirmations and supports samples, resume and current-only retry',async t=>{
 const x=await localServer(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bank-types-')),banks=[];t.after(async()=>{for(const b of banks)b.close();await x.close();fs.rmSync(dir,{recursive:true,force:true});});
 const make=u=>{const auth=x.auth(u),store=new ProjectStore(path.join(dir,u)),bank=new QuestionBank({directory:store.dataDir,store,storage:new SharedBankStorage({auth,fetchImpl:x.fetch}),auth,appVersion:'test',buildDocx:async(_,file)=>fs.writeFileSync(file,'unchanged DOCX'),preview:async(_,file)=>fs.writeFileSync(file,png)});bank.wake=()=>{};bank.autonomous=false;banks.push(bank);return bank;};
 const sqlErrors=[],query=x.db.query.bind(x.db);x.db.query=async(...args)=>{try{return await query(...args);}catch(e){sqlErrors.push(e.message);throw e;}};const a=make(x.A),b=make(x.B);await a.storage.invite('teacher-b@example.test');await a.root();await b.root();const source=path.join(dir,'source.png');fs.writeFileSync(source,png);
 for(const body of ['직각삼각형의 넓이는?','두 각의 크기는?','다음 증명하는 과정의 (가)에 들어갈 식은?']){let project=b.store.create(source);project=b.store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});project=b.store.updateProblem(project.id,project.problems[0].id,p=>{p.original={id:M.uuid(),kind:'original',body,choices:['① 1','② 2'],answer:'②',solution:'기존 확정 풀이',include:true,approval:{status:'approved'}};p.recognition={originalNumber:'17',confirmed:true};});await b.enqueue(project.id,[project.problems[0].original.id]);await b.pump();assert.equal(b.state.jobs.at(-1).status,'complete');await b.storage.visibility(b.state.jobs.at(-1).id,'shared_pending','테스트');}
 let aiCalls=0;const m=new BankMaintenance({bank:a,getBridge:()=>({run:()=>{aiCalls++;throw Error('AI forbidden');}})});t.after(()=>m.close());const j=await m.plan({rules:['types']});assert.equal(j.items.length,3);assert.equal(j.estimate.aiRequestsMax,0);await m.sample(j.id);assert.ok(j.items.every(i=>i.status==='staged'),JSON.stringify(j.items.map(i=>({status:i.status,error:i.error}))));assert.equal(new Set(j.items.map(i=>i.typePlan.types[0].id)).size,3);
 // An unrelated confirmation can change without a review_version increment.
 const conflict=j.items[0];await x.db.exec('reset role');await x.db.query("update bank_catalog set confirmed=confirmed||'{\"scopeEvidence\":{\"independent\":true}}'::jsonb where revision_id=$1",[conflict.baseId]);
 const resumed=new BankMaintenance({bank:a});t.after(()=>resumed.close());await resumed.start(j.id);await resumed.promise;const final=resumed.job(j.id);assert.equal(final.items[0].status,'conflict');assert.equal(final.items.filter(i=>i.status==='complete').length,2,JSON.stringify({items:final.items.map(i=>({status:i.status,error:i.error})),sqlErrors}));assert.equal(aiCalls,0);
 for(const i of final.items.filter(i=>i.status==='complete')){const [now]=await a.storage.rows('bank_catalog','revision_id=eq.'+i.resultId);assert.deepEqual(now.content,i.before.content);assert.deepEqual(now.confirmed,i.before.confirmed);assert.deepEqual(now.metadata.difficulty,i.before.metadata.difficulty);assert.deepEqual(now.metadata.source,i.before.metadata.source);assert.equal(T.primaryKey(now),i.typePlan.types[0].id);for(const f of now.files.filter(f=>!['data','commit'].includes(f.role)))assert.ok(i.before.files.some(old=>old.role===f.role&&old.sha256===f.sha256));const filtered=await a.storage.rpc('bank_search_current',{s:x.S,filters:{type:i.typePlan.types[0].name}});assert.ok(filtered.some(r=>r.question_id===i.questionId));}
 const retry=await resumed.plan({rules:['types']});assert.equal(retry.items.length,1);assert.deepEqual(retry.items[0].before.confirmed.scopeEvidence,{independent:true});await resumed.sample(retry.id);await resumed.start(retry.id);await resumed.promise;assert.equal(retry.status,'complete',JSON.stringify(retry.items.map(i=>i.error)));assert.equal((await resumed.plan({rules:['types']})).items.length,0);assert.equal(aiCalls,0);
});
test('SQL commit guard independently rejects stale confirmations and non-type data changes',async t=>{
 const x=await localServer();t.after(()=>x.close());await x.db.exec('reset role');
 const q=M.uuid(),base=M.uuid(),candidate=M.uuid(),entry=M.uuid(),job=M.uuid();
 const metadata={classification:{types:[],suggested:null,confirmed:null,solutions:[]},difficulty:{aiScore:'4.2'},source:{school:'기존 출처'}},content={body:'넓이는?',choices:[],answer:'2',solution:'기존 풀이'},confirmed={difficulty:'4.2'},files=[{role:'docx',sha256:'same',size:100}];
 await x.db.query('insert into bank_questions(id,space_id,owner_id,owner_email) values($1,$2,$3,$4)',[q,x.S,x.A,'animochoi@gmail.com']);await x.db.query('insert into bank_revisions(id,question_id,actor_id,committed) values($1,$2,$3,true)',[base,q,x.A]);await x.db.query("insert into bank_entries(id,space_id,name,kind,owner_id) values($1,$2,'test','file',$3)",[entry,x.S,x.A]);await x.db.query('insert into bank_catalog(revision_id,space_id,question_id,commit_id,metadata,content,confirmed,files) values($1,$2,$3,$4,$5,$6,$7,$8)',[base,x.S,q,entry,metadata,content,confirmed,files]);
 const auth=x.auth(x.A);await auth.request('/rest/v1/rpc/bank_maintenance_job',{method:'POST',body:{s:x.S,j:job,specification:{rules:['types']}}});await auth.request('/rest/v1/rpc/bank_maintenance_stage',{method:'POST',body:{j:job,b:base,r:candidate,expected:0,report_value:{rules:['types'],typeExpected:{metadata,content,confirmed,files}}}});
 await x.db.exec('reset role');await x.db.query('insert into bank_revisions(id,question_id,parent_id,actor_id) values($1,$2,$3,$4)',[candidate,q,base,x.A]);const incoming=T.apply(metadata,T.infer({content,metadata}));await x.db.query('insert into bank_catalog(revision_id,space_id,question_id,commit_id,metadata,content,confirmed,files) values($1,$2,$3,$4,$5,$6,$7,$8)',[candidate,x.S,q,entry,incoming,content,{},files]);
 await x.db.query("update bank_catalog set confirmed=confirmed||'{\"scopeEvidence\":{\"concurrent\":true}}'::jsonb where revision_id=$1",[base]);await assert.rejects(x.db.query('update bank_revisions set committed=true where id=$1',[candidate]),/計画|계획 이후/);await x.db.query('update bank_catalog set confirmed=$2 where revision_id=$1',[base,confirmed]);
 const bad=structuredClone(incoming);bad.difficulty.aiScore='9.0';await x.db.query('update bank_catalog set metadata=$2 where revision_id=$1',[candidate,bad]);await assert.rejects(x.db.query('update bank_revisions set committed=true where id=$1',[candidate]),/외 내용 변경/);await x.db.query('update bank_catalog set metadata=$2,files=$3 where revision_id=$1',[candidate,incoming,[{role:'docx',sha256:'changed',size:100}]]);await assert.rejects(x.db.query('update bank_revisions set committed=true where id=$1',[candidate]),/DOCX/);
 await x.db.query('update bank_catalog set files=$2 where revision_id=$1',[candidate,files]);await x.db.query('update bank_revisions set committed=true where id=$1',[candidate]);const saved=(await x.db.query('select confirmed,content from bank_catalog where revision_id=$1',[candidate])).rows[0];assert.deepEqual(saved.confirmed,confirmed);assert.deepEqual(saved.content,content);
});
