const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {localServer}=require('./shared-bank-local-server.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{ProjectStore}=require('../app/store.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{BankMaintenance}=require('../app/bank-maintenance.cjs'),M=require('../app/bank-model.cjs');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64');
test('persistent maintenance: admin edits teacher revision, sample/apply, idempotence, backups, undo and CAS with actual SQL',async t=>{
 const x=await localServer(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'bank-maint-')),banks=[];t.after(async()=>{for(const b of banks)b.close();await x.close();fs.rmSync(dir,{recursive:true,force:true});});
 const make=u=>{const auth=x.auth(u),storage=new SharedBankStorage({auth,fetchImpl:x.fetch}),store=new ProjectStore(path.join(dir,u)),bank=new QuestionBank({directory:store.dataDir,store,storage,auth,appVersion:'test',buildDocx:async(input,file)=>fs.writeFileSync(file,'MOCK DOCX '+input.questionId),preview:async(d,f)=>fs.writeFileSync(f,png)});bank.wake=()=>{};bank.autonomous=false;banks.push(bank);return bank;};
 const a=make(x.A),b=make(x.B);await a.storage.invite('teacher-b@example.test');await a.root();await b.root();
 const source=path.join(dir,'2026학년도 테스트중 중2 2학기 중간.png');fs.writeFileSync(source,png);let p=b.store.create(source);p=b.store.addRegion({projectId:p.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});p=b.store.updateProblem(p.id,p.problems[0].id,v=>{v.original={id:M.uuid(),kind:'original',body:'17. $\\frac{13}{2}$, $\\sqrt{2}$, $\\angle ABC$',choices:['① 1','② 2'],answer:'②',solution:'풀이',include:true,approval:{status:'approved'},diagram:require('./workflow-fixtures.cjs').recognition().observedDiagram};v.recognition={originalNumber:'17',confirmed:true};});
 await b.enqueue(p.id,[p.problems[0].original.id]);await b.pump();const first=b.state.jobs[0];assert.equal(first.status,'complete',first.error);await b.storage.visibility(first.id,'shared_pending','관리자 점검');
 const m=new BankMaintenance({bank:a});t.after(()=>m.close());
 await assert.rejects(new BankMaintenance({bank:b}).plan(),/관리자/);
 await assert.rejects(b.storage.rpc('bank_maintenance_job',{s:x.S,j:M.uuid(),specification:{}}));
 const j=await m.plan({rules:['source','render','integrity']});assert.equal(j.items.length,1);assert.equal(j.estimate.aiRequestsMax,0);assert.equal((await a.storage.search()).length,1);
 await m.sample(j.id);assert.equal(j.items[0].status,'staged',j.items[0].error);assert.equal((await a.storage.search()).length,1);assert.match(await m.preview(j.id,first.questionId),/^data:image\/png/);
 await m.start(j.id);await m.promise;assert.equal(j.status,'complete',JSON.stringify(j.items));const latest=(await a.storage.rpc('bank_search_current',{s:x.S}))[0];assert.equal(latest.question_id,first.questionId);assert.notEqual(latest.revision_id,first.id);assert.equal(latest.metadata.source.originalNumber,'17');assert.equal((await a.storage.search()).length,2);

 // Old writers cannot drop new extension fields even when they own the question.
 await x.db.exec('reset role');const stale=M.uuid(),entry=M.uuid();await x.db.query('insert into bank_revisions(id,question_id,parent_id,actor_id) values($1,$2,$3,$4)',[stale,first.questionId,latest.revision_id,x.B]);await x.db.query("insert into bank_entries(id,space_id,name,kind,owner_id) values($1,$2,'old-client','file',$3)",[entry,x.S,x.B]);await x.db.query("insert into bank_catalog(revision_id,space_id,question_id,commit_id,metadata,content,files) values($1,$2,$3,$4,$5,'{}','[]')",[stale,x.S,first.questionId,entry,{source:{school:'old'}}]);await assert.rejects(x.db.query('update bank_revisions set committed=true where id=$1',[stale]),/업데이트 필요/);
 const repeat=await m.plan({rules:['source','render','integrity']});assert.equal(repeat.items.length,0,'unchanged processed data must be skipped');
 const record=(await a.storage.rows('bank_questions','id=eq.'+first.questionId))[0];assert.equal(record.owner_id,x.B);await assert.rejects(b.storage.rpc('bank_maintenance_stage',{j:j.id,b:first.id,r:M.uuid(),expected:0,report_value:{}}));assert.equal((await b.storage.rows('bank_maintenance_jobs')).length,0);
 const undo=await m.undo(j.id);assert.equal(undo.items[0].status,'staged',undo.items[0].error);await m.start(undo.id);await m.promise;assert.equal(undo.status,'complete',JSON.stringify(undo.items));assert.equal((await a.storage.search()).length,3);
 // Restart keeps the pending plan and staged snapshot. A review made afterwards blocks it.
 const conflict=await m.plan({rules:['render']});await m.sample(conflict.id);assert.equal(conflict.items[0].status,'staged',conflict.items[0].error);const restart=new BankMaintenance({bank:a});t.after(()=>restart.close());assert.ok((await restart.status()).jobs.some(k=>k.id===conflict.id));
 const r=conflict.items[0].baseId;await a.storage.review({revisionId:r,patch:{difficulty:'6.5',sharingAllowed:true},reason:'작업 중 검수',expected:conflict.items[0].reviewVersion});await restart.start(conflict.id);await restart.promise;assert.equal(restart.job(conflict.id).items[0].status,'conflict');assert.equal((await a.storage.search()).length,3);
 // Already committed response is recovered without a new version on retry.
 const old=m.job(j.id);old.items[0].status='failed';old.status='failed';await m.start(j.id);await m.promise;assert.equal(old.items[0].status,'complete');assert.equal((await a.storage.search()).length,3);
});
