'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {BankAnalysis}=require('../app/bank-analysis.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{ProjectStore}=require('../app/store.cjs'),{FakeAuth,MemoryDrive}=require('./bank-fixtures.cjs'),C=require('../app/curriculum.js');
const {printedNumber,compareSource,sourceDetails}=require('../app/bank-source-order.cjs');
test('printed source numbers preserve labels and natural source order separately from assigned labels',()=>{
 assert.equal(printedNumber({kind:'original'},{recognition:{sourceQuestionNumber:'17.'}}),'17');assert.equal(printedNumber({kind:'original'},{recognition:{originalNumber:'서술형3'}}),'서술형3');assert.equal(printedNumber({kind:'original'},{recognition:{originalNumber:'3-(2)'}}),'3-(2)');assert.equal(printedNumber({kind:'variant'},{recognition:{originalNumber:'17'}}),null);
 const rows=['10','2','1'].map(n=>({metadata:{source:{documentId:'one',originalNumber:n}}}));assert.deepEqual(rows.sort(compareSource).map(x=>x.metadata.source.originalNumber),['1','2','10']);
 const p1={id:'a',label:'문제 9',regions:[{sourceId:'primary',page:1,x:.05,y:.1}]},p2={id:'b',label:'문제 1',regions:[{sourceId:'primary',page:1,x:.55,y:.1}]};assert.equal(sourceDetails({problems:[p2,p1]},p1,{kind:'original'},'source').originalOrder,1);
});
test('AI recommendations reuse saved content, cache, preserve confirmed values, and recover failures without inventing results',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bank-analysis-')),store=new ProjectStore(dir),file=path.join(dir,'source.png');fs.writeFileSync(file,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64'));let project=store.create(file);project=store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+fs.readFileSync(file).toString('base64')});project=store.updateProblem(project.id,project.problems[0].id,p=>{p.recognition={originalNumber:'17',domains:['geometry']};p.original={id:'question-test',kind:'original',body:'평행사변형의 두 대각선',choices:[],answer:'2',solution:'평행사변형의 두 대각선은 서로를 이등분한다.',approval:{status:'approved'}};});
 const bank=new QuestionBank({directory:dir,store,storage:new MemoryDrive(),auth:new FakeAuth(),appVersion:'test'});bank.wake=()=>{};t.after(()=>{bank.close();fs.rmSync(dir,{recursive:true,force:true});});const leaf=C.leaves.find(n=>n.title.includes('평행사변형'));
 let calls=0,fail=false,stale=false,nullOnce=false;const analyzer=new BankAnalysis({store,getSettings:()=>({model:'mock'}),getBridge:()=>({run:async req=>{calls++;assert.equal(req.images.length,0,'확정 풀이의 난이도 평가는 원본 그림 재대조를 요구하지 않는다');assert.equal(req.purpose,'bank_metadata');assert.equal(JSON.parse(req.text).question.originalNumber,'17');assert.equal(JSON.parse(req.text).assessmentAssumptions.finalSolutionIsCorrect,true);if(fail)throw Error('mock offline');if(stale)store.updateProblem(project.id,project.problems[0].id,p=>p.original.body+=' 변경');const score=nullOnce?null:'4.7';nullOnce=false;return {result:{types:[],typeReason:"모의 응답: 요구 작업 유형 근거 부족",originalNumber:'17',primaryUnitId:leaf.id,relatedUnitIds:[],conditionUnitIds:[],solutions:[{label:'평행사변형 성질',unitIds:[leaf.id],concepts:['대각선의 이등분'],lastUnitId:leaf.id}],score,assessment:score===null?null:require('./fixtures/access-assessment.cjs').accessAssessment('S1','R1'),reason:'저장된 풀이의 개념과 단계 수에 따른 잠정 추정. 기준문항 없음.'}};}})});
 const args={projectId:project.id,questionIds:['question-test']};{const outcome=await analyzer.run(bank,args);assert.equal(outcome.analyzed,1,JSON.stringify(outcome));};let item=Object.values(bank.state.items)[0];assert.equal(item.metadata.difficulty.aiScore,'4.7');assert.equal(item.metadata.difficulty.userScore,null);assert.equal(item.metadata.classification.primaryUnit.id,leaf.id);assert.equal((await analyzer.run(bank,args)).reused,1);assert.equal(calls,1);
 bank.edit([item.id],{userScore:'6.5',primaryUnit:'사용자 확정 단원'});store.updateProblem(project.id,project.problems[0].id,p=>{p.original.solution+=' 다른 풀이';p.original.checks={scope:{status:'incompatible'}};});nullOnce=true;{const outcome=await analyzer.run(bank,args);assert.equal(outcome.analyzed,1,JSON.stringify(outcome));};assert.equal(calls,3,'AI가 그림 확인을 이유로 점수를 비우면 한 번만 다시 요청한다');assert.equal(item.metadata.difficulty.criteriaVersion,require('../app/difficulty-assessment.cjs').version);assert.equal(item.metadata.difficulty.userScore,'6.5');assert.equal(item.metadata.classification.primaryUnit.name,'사용자 확정 단원');
 store.updateProblem(project.id,project.problems[0].id,p=>p.original.solution+=' 변경');fail=true;assert.equal((await analyzer.run(bank,args)).errors.length,1);assert.equal(item.metadata.difficulty.aiScore,null);assert.equal(item.metadata.difficulty.userScore,'6.5');fail=false;stale=true;assert.equal((await analyzer.run(bank,args)).errors.length,1);assert.equal(item.metadata.difficulty.aiScore,null);
});
test('unknown curriculum IDs and scores without solutions are rejected, not replaced with default values',()=>{const {checked}=require('../app/bank-analysis.cjs');const value={types:[],typeReason:"모의 응답: 요구 작업 유형 근거 부족",originalNumber:null,primaryUnitId:null,relatedUnitIds:[],conditionUnitIds:[],solutions:[],score:null,reason:'풀이 없음'};assert.equal(checked(value,false).score,null);assert.throws(()=>checked({...value,primaryUnitId:'imaginary'},true),/소단원/);assert.throws(()=>checked({...value,score:'5.0'},false),/풀이/);});

test('whole source import chooses latest authorized original revisions and restores original order, not upload order',async()=>{
 const {importExam}=require('../app/bank-transfer.cjs'),{randomUUID}=require('node:crypto');const server='https://test.supabase.co',spaceId=randomUUID(),documentId=randomUUID(),source=randomUUID(),calls=[],rows=[];
 for(const number of ['10','2','1'])rows.push({question_id:randomUUID(),revision_id:randomUUID(),commit_id:randomUUID(),created_at:'2026-01-01',metadata:{source:{documentId,originalNumber:number},relations:{}}});
 rows.push({...rows[1],revision_id:randomUUID(),created_at:'2026-02-01'});rows.push({...rows[0],question_id:randomUUID(),revision_id:randomUUID(),metadata:{source:{documentId},relations:{originalQuestionId:rows[0].question_id}}});rows.push({...rows[0],question_id:randomUUID(),revision_id:randomUUID(),metadata:{source:{documentId:source},relations:{}}});
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bank-order-'));try{const bank={auth:{config:()=>({url:server,spaceId})},state:{cache:{},items:{},bindings:{}},save(){},store:{projectDir:id=>path.join(dir,id),write:p=>p},storage:{rows:async(_,filter)=>rows.filter(r=>r.revision_id===filter.split('eq.')[1]),search:async()=>rows},restore:async id=>{const row=rows.find(r=>r.revision_id===id);calls.push(row);return{project:{id:randomUUID(),source:{name:'test',path:''},sources:[{id:'primary',name:'test',path:''}],problems:[{id:randomUUID(),regions:[],cropPaths:[],variants:[],original:{id:randomUUID(),body:row.metadata.source.originalNumber}}]}};}};const result=await importExam(bank,rows[0].revision_id);assert.deepEqual(result.problems.map(p=>p.original.body),['1','2','10']);assert.equal(calls[1].revision_id,rows[3].revision_id);assert.equal(calls.length,3);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
