'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('../app/bank-exam-model.cjs'),C=require('../app/curriculum.js'),legacy=require('./fixtures/bulk-composition-saved.json').rows,D=require('../app/difficulty-assessment.cjs'),saved=legacy.map(c=>({...c,metadata:{...c.metadata,difficulty:{...c.metadata.difficulty,criteriaVersion:D.version}}}));
const units=C.leaves.filter(n=>n.grade==='중2').map(n=>n.id),rules=extra=>({count:10,units,schools:[],profile:{low:20,middle:80,high:0,targetAverage:5},...extra});
function item(i,{score=5,type='type'+i,school='A',visibility='shared_pending',cls={}}={}){return {question_id:'q'+i,revision_id:'r'+i,visibility,metadata:{source:{school},content:{responseType:'single_choice'},classification:{primaryUnit:{id:'m2-6.3'},status:'ai_suggested',types:type?[{id:type,name:type}]:[],...cls},difficulty:{aiScore:score,criteriaVersion:D.version}}};}
test('saved production snapshot: 50 recommended pending questions, 5/44/1 distribution under the new grouping, 49 scoped candidates and diverse complete paper',()=>{
 assert.deepEqual(M.difficultySummary(legacy).counts,{low:0,middle:0,high:0,deferred:0,unknown:50},'saved legacy scores are excluded; remaining selection checks use explicit synthetic v5 fixture scores');assert.equal(saved.length,50);assert.ok(saved.every(c=>c.visibility==='shared_pending'));assert.deepEqual(M.difficultySummary(saved).counts,{low:5,middle:44,high:1,deferred:0,unknown:0});const result=M.selectQuestions(saved,rules());assert.equal(result.eligible,49);assert.equal(result.items.length,10);assert.equal(result.diversity.repeated,0);assert.equal(result.diversity.knownTypes,10);assert.ok(!Object.keys(result.reasons).some(x=>/검수|확인 필요/.test(x)));
 const impossible=M.selectQuestions(saved,rules({profile:{low:0,middle:20,high:80,targetAverage:5}}));assert.equal(impossible.complete,false);assert.deepEqual(impossible.shortages.find(s=>s.label==='상'),{label:'상',requested:8,available:1,missing:7});
});
test('saved review status, missing teacher flags and unknown task types never gate otherwise eligible recommendations',()=>{
 for(const status of ['approved','shared_pending','private']){const c=item(status,{visibility:status,type:null});const r=M.selectQuestions([c],rules({count:1,profile:{low:0,middle:100,high:0,targetAverage:5},status:'approved',avoidSameType:true}));assert.equal(r.complete,true);assert.equal(r.diversity.unknownTypes,1);assert.equal(r.diagnostics.limitedEvidence,1);}
});
test('real missing classification or numeric scores remain explicit unknowns; known out-of-scope concepts are not relaxed',()=>{
 const missing=item('missing');missing.metadata.classification={};const unscored=item('unscored',{score:null});const outside=item('outside',{cls:{primaryUnit:{id:C.leaves.at(-1).id}}});const original=JSON.stringify([missing,unscored,outside]);const r=M.inspectCandidates([missing,unscored,outside],rules());assert.equal(r.eligible.length,0);assert.equal(r.diagnostics.scopeUnknown,1);assert.equal(r.diagnostics.schoolScopeDifficulty.counts.unknown,1);assert.equal(JSON.stringify([missing,unscored,outside]),original);
});
test('final numeric scores determine buckets and preserve legacy teacher bands',()=>{
 const rows=[item('a',{score:3.9}),item('b',{score:4}),item('c',{score:6.5}),item('d',{score:8}),item('e',{score:null})];rows[0].confirmed={difficultyBand:'아주어려움'};rows[2].metadata.difficulty.calibratedScore='7.0';rows[3].confirmed={difficulty:'5.5'};const before=JSON.stringify(rows),summary=M.difficultySummary(rows);assert.deepEqual(summary.counts,{low:0,middle:4,high:0,deferred:0,unknown:1});assert.equal(summary.labelDisagreements,1);assert.equal(summary.sources['기존 적용 보정'],undefined);assert.equal(summary.sources['교사 검수'],1);assert.equal(JSON.stringify(rows),before);
});
test('same unit and response format allow distinct task types; repeated or unknown types still fill required count',()=>{
 const data=[item(1,{type:'distance'}),item(2,{type:'distance'}),item(3,{type:'angle'}),item(4,{type:null})];const r=M.selectQuestions(data,rules({count:3,profile:null}));assert.equal(r.items.length,3);assert.equal(r.diversity.repeated,0);assert.equal(r.diversity.knownTypes,2);assert.equal(r.diversity.unknownTypes,1);
 const forced=M.selectQuestions(data.slice(0,2),rules({count:2,profile:null}));assert.equal(forced.items.length,2);assert.equal(forced.diversity.repeated,1);
});
test('diversity optimization respects hard score/format counts and does not strand a feasible complete combination',()=>{
 const data=[item(1,{score:8.1,type:'X'}),item(2,{score:8.5,type:'Y'}),item(3,{score:5,type:'X'}),item(4,{score:5,type:'Y'})];data[1].metadata.content.responseType='proof';data[3].metadata.content.responseType='proof';const r=M.selectQuestions(data,rules({count:2,profile:{low:0,middle:50,high:50,targetAverage:6.5},types:{선택형:1,서술형:1}}));assert.equal(r.items.length,2);assert.equal(r.diversity.repeated,0);assert.equal(r.items.filter(x=>M.compositionBand(x)==='high').length,1);assert.equal(r.items.filter(x=>M.responseType(x.metadata)==='서술형').length,1);
});
test('small exhaustive oracle verifies maximal type variety under simultaneous bucket and format quotas',()=>{
 let seed=713;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};
 for(let trial=0;trial<25;trial++){const data=Array.from({length:8},(_,i)=>{const c=item(i,{score:random()<.5?5:8.2,type:'T'+Math.floor(random()*4)});if(random()<.5)c.metadata.content.responseType='proof';return c;});let best=Infinity;for(let mask=0;mask<256;mask++){const selected=data.filter((_,i)=>mask>>i&1);if(selected.length!==4||selected.filter(c=>M.compositionBand(c)==='high').length!==2||selected.filter(c=>M.responseType(c.metadata)==='서술형').length!==2)continue;best=Math.min(best,M.diversitySummary(selected).repeated);}const r=M.selectQuestions(data,rules({count:4,profile:{low:0,middle:50,high:50,targetAverage:6.5},types:{선택형:2,서술형:2}}));assert.equal(r.complete,Number.isFinite(best));if(r.complete)assert.equal(r.diversity.repeated,best,'trial '+trial);}
});
test('school switching and retry refresh candidates with no hidden status filter in the loader',async()=>{
 const {loadCompositionCandidates}=await import('../web-bank/composition-summary.js');let calls=0;const rpc=async(name,args)=>{assert.equal(name,'bank_search_current');assert.deepEqual(args.filters,{});calls++;return [item(calls)];};assert.notDeepEqual(await loadCompositionCandidates(rpc,'space'),await loadCompositionCandidates(rpc,'space'));assert.equal(calls,2);
 for(const school of ['학교A','학교B']){const r=M.selectQuestions(saved,rules({count:4,schools:[school],profile:{low:25,middle:75,high:0,targetAverage:5}}));assert.equal(r.items.length,4);assert.ok(r.items.every(c=>c.metadata.source.school===school));}
});
