'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{PassThrough}=require('node:stream'),{EventEmitter}=require('node:events'),crypto=require('node:crypto');
const {ClaudeBridge,environment,selection,resultEnvelope}=require('../app/claude.cjs');
const {ensureRuntime}=require('../app/claude-runtime.cjs');
const schema={type:'object',properties:{answer:{type:'string'}},required:['answer'],additionalProperties:false};
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'exam-claude-'));let calls=[];const spawnImpl=(exe,args,options)=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{queueMicrotask(()=>child.emit('close',null));};let input='';child.stdin.on('data',b=>input+=b);child.stdin.on('finish',()=>{calls.push({exe,args,options,input});queueMicrotask(()=>{child.stdout.write(args[0]==='auth'?JSON.stringify({loggedIn:true,authMethod:'claude.ai'}):JSON.stringify({type:'result',subtype:'success',is_error:false,result:'{"answer":"3"}',num_turns:1})+'\n');child.emit('close',0);});});return child;};return {root,calls,bridge:new ClaudeBridge({cwd:root,requestsDir:path.join(root,'requests'),executable:'claude.exe',spawnImpl})};}
test('Claude uses explicit subscription login, validates selections and structured errors',()=>{assert.equal(environment({ANTHROPIC_API_KEY:'secret',ANTHROPIC_BASE_URL:'elsewhere',CLAUDE_CODE_OAUTH_TOKEN:'secret',PATH:'ok'}).ANTHROPIC_API_KEY,undefined);assert.throws(()=>selection({model:'injected',effort:'high'}));assert.deepEqual(selection({model:'sonnet',effort:'medium'}),{model:'sonnet',effort:'medium'});assert.throws(()=>resultEnvelope('{"type":"result","subtype":"error_max_turns","is_error":true,"errors":["failed"]}'),/failed/);});
test('Claude sends selected images and large schema via stdin, disables tools and session storage',async()=>{const f=fixture();try{const img=path.join(f.root,'crop.png');fs.writeFileSync(img,Buffer.from([137,80,78,71]));const result=await f.bridge.run({context:{id:'p'},text:'추가 요청',model:'sonnet',effort:'medium',images:[img],execution:{instructions:'검수 규칙',schema}});assert.equal(result.result.answer,'3');assert.equal(result.provider,'claude');const call=f.calls[1],message=JSON.parse(call.input);assert.ok(call.args.includes('--no-session-persistence'));assert.ok(call.args.includes('--safe-mode'));assert.equal(call.args[call.args.indexOf('--tools')+1],'');assert.ok(message.message.content[0].text.includes('추가 요청'));assert.equal(message.message.content[1].source.data,fs.readFileSync(img).toString('base64'));assert.equal(f.bridge.active.size,0);assert.equal(call.options.shell,false);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('Claude rejects an image outside selected project and leaves no active job',async()=>{const f=fixture();try{await assert.rejects(f.bridge.run({context:{id:'p'},text:'test',model:'sonnet',effort:'high',images:[__filename],execution:{instructions:'rules',schema}}),/프로젝트 내부/);assert.equal(f.bridge.active.size,0);assert.equal(f.calls.length,1);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('Claude cancellation during auth prevents inference',async()=>{const f=fixture();try{let ready;f.bridge.getAccount=()=>new Promise(resolve=>ready=resolve);const run=f.bridge.run({context:{id:'p'},text:'test',model:'opus',effort:'high',execution:{instructions:'rules',schema}});await f.bridge.cancel('p');ready({available:true});await assert.rejects(run,/취소/);assert.equal(f.calls.length,0);assert.equal(f.bridge.active.size,0);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('Claude runtime verifies size/checksum, deduplicates setup and recovers from failure',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'exam-claude-runtime-'));const bytes=Buffer.from('binary');const release={version:'2.1.284',url:'https://downloads.claude.ai/claude-code-releases/2.1.284/win32-x64/claude.exe',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),size:bytes.length};try{let calls=0;const fetchImpl=async()=>{calls++;return{ok:true,body:[bytes]};};const opts={directory:root,env:{},release,fetchImpl};const [a,b]=await Promise.all([ensureRuntime(opts),ensureRuntime(opts)]);assert.equal(a,b);assert.equal(calls,1);assert.deepEqual(fs.readFileSync(a),bytes);fs.unlinkSync(a);await assert.rejects(ensureRuntime({...opts,release:{...release,sha256:'0'.repeat(64)}}),/무결성/);assert.equal(fs.readdirSync(root).length,0);await ensureRuntime(opts);assert.ok(fs.existsSync(a));}finally{fs.rmSync(root,{recursive:true,force:true});}});
