'use strict';
if(process.versions.electron)require('./desktop-workflow.cjs');else{
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'..'),{_electron}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{
 const dir=fs.mkdtempSync(path.join(root,'data/validation/batch-')),source=path.join(dir,'source.png');await require('sharp')({create:{width:900,height:1000,channels:3,background:'white'}}).png().toFile(source);
 const app=await _electron.launch({executablePath:require('electron'),args:[__filename],env:{...process.env,EXAM_DATA_DIR:dir,EXAM_TEST_SOURCE:source}}),page=await app.firstWindow();page.setDefaultTimeout(25000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const boot=()=>page.evaluate(()=>window.exam.boot()),idle=()=>page.waitForFunction(()=>document.querySelector('#batchStop').hidden&&document.querySelector('#cancelChat').hidden);
 async function crop(top,bottom){const b=await page.locator('#selectionLayer').boundingBox();await page.mouse.move(b.x+b.width*.1,b.y+b.height*top);await page.mouse.down();await page.mouse.move(b.x+b.width*.8,b.y+b.height*bottom,{steps:5});await page.mouse.up();await page.waitForFunction(()=>!document.querySelector('#fitWidth').disabled);}
 async function start(task){await page.locator('#batch-'+task).click();if(task==='recognition'){await page.waitForFunction(()=>document.querySelectorAll('.batch-crop-previews img').length===document.querySelectorAll('.batch-problem-choice').length);}await page.locator('#batchStart').click();await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='일괄 작업 결과'&&document.querySelector('#mainDialog').open);await idle();}
 async function close(){await page.locator('#closeDialog').click();}
 try{
  await page.waitForFunction(()=>document.querySelector('#aiModel').options.length===2);await page.locator('#importSource').click();await page.locator('#confirmImportScope').click();await page.waitForFunction(()=>!document.querySelector('#fitWidth').disabled);
  assert.equal(await page.locator('#batchToolbar').evaluate(n=>n.nextElementSibling.classList.contains('document-bar')),true);assert.equal(await page.locator('#batch-regions').getAttribute('aria-current'),'step');assert.match(await page.locator('#batch-recognition').innerText(),/전체 인식/);assert.equal(await page.locator('#collectRegions').isChecked(),true);await crop(.05,.28);await crop(.4,.65);
  let data=await boot();assert.equal(data.project.problems.length,2);assert.equal(await app.evaluate(()=>global.__requests.length),0);assert.equal(await page.locator('#mainDialog').evaluate(d=>d.open),false);
  await page.reload();await page.waitForFunction(()=>!document.querySelector('#fitWidth').disabled);assert.equal((await boot()).project.problems.length,2);
  await app.evaluate(()=>{global.__failNext=true;global.__recognitionIssues=[{text:'빗금 확인 필요',kind:'reading',location:{regionIndex:0,description:'변 위의 표식'}}];});await start('recognition');data=await boot();assert.equal(data.project.problems.filter(p=>p.recognition).length,1);assert.match(await page.locator('#dialogBody').innerText(),/失败|실패 1/);await close();
  await app.evaluate(()=>global.__recognitionIssues=null);const before=await app.evaluate(()=>global.__requests.length);await start('recognition');assert.equal(await app.evaluate(()=>global.__requests.length),before+1);assert.equal((await boot()).project.problems.filter(p=>p.recognition).length,2);
  await close();await page.locator('#batch-review').click();await page.getByRole('button',{name:'원문 검토',exact:true}).click();
  const reviewCalls=await app.evaluate(()=>global.__requests.length);await page.locator('#batchReviewConfirm').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').textContent.includes('2/2'));await page.locator('#batchReviewPrevious').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').textContent.includes('1/2'));await page.locator('#batchReviewNext').click();await page.locator('#batchReviewConfirm').click();await page.locator('#confirmSourceReview').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').hidden);
  assert.equal(await app.evaluate(()=>global.__requests.length),reviewCalls);assert.equal((await boot()).project.problems.every(p=>p.recognition.confirmed),true);assert.equal((await boot()).project.problems.every(p=>!p.original.solution),true);assert.equal(await page.locator('#batch-solve').getAttribute('aria-current'),'step');assert.equal(await page.locator('#batch-review').evaluate(n=>n.classList.contains('stage-complete')),true);
  await start('solve');assert.equal((await boot()).project.problems.every(p=>p.original.solution),true);await page.getByRole('button',{name:'결과 차례로 검토',exact:true}).click();await page.locator('#batchReviewConfirm').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').textContent.includes('2/2'));await page.locator('#batchReviewConfirm').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').hidden);assert.equal((await boot()).project.problems.every(p=>p.original.approval.status==='approved'),true);
  // A successful recognition retry resolves its old failure without extra AI calls.
  await page.locator('#batch-generation').click();await page.locator('#batchSelectAll').uncheck();await page.locator('.batch-problem-choice').nth(1).check();await page.locator('#batchStart').click();await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='일괄 작업 결과');await idle();await close();
  data=await boot();assert.equal(data.project.problems[0].variants.length,0);assert.equal(data.project.problems[1].variants.length,1);
  await page.locator('#batch-generation').click();assert.equal(await page.locator('#batchAllowUnverified').count(),1);await page.locator('#batchAllowUnverified').check();await page.locator('#batchInstructions').fill('수치만 바꾼 유사문제 2개, 좌우반전 1개 만들어줘');await page.locator('#batchStart').click();await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='일괄 작업 결과');await idle();await close();
  data=await boot();assert.deepEqual(data.project.problems.map(p=>p.variants.length),[3,4]);assert.equal(data.project.problems.flatMap(p=>p.variants).every(q=>q.approval.status==='approved'),true);
  await page.locator('#batch-review').click();await page.getByRole('button',{name:'유사문제 검토',exact:true}).click();await page.locator('#batchReviewConfirm').click();await page.waitForFunction(()=>document.querySelector('#batchReviewNav').textContent.includes('2/7'));assert.equal((await boot()).project.problems[0].variants[0].approval.status,'approved');await page.getByRole('button',{name:'검토 닫기',exact:true}).click();
  // Stop a held request; no later problem starts and already saved variants remain.
  await app.evaluate(()=>global.__hold=true);await page.locator('#batch-generation').click();await page.locator('#batchAllowUnverified').check();const count=await app.evaluate(()=>global.__requests.length);await page.locator('#batchStart').click();await page.waitForFunction(()=>!document.querySelector('#cancelChat').hidden);await page.locator('#batchProgressStop').click();await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='일괄 작업 중지'&&document.querySelector('#mainDialog').open);await idle();assert.equal(await app.evaluate(()=>global.__requests.length),count+1);assert.ok((await boot()).project.problems.flatMap(p=>p.variants).length>=7);assert.deepEqual(errors,[]);await close();await page.screenshot({path:path.join(dir,'batch-screen.png')});console.log('Screenshot: '+path.join(dir,'batch-screen.png'));console.log('PASS Collection persists, failure continues, recognition resumes without repeats, review moves without AI, batch solve, selected/all generation, approval and cancellation (mock AI)');
 }finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});}
