'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),D=require('../app/difficulty-assessment.cjs'),Cache=require('../app/assessment-cache.cjs');
test('retired AI/calibration never supply a fallback, while teacher decisions still apply',()=>{
 const c={metadata:{difficulty:{aiScore:'9.0',aiBand:'아주어려움',criteriaVersion:'old',calibratedScore:'9.5'}}};assert.equal(D.effective(c).number,null);assert.equal(D.effective(c).band,null);c.confirmed={difficulty:'3.5'};assert.equal(D.effective(c).number,3.5);
 const cleaned=D.currentOnly(c);assert.deepEqual(cleaned.metadata.difficulty,c.metadata.difficulty);assert.equal(D.currentAI(cleaned),null);assert.equal(D.effective(cleaned).number,3.5);
 const q={body:'a',solution:'b'},p={};q.assessment=Cache.record({status:'estimated',score:'9.0',band:'아주어려움',reason:'old',features:Object.fromEntries(D.features.map(k=>[k,'old']))},q,p,{}, {criteriaVersion:'old'});assert.equal(Cache.importEmbedded({difficulty:{}},q,p,{}),false,'cached response cannot masquerade as the current criteria');
});
test('fifty stored v5 results retain provenance and history without reinterpreting them as access v2',()=>{
 const file='tmp/difficulty-current-only-20261003/live-state.json';assert.ok(fs.existsSync(file),'fresh read-only production snapshot required');const state=JSON.parse(fs.readFileSync(file));assert.equal(state.items.length,50);
 for(const {catalog:c}of state.items){const before=JSON.stringify(c),active=D.activeAssessment(c),cleaned=D.currentOnly(c);assert.ok(active);assert.deepEqual(cleaned.metadata.difficulty,c.metadata.difficulty);assert.equal(active.criteriaVersion,'expected-10-v5-insight-references-scope-low1');assert.deepEqual(cleaned.confirmed,c.confirmed);for(const k of Object.keys(c.metadata).filter(k=>k!=='difficulty'))assert.deepEqual(cleaned.metadata[k],c.metadata[k]);assert.deepEqual(cleaned.content,c.content);assert.deepEqual(cleaned.files,c.files);assert.equal(JSON.stringify(c),before);assert.equal(D.effective(cleaned).number,D.effective(c).number);assert.equal(JSON.stringify(D.currentOnly(cleaned)),JSON.stringify(cleaned),'repeat application is a no-op');}
});
test('server and clients agree on current-only scores, teacher priority, stale and retired results',async()=>{
 const server=await require('./shared-bank-local-server.cjs').localServer(),db=server.db;try{const cases=[{metadata:{difficulty:{aiScore:'8.4',criteriaVersion:'old'}}},{metadata:{difficulty:{aiScore:'3.2',criteriaVersion:D.version}}},{metadata:{difficulty:{aiScore:'3.2',criteriaVersion:D.version,calibratedScore:'9.0'}}},{metadata:{analysis:{status:'stale'},difficulty:{aiScore:'3.2',criteriaVersion:D.version}}},{metadata:{difficulty:{aiScore:'9.0',criteriaVersion:'old'}},confirmed:{difficulty:'4.3',difficultyBand:'어려움'}}];for(const c of cases){const r=await db.query('select public.bank_difficulty_number($1,$2) as n,public.bank_difficulty_band($1,$2) as b',[c.metadata,c.confirmed||{}]),e=D.effective(c);assert.equal(r.rows[0].n==null?null:Number(r.rows[0].n),e.number);assert.equal(r.rows[0].b,e.band);}}finally{await db.close();}
});
