'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),R=require('../app/difficulty-reassessment.cjs'),D=require('../app/difficulty-assessment.cjs'),C=require('../app/curriculum.js');
const scope=C.build(['m2-8.3','m2-9.1']);
function item(){return {catalog:{question_id:'q',revision_id:'r',metadata:{analysis:{basis:'saved-basis',status:'complete'},difficulty:{aiScore:'5.0',aiBand:'보통',reason:'기존 서술 근거',criteriaVersion:'old',scope}},confirmed:{},content:{body:'stored'}},question:{body:'길이를 구하시오.',choices:[],answer:'3',solution:'주어진 조건에서 구한다.'},scope};}
const options={model:'mock-model',effort:'high'},provenance={provider:'mock',...options,at:'2026-10-03T05:30:00Z'},assessment=score=>require('./fixtures/access-assessment.cjs').accessAssessment(score==='2.0'?'S0':'S4');
test('metadata-only revision binds its score, keeps original evidence and rejects changed content or teacher values',()=>{
 const original=item(),row=R.plan([original],options).rows[0],saved=R.recordResult(original,row,assessment('2.0'),provenance);
 const source={...original,catalog:saved.catalog},target=structuredClone(source);target.catalog.revision_id='11111111-1111-4111-8111-111111111111';
 const carried=R.carryToRevision(source,row.idempotencyKey,target,{at:provenance.at});assert.equal(D.effective(carried.catalog).number,2);assert.equal(carried.catalog.metadata.difficulty.aiScore,'5.0');assert.deepEqual(carried.catalog.metadata.difficulty.rubricAssessments[row.idempotencyKey],saved.record);assert.equal(carried.record.versionBinding.fromRevisionId,'r');
 const rerun=R.inspect({...target,catalog:carried.catalog},options);assert.equal(rerun.status,'reuse_versioned_result');assert.equal(rerun.request.maxCalls,0);
 for(const change of [s=>s.question.body+='changed',s=>s.question.solution+='changed',s=>s.catalog.metadata.analysis.basis='changed',s=>s.catalog.metadata.difficulty.aiScore='6.0',s=>s.catalog.confirmed.difficulty='8.0']){const changed=structuredClone(target);change(changed);assert.throws(()=>R.carryToRevision(source,row.idempotencyKey,changed,{at:provenance.at}));}
});
test('dry-run is stable, immutable and never infers a new number from an old score or narrative',()=>{
 const source=item(),before=JSON.stringify(source),a=R.plan([source],options),b=R.plan([source],options);assert.equal(a.planId,b.planId);assert.equal(a.dryRun,true);assert.equal(a.aiCalls,0);assert.equal(a.maximumProposedCalls,1);assert.equal(a.rows[0].newScore,null);assert.equal(a.newDistribution,null);assert.equal(JSON.stringify(source),before);
 assert.throws(()=>R.plan([source,source],options),/중복 버전/);const req=R.requestFor(source,a.rows[0]);assert.equal(req.maximumCalls,1);assert.equal(req.automaticRetries,0);assert.doesNotMatch(req.text,/oldRawScore|oldScore|aiScore/);assert.deepEqual(JSON.parse(req.text).scope,source.scope);assert.match(req.execution.instructions,/기준 학생/);source.catalog.confirmed.difficulty='6.0';assert.throws(()=>R.requestFor(source,a.rows[0]),/교사 점수/);
});
test('teacher numeric and band decisions remain protected; stale solutions and missing scope require review',()=>{
 for(const [location,key,value]of [['confirmed','difficulty','7.1'],['confirmed','difficultyBand','어려움'],['difficulty','userScore','7.3'],['difficulty','teacherBand','아주어려움']]){const source=item();(location==='confirmed'?source.catalog.confirmed:source.catalog.metadata.difficulty)[key]=value;const p=R.plan([source],options);assert.equal(p.rows[0].status,'teacher_protected');assert.equal(p.maximumProposedCalls,0);}
 const source=item();source.question.solutionStale=true;source.catalog.metadata.analysis.inputState={reviewedCurrent:true};assert.equal(R.plan([source],options).rows[0].status,'needs_solution_review');source.question.solutionStale=false;source.scope={};assert.equal(R.plan([source],options).rows[0].status,'needs_scope_review');
});
test('new version is recorded separately, explicitly activated and idempotent while raw/teacher/source fields survive',()=>{
 const source=item(),before=JSON.stringify(source),row=R.plan([source],options).rows[0],saved=R.recordResult(source,row,assessment('2.0'),provenance);assert.equal(saved.activation,'recorded_only');assert.equal(D.effective(saved.catalog).number,null);assert.equal(saved.catalog.metadata.difficulty.aiScore,'5.0');assert.equal(saved.catalog.metadata.difficulty.criteriaVersion,'old');assert.deepEqual(saved.catalog.content,source.catalog.content);assert.equal(JSON.stringify(source),before);
 const next={...source,catalog:saved.catalog},active=R.activateVersion(next,row.idempotencyKey);assert.equal(D.effective(active.catalog).number,2);assert.equal(D.effective(active.catalog).numberSource,'AI 추천');assert.equal(active.catalog.metadata.difficulty.rubricAssessments[row.idempotencyKey].oldRawScore,undefined);assert.equal(R.activateVersion({...source,catalog:active.catalog},row.idempotencyKey).changed,false);
 assert.equal(R.recordResult({...source,catalog:active.catalog},row,assessment('2.0'),{...provenance,activate:true}).duplicate,true);assert.throws(()=>R.recordResult(next,row,assessment('8.0'),provenance),/덮어쓰지/);assert.equal(R.plan([next],options).rows[0].status,'reuse_versioned_result');assert.equal(R.plan([next],options).maximumProposedCalls,0);
 next.catalog.confirmed.difficulty='6.8';next.catalog.confirmed.difficultyBand='어려움';assert.equal(R.activateVersion(next,row.idempotencyKey).activation,'teacher_protected');assert.equal(D.effective(next.catalog).number,6.8);assert.equal(D.effective(next.catalog).band,'보통');
});
test('concurrent content, basis, revision, raw score or scope changes reject results; malformed results never enter ledger',()=>{
 const source=item(),row=R.plan([source],options).rows[0];for(const change of [s=>s.question.body+=' changed',s=>s.question.solutionStale=true,s=>s.catalog.revision_id='new',s=>s.catalog.metadata.analysis.basis='new',s=>s.catalog.metadata.difficulty.aiScore='6.0',s=>s.scope=C.build(['m2-6.3'])]){const changed=structuredClone(source);change(changed);assert.throws(()=>R.recordResult(changed,row,assessment('2.0'),provenance),/변경/);}
 assert.throws(()=>R.recordResult(source,row,{...assessment('2.0'),band:'아주어려움'},provenance),/형식/);assert.throws(()=>R.recordResult(source,row,assessment('2.0'),{...provenance,model:'different'}),/다른 모델/);
 const accepted=R.recordResult(source,row,assessment('2.0'),{...provenance,activate:true}).catalog;accepted.revision_id='new';assert.equal(D.effective(accepted).number,null,'old revision assessment never becomes active on a new revision');
});
test('dated actual snapshot is read only: no numerical conversion, all old provenance retained',()=>{
 const fs=require('fs'),snapshot='data/backups/phase15-predeploy-2026-10-03T01-08-02-829Z';if(!fs.existsSync(snapshot))return;
 const {readSnapshot}=require('../scripts/plan-difficulty-reassessment.cjs'),{items}=readSnapshot(snapshot),before=JSON.stringify(items),p=R.plan(items,options);assert.equal(p.total,50);assert.equal(p.counts.needs_ai_reassessment,50);assert.equal(p.counts.needs_solution_review,undefined);const held=items.find(x=>x.question.solutionStale);assert.equal(R.currentSolution(held).verification,'saved_current_review_bound_to_unchanged_input');for(const change of [x=>x.question.body+=' changed',x=>x.question.solution+=' changed',x=>x.scope=C.build(['m2-9.1']),x=>x.modules[0].version+=' changed',x=>x.problem.regions[0].x+=0.01,x=>x.question.approval.at='different',x=>x.problem.recognition.sourceStale=true]){const modified=structuredClone(held);change(modified);assert.equal(R.inspect(modified,options).status,'needs_solution_review');}assert.equal(p.rows.filter(r=>r.newScore!==null).length,0);assert.equal(p.rows.reduce((n,r)=>n+r.evidence.structuredFeatureCount,0),0);assert.equal(p.aiCalls,0);assert.equal(JSON.stringify(items),before);
});
