'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const output={exports:{}};vm.runInNewContext(require('esbuild').transformSync(fs.readFileSync(require.resolve('../app/exam-queue-progress.js'),'utf8'),{format:'cjs'}).code,{module:output,exports:output.exports});const {progressView}=output.exports;
test('resuming an individual held question displays active processing rather than a terminal banner',()=>{
 const i=item();i.status='held';i.summary.heldQuestions=8;
 let v=progressView({mode:'running',items:[i]});assert.equal(v.settled,false);assert.equal(v.state,'처리 중');assert.equal(v.number,'논술형 1');assert.equal(v.counts.solve,0);
 delete i.steps['p:solve'];v=progressView({mode:'running',items:[i]});assert.equal(v.settled,false);assert.equal(v.state,'처리 중');
 v=progressView({mode:'paused',items:[i]});assert.equal(v.state,'일시정지');
});
function item(){return {id:'exam',name:'fixture',status:'running',pages:5,steps:{'page:1':{kind:'regions',status:'complete'},'p:recognition':{kind:'recognition',status:'complete'},'p:solve':{kind:'solve',status:'running'}},summary:{activeProblem:'논술형 1',discovered:24,confirmedTotal:null,complete:0,uploaded:0,reviewed:0,failedQuestions:0,heldQuestions:0,unknownQuestions:0,whole:false},discoveryIssues:[],move:{status:'pending'}};}
test('progress uses actual stage records, printed number and unknown total without fake completion',()=>{const v=progressView({mode:'running',items:[item()]});assert.equal(v.index,1);assert.equal(v.number,'논술형 1');assert.equal(v.total,null);assert.equal(v.discovered,24);assert.equal(v.counts.recognition,1);assert.equal(v.counts.solve,0);assert.match(v.stage,/통합 요청/);assert.equal(v.settled,false);});
test('paused request remains its real stage and failures survive a terminal state',()=>{const i=item();i.steps['p:solve']={kind:'solve',status:'held',reason:'reading unresolved'};i.status='held';i.summary.heldQuestions=1;let v=progressView({mode:'paused',reason:'manual pause',items:[i]});assert.equal(v.state,'일시정지');assert.ok(v.reasons.includes('reading unresolved'));v=progressView({mode:'idle',items:[i]});assert.equal(v.state,'처리 종료 · 확인 필요');assert.equal(v.settled,true);});
test('whole success is pending review and later queue position is preserved',()=>{const a=item(),b=item();a.status='complete';a.summary.whole=true;a.steps={};b.id='second';let v=progressView({mode:'running',items:[a,b]});assert.equal(v.index,2);b.status='complete';b.summary.whole=true;b.steps={};v=progressView({mode:'idle',items:[a,b]});assert.equal(v.state,'처리·업로드 완료 · 검수 대기');});

test('progress popup cancel preserves an in-flight artifact and stops the next stage without removing the source',async t=>{
 const os=require('node:os'),path=require('node:path'),{ExamQueue}=require('../app/exam-queue.cjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'queue-popup-cancel-'));
 t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});const source=path.join(dir,'isolated-source.png'),artifact=path.join(dir,'recognition.txt');fs.writeFileSync(source,'isolated source fixture');
 const store=new (require('../app/store.cjs').ProjectStore)(path.join(dir,'data')),queue=new ExamQueue({directory:store.dataDir,store}),id=queue.add([source]).added[0].id;queue.action('start');let release;
 const work=queue.stage(id,'p:recognition','recognition',{fixture:true},async()=>{await new Promise(resolve=>release=resolve);fs.writeFileSync(artifact,'completed recognition');return {artifact};},result=>fs.existsSync(result.artifact));
 const nodes=[],element=(tag,css='',text='')=>{const node={tag,className:css,textContent:text,children:[],open:false,setAttribute(){},append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},addEventListener(){},show(){this.open=true;},close(){this.open=false;}};nodes.push(node);return node;},document={getElementById:id=>nodes.find(n=>n.id===id),querySelector:()=>null,body:{append(){}}},exports={exports:{}};
 vm.runInNewContext(require('esbuild').transformSync(fs.readFileSync(require.resolve('../app/exam-queue-progress.js'),'utf8'),{format:'cjs'}).code,{module:exports,exports:exports.exports,document});
 const controller=exports.exports.installQueueProgress({element,button:(text,css,fn)=>Object.assign(element('button',css,text),{click:fn}),onPause:()=>queue.action('pause'),onResume:()=>queue.action('resume'),onCancel:()=>queue.action('cancel'),onResults:()=>assert.fail('cancel must not open results')});
 controller.update(queue.status(),true);controller.show();document.getElementById('examQueueProgressCancel').click();assert.equal(queue.state.mode,'cancelled');assert.equal(fs.existsSync(source),true);release();assert.equal((await work).result.artifact,artifact);assert.equal(queue.item(id).steps['p:recognition'].status,'complete');assert.equal(fs.readFileSync(artifact,'utf8'),'completed recognition');assert.equal((await queue.stage(id,'p:solve','solve',{},()=>assert.fail('cancel must stop the next stage'),()=>true)).stopped,true);assert.equal(queue.state.usage.calls,0);assert.equal(queue.item(id).status,'cancelled');
});
