'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ProjectStore,atomicWrite}=require('../app/store.cjs');
const {ExamQueue,summary,hash,fileHash}=require('../app/exam-queue.cjs');
const {DEFAULT_SCOPE}=require('../app/rules.cjs');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jBvUAAAAASUVORK5CYII=','base64');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'exam-phase2-test-'));t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});const file=path.join(dir,'서울 신구중 2026 중2 2학기 기말고사.png');fs.writeFileSync(file,png);const store=new ProjectStore(path.join(dir,'data')),queue=new ExamQueue({directory:store.dataDir,store});queue.action('limits',null,{remainingPercent:null});const item=queue.add([file]).snapshot.items[0];queue.action('start');return {dir,file,store,queue,item:queue.item(item.id)};}
function problem(f,number='1',section='objective'){const project=f.queue.ensureProject(f.item.id),saved=f.store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});const p=saved.problems.at(-1);f.store.updateProblem(saved.id,p.id,x=>{x.recognition={body:'문제',originalNumber:number,sourceNumbering:{section},version:1};x.original={id:p.id+'-original',body:'문제',choices:[],answer:'2',solution:'풀이',approval:{status:'pending'}};});for(const stage of ['recognition','solve','analysis','upload'])f.item.steps[p.id+':'+stage]={kind:stage,status:'complete'};return p;}
test('completed queue removal persists, preserves source/artifacts/IDs and readding reuses without new calls',t=>{
 const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});const p=problem(f);f.queue.finish(f.item.id);f.queue.move(f.item.id);
 const source=f.item.currentPath,projectBefore=JSON.stringify(f.store.get(f.item.projectId)),stepsBefore=JSON.stringify(f.item.steps),sourceHash=fileHash(source);
 assert.equal(f.queue.action('remove',f.item.id).items.length,0);assert.equal(fs.existsSync(source),true);assert.equal(JSON.stringify(f.store.get(f.item.projectId)),projectBefore);
 const reopenedStore=new ProjectStore(f.store.dataDir),reopened=new ExamQueue({directory:reopenedStore.dataDir,store:reopenedStore});assert.equal(reopened.status().items.length,0);assert.equal(reopenedStore.get(f.item.projectId).source.path,source);
 assert.equal(reopenedStore.ownsAsset(source),true);const added=reopened.add([source]);assert.deepEqual(added.added,[{id:f.item.id,reused:true}]);const restored=added.snapshot.items[0];assert.equal(restored.projectId,f.item.projectId);assert.equal(reopenedStore.get(restored.projectId).problems[0].id,p.id);assert.equal(JSON.stringify(restored.steps),stepsBefore);assert.equal(fileHash(source),sourceHash);assert.equal(reopened.state.usage.calls,0);assert.equal(restored.move.status,'complete');assert.equal(reopened.state.items.length,1);
});
test('historical discovery exception is separate from active errors only with verified artifacts',t=>{
 const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});const p=problem(f);
 f.store.updateProblem(f.item.projectId,p.id,x=>{x.queueDetectionKeys=[f.item.id+':1:0'];});f.item.pages=1;f.item.steps['page:1']={kind:'regions',status:'complete',result:{regions:[{}]}};f.item.discoveryIssues=['result is not defined'];
 const projectBefore=JSON.stringify(f.store.get(f.item.projectId)),stepsBefore=JSON.stringify(f.item.steps);
 const row=f.queue.status().items[0];assert.deepEqual(row.discoveryIssues,[]);assert.equal(row.resolvedDiscoveryIssues[0].issue,'result is not defined');assert.equal(row.summary.whole,true);assert.deepEqual(f.item.discoveryIssues,['result is not defined']);assert.equal(JSON.stringify(f.store.get(f.item.projectId)),projectBefore);assert.equal(JSON.stringify(f.item.steps),stepsBefore);
 f.queue.finish(f.item.id);assert.equal(f.item.status,'complete');assert.equal(fs.existsSync(f.file),true);assert.equal(f.queue.state.usage.calls,0);
 f.item.discoveryIssues.push('Mixed exam source needs review');const active=f.queue.status().items[0];assert.deepEqual(active.discoveryIssues,['Mixed exam source needs review']);assert.equal(active.summary.whole,false);f.queue.finish(f.item.id);assert.equal(f.item.status,'held');
});
test('unverified pages, capture links, crops or question identities keep discovery exception active',t=>{
 const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});const p=problem(f);
 f.store.updateProblem(f.item.projectId,p.id,x=>{x.queueDetectionKeys=[f.item.id+':1:0'];});f.item.pages=1;f.item.steps['page:1']={kind:'regions',status:'complete',result:{regions:[{}]}};f.item.discoveryIssues=['result is not defined'];
 const original=f.store.get(f.item.projectId),checked=project=>{const s=summary(f.item,project);assert.deepEqual(s.discovery.active,['result is not defined']);assert.deepEqual(s.discovery.resolved,[]);assert.equal(s.whole,false);};
 f.item.steps['page:1'].status='unknown';checked(original);f.item.steps['page:1'].status='complete';
 for(const mutate of [x=>{x.problems[0].queueDetectionKeys=[];},x=>{x.problems[0].cropPaths=[path.join(f.dir,'missing.png')];},x=>{x.problems[0].recognition.sourceNumbering.section='unknown';},x=>{x.problems[0].queueRegionIssue='uncertain mixed exam';}]){const project=structuredClone(original);mutate(project);checked(project);}
 assert.equal(f.queue.state.usage.calls,0);
});
test('queue removal rejects running, partial, unknown totals and cancelled rows',t=>{
 const f=fixture(t);assert.throws(()=>f.queue.action('remove',f.item.id),/완료/);problem(f);f.queue.finish(f.item.id);assert.throws(()=>f.queue.action('remove',f.item.id),/완료/);
 f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});f.queue.finish(f.item.id);f.queue.active={item:f.item};assert.throws(()=>f.queue.action('remove',f.item.id),/완료/);f.queue.active=null;f.item.steps[Object.keys(f.item.steps)[0]].status='held';assert.throws(()=>f.queue.action('remove',f.item.id),/완료/);assert.equal(f.item.hidden,undefined);assert.equal(fs.existsSync(f.file),true);
 f.queue.action('cancel',f.item.id);assert.throws(()=>f.queue.action('remove',f.item.id),/완료/);
});
test('hidden current records still identify another scan and protect pending source moves',t=>{
 const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});problem(f);f.queue.finish(f.item.id);f.item.move={status:'failed',reason:'isolated move failure'};f.queue.action('remove',f.item.id);
 const scan=path.join(f.dir,path.parse(f.file).name+' (scan).png');fs.writeFileSync(scan,Buffer.concat([png,Buffer.from('alternate synthetic scan')]));const second=f.queue.add([scan]).snapshot.items[0];assert.equal(second.duplicateCandidate,f.item.id);assert.equal(second.status,'held');assert.equal(f.queue.item(f.item.id).move.status,'failed');assert.equal(fs.existsSync(f.file),true);assert.equal(f.queue.add([f.file]).snapshot.items.length,2);assert.equal(f.item.move.status,'failed');
});

test('Korean year reaches saved queue metadata; readding preserves manual source fields and ID',t=>{
 const f=fixture(t),file=path.join(f.dir,'2026년기출_서울삼육중_2학년2학기_중간고사.png');
 fs.writeFileSync(file,Buffer.concat([png,Buffer.from('unique-year-fixture')]));
 const item=f.queue.add([file]).snapshot.items.at(-1);
 assert.equal(item.metadata.academicYear,'2026');
 assert.equal(item.metadata.school,'서울삼육중');
 f.queue.edit(item.id,{metadata:{academicYear:'2024',school:'서울삼육중학교',semester:'1학기',exam:'기말고사'}});
 assert.equal(f.queue.add([file]).added[0].id,item.id);
 const reopened=new ExamQueue({directory:f.store.dataDir,store:f.store});
 const value=reopened.status().items.find(x=>x.id===item.id).metadata;
 assert.deepEqual([value.academicYear,value.school,value.semester,value.exam],['2024','서울삼육중학교','1학기','기말고사']);
 assert.equal(reopened.state.usage.calls,0);
});
test('filename-only metadata, hash deduplication and no source copy',t=>{const f=fixture(t);assert.equal(f.item.metadata.school,'신구중');assert.equal(f.item.metadata.grade,'중2');assert.equal(f.item.metadata.academicYear,'2026');assert.equal(f.item.scopeConfirmed,false);assert.equal(f.queue.add([f.file]).added[0].reused,true);const p=f.queue.ensureProject(f.item.id);assert.equal(p.source.path,f.file);assert.equal(fs.readdirSync(path.join(f.store.projectDir(p.id),'assets')).length,0);const reopened=new ProjectStore(f.store.dataDir);new ExamQueue({directory:reopened.dataDir,store:reopened});assert.equal(reopened.get(p.id).source.path,f.file);assert.equal(reopened.ownsAsset(f.file),true);});
test('different bytes, same complete identity hold only ambiguous scan; school/year alone is insufficient',t=>{const f=fixture(t),second=path.join(f.dir,'서울 신구중 2026 중2 2학기 기말고사 (다른 스캔).png');fs.writeFileSync(second,Buffer.concat([png,Buffer.from('scan')]));const b=f.queue.add([second]).snapshot.items[1];assert.equal(b.status,'held');assert.equal(b.duplicateCandidate,f.item.id);const unknown=path.join(f.dir,'신구중 2026 기타.png');fs.writeFileSync(unknown,Buffer.concat([png,Buffer.from('other')]));assert.equal(f.queue.add([unknown]).snapshot.items[2].duplicateCandidate,null);f.queue.edit(b.id,{duplicateDecision:'same'});assert.equal(f.queue.item(b.id).linkedTo,f.item.id);});
test('pause and cancellation preserve current results and stop subsequent execution',async t=>{const f=fixture(t);let release;const work=f.queue.stage(f.item.id,'p:recognition','recognition',{v:1},async()=>{await new Promise(r=>release=r);return {body:'saved'};},r=>!!r?.body);f.queue.action('pause');release();assert.equal((await work).result.body,'saved');assert.equal((await f.queue.stage(f.item.id,'p:solve','solve',{},()=>assert.fail(),()=>true)).stopped,true);f.queue.action('resume');f.queue.action('cancel',f.item.id);assert.equal(fs.existsSync(f.file),true);assert.equal(f.item.steps['p:recognition'].status,'complete');assert.equal(f.queue.next(),null);});
test('completed stage requires both matching dependencies and real artifacts',async t=>{const f=fixture(t);let calls=0,exists=true;const execute=async()=>({path:'fixture',n:++calls}),verify=()=>exists;await f.queue.stage(f.item.id,'p:recognition','recognition',{source:1},execute,verify);assert.equal((await f.queue.stage(f.item.id,'p:recognition','recognition',{source:1},execute,verify)).reused,true);exists=false;const result=await f.queue.stage(f.item.id,'p:recognition','recognition',{source:1},execute,verify);assert.equal(result.held,true);assert.equal(calls,2);exists=true;await f.queue.stage(f.item.id,'p:recognition','recognition',{source:2},execute,verify);assert.equal(calls,3);});
test('interrupted stages distinguish AI from upload and preserve response packets',async t=>{const f=fixture(t);for(const kind of ['regions','recognition','solve','analysis','upload'])f.item.steps['p:'+kind]={kind,status:'running',fingerprint:hash({v:1}),responses:[]};f.queue.save();const recovered=new ExamQueue({directory:f.store.dataDir,store:f.store});assert.equal(recovered.state.mode,'paused');for(const kind of ['regions','recognition','solve','analysis','upload']){const s=recovered.item(f.item.id).steps['p:'+kind];assert.equal(s.status,'unknown');assert.equal(s.unknownKind,kind==='upload'?'upload':'ai');}recovered.action('resume');let calls=0;const out=await recovered.stage(f.item.id,'p:recognition','recognition',{v:1},async()=>++calls,()=>false);assert.equal(out.held,true);assert.equal(calls,0);});
test('persisted AI response is replayed after termination before content apply',async t=>{const f=fixture(t);let calls=0,artifact=false;const bridge=f.queue.bridge({run:async()=>{calls++;return {result:{body:'본문'},tokens:{totalTokens:12}};}}),request={images:[f.file],text:'OCR',model:'mock',effort:'high',execution:{task:'recognition'}};
 const key='p:recognition',basis={source:f.item.hash};const result=await f.queue.stage(f.item.id,key,'recognition',basis,async()=>{await bridge.run(request);throw Error('simulated apply crash');},()=>artifact);assert.equal(result.held,true);f.item.steps[key].status='running';f.queue.save();const recovered=new ExamQueue({directory:f.store.dataDir,store:f.store});recovered.action('resume');const b=recovered.bridge({run:()=>assert.fail('must reuse packet')});await recovered.stage(f.item.id,key,'recognition',basis,async()=>{const r=await b.run(request);artifact=true;return r.result;},()=>artifact);assert.equal(calls,1);assert.equal(recovered.state.usage.calls,1);assert.equal(recovered.state.usage.tokens,12);});
test('AI response loss needs explicit retry and never silently spends again',async t=>{const f=fixture(t);let calls=0;const bridge=f.queue.bridge({run:async()=>{calls++;throw Object.assign(Error('network response lost'),{code:'ECONNRESET'});}});const execute=()=>bridge.run({images:[],text:'x',model:'mock'});await f.queue.stage(f.item.id,'p:r','recognition',{},execute,()=>false);assert.equal(f.item.steps['p:r'].status,'unknown');await f.queue.stage(f.item.id,'p:r','recognition',{},execute,()=>false);assert.equal(calls,1);f.queue.action('retry',f.item.id);await f.queue.stage(f.item.id,'p:r','recognition',{},execute,()=>false);assert.equal(calls,2);});
test('upload response loss queries committed result before any resend',async t=>{const f=fixture(t);f.item.steps['p:u']={kind:'upload',status:'unknown',fingerprint:hash({q:1}),result:{revisionId:'stable'},responses:[]};let checked=0;const result=await f.queue.stage(f.item.id,'p:u','upload',{q:1},()=>assert.fail('must not resend'),async r=>{checked++;return r.revisionId==='stable';});assert.equal(result.reused,true);assert.equal(checked,1);});
test('pre-dispatch transient retry is bounded and every real request is counted',async t=>{const f=fixture(t);let n=0;const bridge=f.queue.bridge({run:async()=>{n++;throw Object.assign(Error('offline'),{code:'ECONNREFUSED',dispatched:false,retryAfterMs:1});}});await f.queue.stage(f.item.id,'p:r','recognition',{},()=>bridge.run({text:'x'}),()=>false);assert.equal(n,3);assert.equal(f.queue.state.usage.calls,3);});
test('auth/quota/common failure pauses all; an individual error does not',async t=>{const f=fixture(t);await f.queue.stage(f.item.id,'p:1','recognition',{},async()=>{throw Error('invalid question');},()=>false);assert.equal(f.queue.state.mode,'running');await f.queue.stage(f.item.id,'p:2','recognition',{},async()=>{throw Object.assign(Error('authentication'),{status:401});},()=>false);assert.equal(f.queue.state.mode,'paused');});
test('retry-after cannot be bypassed by immediate resume',async t=>{const f=fixture(t);await f.queue.stage(f.item.id,'p:r','recognition',{},async()=>{throw Object.assign(Error('rate limit'),{status:429,retryAfterMs:10000});},()=>false);assert.throws(()=>f.queue.action('resume'),/대기/);});
test('request and known-token caps pause before extra provider call; missing tokens are not invented',async t=>{const f=fixture(t);f.queue.action('limits',null,{maxCalls:1});let calls=0;const b=f.queue.bridge({run:async()=>{calls++;return {result:1};}});await f.queue.stage(f.item.id,'p:a','recognition',{},()=>b.run({text:'a'}),()=>true);await f.queue.stage(f.item.id,'p:b','recognition',{},()=>b.run({text:'b'}),()=>true);assert.equal(calls,1);assert.equal(f.queue.state.mode,'paused');assert.equal(f.queue.state.usage.tokenReports,0);});
test('unknown total is discovery count, never max printed number or 24/24',t=>{const f=fixture(t);problem(f,'24');const s=summary(f.item,f.store.get(f.item.projectId));assert.equal(s.confirmedTotal,null);assert.equal(s.discovered,1);assert.equal(s.whole,false);assert.match(s.countLabel,/총수 미확정/);assert.equal(f.queue.finish(f.item.id).items[0].move.status,'held');});
test('objective 1 and written 1 remain distinct stable IDs; compound number is connection metadata',t=>{const f=fixture(t);const a=problem(f,'1','objective'),b=problem(f,'1','written');assert.notEqual(a.id,b.id);assert.deepEqual(summary(f.item,f.store.get(f.item.projectId)).inventory.duplicates,[]);const saved=f.store.replaceRegion({projectId:f.item.projectId,problemId:a.id,regionIndex:0,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});assert.equal(saved.problems[0].id,a.id);assert.equal(saved.problems[0].original.id,a.id+'-original');});
test('confirmed section counts expose missing and duplicate printed numbers',t=>{const f=fixture(t);problem(f,'1');problem(f,'1');f.queue.edit(f.item.id,{metadata:{numbering:{total:3,objectiveCount:3,writtenCount:0,confirmed:true}}});const s=summary(f.item,f.store.get(f.item.projectId));assert.deepEqual(s.inventory.duplicates,['objective:1']);assert.deepEqual(s.inventory.missing,['objective:2','objective:3']);assert.equal(s.whole,false);});
test('invalid counts and metadata do not silently normalize to unrestricted work',t=>{const f=fixture(t);assert.throws(()=>f.queue.edit(f.item.id,{metadata:{numbering:{total:2,objectiveCount:2,writtenCount:1,confirmed:true}}}),/다릅니다/);assert.throws(()=>f.queue.edit(f.item.id,{scope:{}}),/시험 범위/);assert.equal(f.item.scopeConfirmed,false);});
test('whole success moves the one external original without overwriting a name collision',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,objectiveCount:1,writtenCount:0,confirmed:true}}});problem(f);const folder=path.join(f.dir,'완료된 시험지');fs.mkdirSync(folder);const collision=path.join(folder,path.basename(f.file));fs.writeFileSync(collision,'existing');f.queue.finish(f.item.id);const result=f.queue.move(f.item.id).items[0];assert.equal(result.move.status,'complete');assert.equal(fs.existsSync(f.file),false);assert.equal(fs.readFileSync(collision,'utf8'),'existing');assert.equal(fileHash(result.currentPath),f.item.hash);assert.equal(f.store.get(f.item.projectId).source.path,result.currentPath);assert.equal(f.queue.move(f.item.id).items[0].move.status,'complete');assert.equal(fs.readdirSync(folder).length,2);});
test('partial/held/cancelled work never moves the selected original',t=>{const f=fixture(t);const p=problem(f);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});f.item.steps[p.id+':upload'].status='held';assert.throws(()=>f.queue.move(f.item.id),/전체 문항/);assert.equal(fs.existsSync(f.file),true);});
test('move failure is separate from upload and retries do not invalidate uploaded questions',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);f.queue.moveFile=()=>{throw Object.assign(Error('external disconnected'),{code:'EXDEV'});};f.queue.finish(f.item.id);assert.equal(f.queue.move(f.item.id).items[0].move.status,'failed');assert.equal(summary(f.item,f.store.get(f.item.projectId)).uploaded,1);assert.equal(fs.existsSync(f.file),true);f.queue.moveFile=require('../app/windows-move.cjs').moveNoReplace;assert.equal(f.queue.move(f.item.id).items[0].move.status,'complete');});
test('termination after link or after unlink reconciles intended target and updates reopen path',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);const folder=path.join(f.dir,'완료된 시험지');fs.mkdirSync(folder);const target=path.join(folder,path.basename(f.file));fs.linkSync(f.file,target);f.item.move={status:'moving',target};f.queue.save();const r=new ExamQueue({directory:f.store.dataDir,store:f.store});assert.equal(r.item(f.item.id).currentPath,target);assert.equal(r.move(f.item.id).items[0].move.status,'complete');assert.equal(fs.existsSync(f.file),false);assert.equal(f.store.get(f.item.projectId).source.path,target);});
test('corrupt journal is preserved and cannot silently replace restart state',t=>{const f=fixture(t);fs.writeFileSync(f.queue.file,'corrupt');assert.throws(()=>new ExamQueue({directory:f.store.dataDir,store:f.store}),/기존 파일을 보존/);assert.equal(fs.readFileSync(f.queue.file,'utf8'),'corrupt');});

test('failed result lookup preserves unknown upload and never authorizes resend',async t=>{const f=fixture(t);f.item.steps['p:u']={kind:'upload',status:'unknown',fingerprint:hash({q:1}),responses:[]};const result=await f.queue.stage(f.item.id,'p:u','upload',{q:1},()=>assert.fail('lookup failure must not resend'),()=>{throw Object.assign(Error('authentication expired'),{status:401});});assert.equal(result.held,true);assert.equal(f.item.steps['p:u'].unknownKind,'upload');assert.equal(f.queue.state.mode,'paused');});
test('explicit retry resets resolved discovery errors without dropping region confirmations',t=>{const f=fixture(t);f.item.discoveryIssues=['network page failure'];f.item.status='held';f.queue.action('retry',f.item.id);assert.deepEqual(f.item.discoveryIssues,[]);assert.equal(f.item.status,'pending');});
test('termination after original unlink recovers target without copying or resending',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);const folder=path.join(f.dir,'완료된 시험지');fs.mkdirSync(folder);const target=path.join(folder,path.basename(f.file));fs.linkSync(f.file,target);fs.unlinkSync(f.file);f.item.move={status:'moving',target};f.queue.save();const restored=new ExamQueue({directory:f.store.dataDir,store:f.store});assert.equal(restored.item(f.item.id).currentPath,target);assert.equal(restored.item(f.item.id).move.status,'complete');assert.equal(restored.move(f.item.id).items[0].move.status,'complete');assert.equal(f.store.get(f.item.projectId).source.path,target);assert.equal(fs.readdirSync(folder).length,1);});

test('metadata confirmed at preflight detects a previously unknown scan identity',t=>{const f=fixture(t),file=path.join(f.dir,'unknown.png');fs.writeFileSync(file,'different scan');const other=f.queue.add([file]).added[0].id;assert.equal(f.queue.item(other).duplicateCandidate,null);f.queue.edit(other,{metadata:{school:'신구중',grade:'중2',academicYear:'2026',semester:'2학기',exam:'기말고사'}});assert.equal(f.queue.item(other).duplicateCandidate,f.item.id);assert.equal(f.queue.item(other).status,'held');assert.equal(f.queue.next().id,f.item.id);});

test('preflight metadata and scope changes invalidate completed dependent checkpoints before move',t=>{const f=fixture(t),p=problem(f);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});for(const stage of ['recognition','solve','analysis','upload'])f.item.steps[p.id+':'+stage].status='complete';assert.equal(summary(f.item,f.store.get(f.item.projectId)).whole,true);f.queue.edit(f.item.id,{metadata:{school:''}});assert.equal(f.item.steps[p.id+':upload'].status,'pending');assert.throws(()=>f.queue.move(f.item.id),/전체 문항/);assert.equal(fs.existsSync(f.file),true);f.item.steps[p.id+':upload'].status='complete';f.queue.edit(f.item.id,{scope:DEFAULT_SCOPE,scopeConfirmed:true});assert.equal(f.item.steps[p.id+':recognition'].status,'complete');for(const stage of ['solve','analysis','upload'])assert.equal(f.item.steps[p.id+':'+stage].status,'pending');});

test('lost acknowledgement after real rename is reconciled without a second move',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);let moves=0;const native=require('../app/windows-move.cjs').moveNoReplace;f.queue.moveFile=(source,target,options)=>{moves++;native(source,target,options);throw Object.assign(Error('move reply lost'),{moveResultUnknown:true});};const result=f.queue.move(f.item.id).items[0];assert.equal(result.move.status,'complete');assert.equal(moves,1);assert.equal(fs.existsSync(f.file),false);assert.equal(summary(f.item,f.store.get(f.item.projectId)).uploaded,1);f.queue.move(f.item.id);assert.equal(moves,1);});
test('response loss and unavailable lookup recover at restart without another rename',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);let offline=false,moves=0;const native=require('../app/windows-move.cjs').moveNoReplace;f.queue.io={...fs,statSync(...args){if(offline)throw Object.assign(Error('share disconnected during lookup'),{code:'ECONNRESET'});return fs.statSync(...args);}};f.queue.moveFile=(source,target,options)=>{moves++;native(source,target,options);offline=true;throw Object.assign(Error('native response lost'),{moveResultUnknown:true});};assert.equal(f.queue.move(f.item.id).items[0].move.status,'unknown');const target=f.item.move.target;const resumed=new ExamQueue({directory:f.store.dataDir,store:f.store,moveFile:()=>assert.fail('already moved')});assert.equal(resumed.item(f.item.id).move.status,'complete');assert.equal(resumed.item(f.item.id).currentPath,target);assert.equal(f.store.get(f.item.projectId).source.path,target);assert.equal(moves,1);});
test('OS collision appearing after path choice is preserved and gets a distinct name',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);let race=true,collision;const native=require('../app/windows-move.cjs').moveNoReplace;f.queue.moveFile=(source,target,options)=>{if(race){race=false;collision=target;fs.writeFileSync(target,'other process file');}return native(source,target,options);};assert.equal(f.queue.move(f.item.id).items[0].move.status,'complete');assert.equal(fs.readFileSync(collision,'utf8'),'other process file');assert.notEqual(f.item.currentPath,collision);assert.equal(fs.existsSync(f.file),false);});
test('rename collision retries are bounded; repeated collisions never remove the original',t=>{const f=fixture(t);f.queue.edit(f.item.id,{metadata:{numbering:{total:1,confirmed:true}}});problem(f);let attempts=0;f.queue.moveFile=()=>{attempts++;throw Object.assign(Error('concurrent name reservation'),{code:'EEXIST'});};assert.equal(f.queue.move(f.item.id).items[0].move.status,'failed');assert.equal(attempts,8);assert.equal(fs.existsSync(f.file),true);});
test('changed external source is held before resuming an existing project',t=>{const f=fixture(t);problem(f);fs.writeFileSync(f.file,'changed original');assert.throws(()=>f.queue.ensureProject(f.item.id),/내용이 바뀌/);assert.equal(f.store.get(f.item.projectId).problems.length,1);});
