const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../web-bank/mock-exam-model.cjs'),C=require('../app/curriculum.js'),S=require('../app/exam-scope-allocation.cjs'),B=require('../app/bank-exam-model.cjs');
const units=C.tree[1].children.flatMap(t=>t.children).slice(0,3).map(c=>C.descendants(c.id));
function row(id,unit=units[0][0],score=5,format='선택형',school='검증중'){return {question_id:id,revision_id:'r-'+id,metadata:{source:{kind:'학교기출',school},content:{responseType:format},classification:{primaryUnit:{id:unit}}},confirmed:{difficulty:score}};}
function doc(specs,count=2){const d=M.create('mock');d.title='자유 이름';d.schools=['검증중'];d.profile={low:0,middle:100,high:0,targetAverage:5};d.counts={A:{choice:count},B:{choice:count,written:1}};for(const [id,kind,scope]of specs){M.addVariant(d,kind,id);d.variants.at(-1).units=scope;}return d;}
const run=(d,c,targets=d.variants.map(v=>v.id),extra={})=>M.compose({document:d,snapshot:{id:'snapshot',at:'2026-10-10',candidates:c,excludeIds:[],...extra},targetIds:targets});
test('same scope shares nested prefixes, across A/B and B written slots',()=>{const d=doc([['a','A',units[0]],['b','B',units[0]],['c','B',units[0]]]);const r=run(d,[row('x'),row('y'),row('z'),row('w',units[0][0],5,'서술형')]);assert(r.complete);assert.equal(r.sharing.distinct,3);assert(r.sharing.optimal);assert.deepEqual(r.updates.map(u=>u.paper.items.length),[2,3,3]);assert.equal(r.updates[0].paper.items.filter(i=>i.responseType==='서술형').length,0);});
test('partial overlap and subset-only overlap cover each full range',()=>{const d=doc([['a','A',[...units[0],...units[1]]],['b','A',[...units[1],...units[2]]],['c','A',units[2]]]);const r=run(d,[row('u0',units[0][0]),row('u1',units[1][0]),row('u2',units[2][0]),row('u3',units[2][0])]);assert(r.complete);assert.equal(r.sharing.distinct,4);for(const u of r.updates){assert.equal(u.paper.items.length,2);assert.equal(new Set(u.paper.items.map(i=>i.questionId)).size,2);}assert.deepEqual(new Set(r.updates[0].paper.items.map(i=>i.questionId)),new Set(['u0','u1']));});
test('different chapter quotas share the smaller allocation; disjoint scopes do not share',()=>{const d=doc([['a','A',units[0]],['b','A',[...units[0],...units[1]]],['c','A',units[2]]],4);const c=Array.from({length:12},(_,i)=>row('q'+i,units[Math.floor(i/4)][0]));const r=run(d,c);assert(r.complete);const ids=r.updates.map(u=>new Set(u.paper.items.map(i=>i.questionId)));assert.equal([...ids[0]].filter(id=>ids[1].has(id)).length,2);assert.equal([...ids[0]].filter(id=>ids[2].has(id)).length,0);});
test('partial chapter weights and written rounding reuse the canonical allocator',()=>{const d=doc([['b','B',[...units[0],...units[1].slice(0,1)]]],4);d.counts.B.written=2;const candidates=[];for(const u of d.variants[0].units)for(let i=0;i<6;i++)candidates.push(row(u+i,u,5,i<3?'선택형':'서술형'));const r=run(d,candidates);assert(r.complete);const canonical=B.selectQuestions(candidates,M.rulesFor(d,d.variants[0]));assert.deepEqual(r.updates[0].paper.scopeAllocation.groups.map(g=>[g.weight,g.count,g.writtenCount]),canonical.scopeAllocation.groups.map(g=>[g.weight,g.count,g.writtenCount]));assert.equal(S.scopeWeights(d.variants[0].units)[1].weight,1/units[1].length);});
test('joint format/difficulty feasibility avoids greedy false shortages',()=>{const d=doc([['b','B',units[0]]],1);d.profile={low:50,middle:0,high:50,targetAverage:5.5};const r=run(d,[row('tempt',units[0][0],8),row('required',units[0][0],8,'서술형'),row('low',units[0][0],3)]);assert(r.complete);assert.deepEqual(new Set(r.updates[0].paper.items.map(i=>i.questionId)),new Set(['required','low']));const fail=run(d,[row('only-high',units[0][0],8),row('only-low',units[0][0],3)]);assert(!fail.complete);assert(fail.failures[0].shortages.some(s=>s.label==='서술형'&&s.missing===1));});
test('school boundaries, exclusions, and generation failure preserve originals',()=>{const d=doc([['a','A',units[0]]]);const before=JSON.stringify(d),r=run(d,[row('x'),row('y'),row('outside',units[0][0],5,'선택형','다른중')],undefined,{excludeIds:['x']});assert(!r.complete);assert.equal(JSON.stringify(d),before);assert.throws(()=>M.apply(d,r));});
test('a school name on a textbook or generated question never makes it an exam source',()=>{const d=doc([['a','A',units[0]]]),book=row('book'),generated=row('generated');book.metadata.source.kind='교재';generated.metadata.source.kind='AI생성';assert(!run(d,[row('one'),book,generated]).complete);});
test('add/regenerate target only retains untouched paper bytes and frozen revision',()=>{let d=doc([['a','A',units[0]]]);const c=[row('x'),row('y'),row('z')];d=M.apply(d,run(d,c));d.variants[0].paper.items[0].breakBefore='page';d.variants[0].paper.layout=[{columns:[['x'],['y']]}];const original=JSON.stringify(d.variants[0]);M.addVariant(d,'B','b');d.variants[1].units=units[0];d.schools.push('추가중');const changed=c.map(x=>({...x,revision_id:'new-'+x.question_id}));const r=run(d,[...changed,row('w',units[0][0],5,'서술형')],['b']);assert(r.complete);const n=M.apply(d,r);assert.equal(JSON.stringify(n.variants[0]),original);for(const i of n.variants[1].paper.items.filter(i=>i.responseType==='선택형'))assert(i.revisionId.startsWith('r-'));assert.equal(JSON.stringify(M.apply(n,run(n,[...changed,row('w',units[0][0],5,'서술형')],['b'])).variants[0]),original);});
test('all selected external variants excluded, current internal sharing still allowed',()=>{const prior=doc([['a','A',units[0]],['b','A',units[1]]],1);prior.variants[0].paper={items:[{questionId:'x'}]};prior.variants[1].paper={items:[{questionId:'y'}]};assert.deepEqual(M.excludedIds([prior]),['x','y']);const d=doc([['a','A',units[0]],['b','A',units[0]]],1);const r=run(d,[row('x'),row('y'),row('z')],undefined,{excludeIds:M.excludedIds([prior])});assert(r.complete);assert.equal(r.sharing.distinct,1);assert(r.updates.every(u=>u.paper.items[0].questionId==='z'));});
test('stable IDs survive deletes and replacements; save round trip preserves all state',()=>{const d=doc([['a','A',units[0]],['b','A',units[1]]]);const second=JSON.stringify(d.variants[1]);d.variants=d.variants.filter(v=>v.id!=='a');M.addVariant(d,'A','c');assert.equal(JSON.stringify(d.variants[0]),second);assert.equal(d.variants[1].label,'A3');assert.deepEqual(JSON.parse(JSON.stringify(d)),d);});
test('small solver matches an independent exhaustive union oracle',()=>{for(let seed=1;seed<=12;seed++){const d=doc([['a','A',[...units[0],...units[1]]],['b','A',[...units[1],...units[2]]]],2);const c=Array.from({length:8},(_,i)=>row('q'+i,units[(i+seed)%3][0]));const r=run(d,c);assert(r.complete);const options=d.variants.map(v=>{const allowed=c.filter(q=>v.units.includes(q.metadata.classification.primaryUnit.id)),out=[];for(let i=0;i<allowed.length;i++)for(let j=i+1;j<allowed.length;j++)if(allowed[i].metadata.classification.primaryUnit.id!==allowed[j].metadata.classification.primaryUnit.id)out.push([allowed[i].question_id,allowed[j].question_id]);return out;});let optimum=Infinity;for(const a of options[0])for(const b of options[1])optimum=Math.min(optimum,new Set([...a,...b]).size);assert.equal(r.sharing.distinct,optimum);assert(r.sharing.optimal);}});
test('large-bank worker algorithm produces complete conditions and bounded sharing claim',()=>{const d=doc(Array.from({length:10},(_,i)=>['v'+i,i%2?'B':'A',[...units[0],...units[1],...units[2]]]),25);d.counts.B={choice:19,written:4};d.profile={low:30,middle:50,high:20,targetAverage:5};const c=Array.from({length:3000},(_,i)=>row('q'+String(i).padStart(5,'0'),units[i%3][0],[3,5,8][Math.floor(i/3)%3],i%5===0?'서술형':'선택형'));const start=performance.now(),r=run(d,c);assert(r.complete);assert.equal(r.sharing.optimal,false);assert(performance.now()-start<10000);console.log('3000 candidates, 10 variants:',Math.round(performance.now()-start),'ms, distinct',r.sharing.distinct);});
