'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const D=require('../app/difficulty-assessment.cjs'),Cache=require('../app/assessment-cache.cjs'),{BankAnalysis}=require('../app/bank-analysis.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{ProjectStore}=require('../app/store.cjs'),{FakeAuth,MemoryDrive}=require('./bank-fixtures.cjs');
const assessment=()=>require('./fixtures/access-assessment.cjs').accessAssessment('S1');
const response=score=>({originalNumber:'5',primaryUnitId:null,relatedUnitIds:[],conditionUnitIds:[],solutions:[],score,reason:'풀이 개념·추론 단계',types:[],typeReason:'유형 근거 부족',assessment:assessment(score)});
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'phase15-')),store=new ProjectStore(dir),file=path.join(dir,'source.png');fs.writeFileSync(file,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64'));const bank=new QuestionBank({directory:dir,store,storage:new MemoryDrive(),auth:new FakeAuth(),appVersion:'test',buildDocx:async(_,file)=>fs.writeFileSync(file,'mock DOCX'),preview:async()=>{throw Error('preview optional');}});bank.wake=()=>{};t.after(()=>{bank.close();fs.rmSync(dir,{recursive:true,force:true});});function project(body='같은 문제'){let p=store.create(file);p=store.addRegion({projectId:p.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+fs.readFileSync(file).toString('base64')});p=store.updateProblem(p.id,p.problems[0].id,x=>{x.original={id:'q-'+p.id,kind:'original',body,choices:['1','2'],answer:'1',solution:'두 조건에서 값을 대입',diagram:{points:[{name:'A',x:1,y:2}]},approval:{status:'approved'}};x.recognition={originalNumber:'5',conditions:[]};});return p;}return {dir,store,file,bank,project};}
test('four bands preserve raw/direct/calibrated sources, teacher band never becomes a number; invalid12 rejected',()=>{
 assert.deepEqual([3,4,5,6.5,8,10].map(D.band),['쉬움','보통','보통','보통','어려움','아주어려움']);assert.throws(()=>D.score(12));assert.equal(D.normalize({...assessment(),accessLevel:'invalid'}).status,'format_error');
 const c={metadata:{source:{school:'A',grade:'중2'},difficulty:{aiScore:'4.5',aiBand:'보통',criteriaVersion:D.version,scope:{grade:'중2'}}},confirmed:{difficultyBand:'아주어려움'}};
 assert.equal(D.effective(c).number,4.5);assert.equal(D.effective(c).band,'보통');assert.equal(c.confirmed.difficultyBand,'아주어려움');assert.equal(D.statistics([c])[0].all.average,4.5);assert.equal(D.statistics([c])[0].all.distribution.보통,1);
 assert.equal(D.effective({metadata:{difficulty:{aiScore:'4.5',criteriaVersion:D.version,teacherBand:'아주어려움'}},confirmed:{difficultyBand:null}}).band,'보통');
 c.confirmed.difficulty='6.2';c.metadata.difficulty.reassessmentRequired=true;assert.equal(D.effective(c).number,6.2);assert.equal(D.effective(c).numberSource,'교사 검수');assert.equal(require('../app/bank-calibration.cjs').calibrate({rawScore:12},[]).status,'format_error');
 const old={metadata:{difficulty:{aiScore:'4.5',calibratedScore:'4.2',calibration:{version:'old'}}}};assert.equal(D.effective(old).number,null);assert.equal(old.metadata.difficulty.aiScore,'4.5');
});
test('same content in new project and model changes reuse without calls; only changed diagram/conditions expire',async t=>{
 const e=setup(t),p=e.project();let calls=0,model='old-model';const analyzer=new BankAnalysis({store:e.store,getSettings:()=>({model}),getBridge:()=>({run:async()=>{calls++;return {result:response('4.5')};}})}),args=p=>({projectId:p.id,questionIds:[p.problems[0].original.id]});
 await analyzer.run(e.bank,args(p));assert.equal(calls,1);model='new-model';await analyzer.run(e.bank,args(p));assert.equal(calls,1);
 const second=e.project();await analyzer.run(e.bank,args(second));assert.equal(calls,1,'reupload no additional AI');let items=Object.values(e.bank.state.items);assert.ok(items.every(i=>i.metadata.analysis.model==='old-model'));
 const priorItem=items.find(i=>i.projectId===p.id);priorItem.metadata.difficulty.calibratedScore='4.8';priorItem.metadata.difficulty.calibration={version:'old-applied'};e.store.updateProblem(p.id,p.problems[0].id,x=>x.original.diagram.points[0].x=9);e.bank.catalog(p.id);assert.equal(Object.values(e.bank.state.items).find(i=>i.projectId===p.id).metadata.difficulty.aiScore,null);await analyzer.run(e.bank,args(second));assert.equal(calls,1,'unrelated unchanged item not reevaluated');await analyzer.run(e.bank,args(p));assert.equal(calls,2);assert.equal(priorItem.metadata.difficulty.calibratedScore,undefined);assert.equal(priorItem.metadata.difficulty.previousAssessment,undefined);
 e.bank.edit([Object.values(e.bank.state.items).find(i=>i.projectId===p.id).id],{userScore:'8.2'});e.store.updateProblem(p.id,p.problems[0].id,x=>x.recognition.conditions.push({text:'AB=4',origin:'printed'}));await analyzer.run(e.bank,{...args(p),automatic:true});assert.equal(calls,2);assert.equal(Object.values(e.bank.state.items).find(i=>i.projectId===p.id).metadata.difficulty.userScore,'8.2');
 const prior=Cache.basis(second.problems[0].original,second.problems[0],second.scope);assert.equal(prior,Cache.basis({...second.problems[0].original,label:'표시 이름',tags:['b','a']},{...second.problems[0],label:'다른 이름'},second.scope));
 const plan=Cache.comparisonPlan(Object.values(e.bank.state.items),{targetModel:model});assert.equal(plan.aiCalls,0);assert.equal(plan.referenceTruth,false);
 await analyzer.run(e.bank,{...args(second),compare:true});const compared=Object.values(e.bank.state.items).find(i=>i.projectId===second.id);assert.equal(compared.metadata.analysis.model,'old-model');assert.equal(compared.metadata.analysisComparisons[0].model,'new-model');
});
test('embedded assessment avoids default extra call; invalid/missing individual results do not block automatic registration',async t=>{
 const e=setup(t),p=e.project();e.store.updateProblem(p.id,p.problems[0].id,x=>x.original.assessment=Cache.record(assessment(),x.original,x,p.scope,{model:'initial-model'}));let calls=0;const analyzer=new BankAnalysis({store:e.store,getSettings:()=>({model:'changed'}),getBridge:()=>({run:async()=>{calls++;throw Error('must not call');}})});
 await analyzer.run(e.bank,{projectId:p.id,questionIds:[p.problems[0].original.id],automatic:true});assert.equal(calls,0);let item=Object.values(e.bank.state.items)[0];assert.equal(item.metadata.difficulty.aiScore,'4.5');assert.equal(item.metadata.analysis.model,'initial-model');
 const bad=e.project('다른 문제');e.store.updateProblem(bad.id,bad.problems[0].id,x=>x.original.assessment=Cache.record({...assessment(),accessLevel:'invalid'},x.original,x,bad.scope,{}));await analyzer.run(e.bank,{projectId:bad.id,questionIds:[bad.problems[0].original.id],automatic:true});assert.equal(calls,0);item=Object.values(e.bank.state.items).find(i=>i.projectId===bad.id);assert.equal(item.metadata.difficulty.aiScore,null);assert.equal(item.metadata.difficulty.assessmentStatus,'format_error');await e.bank.root();await e.bank.enqueue(bad.id,[bad.problems[0].original.id]);await e.bank.pump();assert.equal(e.bank.state.jobs.at(-1).status,'complete');assert.equal(calls,0);
});
test('bounded bad-response retry and global service failure hold remaining questions without spreading failure',async t=>{
 const e=setup(t),p=e.project();let mode='bad',calls=0;const analyzer=new BankAnalysis({store:e.store,getSettings:()=>({model:'mock'}),getBridge:()=>({run:async()=>{calls++;if(mode==='service')throw Object.assign(Error('service unavailable'),{status:503});return {result:{...response('4.5'),score:'12'}};}})});
 let result=await analyzer.run(e.bank,{projectId:p.id,questionIds:[p.problems[0].original.id]});assert.equal(calls,2);assert.equal(result.errors.length,1);assert.equal(result.waiting,false);
 e.store.updateProblem(p.id,p.problems[0].id,x=>x.variants.push({...structuredClone(x.original),id:'second-question',kind:'variant',body:'다른 문제'}));mode='service';result=await analyzer.run(e.bank,{projectId:p.id,questionIds:[p.problems[0].original.id,'second-question']});assert.equal(calls,3);assert.equal(result.waiting,true);assert.equal(result.errors.length,1);assert.equal(result.waitingIds.length,2);assert.equal(e.bank.state.analysisProgress.status,'waiting');e.bank.auth.config=()=>({spaceId:'test'});e.bank.storage.rows=async()=>{throw Object.assign(Error('authentication expired'),{status:401});};result=await analyzer.run(e.bank,{projectId:p.id,questionIds:[p.problems[0].original.id,'second-question']});assert.equal(result.waiting,true);assert.equal(result.waitingIds.length,2);assert.equal(calls,3,'global preflight failure does not reach AI');
});
test('school statistics and point-rank references are pure saved-data calculations, separate exam/section',()=>{
 const rows=Array.from({length:6},(_,i)=>({question_id:String(i),metadata:{source:{school:'A',grade:'중2',documentId:'examA',originalNumber:String(i+1),originalPoints:i%2?2:4,numbering:{section:'objective'}},difficulty:{aiScore:String(i+1),scope:{unit:'same'},criteriaVersion:D.version},classification:{types:[{name:i%2?'증명':'계산'}]}}}));
 assert.equal(D.pointSignals(rows).length,1);assert.equal(D.pointSignals(rows.map(c=>({...c,metadata:{...c.metadata,source:{...c.metadata.source,originalPoints:4}}}))).length,0);assert.equal(D.pointSignals(rows.slice(0,4)).length,0);assert.equal(D.pointSignals(rows.map((c,i)=>({...c,metadata:{...c.metadata,source:{...c.metadata.source,documentId:'exam'+i}}}))).length,0);
 const stats=D.statistics(rows)[0];assert.equal(stats.all.average,3.5);assert.equal(stats.all.median,3.5);assert.equal(stats.objective.total,6);assert.equal(stats.written.total,0);assert.deepEqual(stats.all.questionTypes,{계산:3,증명:3});assert.equal(require('../app/bank-calibration.cjs').calibrate({rawScore:'4.5'},[]).score,'4.5');
});
module.exports={assessment};
