'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ProjectStore}=require('../app/store.cjs'),{Workflow}=require('../app/workflow.cjs'),{recognition,validation}=require('./workflow-fixtures.cjs'),D=require('../app/difficulty-assessment.cjs');
test('same recognition bytes in another project reuse before provider; solved assessment shares existing request and malformed score cannot fail the solution',async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'phase15-workflow-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const file=path.join(directory,'original.png'),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64');fs.writeFileSync(file,png);const store=new ProjectStore(directory);
 function make(){let p=store.create(file);return store.addRegion({projectId:p.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});}
 let calls=0,model='first-model',bad=false;const evidence=require('./fixtures/access-assessment.cjs').accessAssessment('S1');
 const workflow=new Workflow({store,directory,getSettings:()=>({model,effort:'high'}),getBridge:()=>({run:async req=>{calls++;assert.match(req.execution.instructions,/assessment 안에/);return {tokens:{output:100},result:req.execution.task==='recognition'?{reply:'인식',recognition:{...recognition(),assessment:evidence}}:{reply:'풀이',answer:'2',solution:'조건에서 값을 대입하여 2를 구한다.',questionType:'single_value',validation:validation(),holdReason:'',assessment:bad?{...evidence,accessLevel:'invalid'}:evidence}};}})});
 const a=make(),base=p=>({projectId:p.id,problemId:p.problems[0].id,provider:'codex'});await workflow.run({...base(a),task:'recognition'});assert.equal(calls,1);model='second-model';const b=make(),cached=await workflow.run({...base(b),task:'recognition'});assert.equal(calls,1);assert.equal(cached.run.aiCalls,0);assert.equal(cached.run.tokens,null);assert.equal(cached.run.responseModel,'first-model');assert.equal(store.get(b.id).problems[0].original.assessment.model,'first-model');
 workflow.confirmSource(b.id,b.problems[0].id);await workflow.run({...base(b),task:'solve',force:true});assert.equal(calls,2);let q=store.get(b.id).problems[0].original;assert.equal(q.assessment.score,'4.5');assert.equal(q.assessment.model,'second-model');bad=true;await workflow.run({...base(b),task:'solve',force:true});q=store.get(b.id).problems[0].original;assert.equal(q.answer,'2');assert.equal(q.assessment.status,'format_error');assert.equal(q.assessment.score,null);assert.equal(calls,3);
});
