'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),D=require('../app/difficulty-assessment.cjs');
const {localServer}=require('./shared-bank-local-server.cjs');
test('teacher bands and direct numbers preserve originals and SQL filters agree with stored-data statistics',async t=>{
 const x=await localServer();t.after(()=>x.close());const rpc=(uid,name,args)=>x.auth(uid).request('/rest/v1/rpc/'+name,{method:'POST',body:args});await rpc(x.A,'bank_join',{s:x.S});await rpc(x.A,'bank_invite',{s:x.S,email_address:'teacher-b@example.test',enabled_value:true});await rpc(x.B,'bank_join',{s:x.S});
 const q=crypto.randomUUID(),r=crypto.randomUUID(),f=crypto.randomUUID();await x.db.exec('reset role');await x.db.query("insert into bank_questions(id,space_id,owner_id,owner_email) values($1,$2,$3,'animochoi@gmail.com')",[q,x.S,x.A]);await x.db.query("insert into bank_revisions(id,question_id,actor_id,committed,visibility) values($1,$2,$3,true,'approved')",[r,q,x.A]);await x.db.query("insert into bank_entries(id,space_id,name,kind,owner_id) values($1,$2,'commit','file',$3)",[f,x.S,x.A]);
 const metadata={source:{school:'통계중',grade:'중2',documentId:crypto.randomUUID(),originalNumber:'5',originalPoints:4},difficulty:{aiScore:'4.0',aiBand:'보통',criteriaVersion:D.version,scope:{grade:'중2'},assessment:{model:'historical-model'}},classification:{types:[{name:'증명'}]}};await x.db.query("insert into bank_catalog(revision_id,space_id,question_id,commit_id,metadata,content,files,confirmed) values($1,$2,$3,$4,$5,'{}','[]',$6)",[r,x.S,q,f,metadata,{sharingNote:'legacy'}]);
 await rpc(x.B,'bank_difficulty_save',{r,p:{difficultyBand:'아주어려움',originalPointsReviewed:true},expected:0});const rows=await rpc(x.B,'bank_difficulty_rows',{s:x.S});assert.equal(rows[0].metadata.difficulty.aiScore,'4.0');assert.equal(rows[0].metadata.difficulty.assessment.model,'historical-model');assert.equal(D.statistics(rows)[0].all.average,4);assert.equal(D.statistics(rows)[0].all.distribution.보통,1);
 assert.equal((await rpc(x.B,'bank_search_current',{s:x.S,filters:{difficultyBand:'아주어려움'},start_at:0})).length,0);assert.equal((await rpc(x.B,'bank_search_current',{s:x.S,filters:{difficultyBand:'보통'},start_at:0})).length,1);
 await assert.rejects(rpc(x.B,'bank_difficulty_save',{r,p:{difficulty:'12'},expected:1}),/범위/);await assert.rejects(rpc(x.B,'bank_difficulty_save',{r,p:{difficulty:'6.2'},expected:null}),/최신/);
 await rpc(x.B,'bank_difficulty_save',{r,p:{difficulty:'6.2'},expected:1});const updated=await rpc(x.B,'bank_difficulty_rows',{s:x.S});assert.equal(D.statistics(updated)[0].all.average,6.2);assert.equal(updated[0].confirmed.sharingNote,'legacy');assert.equal(updated[0].metadata.difficulty.aiScore,'4.0');assert.equal((await rpc(x.B,'bank_search_current',{s:x.S,filters:{min:'6.0',max:'6.5'},start_at:0})).length,1);await assert.rejects(rpc(x.X,'bank_difficulty_rows',{s:x.S}));
});
