const test=require('node:test'),assert=require('node:assert/strict');
const {shuffleChoices,rubricErrors,rubricPolicy,withRubric}=require('../app/production-policy.cjs');
const {item,validation}=require('./workflow-fixtures.cjs');
test('shuffle updates answer, solution, verification and rubric references together',()=>{
 const i=item();i.questionType='single_choice';i.question.choices=['① 2','② 4','③ 6'];i.question.answer='②';i.question.solution='①은 틀림, ②가 맞음. 선택지 2번을 확인.';i.validation.correctChoiceIndices=[1];i.validation.rubric.steps[0].description='②를 선택';const m=shuffleChoices(i,()=>0);
 assert.deepEqual(m.order,[1,2,0]);assert.deepEqual(i.question.choices,['4','6','2']);assert.equal(i.question.answer,'① 4');assert.match(i.question.solution,/③은 틀림, ①가 맞음/);assert.match(i.question.solution,/선택지 1번/);assert.equal(i.validation.rubric.steps[0].description,'①를 선택');assert.deepEqual(i.validation.correctChoiceIndices,[0]);
});
test('choice shuffle never changes short answer questions or malformed answer references',()=>{const i=item(),before=structuredClone(i);assert.equal(shuffleChoices(i),null);assert.deepEqual(i,before);i.questionType='single_choice';i.question.choices=['a','b'];i.validation.correctChoiceIndices=[9];assert.equal(shuffleChoices(i),null);});
test('grading requires positive step allocations totaling six; includes wrong-option reasons',()=>{const r=validation().rubric;assert.deepEqual(rubricErrors(r),[]);r.steps[0].points=3;assert.equal(rubricErrors(r).length,1);assert.equal(rubricErrors(null).length,1);assert.match(rubricPolicy,/틀린 보기.*왜 틀렸는지/);assert.match(withRubric('풀이',validation().rubric),/총 6점/);});
test('PDF always includes fast answers then detailed solutions, including legacy student requests',()=>{const {documentHtml}=require('../app/pdf-export.cjs');const q={...item().question,solution:withRubric('SECRET SOLUTION',validation().rubric)};const base={title:'<script>evil</script>',settings:{workspaceLines:0,audience:'student'},questions:[q]};const student=documentHtml(base);assert.ok(student.includes('SECRET SOLUTION'));assert.ok(student.indexOf('빠른 정답')<student.indexOf('상세 풀이'));assert.ok(student.includes('총 6점'));assert.ok(student.includes('&lt;script&gt;'));const teacher=documentHtml({...base,settings:{...base.settings,audience:'teacher'}});assert.match(teacher,/SECRET SOLUTION/);assert.match(teacher,/총 6점/);assert.match(teacher,/column-rule/);});
