'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ProjectStore}=require('../app/store.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),M=require('../app/bank-model.cjs');
const {FakeAuth,MemoryDrive}=require('./bank-fixtures.cjs');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64');
test('retired provenance commit failure preserves its existing payload and blocks duplicate uploads after restart',async t=>{
 const s=setup(t),id=s.p.problems[0].original.id;
 await s.bank.root();await s.bank.enqueue(s.p.id,[id]);
 const put=s.storage.put.bind(s.storage);let commitAttempts=0;
 s.storage.put=async args=>{if(args.properties.role==='commit'){commitAttempts++;throw Object.assign(Error('Revision payload frozen or retired'),{code:'conflict'});}return put(args);};
 await s.bank.pump();const job=s.bank.state.jobs[0];assert.equal(job.status,'conflict');assert.equal(job.committed,undefined);
 const fileIds=[...s.storage.files.keys()],outbox=fs.readdirSync(path.join(s.bank.dir,'outbox'));
 await assert.rejects(s.bank.enqueue(s.p.id,[id]),e=>e.code==='conflict'&&e.message.includes(job.revisionId));
 s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.body+=' local edit');
 await assert.rejects(s.bank.enqueue(s.p.id,[id]),/Revision payload frozen or retired/);
 s.bank.close();const restarted=new QuestionBank(s.options);restarted.wake=()=>{};t.after(()=>restarted.close());
 await assert.rejects(restarted.enqueue(s.p.id,[id]),/Revision payload frozen or retired/);
 // Older operator queues stored this server failure as failed rather than conflict.
 restarted.state.jobs[0].status='failed';await assert.rejects(restarted.enqueue(s.p.id,[id]),/Revision payload frozen or retired/);
 await restarted.pump();assert.equal(commitAttempts,1);assert.equal(restarted.state.jobs.length,1);
 assert.deepEqual([...s.storage.files.keys()],fileIds);assert.deepEqual(fs.readdirSync(path.join(s.bank.dir,'outbox')),outbox);
 assert.match(s.store.get(s.p.id).problems[0].original.body,/local edit/);
});
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'exam-bank-'));const store=new ProjectStore(path.join(dir,'data')),source=path.join(dir,'test.png');fs.writeFileSync(source,png);let p=store.create(source);for(let i=0;i<2;i++){p=store.addRegion({projectId:p.id,region:{page:1,x:0,y:i*.4,width:.5,height:.4},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});const target=p.problems.at(-1);p=store.updateProblem(p.id,target.id,q=>{q.original={id:M.uuid(),kind:'original',body:'$\\frac{13}{2}\\mathrm{cm}$, $\\sqrt{2}$, $x_1^2$, $\\angle ABC$, $\\overline{AB}$',choices:['① 1','② 2'],answer:'②',solution:'이유를 설명하고 $x=2$를 구한다.',include:true,approval:{status:'approved',method:'manual_user_authorized'},diagram:require('./workflow-fixtures.cjs').recognition().observedDiagram,figurePlacements:{diagram:'after:0'},hiddenFigureIds:[],statementBox:['ㄱ. 조건'],checks:{ai:{usedConcepts:['삼각형'],status:'passed'}}};q.recognition={confirmed:true,materials:[],printedAnswer:'②',originalNumber:String(17+i)};});}
 const storage=new MemoryDrive(),auth=new FakeAuth();const options={directory:store.dataDir,store,storage,auth,appVersion:'test',buildDocx:async(input,file)=>fs.writeFileSync(file,Buffer.from('MOCK DOCX '+input.project.problems[0].original.body)),preview:async()=>{throw Error('mock optional preview unavailable');}};
 const bank=new QuestionBank(options);bank.wake=()=>{};t.after(()=>{bank.close();fs.rmSync(dir,{recursive:true,force:true});});return {dir,store,p,bank,storage,auth,options};}
async function upload(s,ids=s.p.problems.map(p=>p.original.id)){await s.bank.root();await s.bank.enqueue(s.p.id,ids);await s.bank.pump();assert.ok(s.bank.state.jobs.every(j=>j.status==='complete'),JSON.stringify(s.bank.state.jobs.map(j=>[j.status,j.error])));}
test('native roundtrip in a fresh local store, source deduplication, metadata and DOCX bytes (mock Drive)',async t=>{const s=setup(t);s.bank.catalog(s.p.id);const items=Object.values(s.bank.state.items);s.bank.editSource(s.p.id,'primary',{kind:'학교기출',school:'테스트중',region:'서울',academicYear:'2025',grade:'중2',semester:'2학기',exam:'중간'});s.bank.edit([items[0].id],{userScore:'4.7',tags:['기하'],isReference:true});await upload(s);assert.equal([...s.storage.files.values()].filter(f=>f.meta.appProperties.role==='source').length,1);const job=s.bank.state.jobs[0],original=fs.readFileSync(path.join(s.bank.dir,'outbox',job.id,'question.docx'));
 const otherStore=new ProjectStore(path.join(s.dir,'fresh-pc')),other=new QuestionBank({...s.options,directory:otherStore.dataDir,store:otherStore});other.wake=()=>{};t.after(()=>other.close());await other.root(s.bank.state.root.id);await other.refresh();const restored=await other.restore(job.revisionId),q=restored.project.problems[0].original;assert.deepEqual(q,s.p.problems[0].original);assert.equal(Object.values(other.state.items)[0].metadata.difficulty.userScore,'4.7');assert.equal(Object.values(other.state.items)[0].metadata.difficulty.aiScore,null);assert.deepEqual(fs.readFileSync(path.join(otherStore.projectDir(restored.project.id),'exports','bank-original.docx')),original);assert.deepEqual(fs.readFileSync(restored.project.source.path),png);assert.doesNotMatch(JSON.stringify(JSON.parse(fs.readFileSync(path.join(s.bank.dir,'outbox',job.id,'question.json')))),/C:\\\\Users/);assert.equal(job.previewStatus,'failed_optional');
 const again=new ProjectStore(otherStore.dataDir).get(restored.project.id);assert.equal(again.problems[0].original.body,q.body);
});
test('response loss after commit is idempotent across queue restart; required partial upload is not complete',async t=>{const s=setup(t);await s.bank.root();s.storage.failRole='data';await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);await s.bank.pump();assert.equal((await s.storage.commits(s.bank.state.root.id)).files.length,0);assert.equal(s.bank.state.jobs[0].status,'queued');s.storage.failRole=null;s.storage.loseRole='commit';s.bank.retry(s.bank.state.jobs[0].id);await s.bank.pump();assert.equal(s.bank.state.jobs[0].status,'queued');assert.equal((await s.storage.commits(s.bank.state.root.id)).files.length,1);s.bank.close();const restarted=new QuestionBank(s.options);restarted.wake=()=>{};t.after(()=>restarted.close());restarted.retry(restarted.state.jobs[0].id);await restarted.pump();assert.equal(restarted.state.jobs[0].status,'complete',restarted.state.jobs[0].error);assert.equal((await s.storage.commits(s.bank.state.root.id)).files.length,1);const ids=[...s.storage.files.keys()];await restarted.enqueue(s.p.id,[s.p.problems[0].original.id]);assert.equal(restarted.state.jobs.length,1);assert.deepEqual([...s.storage.files.keys()],ids);});
test('pending snapshot is immutable even if source and question change after enqueue',async t=>{const s=setup(t);await s.bank.root();await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);fs.writeFileSync(s.p.source.path,'changed local source');s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.body='new content');await s.bank.pump();assert.equal(s.bank.state.jobs[0].status,'complete');const restored=await s.bank.restore(s.bank.state.jobs[0].id);assert.equal(restored.project.problems[0].original.body,s.p.problems[0].original.body);assert.deepEqual(fs.readFileSync(restored.project.source.path),png);});
test('branch edits preserve both revisions; changing tags does not move the question folder',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);const base=s.bank.state.jobs[0],one=await s.bank.restore(base.id),two=await s.bank.restore(base.id);for(const [i,result]of [one,two].entries()){s.store.updateProblem(result.project.id,result.project.problems[0].id,p=>p.original.body+=' change'+i);await s.bank.enqueue(result.project.id,[result.project.problems[0].original.id]);await s.bank.pump();}assert.equal(s.bank.state.jobs[1].status,'complete');assert.equal(s.bank.state.jobs[2].status,'conflict');assert.equal(s.bank.state.jobs[2].committed,true);assert.equal(s.bank.state.jobs[2].parentRevisionId,base.id);assert.equal((await s.storage.commits(s.bank.state.root.id,base.questionId)).files.length,3);});
test('source metadata updates and a variant reuse original bytes without moving old folders',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);const first=s.bank.state.jobs[0];s.bank.editSource(s.p.id,'primary',{kind:'학교기출',academicYear:'2020',school:'변경중'});await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);await s.bank.pump();assert.equal(s.bank.state.jobs[1].folderId,first.folderId);const v={...structuredClone(s.p.problems[0].original),id:M.uuid(),kind:'variant',provenance:{variant:'numbers'}};s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.variants.push(v));await s.bank.enqueue(s.p.id,[v.id]);await s.bank.pump();assert.equal(s.bank.state.jobs.at(-1).status,'complete',s.bank.state.jobs.at(-1).error);assert.equal([...s.storage.files.values()].filter(f=>f.meta.appProperties.role==='source').length,1);assert.equal(s.bank.state.items[s.bank.state.jobs.at(-1).questionId].metadata.management.review,'needs_user_review');});
test('remote tampering and absolute file references are rejected',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);const job=s.bank.state.jobs[0],commit=s.bank.state.cache[job.id],asset=commit.files.find(f=>f.role==='asset');s.storage.files.get(asset.id).bytes=Buffer.from('broken');await assert.rejects(s.bank.restore(job.id),/integrity/);const bundle=JSON.parse(fs.readFileSync(path.join(s.bank.dir,'outbox',job.id,'question.json')));bundle.native.project.problems[0].original.body='C:\\Users\\private\\secret.txt';assert.throws(()=>M.restoreSnapshot(bundle,new Map(),path.join(s.dir,'unsafe')));});
test('difficulty keeps null and one decimal, no legacy label conversion',()=>{assert.equal(M.score(null),null);assert.equal(M.score(''),null);assert.equal(M.score('3'),'3.0');assert.equal(M.score('8.2'),'8.2');assert.throws(()=>M.score('10.1'));assert.throws(()=>M.score('4.75'));const m=M.metadata({difficulty:'상',choices:[]},{},{scope:{}});assert.equal(m.difficulty.aiScore,null);assert.equal(m.difficulty.userScore,null);assert.equal(m.difficulty.legacyLabel,'상');});
test('corrupt bank state does not overwrite it or prevent existing project operations',t=>{const s=setup(t);s.bank.close();fs.writeFileSync(s.bank.file,'invalid');const bank=new QuestionBank(s.options);assert.ok(bank.blockedError);bank.close();assert.equal(fs.readFileSync(s.bank.file,'utf8'),'invalid');assert.ok(s.store.get(s.p.id).problems.length);});
test('autosave waits for completed runs, batches edits and persists pending dirty work; offline local edits are visible',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);s.store.onWrite=(p,b)=>s.bank.observe(p,b);s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.solution+=' local edit');assert.equal(Object.values(s.bank.state.items)[0].status,'local');assert.equal(s.bank.state.jobs.length,1);await s.bank.setAuto(true);s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>{p.runs=[{status:'running'}];p.original.solution+=' partial';});assert.equal(s.bank.state.dirty.length,0);s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.runs[0].status='completed');assert.equal(s.bank.state.dirty.length,1);s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.solution+=' final');assert.equal(s.bank.state.dirty.length,1);clearTimeout(s.bank.debounce);const restarted=new QuestionBank(s.options);restarted.wake=()=>{};t.after(()=>restarted.close());await restarted.flushDirty();await restarted.pump();assert.equal(restarted.state.jobs.length,2);assert.equal(restarted.state.jobs.at(-1).status,'complete');assert.match(JSON.parse(fs.readFileSync(path.join(restarted.dir,'outbox',restarted.state.jobs.at(-1).id,'question.json'))).native.project.problems[0].original.solution,/final$/);});
test('no authentication preserves local package; permission errors stop automatic retries',async t=>{const s=setup(t);s.auth.connected=false;await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);await s.bank.pump();const job=s.bank.state.jobs[0];assert.equal(job.status,'auth');assert.ok(fs.existsSync(path.join(s.bank.dir,'outbox',job.id,'question.docx')));await s.bank.connect();await s.bank.root();const {BankError}=require('../app/bank-auth.cjs');s.storage.put=async()=>{throw new BankError('quota full','permission');};await s.bank.pump();assert.equal(job.status,'failed');assert.equal(job.attempts,2);await s.bank.pump();assert.equal(job.attempts,2);});
test('optional external PDF attachment and raw TeX survive without replacing native equations',async t=>{const s=setup(t);s.p=s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.diagram.labels=[{x:2,y:2,text:'\\frac{13}{2}'}]);s.bank.catalog(s.p.id);const item=Object.values(s.bank.state.items)[0],file=path.join(s.dir,'outside-edited.pdf');fs.writeFileSync(file,'%PDF-test-only');s.bank.attach(item.id,[file]);await upload(s,[s.p.problems[0].original.id]);const restored=await s.bank.restore(s.bank.state.jobs[0].id);assert.equal(restored.project.problems[0].original.diagram.labels[0].text,'\\frac{13}{2}');const attachment=s.bank.state.items[item.id].attachments[0];assert.equal(fs.readFileSync(attachment.localPath,'utf8'),'%PDF-test-only');assert.notEqual(attachment.localPath,file);});
test('restored variants keep independent IDs and original question linkage',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);const originalId=s.bank.state.jobs[0].questionId,v={...structuredClone(s.p.problems[0].original),id:M.uuid(),kind:'variant',provenance:{variant:'numbers'}};s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.variants.push(v));await s.bank.enqueue(s.p.id,[v.id]);await s.bank.pump();const variantJob=s.bank.state.jobs.at(-1),restored=await s.bank.restore(variantJob.id);assert.equal(restored.project.problems[0].original.include,false);s.bank.catalog(restored.project.id);const saved=s.bank.state.items[variantJob.questionId];assert.notEqual(saved.id,originalId);assert.equal(saved.metadata.relations.originalQuestionId,originalId);assert.equal(saved.metadata.relations.originalRevisionId,s.bank.state.jobs[0].id);});
test('fresh PC uses question folder ID after source metadata and folder display name change',async t=>{const s=setup(t);await upload(s,[s.p.problems[0].original.id]);s.bank.editSource(s.p.id,'primary',{kind:'학교기출',school:'다른 이름',academicYear:'2024'});await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);await s.bank.pump();const job=s.bank.state.jobs.at(-1);s.storage.files.get(job.folderId).meta.name='사용자가 변경한 폴더 이름';const store=new ProjectStore(path.join(s.dir,'new-pc')),bank=new QuestionBank({...s.options,directory:store.dataDir,store});bank.wake=()=>{};t.after(()=>bank.close());await bank.root(s.bank.state.root.id);await bank.refresh();const restored=await bank.restore(job.id);bank.edit([job.questionId],{userScore:'6.5'});await bank.enqueue(restored.project.id,[restored.project.problems[0].original.id]);await bank.pump();assert.equal(bank.state.jobs[0].status,'complete',bank.state.jobs[0].error);assert.equal(bank.state.jobs[0].folderId,job.folderId);});
test('successful output schedules only selected questions; dirty registration failure remains recoverable',async t=>{const s=setup(t);await s.bank.root();await s.bank.setAuto(true);s.bank.afterExport({projectId:s.p.id,originalsOnly:true});assert.equal(s.bank.state.dirty.length,2);clearTimeout(s.bank.debounce);const original=s.bank.enqueue;s.bank.enqueue=async()=>{throw Error('mock disk unavailable');};await s.bank.flushDirty();assert.equal(s.bank.state.dirty.length,2);s.bank.enqueue=original;await s.bank.flushDirty();assert.equal(s.bank.state.dirty.length,0);assert.equal(s.bank.state.jobs.length,2);});
test('generated source folders use recorded creation year, never infer it from registration year',()=>{assert.deepEqual(M.folderSegments({source:{kind:'AI생성',generatedAt:'2024-12-31T12:00:00Z'}},M.uuid(),'2026-09-30'),['03_유사문제·자체제작','2024년']);assert.deepEqual(M.folderSegments({source:{kind:'자체제작'}},M.uuid(),'2026-09-30'),['03_유사문제·자체제작','연도미상']);});

test('source suggestions require confirmation; saved blanks and internal IDs survive, unchanged confirmation does not dirty uploads',async t=>{
 const s=setup(t);let catalog=s.bank.catalog(s.p.id);assert.equal(catalog.sources[0].suggested,true);assert.equal(catalog.sources[0].metadata.school,null);assert.deepEqual(s.bank.state.sourceMeta,{});
 const metadata={...catalog.sources[0].metadata,school:null,schoolId:'existing-school-id',taxonomyVersion:'existing-v1'};
 s.bank.editSource(s.p.id,'primary',metadata);await upload(s,[s.p.problems[0].original.id]);
 catalog=s.bank.catalog(s.p.id);assert.equal(catalog.sources[0].suggested,false);assert.equal(catalog.sources[0].metadata.school,null);assert.equal(catalog.sources[0].metadata.schoolId,'existing-school-id');assert.equal(catalog.sources[0].metadata.taxonomyVersion,'existing-v1');
 s.bank.editSource(s.p.id,'primary',catalog.sources[0].metadata);assert.equal(s.bank.state.items[s.bank.state.jobs[0].questionId].status,'complete');await s.bank.enqueue(s.p.id,[s.p.problems[0].original.id]);assert.equal(s.bank.state.jobs.length,1);
});
test('AI recommendation remains distinct from user approval after upload and fresh restore',async t=>{
 const s=setup(t);s.bank.catalog(s.p.id);const item=Object.values(s.bank.state.items)[0],p=s.p.problems[0],basis=require('../app/bank-analysis.cjs').basis(p.original,p,s.p.scope);item.metadata.classification.primaryUnit={id:'unit-example',name:'평행사변형의 성질'};item.metadata.classification.suggested={primaryUnit:item.metadata.classification.primaryUnit,reason:'풀이 근거'};item.metadata.classification.status='ai_suggested';item.metadata.difficulty.aiScore='4.7';item.metadata.difficulty.assessment=require('./fixtures/access-assessment.cjs').accessAssessment('S1','R1');item.metadata.difficulty.userScore=null;item.metadata.difficulty.reason='예상 난이도';item.metadata.analysis={status:'complete',basis};s.bank.save();
 await upload(s,[s.p.problems[0].original.id]);const job=s.bank.state.jobs[0];const freshStore=new ProjectStore(path.join(s.dir,'fresh-recommendation'));const fresh=new QuestionBank({...s.options,directory:freshStore.dataDir,store:freshStore});fresh.wake=()=>{};t.after(()=>fresh.close());await fresh.root(s.bank.state.root.id);await fresh.refresh();await fresh.restore(job.id);const restored=Object.values(fresh.state.items)[0].metadata;assert.equal(restored.classification.primaryUnit.name,'평행사변형의 성질');assert.equal(restored.classification.confirmed,null);assert.equal(restored.difficulty.aiScore,'4.7');assert.equal(restored.difficulty.userScore,null);
});
test('authorized latest reupload keeps one question ID and restores matching content, DOCX and recommendation',async t=>{
 const s=setup(t),id=s.p.problems[0].original.id;
 await upload(s,[id]);const first=s.bank.state.jobs[0],bankId=first.questionId;
 s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>{p.original.body+=' 최종 수정';});
 s.bank.catalog(s.p.id);const item=s.bank.state.items[bankId];
 item.metadata.classification.primaryUnit={id:'unit-final',name:'평행사변형의 성질'};
 item.metadata.classification.status='ai_suggested';item.metadata.difficulty.aiScore='4.7';item.metadata.difficulty.assessment=require('./fixtures/access-assessment.cjs').accessAssessment('S1','R1');
 item.metadata.difficulty.userScore=null;s.bank.save();
 await s.bank.enqueue(s.p.id,[id]);await s.bank.pump();
 const latest=s.bank.state.jobs.at(-1);assert.equal(latest.status,'complete');
 assert.equal(latest.questionId,bankId);assert.equal(latest.parentRevisionId,first.revisionId);
 const freshStore=new ProjectStore(path.join(s.dir,'fresh-latest'));
 const fresh=new QuestionBank({...s.options,directory:freshStore.dataDir,store:freshStore});
 fresh.wake=()=>{};t.after(()=>fresh.close());await fresh.root(s.bank.state.root.id);await fresh.refresh();
 const restored=await fresh.restore(latest.revisionId);
 assert.match(restored.project.problems[0].original.body,/최종 수정$/);
 const current=Object.values(fresh.state.items)[0];assert.equal(current.id,bankId);
 assert.equal(current.metadata.difficulty.aiScore,'4.7');
 assert.equal(current.metadata.classification.primaryUnit.name,'평행사변형의 성질');
 assert.match(fs.readFileSync(path.join(freshStore.projectDir(restored.project.id),'exports','bank-original.docx'),'utf8'),/최종 수정/);
 assert.equal((await s.storage.commits(s.bank.state.root.id,bankId)).files.length,2);
});
test('a revision depending on a conflicted uncommitted upload stays paused',async t=>{
 const s=setup(t),id=s.p.problems[0].original.id;await s.bank.root();await s.bank.enqueue(s.p.id,[id]);s.store.updateProblem(s.p.id,s.p.problems[0].id,p=>p.original.body+=' 수정');await s.bank.enqueue(s.p.id,[id]);assert.equal(s.bank.state.jobs[1].parentRevisionId,s.bank.state.jobs[0].revisionId);s.bank.state.jobs[0].status='conflict';await s.bank.pump();assert.equal(s.bank.state.jobs[1].status,'paused');assert.match(s.bank.state.jobs[1].error,/직전 버전이 수정 충돌/);
});
