'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const Policy=require('../app/queue-usage-policy.cjs'),{ExamQueue}=require('../app/exam-queue.cjs');
const window=(usedPercent,duration=10080)=>({usedPercent,windowDurationMins:duration,resetsAt:Math.floor(Date.now()/1000)+86400});
const account=(used=2,secondary=null)=>({account:{type:'chatgpt'},rateLimits:{rateLimitsByLimitId:{codex:{limitId:'codex',primary:window(used),secondary},base_model_inference:{primary:window(99)}}}});
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'queue-usage-policy-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const store={get:()=>({problems:[]})},queue=new ExamQueue({directory,store});queue.state.items.push({id:'q',metadata:{},steps:{},move:{},status:'pending'});queue.action('start');return {queue,directory,store};}
async function run(queue,bridge,key='one'){return queue.stage('q',key,'recognition',{key},()=>queue.bridge(bridge).run({text:key}),()=>true);}
test('percent accepts explicit blank and integer boundaries only',()=>{for(const x of [null,''])assert.equal(Policy.percent(x),null);for(const x of [1,20,100])assert.equal(Policy.percent(x),x);for(const x of [undefined,'20',' ',0,-1,101,1.5,NaN,Infinity,true])assert.throws(()=>Policy.percent(x));});
test('official codex windows never mix reserve or fabricate missing usage',()=>{assert.equal(Policy.accountWindows(account())[0].usedPercent,2);assert.equal(Policy.accountWindows(account(2,window(3,300))).length,2);for(const invalid of [{error:'offline',...account(),error:'offline'},{account:{type:'apikey'}},account(null),account('2'),account(NaN)])assert.throws(()=>Policy.accountWindows(invalid));const missing=account();delete missing.rateLimits.rateLimitsByLimitId.codex;missing.rateLimits.rateLimits={limitId:'codex',primary:window(1)};assert.throws(()=>Policy.accountWindows(missing));const stale=account();stale.rateLimits.rateLimitsByLimitId.codex.primary.resetsAt=1;assert.throws(()=>Policy.accountWindows(stale));});
test('default 20 and disabled historical local caps preserve counters across restart',t=>{const {queue,directory,store}=fixture(t);queue.state.usage={calls:47,tokens:1395047,tokenReports:47};queue.state.limits.maxCalls=55;queue.state.limits.maxTokens=1500000;delete queue.state.limits.remainingPercent;delete queue.state.limits.usageEnabled;queue.save();const reopened=new ExamQueue({directory,store});assert.equal(reopened.state.limits.remainingPercent,20);assert.equal(reopened.state.limits.usageEnabled,false);assert.equal(reopened.state.limits.maxCalls,55);assert.deepEqual(reopened.state.usage,{calls:47,tokens:1395047,tokenReports:47});assert.equal(reopened.state.mode,'paused');});
test('blank release and valid explicit value persist; invalid setting is atomic',t=>{const {queue,directory,store}=fixture(t);queue.action('limits',null,{remainingPercent:null});let reopened=new ExamQueue({directory,store});assert.equal(reopened.state.limits.remainingPercent,null);reopened.action('limits',null,{remainingPercent:35});reopened=new ExamQueue({directory,store});assert.equal(reopened.state.limits.remainingPercent,35);const before=fs.readFileSync(reopened.file,'utf8');assert.throws(()=>reopened.action('limits',null,{maxQuestions:25,remainingPercent:101}));assert.equal(fs.readFileSync(reopened.file,'utf8'),before);assert.equal(reopened.state.limits.maxQuestions,300);});
test('blank removes local counters as a gate, but keeps recording without account reads',async t=>{const {queue}=fixture(t);queue.action('limits',null,{remainingPercent:null});queue.state.usage.calls=10001;queue.state.usage.tokens=10000001;const result=await run(queue,{getAccount:()=>assert.fail('blank must not need usage query'),run:async()=>({result:'saved',tokens:5})});assert.equal(result.result.result,'saved');assert.equal(queue.state.usage.calls,10002);assert.equal(queue.state.usage.tokens,10000006);});
test('at threshold either official time window stops before provider dispatch',async t=>{for(const usage of [account(80),account(2,window(80,300)),account(99)]){const {queue}=fixture(t);const result=await run(queue,{getAccount:async options=>{assert.deepEqual(options,{force:true});return usage;},run:()=>assert.fail('threshold dispatch')});assert.equal(result.held,true);assert.equal(queue.state.mode,'paused');assert.equal(queue.state.usage.calls,0);}});
test('successful request crossing threshold preserves packet and local result then pauses',async t=>{const {queue,directory,store}=fixture(t);let reads=0;const result=await run(queue,{getAccount:async()=>account(++reads===1?79:83),run:async()=>({result:{body:'completed'},tokens:120})});assert.equal(result.result.result.body,'completed');assert.equal(queue.state.items[0].steps.one.status,'complete');assert.equal(queue.state.items[0].steps.one.responses[0].status,'complete');assert.equal(queue.state.mode,'paused');assert.equal(queue.state.usage.tokens,120);assert.equal((await run(queue,{run:()=>assert.fail('no next call')},'two')).stopped,true);const reopened=new ExamQueue({directory,store});assert.equal(reopened.state.items[0].steps.one.result.result.body,'completed');});
test('account read failure before dispatch and after completion is safe',async t=>{for(const failAfter of [false,true]){const {queue}=fixture(t);let calls=0,reads=0;const result=await run(queue,{getAccount:async()=>{if(!failAfter||reads++)throw Error('offline');return account();},run:async()=>{calls++;return {result:'kept'};}});assert.equal(calls,failAfter?1:0);assert.equal(queue.state.mode,'paused');assert.equal(failAfter?result.result.result:result.held,failAfter?'kept':true);assert.match(queue.state.usageObservation.error,/offline/);}});
test('other provider cannot silently bypass explicit percentage; manual work is outside queue scope',async t=>{const {queue}=fixture(t);const b=queue.bridge({run:()=>assert.fail('other provider dispatch')},{provider:'gemini'});assert.equal((await queue.stage('q','g','solve',{},()=>b.run({text:'g'}),()=>true)).held,true);assert.equal(queue.state.mode,'paused');assert.equal(await queue.bridge({run:async()=>42}).run({text:'manual'}),42);});
test('provider quota and rate limits still pause even with blank app limit',async t=>{for(const error of [Object.assign(Error('provider exhausted'),{code:'quota'}),Object.assign(Error('rate limit'),{status:429,retryAfterMs:10000})]){const {queue}=fixture(t);queue.action('limits',null,{remainingPercent:null});await run(queue,{run:async()=>{throw error;}});assert.equal(queue.state.mode,'paused');if(error.status===429)assert.throws(()=>queue.action('resume'));}});
test('disabled local cap never turns bounded pre-dispatch retries into unlimited retry',async t=>{const {queue}=fixture(t);queue.action('limits',null,{remainingPercent:null,maxRetries:2});let calls=0;await run(queue,{run:async()=>{calls++;throw Object.assign(Error('offline'),{dispatched:false,code:'ECONNRESET',retryAfterMs:1});}});assert.equal(calls,3);assert.equal(queue.state.usage.calls,3);});
test('percent rechecked before retry prevents a second dispatch',async t=>{const {queue}=fixture(t);let calls=0,reads=0;await run(queue,{getAccount:async()=>account(++reads===1?79:80),run:async()=>{calls++;throw Object.assign(Error('offline'),{dispatched:false,code:'ECONNRESET',retryAfterMs:1});}});assert.equal(calls,1);assert.equal(queue.state.mode,'paused');});
test('cached completed packet needs neither account lookup nor another charge',async t=>{const {queue}=fixture(t);let calls=0;const b={getAccount:async()=>account(),run:async()=>{calls++;return {result:'packet'};}};await run(queue,b);queue.state.items[0].steps.one.status='pending';await run(queue,{getAccount:()=>assert.fail('cached lookup'),run:()=>assert.fail('cached dispatch')});assert.equal(calls,1);assert.equal(queue.state.usage.calls,1);});
test('legacy 20 migrates to remaining 20 once without erasing counters or user settings',t=>{const {queue,directory,store}=fixture(t);delete queue.state.limits.remainingPercent;queue.state.limits.accountUsedPercent=20;queue.state.usage.calls=56;queue.save();const next=new ExamQueue({directory,store});assert.equal(next.state.limits.remainingPercent,20);assert.equal(Object.hasOwn(next.state.limits,'accountUsedPercent'),false);assert.equal(next.state.usagePolicyMigration.previousUsedPercent,20);assert.equal(next.state.usage.calls,56);next.action('limits',null,{remainingPercent:15});assert.equal(new ExamQueue({directory,store}).state.limits.remainingPercent,15);});
test('20 used is 80 remaining and does not ask for approval',async()=>{const observed=await Policy.check({bridge:{getAccount:async()=>account(20)},limit:20});assert.equal(observed.windows[0].remainingPercent,80);});
test('explicit approval resumes only the same scope without repeated prompts, including after restart',async t=>{const {queue,directory,store}=fixture(t);let calls=0;const bridge={getAccount:async()=>account(85),run:async()=>({result:++calls})};await run(queue,bridge);assert.equal(calls,0);const pending=queue.state.usageConfirmation;assert.ok(pending);assert.throws(()=>queue.action('approveUsage',null,{scope:'wrong'}));queue.action('approveUsage',null,{scope:pending.scope});queue.action('resume');assert.equal((await run(queue,bridge)).result.result,1);assert.equal((await run(queue,bridge,'two')).result.result,2);const next=new ExamQueue({directory,store});next.action('resume');await run(next,bridge,'three');assert.equal(calls,3);next.state.items[0].scope={changed:true};await run(next,bridge,'four');assert.equal(calls,3);assert.ok(next.state.usageConfirmation);});
test('approval handles unknown usage honestly but never overrides official exhaustion or 429',async t=>{const unknown=await Policy.check({bridge:{getAccount:async()=>{throw Error('offline');}},limit:20,approved:true});assert.equal(unknown.status,'unknown');assert.equal(unknown.windows,undefined);await assert.rejects(Policy.check({bridge:{getAccount:async()=>account(100)},limit:20,approved:true}),/소진/);const {queue}=fixture(t);queue.state.usageApprovals={[queue.usageScope(queue.state.items[0])]:{at:new Date().toISOString()}};await run(queue,{getAccount:async()=>account(90),run:async()=>{throw Object.assign(Error('rate limit'),{status:429});}});assert.equal(queue.state.mode,'paused');assert.throws(()=>queue.action('resume'));});
