'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ExamQueue,fileHash,summary}=require('../app/exam-queue.cjs');
const counts={total:25,objectiveCount:23,writtenCount:2};
function fixture(t){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'queue-total-confirmation-'));t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});
 const file=path.join(dir,'source.png');fs.writeFileSync(file,'unchanged fixture source');
 const project={id:'project',problems:Array.from({length:25},(_,i)=>({id:'p'+i,original:{id:'p'+i+'-original',approval:{status:'pending'}},recognition:{originalNumber:String(i<23?i+1:i-22),sourceNumbering:{section:i<23?'objective':'written'}},regions:[{page:1,x:i/30,y:0,width:.02,height:1}],cropPaths:[file],queueDetectionKeys:['queue:1:'+i]}))};
 const store={get:()=>project,write:()=>assert.fail('must not write project')},queue=new ExamQueue({directory:dir,store});
 const item={id:'queue',projectId:project.id,originalPath:file,currentPath:file,hash:fileHash(file),pages:1,status:'complete',metadata:{school:'fixture',numbering:{total:null,objectiveCount:23,writtenCount:2,confirmed:false}},steps:{'page:1':{kind:'regions',status:'complete',result:{regions:Array.from({length:25},()=>({}))}}},move:{status:'held',reason:'count unconfirmed'},discoveryIssues:[]};
 for(const p of project.problems)for(const kind of ['recognition','solve','analysis','upload'])item.steps[p.id+':'+kind]={kind,status:'complete',fingerprint:p.id+kind,result:{jobId:'job-'+p.id,revisionId:'revision-'+p.id},responses:[{status:'complete',value:{result:'retained'}}]};
 queue.state.items=[item];queue.state.mode='paused';queue.state.usage={calls:47,tokens:1395047,tokenReports:47};queue.save();
 queue.move=()=>assert.fail('must not move source');queue.bridge=()=>assert.fail('must not call AI');
 return {dir,file,project,store,queue,item,confirm:value=>queue.action('confirmTotal',item.id,value||counts)};
}
test('explicit 23+2 confirmation changes only local completion evidence, preserving every prior field',t=>{const f=fixture(t),before=structuredClone(f.queue.state),project=JSON.stringify(f.project),source=fs.readFileSync(f.file);assert.equal(summary(f.item,f.project).whole,false);f.confirm();assert.equal(summary(f.item,f.project).whole,true);assert.equal(summary(f.item,f.project).confirmedTotal,25);assert.deepEqual(f.item.completionConfirmation.numbering,{...counts,confirmed:true});const after=structuredClone(f.queue.state);delete after.items[0].completionConfirmation;assert.deepEqual(after,before);assert.equal(JSON.stringify(f.project),project);assert.deepEqual(fs.readFileSync(f.file),source);assert.equal(f.item.move.status,'held');});
test('held and unfinished upload remain incomplete even after valid numeric confirmation',t=>{const f=fixture(t);f.item.steps['p9:solve'].status='held';f.item.steps['p9:solve'].reason='print unclear';f.item.steps['p9:upload'].status='pending';f.item.status='held';const before=JSON.stringify(f.item.steps);f.confirm();const s=summary(f.item,f.project);assert.equal(s.confirmedTotal,25);assert.equal(s.whole,false);assert.equal(s.held,1);assert.equal(s.uploaded,24);assert.equal(JSON.stringify(f.item.steps),before);assert.equal(f.item.status,'held');});
test('running queue or in-flight step rejects without rewriting journal',t=>{for(const condition of ['running','active']){const f=fixture(t);if(condition==='running')f.queue.state.mode='running';else f.queue.active={};f.queue.save();const bytes=fs.readFileSync(f.queue.file);assert.throws(()=>f.confirm(),/멈춘/);assert.deepEqual(fs.readFileSync(f.queue.file),bytes);}});
test('invalid counts are rejected atomically',t=>{for(const value of [{...counts,total:24},{...counts,total:0},{...counts,total:25.5},{...counts,objectiveCount:24,writtenCount:1},{...counts,writtenCount:-1},{total:25}]){const f=fixture(t),bytes=fs.readFileSync(f.queue.file);assert.throws(()=>f.confirm(value));assert.deepEqual(fs.readFileSync(f.queue.file),bytes);assert.equal(f.item.completionConfirmation,undefined);}});
test('missing duplicated and unknown printed numbering cannot be declared whole',t=>{for(const change of ['missing','duplicate','unknown']){const f=fixture(t);if(change==='missing')f.project.problems.pop();if(change==='duplicate')f.project.problems[1].recognition.originalNumber='1';if(change==='unknown')f.project.problems[0].recognition.sourceNumbering.section='unknown';const bytes=fs.readFileSync(f.queue.file);assert.throws(()=>f.confirm());assert.deepEqual(fs.readFileSync(f.queue.file),bytes);}});
test('source modification, missing captures and incomplete discovery block confirmation',t=>{for(const change of ['source','crop','page','link']){const f=fixture(t);if(change==='source')fs.writeFileSync(f.file,'changed');if(change==='crop')f.project.problems[0].cropPaths=[];if(change==='page')f.item.pages=2;if(change==='link')f.project.problems[0].queueDetectionKeys=[];const bytes=fs.readFileSync(f.queue.file);assert.throws(()=>f.confirm());assert.deepEqual(fs.readFileSync(f.queue.file),bytes);}});
test('confirmation survives restart with original upload response packets',t=>{const f=fixture(t);f.confirm();const steps=JSON.stringify(f.item.steps);const reopened=new ExamQueue({directory:f.dir,store:f.store});assert.equal(reopened.status().items[0].summary.whole,true);assert.equal(JSON.stringify(reopened.item('queue').steps),steps);assert.equal(reopened.state.mode,'paused');assert.equal(reopened.state.usage.calls,47);});
test('changed counted inputs invalidate local confirmation without adjusting uploaded fingerprints',t=>{for(const change of ['number','id','crop','source','count']){const f=fixture(t);f.confirm();const steps=JSON.stringify(f.item.steps);if(change==='number')f.project.problems[0].recognition.originalNumber='99';if(change==='id')f.project.problems[0].id='changed';if(change==='crop')f.project.problems[0].cropPaths=['changed'];if(change==='source')f.item.metadata.school='another';if(change==='count')f.item.metadata.numbering.objectiveCount=24;assert.equal(summary(f.item,f.project).confirmedTotal,null);assert.equal(summary(f.item,f.project).whole,false);assert.equal(JSON.stringify(f.item.steps),steps);}});
test('normal metadata edits still invalidate uploads and do not silently bypass existing policy',t=>{const f=fixture(t);f.confirm();f.queue.edit(f.item.id,{metadata:{school:'changed school'}});assert.ok(Object.entries(f.item.steps).filter(([k])=>k.endsWith(':upload')).every(([,s])=>s.status==='pending'));assert.equal(summary(f.item,f.project).whole,false);});
test('cancelled or unprepared entry cannot be confirmed',t=>{for(const change of ['cancelled','unprepared']){const f=fixture(t);if(change==='cancelled')f.item.status='cancelled';else f.item.projectId=null;assert.throws(()=>f.confirm(),/시험지/);assert.equal(f.item.completionConfirmation,undefined);}});
