'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {localServer}=require('./shared-bank-local-server.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{ProjectStore}=require('../app/store.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),M=require('../app/bank-model.cjs');
test('A upload → approved B restore → B fork, real SQL/RLS + actual verification function, simulated HTTP',async t=>{
 const server=await localServer(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'shared-flow-')),banks=[];t.after(async()=>{for(const b of banks)b.close();await server.close();fs.rmSync(dir,{recursive:true,force:true});});
 const make=(who)=>{const store=new ProjectStore(path.join(dir,who)),auth=server.auth(who),storage=new SharedBankStorage({auth,fetchImpl:server.fetch}),bank=new QuestionBank({directory:store.dataDir,store,auth,storage,appVersion:'test',buildDocx:async(input,file)=>fs.writeFileSync(file,'MOCK DOCX '+input.questionId)});bank.wake=()=>{};banks.push(bank);return{bank,store,storage,auth};};
 await server.db.exec('reset role;set role anon');await assert.rejects(server.db.query('select * from bank_catalog'),/permission/);await assert.rejects(server.db.query('select bank_search($1)',[server.S]),/permission/);await assert.rejects(server.db.query('select * from storage.objects'),/permission/);
 const a=make(server.A),b=make(server.B),x=make(server.X);await assert.rejects(b.bank.root(),/초대/);await a.storage.invite('teacher-b@example.test');await a.bank.root();await b.bank.root();await assert.rejects(x.bank.root(),/초대/);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bX8AAAAASUVORK5CYII=','base64'),source=path.join(dir,'test.png');fs.writeFileSync(source,png);let p=a.store.create(source);p=a.store.addRegion({projectId:p.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+png.toString('base64')});p=a.store.updateProblem(p.id,p.problems[0].id,v=>{v.original={id:M.uuid(),kind:'original',body:'$\\frac{13}{2}$, $\\sqrt{2}$, $\\angle ABC$',choices:['① 1','② 2'],answer:'②',solution:'이유를 설명합니다.',include:true,approval:{status:'approved'},diagram:require('./workflow-fixtures.cjs').recognition().observedDiagram};v.recognition={confirmed:true};});
 await a.bank.enqueue(p.id,[p.problems[0].original.id]);await a.bank.pump();const first=a.bank.state.jobs[0];assert.equal(first.status,'complete',first.error);await b.bank.refresh();assert.equal(b.bank.status().cached.length,1);const completed=(await a.storage.commits(server.S,first.questionId)).files[0];assert.equal((await b.storage.get(completed.id)).id,completed.id);await assert.rejects(x.storage.get(completed.id),/권한/);assert.ok((await server.sql(server.B,'select * from storage.objects')).rows.length>0);await server.db.exec('reset role');await server.db.query('delete from bank_catalog where revision_id=$1',[first.id]);assert.equal((await a.storage.reindex()).count,1);assert.equal((await a.storage.reindex()).count,0);await assert.rejects(b.storage.review({revisionId:first.id,patch:{sharingAllowed:true},reason:'unauthorized',expected:0}),/privilege|permission/i);await a.storage.review({revisionId:first.id,patch:{sharingAllowed:true,difficulty:'4.7'},reason:'검수 완료',expected:0});await b.bank.refresh();assert.equal(b.bank.status().cached[0].author.email,'animochoi@gmail.com');const restored=await b.bank.restore(first.id);assert.deepEqual(restored.project.problems[0].original,p.problems[0].original);assert.deepEqual(fs.readFileSync(path.join(b.store.projectDir(restored.project.id),'exports/bank-original.docx')),fs.readFileSync(path.join(a.bank.dir,'outbox',first.id,'question.docx')));
 b.store.updateProblem(restored.project.id,restored.project.problems[0].id,q=>q.original.body+=' B 수정');await b.bank.enqueue(restored.project.id,[restored.project.problems[0].original.id]);await b.bank.pump();const copy=b.bank.state.jobs[0];assert.equal(copy.status,'complete',copy.error);assert.notEqual(copy.questionId,first.questionId);assert.equal(copy.parentRevisionId,null);assert.equal(b.bank.state.items[copy.questionId].metadata.relations.derivedFromQuestionId,first.questionId);
 await assert.rejects(b.storage.rpc('bank_begin_revision',{s:server.S,q:first.questionId,r:M.uuid(),p:first.id}),/다른 교사/);assert.equal((await a.storage.commits(server.S,first.questionId)).files.length,1);
 const pending=await a.storage.generateId(),bytes=Buffer.alloc(6291456+15,9),file=path.join(dir,'large.bin');fs.writeFileSync(file,bytes);let loss=true;const lostStorage=new SharedBankStorage({auth:a.auth,fetchImpl:async(u,o)=>{const r=await server.fetch(u,o);if(loss&&o.method==='POST'&&u.includes('/storage/')){loss=false;throw Error('lost response');}return r;}}),props={role:'source',rootId:server.S,sourceKey:'9'.repeat(64)};
 await assert.rejects(lostStorage.put({file,id:pending,name:'large.bin',parent:server.S,properties:props}),/연결/);assert.equal((await a.storage.get(pending)).verified,false);await lostStorage.put({file,id:pending,name:'large.bin',parent:server.S,properties:props});assert.deepEqual(await a.storage.download(pending),bytes);assert.equal([...server.bytes.keys()].filter(k=>k.includes(pending)).length,2);
 const corrupted=[...server.bytes.keys()].find(k=>k.includes(pending));server.bytes.set(corrupted,Buffer.alloc(6291456,8));await assert.rejects(a.storage.download(pending),/무결성/);
 const exam=M.uuid(),teacherExam=M.uuid(),examDoc={title:'백업할 시험지',items:[{questionId:first.questionId,revisionId:first.id,workspaceMm:25}],layout:[{columns:[[first.questionId],[]]}]};await a.storage.rpc('bank_exam_save',{s:server.S,e:exam,expected:0,doc:examDoc});await b.storage.rpc('bank_exam_save',{s:server.S,e:teacherExam,expected:0,doc:{...examDoc,title:'동료 개인 시험지'}});await a.storage.rpc('bank_rate',{r:first.id,value:4.7,adopt:true});
 const transfer=require('../app/bank-transfer.cjs'),saved=await transfer.backup(a.bank,path.join(dir,'archive'),{admin:true});assert.equal(saved.versions,2);const manifest=JSON.parse(fs.readFileSync(path.join(dir,'archive/backup.json'),'utf8'));assert.ok(manifest.audit.length);assert.ok(manifest.records.every(r=>r.revision.actor_id&&r.question.owner_email));assert.equal(manifest.personal,undefined);assert.equal(manifest.workspace.exams.length,1);assert.equal(manifest.workspace.exams[0].id,exam);assert.equal(manifest.workspace.history.length,1);assert.equal(manifest.workspace.ratings[0].score,'4.7');const recovered=await transfer.restoreBackup(a.bank,path.join(dir,'archive'));assert.equal(recovered.versions,2);assert.ok(fs.existsSync(recovered.workspaceFile));assert.equal(JSON.parse(fs.readFileSync(recovered.workspaceFile)).exams[0].document.items[0].workspaceMm,25);assert.ok(recovered.projects.every(p=>p.bankArchive.revisionId));const archivedFile=path.join(dir,'archive/files',manifest.files[0].id),originalFile=fs.readFileSync(archivedFile);fs.writeFileSync(archivedFile,'tampered');await assert.rejects(transfer.restoreBackup(a.bank,path.join(dir,'archive')),/무결성/);fs.writeFileSync(archivedFile,originalFile);
 await assert.rejects(transfer.backup(b.bank,path.join(dir,'forbidden-backup'),{admin:true}),/관리자/);
 const selection={format:'examstudio-selection-v1',server:a.auth.config().url,spaceId:server.S,items:[{questionId:copy.questionId,revisionId:copy.id},{questionId:first.questionId,revisionId:first.id}]};const merged=await transfer.importSelection(a.bank,selection);assert.equal(merged.problems.length,2);assert.match(merged.problems[0].original.body,/B 수정/);assert.equal(merged.problems[1].original.body,p.problems[0].original.body);assert.equal(new Set(merged.problems.map(p=>p.id)).size,2);assert.ok(merged.sources.every(s=>fs.existsSync(s.path)));assert.throws(()=>transfer.selection({...selection,spaceId:M.uuid()},a.auth.config()));
 await assert.rejects(b.storage.role('teacher-b@example.test','reviewer'),/privilege|permission/i);
 await a.storage.role('teacher-b@example.test','reviewer');assert.equal((await b.auth.membership()).role,'reviewer');
 const suggested=await b.storage.propose({revisionId:first.id,patch:{difficulty:'6.5'},reason:'비교 검토',expected:1});await a.storage.review({revisionId:first.id,patch:{difficulty:'6.5'},reason:'근거 확인',expected:1,proposal:suggested});await assert.rejects(a.storage.review({revisionId:first.id,patch:{difficulty:'8.2'},reason:'stale',expected:1}),/동시 수정/);
 const unit=M.uuid();await a.storage.rpc('bank_taxonomy_save',{s:server.S,item:unit,label_value:'삼각형',kind_value:'unit',parent_value:null,expected:0});await a.storage.review({revisionId:first.id,patch:{unitId:unit},reason:'분류 연결',expected:2});await a.storage.rpc('bank_taxonomy_save',{s:server.S,item:unit,label_value:'삼각형의 성질',kind_value:'unit',parent_value:null,expected:1});assert.equal((await b.storage.search({unit:'삼각형의 성질'})).length,1);
 await a.storage.personal(first.questionId,'PRIVATE SECRET NOTE',true);assert.equal((await b.storage.rows('bank_personal','question_id=eq.'+first.questionId)).length,0);
 await a.storage.archive(first.questionId,true,'오류 검토');await a.storage.role('teacher-b@example.test','teacher');await b.bank.refresh({rescan:true});assert.equal(b.bank.status().cached.some(c=>c.questionId===first.questionId),true); // Existing saved exam retains access to its frozen revision.
await a.storage.archive(first.questionId,false,'검토 후 복구');await b.bank.refresh();
 await a.storage.invite('teacher-b@example.test',false);await assert.rejects(b.bank.refresh(),/초대/);await assert.rejects(b.bank.restore(first.id),/권한/);
});
