'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {SharedBankAuth,configuration}=require('../app/shared-bank-auth.cjs');
const config={url:'https://test-project.supabase.co',spaceId:'57fcd460-b526-487f-9075-5503e4d07145',publishableKey:'sb_publishable_test'};
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'shared-auth-'));let url,approved=true;const requests=[];const auth=new SharedBankAuth({directory,port:0,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).reverse(),decryptString:b=>Buffer.from(b).reverse().toString()},openExternal:async u=>{url=new URL(u);},fetchImpl:async(u,opts)=>{requests.push({url:u,...opts});return Response.json(u.includes('/token?')?{access_token:'test-access',refresh_token:'test-refresh',expires_in:3600}:u.endsWith('/user')?{id:'teacher-b',email:'teacher-b@example.test',email_confirmed_at:'2026-01-01'}:approved?{userId:'teacher-b',role:'teacher',email:'teacher-b@example.test'}:{message:'초대 필요'},{status:u.endsWith('bank_join')&&!approved?403:200});}});auth.configure(config);t.after(()=>{auth.cancel();fs.rmSync(directory,{recursive:true,force:true});});return{auth,requests,get url(){return url;},set approved(v){approved=v;}};}
async function start(s){const result=s.auth.connect();result.catch(()=>{});for(let i=0;!s.url&&i<100;i++)await new Promise(r=>setTimeout(r,5));assert.ok(s.url);return{result,callback:new URL(s.url.searchParams.get('redirect_to'))};}
test('shared OAuth accepts approved colleagues, validates loopback state and PKCE, encrypts own tokens (mock Auth)',async t=>{const s=fixture(t),{result,callback}=await start(s);assert.equal(s.url.searchParams.get('provider'),'google');assert.equal(s.url.searchParams.has('login_hint'),false);const state=callback.searchParams.get('bank_state');callback.searchParams.set('bank_state','wrong');callback.searchParams.set('code','once');assert.equal((await fetch(callback)).status,400);assert.equal(s.requests.length,0);callback.searchParams.set('bank_state',state);await fetch(callback);await result;assert.equal(s.auth.status().account.email,'teacher-b@example.test');const exchange=JSON.parse(s.requests[0].body);assert.equal(crypto.createHash('sha256').update(exchange.code_verifier).digest('base64url'),s.url.searchParams.get('code_challenge'));assert.doesNotMatch(fs.readFileSync(s.auth.file,'utf8'),/test-refresh/);s.auth.invalidate();assert.equal(await s.auth.token(),'test-access');s.auth.disconnect();assert.equal(s.auth.status().connected,false);assert.equal(s.auth.read().tokens,undefined);});
test('valid Google account without invitation is denied; no token persisted (mock Auth)',async t=>{const s=fixture(t);s.approved=false;const{result,callback}=await start(s);callback.searchParams.set('code','once');await fetch(callback);await assert.rejects(result,/초대/);assert.equal(s.auth.status().connected,false);assert.equal(s.auth.read().tokens,undefined);});
test('desktop connection configuration rejects secret/service-role keys and untrusted URLs',()=>{assert.deepEqual(configuration(config),config);assert.throws(()=>configuration({...config,publishableKey:'sb_secret_do-not-distribute'}));const jwt='e30.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.signature';assert.throws(()=>configuration({...config,publishableKey:jwt}));assert.throws(()=>configuration({...config,url:'https://attacker.invalid'}));});

test('account switch forwards browser choice and requests Google account selection without account lock (mock Auth)',async t=>{
 const s=fixture(t),open=s.auth.openExternal;let options;s.auth.openExternal=async(url,value)=>{options=value;await open(url);};
 const pending=s.auth.connect({browser:'edge'});pending.catch(()=>{});for(let i=0;!s.url&&i<100;i++)await new Promise(r=>setTimeout(r,5));
 assert.deepEqual(options,{browser:'edge'});assert.equal(s.url.searchParams.get('prompt'),'select_account');assert.equal(s.url.searchParams.has('login_hint'),false);
 const callback=new URL(s.url.searchParams.get('redirect_to'));callback.searchParams.set('code','one-time-test');await fetch(callback);await pending;assert.equal(s.auth.status().connected,true);
});
