'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),guide=require('../app/solution-guide.js'),render=require('../app/solution-guide-render.js'),{fixture}=require('./fixtures/solution-guide.cjs');
const key=m=>[m.from,m.to].sort().join('-');
const marks=(g,s)=>Object.fromEntries(guide.project(g,s).diagram.equalLengthMarks.map(m=>[key(m),{group:m.group,count:m.count}]));
test('square sides and diagonal half lengths have different marks in the reported simultaneous view',()=>{const q=fixture(),g=q.solutionGuide;g.steps[1].view.relationIds.unshift('square');q.solutionGuide=guide.bind(g,q);assert.ok(guide.current(q));const m=marks(g,g.steps[1]);assert.equal(m['A-B'].count,m['B-C'].count);assert.equal(m['A-O'].count,m['C-O'].count);assert.notEqual(m['A-B'].count,m['A-O'].count);assert.notEqual(m['A-O'].count,m['B-O'].count);assert.equal(new Set(Object.values(m).map(m=>m.group)).size,3);assert.equal(render.figure(g,g.steps[1]).layout.collisions.length,0);});
test('relation/view ordering and stage changes preserve equality-group identities',()=>{const g=fixture().solutionGuide;g.steps[1].view.relationIds.unshift('square');const before=marks(g,g.steps[1]);const reversed=structuredClone(g);reversed.relations=[reversed.relations[0],...reversed.relations.slice(1,-1).reverse(),reversed.relations.at(-1)];guide.validate(reversed);reversed.steps[1].view.relationIds.reverse();assert.deepEqual(marks(reversed,reversed.steps[1]),before);const later=marks(g,g.steps[2]);for(const edge of ['A-O','C-O','B-O','D-O'])assert.deepEqual(later[edge],before[edge]);assert.deepEqual(marks(g,g.steps[0])['A-B'],before['A-B']);});
test('overlapping explicitly equal sides merge transitively and paint each edge only once',()=>{const g=fixture().solutionGuide;g.relations.push({id:'square-again',kind:'equalLength',points:['A','B','B','C'],origin:'derived',reason:'정사각형의 변',dependsOn:['square'],value:null,criterion:null});g.steps[1].view.relationIds.unshift('square','square-again');for(let i=0;i<6;i++){g.relations.push({...g.relations.at(-1),id:'duplicate-'+i});g.steps[1].view.relationIds.push('duplicate-'+i);}guide.validate(g);const projected=guide.project(g,g.steps[1]);const m=marks(g,g.steps[1]);assert.equal(projected.diagram.equalLengthMarks.filter(x=>key(x)==='A-B').length,1);assert.deepEqual(m['A-B'],m['B-C']);assert.notEqual(m['A-B'].group,m['A-O'].group);});
test('coordinate coincidence never creates an unasserted equality group',()=>{const g=fixture().solutionGuide;const m=marks(g,g.steps[1]);const p=new Map(g.diagram.points.map(p=>[p.name,p]));const distance=(a,b)=>Math.hypot(p.get(a).x-p.get(b).x,p.get(a).y-p.get(b).y);assert.equal(distance('A','O'),distance('B','O'));assert.notEqual(m['A-O'].group,m['B-O'].group);g.relations.push({id:'linked',kind:'equalLength',points:['A','O','B','O'],origin:'derived',reason:'정사각형의 두 대각선은 길이가 같고 서로를 이등분한다.',dependsOn:['square'],value:null,criterion:null});guide.validate(g);g.steps[1].view.relationIds.push('linked');const merged=marks(g,g.steps[1]);assert.deepEqual(merged['A-O'],merged['B-O']);assert.deepEqual(merged['A-O'],merged['D-O']);});
test('a whole guide cannot silently exceed the renderer five distinct tick patterns',()=>{const g=fixture().solutionGuide;for(let i=0;i<4;i++){const a='X'+i,b='Y'+i,c='Z'+i;g.diagram.points.push({name:a,x:i+30,y:0},{name:b,x:i+30,y:1},{name:c,x:i+30,y:2});g.relations.push({id:'extra'+i,kind:'equalLength',points:[a,b,b,c],origin:'given',reason:'합성 조건',dependsOn:[],value:null,criterion:null});}assert.throws(()=>guide.validate(g),/5개/);});
