'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('../app/solution-guide.js'),{fixture}=require('./fixtures/solution-guide.cjs');
function common(points=['A','O','O','A']){const g=structuredClone(fixture().solutionGuide);g.relations.unshift({id:'common',kind:'equalLength',points,origin:'derived',reason:'두 삼각형의 공통변이다.',dependsOn:[],criterion:null,value:null});return g;}
test('a nondegenerate common side is a reflexive fact, including reversed endpoints',()=>{assert.ok(G.validate(common()));assert.ok(G.validate(common(['A','O','A','O'])));});
test('the common-side exception does not admit unsupported equal lengths or coincident aliases',()=>{assert.throws(()=>G.validate(common(['A','O','O','C'])),/선행/);const g=common(['A','O','alias','O']);g.diagram.points.push({...g.diagram.points[0],name:'alias'});assert.throws(()=>G.validate(g),/선행/);assert.throws(()=>G.validate(common(['A','A','A','A'])),/선행|일치/);const zero=common();zero.diagram.points.find(p=>p.name==='A').x=0;assert.throws(()=>G.validate(zero),/일치/);});
test('common facts still reject forward or cyclic dependencies and duplicated SAS premises',()=>{const g=common();g.relations[0].dependsOn=['square'];assert.throws(()=>G.validate(g),/앞 단계/);g.relations[0].dependsOn=['common'];assert.throws(()=>G.validate(g),/앞 단계/);const s=common();s.relations.find(r=>r.kind==='congruence').dependsOn=['common','common','angle-o'];assert.throws(()=>G.validate(s),/세 조건/);});
test('generated titles, narrative and relation reasons report Han without modifying input',()=>{const q=fixture();q.solutionGuide.steps[0].title='所有 조건';q.solutionGuide.relations[0].reason='原문 조건';q.solution='모든 조건에서 面積을 구한다.';const before=JSON.stringify(q),issues=G.languageIssues(q);assert.equal(issues.length,3);assert.equal(JSON.stringify(q),before);assert.throws(()=>G.bind(q.solutionGuide,{...q,solution:G.plainText(q.solutionGuide)}),/한자 혼입/);});
test('source, exact source quotations, mathematical notation and point names are preserved',()=>{const q=fixture();q.body='인쇄 원문 「甲乙」에서 넓이를 구한다.';q.choices=['原文'];q.observedDiagram={points:[{name:'甲',x:1,y:0}]};q.solution='원문의 「甲乙」을 그대로 읽는다. 점 甲에서 $\\angle ABC=60^\\circ$이고 $\\mathrm{甲}=x$이다. \\(甲+1\\)도 기호다.';const before=JSON.stringify(q);assert.deepEqual(G.languageIssues(q),[]);assert.equal(JSON.stringify(q),before);q.solution='원문에 없는 「所有」 설명';assert.ok(G.languageIssues(q).length);});
test('ordinary symbols and legacy stored guides are not erased or silently normalized',()=>{const q=fixture();q.solution='점 A′에서 ∠ABC와 △ABC, α+β≤180°를 비교한다.';assert.deepEqual(G.languageIssues(q),[]);const legacy=fixture();legacy.solutionGuide.steps[0].title='所有 조건';legacy.solution=G.plainText(legacy.solutionGuide);legacy.solutionGuide.basis=G.basis(legacy);assert.ok(G.current(legacy));assert.throws(()=>G.bind(legacy.solutionGuide,legacy),/한자 혼입/);});
test('policy states Korean prose and a narrow common-side rule without blanket deletion',()=>{const policy=require('../app/solution-guide-policy.cjs');assert.match(policy,/자연스러운 한글/);assert.match(policy,/일괄 삭제하거나 임의 번역하지 않는다/);assert.match(policy,/공통변의 반사적 동일성/);});
test('workflow output validation also flags Han in explanations without a guide',()=>{const q=fixture();q.solutionGuide=null;q.solution='面積은 24이다.';const before=JSON.stringify(q),{programCheck}=require('../app/workflow.cjs'),{validation}=require('./workflow-fixtures.cjs');const result=programCheck({question:q,questionType:'single_value',validation:validation()},{forbidden:[]});assert.ok(result.program.errors.some(x=>/한자 혼입/.test(x)));assert.ok(result.program.executed.includes('korean-explanation-prose-scan'));assert.equal(JSON.stringify(q),before);});
