'use strict';
// One short browser pass: real app bundle + local SQL/RLS, simulated auth/HTTP.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {localServer}=require('./shared-bank-local-server.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{ProjectStore}=require('../app/store.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{uuid}=require('../app/bank-model.cjs');
(async()=>{
 const server=await localServer(),directory=path.resolve('tmp/phase15-20261003/ui');fs.mkdirSync(directory,{recursive:true});
 const auth=server.auth(server.A),storage=new SharedBankStorage({auth,fetchImpl:server.fetch}),store=new ProjectStore(path.join(directory,'fixture-'+uuid()));let bank,browser,web;
 try{
  const image=path.join(directory,'blank.png');await require('sharp')({create:{width:100,height:100,channels:3,background:'#ffffff'}}).png().toFile(image);
  let project=store.create(image);
  for(const n of ['1','3','서답형 1']){project=store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:.5,height:.5},imageDataUrl:'data:image/png;base64,'+fs.readFileSync(image).toString('base64')});const p=project.problems.at(-1);project=store.updateProblem(project.id,p.id,p=>{p.original={id:uuid(),kind:'original',body:'원본 '+n+' 검증 문항. 값을 구하시오.',choices:['1','2'],answer:'1',solution:'주어진 값을 대입한다.',include:true,approval:{status:'approved'}};p.recognition={confirmed:true,originalNumber:n,points:4,sourceNumbering:{section:n.includes('서답')?'written':'objective'}};});}
  bank=new QuestionBank({directory:store.dataDir,store,storage,auth,appVersion:'test',buildDocx:async(i,file)=>fs.writeFileSync(file,'mock docx'),preview:async(i,file)=>fs.copyFileSync(image,file)});bank.wake=()=>{};await bank.root();bank.catalog(project.id);bank.editSource(project.id,'primary',{kind:'학교기출',school:'로컬검증중',academicYear:'2026',grade:'중2',semester:'2학기',exam:'중간고사',numbering:{total:4,objectiveCount:3,writtenCount:1,confirmed:true,evidence:'격리 테스트'}});
  for(const item of Object.values(bank.state.items)){Object.assign(item.metadata.difficulty,{aiScore:'4.0',aiBand:'보통',criteriaVersion:require('../app/difficulty-assessment.cjs').version,scope:{grade:'중2'}});}
  await bank.enqueue(project.id,project.problems.map(p=>p.original.id));await bank.pump();assert.ok(bank.state.jobs.every(j=>j.status==='complete'),JSON.stringify(bank.state.jobs.map(j=>j.error)));
  await storage.invite('teacher-b@example.test');await server.auth(server.B).membership();
  const config=path.join(directory,'config.json');fs.writeFileSync(config,JSON.stringify(auth.config()));const dist=await require('../scripts/build-bank-web.cjs').build(config,path.join(directory,'site'));
  web=http.createServer((req,res)=>{const file=path.join(dist,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(dist+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(file));});await new Promise(resolve=>web.listen(0,'127.0.0.1',resolve));
  const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));browser=await chromium.launch({channel:'msedge',headless:true});
  const writes=[];
  async function pageFor(uid){const context=await browser.newContext({viewport:{width:390,height:844}});const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';await context.addInitScript(({uid,jwt})=>sessionStorage.setItem('sb-test-project-auth-token',JSON.stringify({access_token:jwt,refresh_token:'test',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id:uid,email:'teacher-b@example.test',aud:'authenticated',role:'authenticated'}})),{uid,jwt});const p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>{throw e;});p.on('dialog',d=>{if(p.declineNext){p.declineNext=false;return d.dismiss();}return d.accept(d.type()==='prompt'?(p.promptAnswer||''):undefined);});await p.route('https://test-project.supabase.co/**',async route=>{const req=route.request();if(/bank_exam_save|bank_review_save|bank_rate_save/.test(req.url()))writes.push(req.url().split('/').at(-1));const response=await server.fetch(req.url(),{method:req.method(),headers:req.headers(),body:req.postData()||undefined});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});await p.goto('http://127.0.0.1:'+web.address().port);return p;}
  const p=await pageFor(server.B);await p.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await p.getByRole('button',{name:'상세 보기'}).first().click();await p.getByRole('button',{name:'검수 저장',exact:true}).waitFor();
  await p.getByLabel('교사 난이도 구간 (선택)',{exact:true}).selectOption('아주어려움');await p.getByLabel('원본 배점 확인 완료',{exact:true}).check();await p.getByRole('button',{name:'검수 저장',exact:true}).click();await p.getByText('검수 내용을 저장했습니다. 검수 완료 후에도 수정할 수 있습니다.').waitFor();
  await p.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await p.getByText('상세 필터',{exact:true}).click();await p.getByLabel('난이도 구간',{exact:true}).selectOption('아주어려움');await p.getByRole('button',{name:'검색',exact:true}).click();await p.getByText(/1개 표시/).waitFor();await p.getByText('4.0점 · AI 원점수 / 아주어려움 · 교사 구간',{exact:true}).waitFor();
  await p.getByRole('button',{name:'상세 보기'}).click();await p.getByLabel('직접 수정 점수 (선택)',{exact:true}).fill('6.2');await p.getByRole('button',{name:'검수 저장',exact:true}).click();await p.getByText('검수 내용을 저장했습니다. 검수 완료 후에도 수정할 수 있습니다.').waitFor();await p.getByText('6.2점 · 공동 확정 / 아주어려움 · 교사 구간',{exact:true}).waitFor();await p.screenshot({path:path.join(directory,'teacher-evidence-mobile.png'),fullPage:true});
  await p.locator('#nav').getByRole('button',{name:'학교·시험지'}).click();await p.getByText('학교별 난이도 통계',{exact:true}).click();await p.getByRole('button',{name:'저장 자료로 통계 조회'}).click();await p.getByText('AI 분석 3/3문항',{exact:false}).waitFor();await p.getByText(/평균 4.7 · 중앙값 4.0/).waitFor();await p.getByText(/아주어려움 1/).waitFor();await p.getByLabel('통계 응답형식',{exact:true}).selectOption('written');await p.getByText(/평균 6.2 · 중앙값 6.2/).waitFor();await p.setViewportSize({width:1280,height:900});await p.screenshot({path:path.join(directory,'statistics-desktop.png'),fullPage:true});
  const stored=await storage.rpc('bank_difficulty_rows',{s:server.S}),corrected=stored.find(c=>c.confirmed.difficulty==='6.2');assert.ok(corrected);assert.equal(corrected.metadata.difficulty.aiScore,'4.0');assert.equal(corrected.confirmed.difficultyBand,'아주어려움');assert.equal(corrected.confirmed.originalPointsReviewed,true);
  fs.writeFileSync(path.join(directory,'result.json'),JSON.stringify({passed:true,teacherBand:'아주어려움',rawScore:'4.0',directScore:'6.2',schoolAverage:4.7,writtenAverage:6.2,realAiCalls:0,productionWrites:0},null,2));console.log('PASS phase 1.5 core browser workflow',directory);
 }finally{bank?.close();await browser?.close();if(web)await new Promise(resolve=>web.close(resolve));await server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
