'use strict';
// One short browser pass: real app bundle + local SQL/RLS, simulated auth/HTTP.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {localServer}=require('./shared-bank-local-server.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{ProjectStore}=require('../app/store.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{uuid}=require('../app/bank-model.cjs');
(async()=>{
 const server=await localServer(),directory=path.resolve('tmp/phase1-20261003/ui');fs.mkdirSync(directory,{recursive:true});
 const auth=server.auth(server.A),storage=new SharedBankStorage({auth,fetchImpl:server.fetch}),store=new ProjectStore(path.join(directory,'fixture-'+uuid()));let bank,browser,web;
 try{
  const image=path.join(directory,'blank.png');await require('sharp')({create:{width:100,height:100,channels:3,background:'#ffffff'}}).png().toFile(image);
  let project=store.create(image);
  for(const n of ['1','3','서답형 1']){project=store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:.5,height:.5},imageDataUrl:'data:image/png;base64,'+fs.readFileSync(image).toString('base64')});const p=project.problems.at(-1);project=store.updateProblem(project.id,p.id,p=>{p.original={id:uuid(),kind:'original',body:'원본 '+n+' 검증 문항. 값을 구하시오.',choices:['1','2'],answer:'1',solution:'주어진 값을 대입한다.',include:true,approval:{status:'approved'}};p.recognition={confirmed:true,originalNumber:n,points:4,sourceNumbering:{section:n.includes('서답')?'written':'objective'}};});}
  bank=new QuestionBank({directory:store.dataDir,store,storage,auth,appVersion:'test',buildDocx:async(i,file)=>fs.writeFileSync(file,'mock docx'),preview:async(i,file)=>fs.copyFileSync(image,file)});bank.wake=()=>{};await bank.root();bank.catalog(project.id);bank.editSource(project.id,'primary',{kind:'학교기출',school:'로컬검증중',academicYear:'2026',grade:'중2',semester:'2학기',exam:'중간고사',numbering:{total:4,objectiveCount:3,writtenCount:1,confirmed:true,evidence:'격리 테스트'}});
  await bank.enqueue(project.id,project.problems.map(p=>p.original.id));await bank.pump();assert.ok(bank.state.jobs.every(j=>j.status==='complete'),JSON.stringify(bank.state.jobs.map(j=>j.error)));
  await storage.invite('teacher-b@example.test');await server.auth(server.B).membership();
  const config=path.join(directory,'config.json');fs.writeFileSync(config,JSON.stringify(auth.config()));const dist=await require('../scripts/build-bank-web.cjs').build(config,path.join(directory,'site'));
  web=http.createServer((req,res)=>{const file=path.join(dist,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(dist+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(file));});await new Promise(resolve=>web.listen(0,'127.0.0.1',resolve));
  const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));browser=await chromium.launch({channel:'msedge',headless:true});
  const writes=[];
  async function pageFor(uid){const context=await browser.newContext({viewport:{width:390,height:844}});const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';await context.addInitScript(({uid,jwt})=>sessionStorage.setItem('sb-test-project-auth-token',JSON.stringify({access_token:jwt,refresh_token:'test',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id:uid,email:'teacher-b@example.test',aud:'authenticated',role:'authenticated'}})),{uid,jwt});const p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>{throw e;});p.on('dialog',d=>{if(p.declineNext){p.declineNext=false;return d.dismiss();}return d.accept(d.type()==='prompt'?(p.promptAnswer||''):undefined);});await p.route('https://test-project.supabase.co/**',async route=>{const req=route.request();if(/bank_exam_save|bank_review_save|bank_rate_save/.test(req.url()))writes.push(req.url().split('/').at(-1));const response=await server.fetch(req.url(),{method:req.method(),headers:req.headers(),body:req.postData()||undefined});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});await p.goto('http://127.0.0.1:'+web.address().port);return p;}
  const p=await pageFor(server.B);await p.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await p.getByRole('button',{name:'상세 보기'}).first().click();await p.getByRole('button',{name:'검수 저장',exact:true}).waitFor();
  for(const label of ['공동 확정 점수','공동 이용 근거','변경 사유','공동 단원 기준','공동 유형 기준'])assert.equal(await p.getByLabel(label,{exact:false}).count(),0,label);
  assert.equal(await p.getByLabel('난이도 점수 슬라이더').count(),1);
  await p.getByLabel('직접 수정 점수 (선택)').fill('5.2');await p.getByRole('button',{name:'검수 저장',exact:true}).click();await p.getByText('검수 내용을 저장했습니다. 검수 완료 후에도 수정할 수 있습니다.').waitFor();
  await p.getByLabel('출제유형',{exact:true}).fill('직접 수정');await p.getByRole('button',{name:'다음 문항',exact:true}).click();await p.getByRole('button',{name:'계속 편집',exact:true}).click();assert.equal(await p.getByLabel('출제유형',{exact:true}).inputValue(),'직접 수정');
  await p.getByRole('button',{name:'다음 문항',exact:true}).click();await p.getByRole('button',{name:'저장 후 이동',exact:true}).click();await p.getByText('2 / 3',{exact:true}).waitFor();await p.getByRole('button',{name:'이전 문항',exact:true}).click();await p.getByText('1 / 3',{exact:true}).waitFor();assert.equal(await p.getByLabel('출제유형',{exact:true}).inputValue(),'직접 수정');
  await p.getByLabel('출제유형',{exact:true}).fill('완료 뒤 수정');await p.getByRole('button',{name:'검수 저장',exact:true}).click();await p.getByText('검수 내용을 저장했습니다. 검수 완료 후에도 수정할 수 있습니다.').waitFor();await p.screenshot({path:path.join(directory,'review-mobile.png'),fullPage:true});
  await p.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await p.getByRole('button',{name:'미리보기',exact:true}).first().click();await p.getByRole('dialog').getByRole('button',{name:'다음 문항'}).click();await p.getByRole('dialog').getByText('2 / 3',{exact:true}).waitFor();await p.getByRole('dialog').getByRole('button',{name:'닫기'}).click();
  await p.locator('#nav').getByRole('button',{name:'시험지',exact:true}).click();await p.getByRole('button',{name:'새 시험지 만들기'}).click();await p.getByLabel('시험지 제목',{exact:true}).fill('명시적 저장 시험지');
  assert.equal(writes.filter(n=>n==='bank_exam_save').length,0);p.declineNext=true;await p.getByRole('button',{name:'지금 서버에 저장'}).click();assert.equal(writes.filter(n=>n==='bank_exam_save').length,0);await p.getByRole('button',{name:'지금 서버에 저장'}).click();await p.getByText('내 시험지에 저장했습니다.',{exact:true}).waitFor();assert.equal(writes.filter(n=>n==='bank_exam_save').length,1);
  const saved=(await storage.rpc('bank_exam_list',{s:server.S,start_at:0}));assert.equal(saved.length,0,'other account private');
  const second=await pageFor(server.B);await second.locator('#nav').getByRole('button',{name:'시험지',exact:true}).click();await second.getByText('명시적 저장 시험지',{exact:true}).waitFor();await second.getByRole('button',{name:'이어 편집'}).click();await second.getByLabel('시험지 제목',{exact:true}).waitFor();assert.equal(await second.getByLabel('시험지 제목',{exact:true}).inputValue(),'명시적 저장 시험지');assert.equal(writes.filter(n=>n==='bank_exam_save').length,1);
  await p.locator('#nav').getByRole('button',{name:'홈',exact:true}).click();await p.getByRole('button',{name:/기출문제 복원하기/}).click();await p.locator('.source-tree-level').first().waitFor();for(const d of await p.locator('.source-tree-level').all())await d.locator(':scope > summary').click();await p.getByRole('button',{name:/2학기 중간고사/}).click();await p.getByRole('heading',{name:/3\/4문항/}).waitFor();await p.getByText(/누락 원본 번호: 객관식 2번/).waitFor();assert.equal(writes.filter(n=>n==='bank_exam_save').length,1);await p.screenshot({path:path.join(directory,'restore-mobile.png'),fullPage:true});
  await p.setViewportSize({width:1280,height:900});await p.screenshot({path:path.join(directory,'restore-desktop.png'),fullPage:true});
  await second.locator('#nav').getByRole('button',{name:'시험지',exact:true}).click();await second.getByRole('button',{name:'시험지 실제 삭제'}).click();assert.equal(await second.getByText('명시적 저장 시험지',{exact:true}).count(),1);
  second.promptAnswer='명시적 저장 시험지';await second.getByRole('button',{name:'시험지 실제 삭제'}).click();await second.getByText('서버에 저장한 시험지가 없습니다. 새 시험지를 만들어 저장하세요.').waitFor();assert.equal(writes.filter(n=>n==='bank_exam_save').length,1);
  const owner=await pageFor(server.A);await owner.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await owner.getByRole('button',{name:'상세 보기'}).first().click();await owner.getByRole('button',{name:'문항 실제 삭제'}).waitFor();const revision=owner.url().split('question/')[1],catalog=(await storage.rows('bank_catalog','revision_id=eq.'+revision))[0];
  await owner.getByRole('button',{name:'문항 실제 삭제'}).click();await owner.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='문항 실제 삭제'&&!b.disabled));assert.equal((await storage.rpc('bank_search_current',{s:server.S,filters:{},start_at:0})).length,3);
  owner.promptAnswer=catalog.question_id;await owner.getByRole('button',{name:'문항 실제 삭제'}).click();await owner.getByText('문항과 전용 파일을 삭제했습니다.').waitFor();assert.equal((await storage.rpc('bank_search_current',{s:server.S,filters:{},start_at:0})).length,2);
  fs.writeFileSync(path.join(directory,'result.json'),JSON.stringify({passed:true,writes,sourceItems:3,expected:4,missing:'objective:2',examDeletionConfirmed:true,questionDeletionConfirmed:true,saveCancellation:true,productionWrites:0},null,2));console.log('PASS phase 1 core browser workflow',directory);
 }finally{bank?.close();await browser?.close();if(web)await new Promise(resolve=>web.close(resolve));await server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
