'use strict';
// Real browser UI and real local SQL/RLS; identity and HTTP endpoints are simulated.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {localServer}=require('./shared-bank-local-server.cjs'),{SharedBankStorage}=require('../app/shared-bank-storage.cjs'),{ProjectStore}=require('../app/store.cjs'),{QuestionBank}=require('../app/question-bank.cjs'),{uuid}=require('../app/bank-model.cjs');
(async()=>{const server=await localServer(),directory=fs.mkdtempSync(path.join(__dirname,'../data/validation/web-bank-')),auth=server.auth(server.A),storage=new SharedBankStorage({auth,fetchImpl:server.fetch}),store=new ProjectStore(path.join(directory,'data'));let bank,browser,web;
try{
 const image=path.join(directory,'sample.png');await require('sharp')({create:{width:600,height:500,channels:3,background:'#ffffff'}}).png().toFile(image);let project=store.create(image);project=store.addRegion({projectId:project.id,region:{page:1,x:0,y:0,width:1,height:1},imageDataUrl:'data:image/png;base64,'+fs.readFileSync(image).toString('base64')});project=store.updateProblem(project.id,project.problems[0].id,p=>{p.original={id:uuid(),kind:'original',body:'$\\overline{AB}=\\frac{13}{2}\\,\\mathrm{cm}$인 삼각형의 넓이를 구하시오. <script>window.injected=true</script>',choices:['① 12','② 24'],answer:'②',solution:'밑변과 높이를 곱한 뒤 2로 나눕니다.',include:true,approval:{status:'approved'}};p.recognition={confirmed:true};});
 bank=new QuestionBank({directory:store.dataDir,store,storage,auth,appVersion:'test',buildDocx:async(i,file)=>fs.writeFileSync(file,'mock docx'),preview:async(i,file)=>fs.copyFileSync(image,file)});bank.wake=()=>{};await bank.root();bank.catalog(project.id);bank.editSource(project.id,'primary',{school:'검증중',academicYear:'2026',grade:'중2',semester:'2학기'});await bank.enqueue(project.id,[project.problems[0].original.id]);await bank.pump();const job=bank.state.jobs[0];assert.equal(job.status,'complete',job.error);await storage.review({revisionId:job.id,patch:{sharingAllowed:true,difficulty:'4.7',primaryUnit:'삼각형'},reason:'검수',expected:0});await storage.invite('teacher-b@example.test');
 const config=path.join(directory,'public-config.json');fs.writeFileSync(config,JSON.stringify(auth.config()));const dist=await require('../scripts/build-bank-web.cjs').build(config,path.join(directory,'site'));
 web=http.createServer((req,res)=>{const file=path.join(dist,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(dist)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Security-Policy',fs.readFileSync(path.join(dist,'_headers'),'utf8').split('Content-Security-Policy: ')[1].split('\n')[0].trim());res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>web.listen(0,'127.0.0.1',r));
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));browser=await chromium.launch({channel:'msedge',headless:true});
 async function pageFor(uid){const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});if(uid){const jwt=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';await context.addInitScript(({uid,jwt})=>sessionStorage.setItem('sb-test-project-auth-token',JSON.stringify({access_token:jwt,refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id:uid,email:uid.startsWith('a')?'animochoi@gmail.com':uid.startsWith('b')?'teacher-b@example.test':'outsider@example.test',aud:'authenticated',role:'authenticated'}})),{uid,jwt});}const page=await context.newPage();await page.route('https://test-project.supabase.co/**',async route=>{const req=route.request(),response=await server.fetch(req.url(),{method:req.method(),headers:req.headers(),body:req.postData()||undefined});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});return page;}
 const b=await pageFor(server.B);await b.goto('http://127.0.0.1:'+web.address().port);await b.getByText('검증중',{exact:false}).first().waitFor();assert.equal(await b.evaluate(()=>window.injected),undefined);await b.locator('.stat strong').first().filter({hasText:'1'}).waitFor();await b.screenshot({path:path.join(directory,'mobile-home.png'),fullPage:true});await b.screenshot({path:path.join(directory,'mobile-home-viewport.png')});assert.equal(await b.locator('.profile-menu').isVisible(),false);await b.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await b.locator('.cards .katex').first().waitFor();await b.screenshot({path:path.join(directory,'mobile-search.png'),fullPage:true});for(const width of [360,390,768,1280]){await b.setViewportSize({width,height:844});assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'horizontal overflow '+width);}await b.setViewportSize({width:390,height:844});await b.getByRole('button',{name:'미리보기',exact:true}).click();await b.getByRole('dialog').locator('.native-question .katex').first().waitFor();await b.getByRole('button',{name:'닫기',exact:true}).click();await b.getByText('상세 필터',{exact:true}).click();await b.getByLabel('난이도 최소 (확정·등록자·AI 순)',{exact:true}).fill('4.0');await b.getByLabel('난이도 최대 (보정 전)',{exact:true}).fill('5.0');await b.getByRole('button',{name:'검색',exact:true}).click();await b.getByText('4.7점 · 공동 확정').waitFor();b.once('dialog',d=>d.accept());await b.getByRole('button',{name:'시험지에 담기',exact:true}).click();await b.locator('#nav').getByRole('button',{name:'시험지',exact:true}).click();await b.getByRole('button',{name:'새 시험지 만들기'}).click();const downloading=b.waitForEvent('download');await b.getByRole('button',{name:'선택 목록 내보내기'}).click();const download=await downloading;const chosen=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(chosen.items[0].revisionId,job.id);
 await b.locator('#nav').getByRole('button',{name:'문항찾기'}).click();await b.getByRole('button',{name:'상세 보기'}).click();await b.getByLabel('변경 사유').fill('난이도 비교 제안');await b.getByLabel('공동 확정 점수 또는 제안 (빈칸 = 미평가)').fill('6.5');await b.getByRole('button',{name:'공동 분류 수정 제안'}).click();await b.getByText('분류 수정안을 검수자에게 제출했습니다. 공동 확정값은 승인 후 반영됩니다.',{exact:true}).waitFor();assert.equal((await storage.rows('bank_catalog','revision_id=eq.'+job.id))[0].confirmed.difficulty,'4.7');
 const a=await pageFor(server.A);await a.goto('http://127.0.0.1:'+web.address().port);await a.getByLabel('내 계정 메뉴').click();await a.getByRole('button',{name:'관리',exact:true}).click();await a.getByText('Storage 기록',{exact:false}).first().waitFor();await a.screenshot({path:path.join(directory,'admin.png'),fullPage:true});
 const x=await pageFor(server.X);await x.goto('http://127.0.0.1:'+web.address().port);await x.getByText('로그인은 되었지만 공동 문제은행 이용 승인이 필요합니다.',{exact:false}).waitFor();assert.equal(await x.locator('#workspace').isVisible(),false);
 await a.getByLabel('내 계정 메뉴').click();await a.getByRole('button',{name:'멤버 관리'}).click();await a.getByLabel('참여 이메일 (선택)').fill('outsider@example.test');await a.getByRole('button',{name:'초대 링크 만들기'}).click();
 const inviteLink=await a.getByLabel('생성된 초대 링크').inputValue();assert.match(inviteLink,/#invite\/[A-Za-z0-9_-]{43}$/);
 await x.goto(inviteLink);await x.getByRole('button',{name:'참여하기 / 승인 신청'}).waitFor();assert.equal(await x.locator('#workspace').isVisible(),false);
 await x.getByRole('button',{name:'참여하기 / 승인 신청'}).click();await x.locator('#workspace').waitFor({state:'visible'});assert.equal((await server.sql(server.A,"select count(*)::integer n from bank_members where email='outsider@example.test'")).rows[0].n,1);
 const guest=await pageFor(null);await guest.goto('http://127.0.0.1:'+web.address().port);await guest.getByRole('button',{name:'Google로 로그인'}).waitFor();assert.equal(await guest.locator('#workspace').isVisible(),false);
 await b.screenshot({path:path.join(directory,'teacher.png'),fullPage:true});console.log('PASS web login gate / server filtering / preview metadata / proposal separation / selection export / owner usage UI; simulated identities and HTTP, local real PostgreSQL. '+directory);
}finally{bank?.close();await browser?.close();web?.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

