'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {moveNoReplace}=require('../app/windows-move.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'phase2-native-move-'));t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});const source=path.join(dir,'한글 & $() ; 원본.png'),destination=path.join(dir,'완료된 시험지','원본.png'),bytes=Buffer.from('isolated original');fs.writeFileSync(source,bytes);fs.mkdirSync(path.dirname(destination));return {source,destination,bytes,expectedHash:crypto.createHash('sha256').update(bytes).digest('hex')};}
test('real MoveFileExW moves a Unicode fixture once, without a link or source copy',{skip:process.platform!=='win32'},t=>{const f=fixture(t);const packet=moveNoReplace(f.source,f.destination,f);assert.equal(packet.flags,0);assert.equal(packet.operation,'MoveFileExW');assert.equal(fs.existsSync(f.source),false);assert.deepEqual(fs.readFileSync(f.destination),f.bytes);assert.equal(fs.statSync(f.destination).nlink,1);});
test('real OS no-replace refuses an existing destination and preserves both files',{skip:process.platform!=='win32'},t=>{const f=fixture(t);fs.writeFileSync(f.destination,'unrelated collision');assert.throws(()=>moveNoReplace(f.source,f.destination,f),e=>e.code==='EEXIST');assert.deepEqual(fs.readFileSync(f.source),f.bytes);assert.equal(fs.readFileSync(f.destination,'utf8'),'unrelated collision');});
test('helper checks selected content again before invoking native rename',{skip:process.platform!=='win32'},t=>{const f=fixture(t);fs.writeFileSync(f.source,'changed after selection');assert.throws(()=>moveNoReplace(f.source,f.destination,f),e=>e.code==='source_changed'&&e.dispatched===false);assert.equal(fs.readFileSync(f.source,'utf8'),'changed after selection');assert.equal(fs.existsSync(f.destination),false);});
test('native arguments are separate parameters and no overwrite/copy flag is accepted',t=>{const f=fixture(t);let seen=false;moveNoReplace(f.source,f.destination,{...f,execute:(exe,args,options)=>{seen=true;assert.equal(args[args.indexOf('-Source')+1],f.source);assert.equal(args[args.indexOf('-Destination')+1],f.destination);assert.equal(options.windowsHide,true);assert.equal(options.shell,undefined);return JSON.stringify({ok:true,operation:'MoveFileExW',flags:0});}});assert.equal(seen,true);assert.throws(()=>moveNoReplace(f.source,f.destination,{...f,execute:()=>JSON.stringify({ok:true,operation:'MoveFileExW',flags:1})}));});
test('cross-volume rejection cannot become copy/delete fallback',t=>{const f=fixture(t);assert.throws(()=>moveNoReplace(f.source,f.destination,{...f,execute:()=>JSON.stringify({ok:false,operation:'MoveFileExW',flags:0,win32Code:17})}),e=>e.code==='EXDEV');assert.deepEqual(fs.readFileSync(f.source),f.bytes);assert.equal(fs.existsSync(f.destination),false);});
test('lost process response and disconnected share are marked result unknown',t=>{const f=fixture(t);for(const execute of [()=>{throw Object.assign(Error('timed out'),{code:'ETIMEDOUT'});},()=>JSON.stringify({ok:false,operation:'MoveFileExW',flags:0,win32Code:64})])assert.throws(()=>moveNoReplace(f.source,f.destination,{...f,execute}),e=>e.moveResultUnknown===true);assert.deepEqual(fs.readFileSync(f.source),f.bytes);});
test('setup failure before OS dispatch retains the source and identifies no move',t=>{const f=fixture(t);assert.throws(()=>moveNoReplace(f.source,f.destination,{...f,execute:()=>JSON.stringify({setupError:true,message:'no native helper'})}),e=>e.dispatched===false);assert.equal(fs.existsSync(f.source),true);});
