'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),D=require('./difficulty-assessment.cjs');
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(D.canonical(v))).digest('hex');
// IDs/labels, filenames, timestamps, approval state and cosmetic placement do not
// determine assessment. Mathematical point names/conditions remain significant.
function scope(s={}){return Object.fromEntries(Object.entries(s||{}).filter(([k])=>!['name','label','title','updatedAt','version'].includes(k)).map(([k,v])=>[k,Array.isArray(v)?v.map(D.canonical).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))):v]));}
function basis(q,p,s){return hash({body:q.body,choices:q.choices,answer:q.answer,solution:require('./solution-display.js').solutionText(q),solutionStale:!!q.solutionStale,solutionDraft:!!q.solutionDraft,diagram:q.diagram||q.observedDiagram||null,layout:q.layoutDocument||null,statementBox:q.statementBox||[],conditions:p?.recognition?.conditions||[],marks:p?.recognition?.marks||[],scope:scope(s)});}
function source(p,s,criteria){return hash({stage:'pre-recognition-v1',images:(p.cropPaths||[]).map(f=>require('./lossless-local-identity.cjs').digest(f,'raw',crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'))),scope:scope(s),criteria});}
function record(value,q,p,s,provenance={}){const criteria=provenance.criteriaVersion||D.version;return {...D.normalize(value),inputHash:basis(q,p,s),scope:structuredClone(s||{}),model:provenance.model||null,provider:provenance.provider||null,effort:provenance.effort||null,instructionsVersion:criteria,criteriaVersion:criteria,at:new Date().toISOString()};}
function importEmbedded(metadata,q,p,s){const a=q.assessment;if(!a||a.criteriaVersion!==D.version||a.inputHash!==basis(q,p,s))return false;if(metadata.analysis?.status==='complete'&&metadata.analysis.basis===a.inputHash)return false;const proofPolicy=require('./difficulty-policy.cjs'),proofAdjustment=metadata.analysis?.basis===a.inputHash?proofPolicy.rebase({body:q.body,metadata},a.score):proofPolicy.adjustment({body:q.body},a.score);const d=metadata.difficulty;D.preserveHistory(d);if(metadata.analysis?.basis&&metadata.analysis.basis!==a.inputHash){}d.assessmentStatus=a.status;d.features=a.features;d.aiBand=a.band;d.reason=a.reason;d.aiScore=a.score;d.proofAdjustment=proofAdjustment;d.criteriaVersion=a.criteriaVersion;d.scope=structuredClone(a.scope);d.assessment=structuredClone(a);d.reassessmentRequired=false;if(d.userScore==null)d.status=a.status==='estimated'?'ai_suggested':'unevaluated';metadata.analysis={status:a.status==='estimated'?'complete':'unavailable',basis:a.inputHash,model:a.model,provider:a.provider,criteriaVersion:a.criteriaVersion,at:a.at,origin:'existing_request',error:a.status==='estimated'?null:a.reason};return true;}
function comparisonPlan(items,{limit=12,targetModel}){const selected=[],seen=new Set();for(const item of [...items].sort((a,b)=>String(a.id).localeCompare(String(b.id)))){const m=item.metadata||{},d=m.difficulty||{},e=D.effective({metadata:m}),key=JSON.stringify([m.source?.grade,scope(d.scope),e.band,m.content?.responseType]);if(d.aiScore==null||seen.has(key))continue;seen.add(key);selected.push({questionId:item.id,localQuestionId:item.questionId,projectId:item.projectId,comparisonRequest:{projectId:item.projectId,questionIds:[item.questionId],compare:true},basis:m.analysis?.basis,previousModel:m.analysis?.model,previousScore:d.aiScore,targetModel});if(selected.length>=Math.min(30,Math.max(1,limit)))break;}return {status:'plan_only',selected,aiCalls:0,referenceTruth:false,automaticCalibration:false};}
module.exports={hash,scope,basis,source,record,importEmbedded,comparisonPlan};
function readRecognition(store,key){try{return JSON.parse(fs.readFileSync(require('node:path').join(store.dataDir,'recognition-input-cache.json'),'utf8'))[key]||null;}catch{return null;}}
function writeRecognition(store,key,value){const path=require('node:path').join(store.dataDir,'recognition-input-cache.json');let values={};try{values=JSON.parse(fs.readFileSync(path,'utf8'));}catch{}delete values[key];values[key]=value;require('./store.cjs').atomicWrite(path,Object.fromEntries(Object.entries(values).slice(-200)));}
Object.assign(module.exports,{readRecognition,writeRecognition});
