'use strict';
const fs=require('node:fs'),path=require('node:path');
const {QuestionBank}=require('./question-bank.cjs'),{SharedBankAuth}=require('./shared-bank-auth.cjs'),{SharedBankStorage}=require('./shared-bank-storage.cjs'),{validId,digest}=require('./bank-drive.cjs');
function installBank({directory,store,handle,shell,dialog,window,safeStorage,buildDocument,decorate,send,appVersion,blocked,getBridge,getSettings}){
 const auth=new SharedBankAuth({directory:path.join(directory,'shared-bank-auth'),safeStorage,openExternal:(url,options)=>require('./bank-login-browser.cjs').openBankLogin(url,options,{shell})}),storage=new SharedBankStorage({auth});
 const bundled=path.join(__dirname,'shared-bank-config.json');if(!auth.status().configured&&fs.existsSync(bundled))auth.configure(JSON.parse(fs.readFileSync(bundled,'utf8')));
 const bankDirectory=()=>path.join(directory,'shared-banks',auth.status().configured?digest(Buffer.from(JSON.stringify([auth.config().url,auth.config().spaceId]))).slice(0,24):'unconfigured');
 const rendererVersion=require('crypto').randomUUID();
 const createBank=()=>new QuestionBank({rendererVersion,losslessUploads:require('./lossless-config.json').enabled===true,directory:bankDirectory(),store,auth,storage,appVersion,onEvent:send,buildDocx:async(input,output)=>{
  const project=structuredClone(input.project);project.problems=project.problems.filter(p=>p.id===input.problemId);project.settings.audience='teacher';
  for(const p of project.problems)for(const q of [p.original,...p.variants].filter(Boolean))q.include=q.id===input.questionId;
  const target=project.problems.flatMap(p=>[p.original,...p.variants]).find(q=>q?.id===input.questionId);if(target.approval?.status!=='approved')project.title+=' · 미검수 보관본';
  return buildDocument(project,output,{archive:true,directory:path.join(path.dirname(output),'render')});
 },preview:async(document,output)=>{
  // Reuse the existing PDF renderer; preview is optional and never the native source.
  const {BrowserWindow}=require('electron'),dir=path.join(path.dirname(document),'render'),snapshot=JSON.parse(fs.readFileSync(path.join(dir,'export-input.json'),'utf8'));
  const html=path.join(dir,'bank-preview.html');fs.writeFileSync(html,require('./pdf-export.cjs').documentHtml(snapshot));
  const w=new BrowserWindow({show:false,width:794,height:1123,useContentSize:true,backgroundColor:'#ffffff',webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,sandbox:true}});
  try{await w.loadURL(require('node:url').pathToFileURL(html).href);await w.webContents.executeJavaScript('Promise.all([document.fonts.ready,...Array.from(document.images,i=>i.decode())]).then(()=>true)');const image=await w.webContents.capturePage();if(image.isEmpty())throw Error('미리보기 이미지가 없습니다.');fs.writeFileSync(output,image.toPNG());}finally{w.destroy();}
 }});
 let bank=createBank();const analysis=new (require('./bank-analysis.cjs').BankAnalysis)({store,getBridge,getSettings});
 let maintenance=new (require('./bank-maintenance.cjs').BankMaintenance)({bank,getBridge,getSettings,blocked:()=>blocked()||analysis.running,onEvent:send});
 const register=handle;handle=(name,fn)=>register(name,(...args)=>{if(bank.blockedError&&name!=='bankStatus')throw Error(bank.blockedError);return fn(...args);});
 let analysisTimer,analysisClosed=false;
 const schedule=()=>{clearTimeout(analysisTimer);analysisTimer=setTimeout(runAnalysis,4000);analysisTimer.unref?.();};
 const runAnalysis=async()=>{if(analysisClosed||bank.state.analysisPaused)return;if(blocked()||analysis.running){schedule();return;}const activeBank=bank,task=activeBank.state.analysisQueue?.[0];if(!task)return;const captured=JSON.parse(JSON.stringify(task));task.inFlightIds=captured.questionIds;task.questionIds=[];activeBank.save();try{const project=store.get(captured.projectId);const ids=captured.questionIds.filter(id=>project.problems.some(p=>[p.original,...p.variants].some(q=>q?.id===id)));if(ids.length){const result=await analysis.run(activeBank,{...captured,automatic:true,questionIds:ids,provider:activeBank.state.analysisProvider||'codex'});if(result.waiting){task.questionIds=[...new Set([...task.questionIds,...result.waitingIds])];activeBank.state.analysisPaused=result.errors[0]?.message||'서비스 대기';}}}catch(e){activeBank.state.analysisError=String(e.message);}finally{delete task.inFlightIds;if(!task.questionIds.length)activeBank.state.analysisQueue=activeBank.state.analysisQueue.filter(x=>x!==task);activeBank.save();if(bank.state.analysisQueue?.length&&!bank.state.analysisPaused)schedule();}};
 store.onWrite=(p,previous)=>{if(p.queueSource)return;bank.observe(p,previous);const changed=[];for(const problem of p.problems){const old=previous?.problems?.find(x=>x.id===problem.id);for(const q of [problem.original,...problem.variants].filter(Boolean)){const before=[old?.original,...(old?.variants||[])].find(x=>x?.id===q.id);if(q.body&&(!before||require('./bank-analysis.cjs').basis(q,problem,p.scope)!==require('./bank-analysis.cjs').basis(before,old,previous.scope)))changed.push(q.id);}}if(changed.length){bank.state.analysisQueue||=[];let task=bank.state.analysisQueue.find(x=>x.projectId===p.id);if(!task)bank.state.analysisQueue.push(task={projectId:p.id,questionIds:[]});task.questionIds=[...new Set([...task.questionIds,...changed])];bank.save();schedule();}};
 for(const task of bank.state.analysisQueue||[]){task.questionIds=[...new Set([...task.questionIds,...(task.inFlightIds||[])])];delete task.inFlightIds;}
 if(bank.state.analysisQueue?.length){bank.save();schedule();}
 handle('bankStatus',({projectId,provider}={})=>{if(['codex','gemini','claude'].includes(provider))bank.state.analysisProvider=provider;const status=projectId?bank.catalog(projectId):bank.status();return {...status,typeCatalog:require('./question-types.cjs').detailedCatalog,uploadRunning:bank.running,uploadActiveJobId:bank.activeId||null,analysisRunning:analysis.running,analysisPending:(bank.state.analysisQueue||[]).map(task=>({projectId:task.projectId,count:new Set([...(task.questionIds||[]),...(task.inFlightIds||[])]).size}))};});
 handle('bankConfigure',async()=>{if(bank.running||analysis.running||maintenance.active)throw Error('업로드·분석이 끝난 후 연결 설정을 변경하세요.');const result=await dialog.showOpenDialog(window(),{title:'관리자에게 받은 공동 문제은행 연결 JSON 선택',properties:['openFile'],filters:[{name:'JSON',extensions:['json']}]});if(result.canceled)return bank.status();const config=require('./shared-bank-auth.cjs').configuration(JSON.parse(fs.readFileSync(result.filePaths[0],'utf8')));maintenance.close();bank.close();auth.configure(config);bank=createBank();maintenance=new(require('./bank-maintenance.cjs').BankMaintenance)({bank,getBridge,getSettings,blocked:()=>blocked()||analysis.running,onEvent:send});bank.wake();return bank.status();});
 handle('bankConnect',async(options={})=>{const previous=auth.status().account?.id;await bank.connect({browser:options.browser||'auto'});if(previous&&previous!==auth.status().account?.id){bank.state.auto=false;bank.save();}return bank.root();});
 handle('bankSearch',async({filters={},start=0}={})=>{const rows=await storage.search(filters,start);for(const c of rows)bank.state.cache[c.revision_id]={...bank.state.cache[c.revision_id],commitId:c.commit_id,revisionId:c.revision_id,questionId:c.question_id,metadata:c.metadata,author:{email:c.owner_email}};bank.save();return rows;});
 handle('bankCatalog',({revisionId})=>storage.rows('bank_catalog','revision_id=eq.'+revisionId));
 handle('bankRevisionStatus',async({revisionId})=>{
  if(!/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(revisionId))throw Error('기존 revision ID를 확인하세요.');
  const job=bank.state.jobs.find(j=>j.revisionId===revisionId),ids=[...new Set(Object.values(job?.remote||{}).map(r=>r?.id).filter(id=>/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(id)))];
  const [revisions,catalog,entries]=await Promise.all([storage.rows('bank_revisions','id=eq.'+revisionId),storage.rows('bank_catalog','revision_id=eq.'+revisionId),ids.length?storage.rows('bank_entries','id=in.('+ids.join(',')+')'):Promise.resolve([])]);
  return {revisionId,reservationScope:'locally-recorded-file-ids',queriedFileIds:ids,revisions:revisions.map(r=>({id:r.id,questionId:r.question_id,parentId:r.parent_id,committed:r.committed})),catalog:catalog.map(c=>({revisionId:c.revision_id,questionId:c.question_id,commitId:c.commit_id})),entries:entries.map(e=>({id:e.id,role:e.props?.role,kind:e.kind,verified:e.verified,size:e.size,chunks:e.chunks,sha256:e.sha256}))};
 });
 handle('bankReviewSave',async({revisionId,patch,expected})=>{const row=(await storage.rows('bank_catalog','revision_id=eq.'+revisionId))[0];if(!row)throw Error('문항을 읽을 수 없습니다.');return storage.rpc('bank_review_save',{r:revisionId,p:require('./question-types.cjs').reviewPatch(patch,row),expected});});handle('bankRateSave',({revisionId,value})=>storage.rpc('bank_rate_save',{r:revisionId,value}));handle('bankReview',args=>storage.review(args));handle('bankPropose',args=>storage.propose(args));handle('bankRole',({email,role})=>storage.role(email,role));handle('bankUsage',()=>storage.usage());handle('bankReindex',()=>storage.reindex());
 handle('bankPreview',async({id})=>{const meta=await storage.get(id);if(meta.appProperties?.role!=='preview'||Number(meta.size)>12*1024*1024)throw Error('미리보기 파일을 확인하세요.');const bytes=await storage.download(id);return 'data:'+require('./lossless-image.cjs').mime(bytes)+';base64,'+bytes.toString('base64');});
 handle('bankImportExam',async({revisionId})=>{if(blocked())throw Error('현재 작업을 마친 후 불러오세요.');return decorate(await require('./bank-transfer.cjs').importExam(bank,revisionId));});
 handle('bankImportSelection',async({items,order}={})=>{if(blocked())throw Error('현재 작업을 마친 후 불러오세요.');let value;if(items)value={format:'examstudio-selection-v1',server:auth.config().url,spaceId:auth.config().spaceId,items,order};else{const pick=await dialog.showOpenDialog(window(),{title:'웹에서 저장한 선택 목록',properties:['openFile'],filters:[{name:'JSON',extensions:['json']}]});if(pick.canceled)return null;if(fs.statSync(pick.filePaths[0]).size>1024*1024)throw Error('선택 목록 파일이 너무 큽니다.');value=JSON.parse(fs.readFileSync(pick.filePaths[0],'utf8'));}const project=await require('./bank-transfer.cjs').importSelection(bank,value);return decorate(project);});
 handle('bankBackup',async({admin=false,revisionIds=[]}={})=>{const pick=await dialog.showOpenDialog(window(),{title:admin?'관리자 공동 자료 백업 위치':'선택 문항 내려받기 위치',properties:['openDirectory','createDirectory']});if(pick.canceled)return null;const target=path.join(pick.filePaths[0],'문제은행-백업-'+new Date().toISOString().replace(/[:.]/g,'-'));return require('./bank-transfer.cjs').backup(bank,target,{admin,revisionIds});});
 handle('bankRestoreBackup',async()=>{if(blocked())throw Error('현재 작업을 마친 후 복원하세요.');const pick=await dialog.showOpenDialog(window(),{title:'backup.json이 있는 백업 폴더',properties:['openDirectory']});if(pick.canceled)return null;const result=await require('./bank-transfer.cjs').restoreBackup(bank,pick.filePaths[0]);return{versions:result.versions,workspaceFile:result.workspaceFile,project:result.projects[0]?decorate(result.projects[0]):null};});
 handle('bankMaintenanceCandidates',()=>maintenance.candidates());handle('bankMaintenanceStatus',()=>maintenance.status());handle('bankMaintenancePlan',args=>maintenance.plan(args));handle('bankMaintenanceSample',({id})=>maintenance.sample(id));handle('bankMaintenanceStart',({id})=>maintenance.start(id));handle('bankMaintenancePause',({id})=>maintenance.pause(id));handle('bankMaintenanceUndo',({id})=>maintenance.undo(id));handle('bankMaintenancePreview',({id,questionId,before})=>maintenance.preview(id,questionId,before));
 handle('bankMembers',()=>storage.members());handle('bankInvite',({email,enabled})=>storage.invite(email,enabled));
 handle('bankExportConfig',async()=>{const result=await dialog.showSaveDialog(window(),{title:'동료에게 전달할 공개 연결 설정 저장',defaultPath:'문제공방-공동은행.json',filters:[{name:'JSON',extensions:['json']}]});if(!result.canceled)fs.writeFileSync(result.filePath,JSON.stringify(auth.config(),null,2));return !result.canceled;});handle('bankCancelConnect',()=>{auth.cancel();return bank.status();});handle('bankDisconnect',()=>bank.disconnect());
 handle('bankRoot',({id}={})=>bank.root(id||null));handle('bankAuto',({enabled})=>bank.setAuto(enabled));
 handle('bankAnalysisComparisonPlan',args=>require('./assessment-cache.cjs').comparisonPlan(Object.values(bank.state.items),args));
 handle('bankAnalyze',args=>{if(blocked())throw Error('현재 문항 작업이 끝난 후 추천하세요.');return analysis.run(bank,args).then(result=>{if(!result.waiting){bank.state.analysisPaused=null;bank.save();if(bank.state.analysisQueue?.length)schedule();}return result;});});
 handle('bankTargets',({projectId,questionIds})=>bank.targets(projectId,questionIds));
 handle('bankSave',({projectId,questionIds,selections})=>bank.enqueue(projectId,questionIds,selections));
 handle('bankEdit',({ids,patch})=>{if(analysis.running)throw Error('소단원·난이도 추천이 끝난 뒤 문항 태그·점수를 수정하세요.');return bank.edit(ids,patch);});handle('bankSource',({projectId,sourceId,metadata})=>bank.editSource(projectId,sourceId,metadata));
 handle('bankAttach',async({id})=>{const result=await dialog.showOpenDialog(window(),{title:'이 문항에 보관할 기존 HWP·PDF 선택',properties:['openFile','multiSelections'],filters:[{name:'기존 출력 파일',extensions:['hwp','pdf']}]});if(result.canceled)return bank.status();return bank.attach(id,result.filePaths);});
 handle('bankRefresh',params=>bank.refresh(params));handle('bankRetry',({id})=>bank.retry(id));handle('bankRetryTimedOut',({limit})=>bank.retryTimedOut(limit));handle('bankPause',({id})=>bank.pause(id));
 handle('bankRestore',async({revisionId})=>{if(blocked())throw Error('진행 중인 문항 작업을 마친 후 불러오세요.');const result=await bank.restore(revisionId);result.project=decorate(result.project);return result;});
 handle('bankOpenFolder',()=>{throw Error('공동 저장 문항은 저장 문항 목록에서 확인하세요. 관리자 대시보드는 일반 교사에게 공개하지 않습니다.');});
 bank.wake();if(bank.state.dirty.length)void bank.flushDirty();return {bank:()=>bank,rehydrate:project=>require('./lossless-restore.cjs').rehydrate(project,storage),analysis,close:()=>{analysisClosed=true;clearTimeout(analysisTimer);maintenance.close();bank.close();},afterExport:(args)=>bank.afterExport(args)};
}
module.exports={installBank};
