const fineTypeLabel=row=>{const c=row.metadata?.classification||{},t=row.confirmed?.types?.[0]||c.confirmed?.types?.[0]||c.types?.[0];return t?.coreTask?.name||row.confirmed?.type||t?.name||'';};
function attachTypes(input,list){const d=document.createElement('datalist');d.id='fine-types-'+Math.random().toString(36).slice(2);for(const t of list||[]){const o=document.createElement('option');o.value=t.name;d.append(o);}input.parentElement.append(d);input.setAttribute('list',d.id);}
const statuses={local:'내 PC에 저장됨',queued:'업로드 대기',preparing:'파일 준비 중',uploading:'업로드 중',complete:'업로드 완료',auth:'로그인 확인 필요',failed:'업로드 실패 · 재시도 가능',conflict:'수정 버전 확인 필요',paused:'업로드 일시정지'};
export function recommendationFailure(item,q){
 const error=item.metadata?.analysis?.error;if(!error)return '';
 if(error==='풀이와 근거 없이 난이도를 확정할 수 없습니다.'&&q?.solution?.trim()&&q.solutionStale)return '이전 AI 추천은 저장 풀이의 변경됨 상태 때문에 확정 풀이로 인정하지 않았습니다. 현재 풀이를 검토한 선택 문항만 AI 추천을 다시 실행하세요.';
 return error;
}
export function installBankUI({api,state,$,element,button,openDialog,renderAll,loadProject,workflowUI,blocked,toast,getProvider,renderQuestion}){
 let snapshot=null,refreshTimer=null,loginBrowser='auto',selectionState=null,analyzing=false,activity=null,observedBackgroundAt=null,dismissedBackgroundAt=null;
 const statusText=s=>statuses[s]||s||'로컬 저장';
 function progressText(){
  if(!activity){
   const p=snapshot?.analysisProgress,projectId=state.project?.id,pending=snapshot?.analysisPending?.find(x=>x.projectId===projectId);
   if(p?.projectId===projectId&&p.status==='running'&&snapshot.analysisRunning)observedBackgroundAt=p.startedAt;
   if(p?.projectId===projectId&&observedBackgroundAt===p.startedAt&&dismissedBackgroundAt!==p.startedAt){
    const running=p.status==='running'&&snapshot.analysisRunning;
    const title=p.status==='waiting'?'AI 서비스 복구 대기 · 추가 요청 중지':running?'소단원·난이도 자동 추천 중':p.status==='complete'?'소단원·난이도 자동 추천 완료':p.status==='partial'?'소단원·난이도 추천 일부 실패':'소단원·난이도 추천 중단 확인 필요';
    const detail=`${p.completed||0}/${p.total||0}문항 처리 · 새 추천 ${p.analyzed||0} · 재사용 ${p.reused||0} · 실패 ${p.failed||0}${running&&p.currentQuestionId?` · 현재 ${Math.min((p.completed||0)+1,p.total)}번째 문항`:''}${p.error?' · '+p.error:''}`;
    return {title,detail,done:!running};
   }
   if(pending?.count)return {title:'소단원·난이도 자동 추천 대기',detail:`${pending.count}문항 대기 · 문항 본문과 저장된 풀이를 분석합니다. 업로드 창은 계속 사용할 수 있습니다.`,done:false};
   return null;
  }
  if(activity.kind==='recommend'){
   const p=snapshot?.analysisProgress;
   if(activity.error)return {title:'소단원·난이도 추천 실패',detail:activity.error,done:true};
   if(activity.waitingForBackground&&p?.projectId===activity.projectId&&snapshot.analysisRunning)return {title:'진행 중인 소단원·난이도 자동 추천 대기',detail:`${p.completed||0}/${p.total||0}문항 처리 · 새 추천 ${p.analyzed||0} · 재사용 ${p.reused||0} · 실패 ${p.failed||0}`,done:false};
   if(p?.projectId===activity.projectId&&Date.parse(p.startedAt)>=activity.startedAt-1000){const detail=`${p.completed||0}/${p.total||activity.total}문항 처리 · 새 추천 ${p.analyzed||0} · 재사용 ${p.reused||0} · 실패 ${p.failed||0}`;return {title:p.status==='waiting'?'AI 서비스 복구 대기 · 추가 요청 중지':p.status==='running'?'소단원·난이도 추천 중':p.status==='complete'?'소단원·난이도 추천 완료':'소단원·난이도 추천 일부 실패',detail,done:p.status!=='running'};}
   return {title:'소단원·난이도 추천 준비 중',detail:`선택 ${activity.total}문항`,done:false};
  }
  const jobs=(activity.itemIds||[]).map(id=>snapshot?.items.find(i=>i.id===id)).map(i=>i&&snapshot?.jobs.find(j=>j.revisionId===i.latestRevisionId)).filter(Boolean),complete=jobs.filter(j=>j.status==='complete'&&j.committed).length,failed=jobs.filter(j=>['failed','conflict','auth','paused'].includes(j.status)).length,active=jobs.filter(j=>['queued','preparing','uploading'].includes(j.status)),known=jobs.length;
  const file=active.find(j=>j.status==='uploading'&&Number.isInteger(j.filesTotal));
  const detail=`저장 완료 ${complete}/${activity.total}문항 · 진행/대기 ${active.length} · 확인 필요 ${failed}${file?` · 현재 문항 파일 ${file.filesCompleted||0}/${file.filesTotal}개`:''}${known<activity.total?` · ${activity.total-known}문항은 기존 작업 확인 중`:''}`;
  if(activity.error)return {title:'문제은행 업로드 실패',detail:activity.error+' · '+detail,done:true};
  if(complete+failed>=activity.total)return {title:failed?'문제은행 업로드 일부 실패':'문제은행 업로드 완료',detail,done:true};
  return {title:activity.enqueueing?'문제은행 저장 대기열 준비 중':'문제은행 업로드 중',detail,done:false};
 }
 function renderProgress(){const panel=$('bankProgressPanel');if(!panel)return;const info=progressText();if(!info){panel.hidden=true;return;}panel.hidden=false;panel.querySelector('strong').textContent=info.title;panel.querySelector('span').textContent=info.detail;const close=panel.querySelector('button');close.hidden=!info.done;panel.classList.toggle('bank-progress-error',/실패|확인 필요/.test(info.title));}
 function beginProgress(kind,projectId,total){activity={kind,projectId,total,startedAt:Date.now(),enqueueing:kind==='upload',itemIds:[]};renderProgress();}
 const act=fn=>async event=>{const control=event?.currentTarget;if(control?.disabled)return;if(control)control.disabled=true;try{await fn();}catch(e){const node=$('bankMessage');if(node)node.textContent=String(e.message).replace(/^Error invoking remote method '[^']+': (?:Error: )?/,'');else toast(e.message,true);}finally{if(control?.isConnected)control.disabled=false;}};
 function shell(title,active=''){
  const root=openDialog(title,'문제공방 · 교사용 문제은행','bank-modal'),nav=element('div','bank-actions bank-tabs');nav.setAttribute('role','tablist');nav.setAttribute('aria-label','문제은행');
  for(const [name,fn,key] of [['시험지 공통 정보',common,'common'],['현재 문항',local,'local'],['업로드 작업',jobs,'jobs'],['저장 문항 목록',remote,'remote'],['연결 설정',settings,'settings']]){const b=button(name,'button compact outline',act(fn));b.setAttribute('role','tab');b.setAttribute('aria-selected',String(active===key));nav.append(b);}
  const message=element('p','review-notice');message.id='bankMessage';message.setAttribute('aria-live','polite');if(['common','local','jobs'].includes(active)){const panel=element('div','bank-progress-panel');panel.id='bankProgressPanel';panel.setAttribute('role','status');panel.setAttribute('aria-live','polite');const dismiss=button('닫기','button compact outline',()=>{dismissedBackgroundAt=snapshot?.analysisProgress?.startedAt||null;activity=null;renderProgress();});panel.append(element('strong'),element('span'),dismiss);root.append(panel);}root.append(nav,message);renderProgress();return root;
 }
 async function entry(questionIds=null){const s=await read();selectionState=state.project?{projectId:state.project.id,ids:questionIds?new Set(questionIds):null}:null;if(s.auth.connected)await common();else await settings();}
 async function preview(p,q,item){const dialog=element('dialog','bank-preview-modal');dialog.setAttribute('aria-label','등록할 문제 보기');const close=button('닫기','button outline',()=>dialog.close());dialog.append(element('h3','',item?.metadata.source.originalNumber?'원문 '+item.metadata.source.originalNumber+'번':'등록할 문제 보기'),close,element('p','editor-hint',describe(item)),await renderQuestion(p,q));const reasons=[...new Set([item?.metadata.classification.suggested?.reason,item?.metadata.difficulty.reason].filter(Boolean))];if(reasons.length){const details=element('details');details.append(element('summary','','소단원·난이도 추천 근거'),...reasons.map(r=>element('p','',r)));dialog.append(details);}dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();}
 async function read(catalog=false){snapshot=await api.bankStatus(catalog&&state.project?{projectId:state.project.id}:{});if(snapshot.error)toast(snapshot.error,true);refreshCards();return snapshot;}
 const score=item=>{if(item.finalDifficulty){const e=item.finalDifficulty;return e.number===null?'미분석·판단보류':e.number.toFixed(1)+'점 · '+e.numberSource+' / '+(e.number<=3?'하':e.number<8?'중':'상');}const d=item.metadata?.difficulty,a=item.metadata?.analysis;if(d?.userScore!==null&&d?.userScore!==undefined)return d.userScore+'점 · 내 평가';if(d?.criteriaVersion===snapshot?.difficultyCriteriaVersion&&!d?.reassessmentRequired&&d?.aiScore!==null&&d?.aiScore!==undefined)return d.aiScore+'점 · AI 추천';if(a?.status==='running')return '난이도 평가 중';if(a?.status==='failed')return '미평가 · AI 추천 실패';if(a?.status==='complete')return '미평가 · 새 풀이 기준으로 재분석 필요';return '미평가 · 추천 전';};
 function describe(item){const m=item.metadata||{},s=m.source||{};return [s.originalNumber?'원문 '+s.originalNumber+'번':s.position?.page?`원본 ${s.position.page}쪽 · 번호 확인 필요`:'번호 확인 필요',s.school||s.materialTitle||'출처 미확인',s.academicYear?`${s.academicYear}학년도`:'연도미상',[s.grade,s.semester,s.exam].filter(Boolean).join(' '),m.classification?.primaryUnit?(m.classification.primaryUnit.name+(m.classification.status==='ai_suggested'?' · AI 추천':'')):'소단원 추천 전',score(item),m.management?.review==='approved'?'문항 검토 완료':'문항 검토 필요'].filter(Boolean).join(' · ');}
 function field(root,label,value='',type='text'){const wrapper=element('label','bank-field'),input=element(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value??'';wrapper.append(element('span','',label),input);root.append(wrapper);return input;}
 async function settings(){const s=await read(),root=shell('비공개 공동 문제은행 연결','settings');const comparisonModel=field(root,'비교 대상 모델명 (계획만 작성)','');root.append(button('대표표본 비교 계획 · AI 호출 없음','button outline',act(async()=>{const plan=await api.bankAnalysisComparisonPlan({targetModel:comparisonModel.value||null,limit:12});const output=field(root,'비교할 대표표본 · 정답 기준 아님',JSON.stringify(plan,null,2),'textarea');output.readOnly=true;})));
  root.append(element('p','',`현재 계정: ${s.auth.account?.email||'연결 안 됨'} · ${s.auth.connected?'초대 확인됨':s.auth.error||'자기 Google 계정으로 로그인하세요.'}`),element('p','',`공동 저장소: ${s.root?.name||'연결 전'} · ${s.auth.projectUrl||'연결 설정 필요'}`));
  const browserLabel=element('label','bank-field'),browser=element('select');browser.id='bankLoginBrowser';for(const [value,label] of [['auto','Chrome / Edge 자동 선택'],['chrome','Chrome'],['edge','Microsoft Edge'],['default','Windows 기본 브라우저']]){const o=element('option','',label);o.value=value;browser.append(o);}browser.value=loginBrowser;browser.addEventListener('change',()=>loginBrowser=browser.value);browserLabel.append(element('span','','로그인할 브라우저'),browser);root.append(browserLabel);
  root.append(element('p','editor-hint','별도로 열린 Chrome·Edge에서 로그인하세요. 계정 선택 화면의 ‘다른 계정 사용’을 누르면 새 계정으로 로그인할 수 있습니다. ‘안전하지 않은 브라우저’가 나오면 다른 브라우저를 선택하세요. 로그인 계정은 관리자의 초대·승인도 필요합니다.'));
  const login=async()=>{$('bankMessage').textContent='별도로 열린 브라우저에서 본인 계정을 선택하세요. 완료되면 문제공방으로 돌아오세요.';await api.bankConnect({browser:loginBrowser});await common();};
  const actions=element('div','bank-actions');actions.append(button('내 Google 계정으로 로그인','button primary',act(login)));if(s.auth.account)actions.append(button('다른 계정으로 로그인','button outline',act(login)));actions.append(button('로그인 취소','button quiet',act(()=>api.bankCancelConnect())),button('연결 해제','button outline',act(async()=>{await api.bankDisconnect();await settings();})));root.append(actions);
  const advanced=element('details');advanced.append(element('summary','','고급 연결 설정'),button('공동 은행 연결 JSON 불러오기','button outline',act(async()=>{await api.bankConfigure();await settings();})));root.append(advanced);
  if(s.auth.connected)root.append(button('이전 등록 문항 목록 연결','button outline',act(async()=>{$('bankMessage').textContent='내 기존 완료 자료를 검증하고 새 검색 목록에 연결합니다…';const r=await api.bankReindex();$('bankMessage').textContent=r.count+'개 버전을 연결했습니다. 원본 파일은 변경하지 않았습니다.';})),button('공동 저장소 연결 확인','button outline',act(async()=>{await api.bankRoot({});await settings();})));
  root.append(element('p','editor-hint','관리자 비밀번호·관리자 키를 공유하지 않습니다. 다른 교사의 문항은 불러와 편집·출력할 수 있으며, 수정 후 등록하면 내 새 복사본으로 보관합니다. 원문은 덮어쓰지 않습니다.'));
  const label=element('label','bank-check'),auto=element('input');auto.type='checkbox';auto.id='bankAutoSave';auto.checked=s.automatic;label.append(auto,document.createTextNode('변환·확정 수정 후 공동 문제은행 자동 저장'));auto.addEventListener('change',act(async()=>{try{await api.bankAuto({enabled:auto.checked});await read();}catch(e){auto.checked=!auto.checked;throw e;}}));root.append(label,element('p','editor-hint','이후 완성·수정되는 문항만 등록합니다. 과거 문항은 직접 선택하세요. 연결하지 않아도 로컬 편집·출력은 계속 작동합니다.'));
  if(s.auth.member?.role==='owner'){
   root.append(button('문항 관리 → 일괄 업데이트','button primary',act(maintenance)));
   root.append(button('관리자 공동 자료 백업','button outline',act(async()=>{const r=await api.bankBackup({admin:true});if(r)toast(r.versions+'개 버전 백업: '+r.directory);})),button('파일 사용량 확인','button outline',act(async()=>{const u=await api.bankUsage();$('bankMessage').textContent=`문항 ${u.questions}개 · Storage 기록 ${(u.actualStorageBytes/1048576).toFixed(1)} MiB / 무료 1GB. 전송량·청구 사용량은 Supabase 대시보드에서 확인하세요.`;})));root.append(button('동료용 공개 연결 JSON 저장','button outline',act(()=>api.bankExportConfig())));
   const email=field(root,'초대할 선생님의 Google 이메일');root.append(button('이 계정 사용 승인','button primary',act(async()=>{if(!window.confirm(email.value+' 계정에 승인된 공동 문항 읽기와 자기 문항 등록을 허용할까요?'))return;await api.bankInvite({email:email.value.trim(),enabled:true});await settings();})));
   const members=await api.bankMembers();for(const m of members){const row=element('div','bank-list-row');row.append(element('span','',m.email+' · '+(m.role==='owner'?'관리자':m.enabled?'승인됨':'접근 중지')));if(m.role!=='owner')row.append(button(m.role==='reviewer'?'일반 교사로':'검수자 지정','button outline compact',act(async()=>{if(!window.confirm('검수자는 공동 값 승인 권한을 갖습니다. 역할을 변경할까요?'))return;await api.bankRole({email:m.email,role:m.role==='reviewer'?'teacher':'reviewer'});await settings();})),button(m.enabled?'접근 중지':'다시 승인','button outline compact',act(async()=>{if(!window.confirm(m.email+' 계정의 접근 권한을 변경할까요?'))return;await api.bankInvite({email:m.email,enabled:!m.enabled});await settings();})));root.append(row);}
  }
  root.append(element('p','editor-hint','처음 운영을 준비할 때는 SHARED-BANK-SETUP.md 안내가 필요합니다. 연결 JSON에는 공개 접속 정보만 들어 있습니다. 초대는 사용 권한 등록이며 이메일을 자동 발송하지 않습니다.'));
 }

 async function maintenance(){
  const labels={planned:'대상 확인',sampling:'샘플 처리 중',staged:'변경 확인 대기',running:'처리 중',paused:'일시정지',complete:'완료',failed:'실패·재시도',pending:'대기',conflict:'새 수정과 충돌'};
  const data=await api.bankMaintenanceStatus(),root=shell('문항 관리 → 일괄 업데이트');
  root.append(element('p','review-notice','관리자 PC의 앱에서 실행합니다. 앱 종료 시 멈추며 이 PC에서 재개할 수 있습니다. 서버에는 대상 버전과 변경 이력을 기록합니다. 기존 문항은 계속 열고 출력할 수 있습니다.'),element('p','editor-hint','DB 구조 변경은 별도 마이그레이션입니다. 아래 작업은 기존 문항의 추천·파생 파일을 새 버전으로 준비합니다. 사용자 확정값은 보호합니다.'));
  const choices=[];for(const r of data.rules){const label=element('label','bank-check'),check=element('input');check.type='checkbox';check.value=r.id;check.checked=['source','render','integrity'].includes(r.id);label.append(check,document.createTextNode(`${r.title} · ${r.version}${r.ai?' · AI 호출 가능':''}`));root.append(label);choices.push(check);}
  const candidates=await api.bankMaintenanceCandidates(),select=(label,options)=>{const wrap=element('label','bank-field'),input=element('select');const all=element('option','','전체');all.value='';input.append(all);for(const [value,title] of options){const option=element('option','',title);option.value=value;input.append(option);}wrap.append(element('span','',label),input);root.append(wrap);return input;};
  const school=select('학교',[...new Set(candidates.map(c=>c.source.school).filter(Boolean))].map(s=>[s,s])),papers=new Map();for(const c of candidates)if(c.source.documentId&&!papers.has(c.source.documentId))papers.set(c.source.documentId,[c.source.school||c.source.materialTitle||'출처 미확인',c.source.academicYear,c.source.grade,c.source.semester,c.source.exam].filter(Boolean).join(' · ')+' ('+c.source.documentId.slice(0,6)+')');const source=select('원본 시험지',[...papers]);
  const pick=element('details'),picked=[];pick.append(element('summary','','개별 문항 선택 (기본: 전체 선택)'));for(const c of candidates){const label=element('label','bank-check'),input=element('input');input.type='checkbox';input.value=c.id;input.checked=true;picked.push(input);label.append(input,document.createTextNode([c.source.school||c.source.materialTitle||'출처 미확인',c.source.originalNumber?'원문 '+c.source.originalNumber+'번':'번호 확인 필요',c.unit||'미분류'].join(' · ')));pick.append(label);}root.append(pick);
  const missing=element('select');for(const [value,title] of [['','전체 중 이전 처리 버전·변경 자료'],['preview','미리보기 누락'],['source.school','학교 누락'],['source.originalNumber','원문 번호 누락'],['classification.primaryUnit','소단원 누락'],['difficulty.aiScore','AI 난이도 누락']]){const option=element('option','',title);option.value=value;missing.append(option);}root.append(missing);
  root.append(button('대상과 예상 사용량 확인','button primary',act(async()=>{if(!picked.some(c=>c.checked))throw Error('문항을 한 개 이상 선택하세요.');const j=await api.bankMaintenancePlan({rules:choices.filter(c=>c.checked).map(c=>c.value),filters:{school:school.value,sourceId:source.value,ids:picked.filter(c=>c.checked).map(c=>c.value),missing:missing.value},provider:getProvider()});await maintenance();toast(`${j.estimate.questions}문항 · 최대 AI 요청 ${j.estimate.aiRequestsMax}회. 아직 적용하지 않았습니다.`);})),button('진행 상황 새로고침','button outline',act(maintenance)));
  for(const j of [...data.jobs].reverse()){
   const box=element('section','bank-maintenance-job'),counts=j.items.reduce((a,i)=>(a[i.status]=(a[i.status]||0)+1,a),{});box.append(element('h3','',`${j.spec.undoOf?'되돌리기':'일괄 업데이트'} · ${j.createdAt.slice(0,16).replace('T',' ')} · ${labels[j.status]||j.status}`),element('p','',`대상 ${j.items.length}개 · ${Object.entries(counts).map(([key,n])=>(labels[key]||key)+' '+n).join(' · ')} · 최대 AI 요청 ${j.estimate.aiRequestsMax}회 · 확인된 다운로드 ${((j.estimate.knownDownloadBytes||0)/1048576).toFixed(1)} MiB`),element('p','editor-hint','AI 토큰·요금과 재생성 업로드 크기는 실행 전 확정할 수 없습니다. 기존 AI 연결의 이용 조건이 적용됩니다. 미리보기·파일 검증이 실패하면 해당 문항을 반영하지 않습니다.'));
   if(j.message||j.syncError)box.append(element('p','review-notice',j.syncError||j.message));
   const actions=element('div','bank-actions');actions.append(button('샘플 3개 먼저 처리','button outline',act(async()=>{if(j.estimate.aiRequestsMax&&!window.confirm('선택한 샘플의 AI 분석이 현재 연결로 실행될 수 있습니다. 진행할까요?'))return;await api.bankMaintenanceSample({id:j.id});await maintenance();})),button('변경 확인 후 적용 / 재개·재시도','button primary',act(async()=>{if(!window.confirm('아래 샘플 변경 전후와 미해결 항목을 확인했나요? 실패·대기 항목을 처리하고 새 버전으로 반영합니다.'))return;await api.bankMaintenanceStart({id:j.id});await maintenance();})),button('중단','button outline',act(async()=>{await api.bankMaintenancePause({id:j.id});await maintenance();})),button('되돌리기 계획','button outline',act(async()=>{await api.bankMaintenanceUndo({id:j.id});await maintenance();})));box.append(actions);
   for(const i of j.items){const detail=element('details');detail.append(element('summary','',`${i.before?.metadata?.source?.school||'출처 미확인'} · ${i.before?.metadata?.source?.originalNumber||i.questionId} · ${labels[i.status]||i.status}`));if(i.error)detail.append(element('p','review-notice',i.error));detail.append(element('p','editor-hint',`기준 버전 ${i.baseId} → ${i.resultId||'준비 전'}`));for(const d of i.diff||[])detail.append(element('p','',`${d.field}: ${JSON.stringify(d.before)} → ${JSON.stringify(d.after)}`));for(const e of i.evidence||[])detail.append(element('p','editor-hint','복구 근거: '+JSON.stringify(e)));for(const u of i.unresolved||[])detail.append(element('p','review-notice',u.field+' · '+u.reason));if(i.uploadId)detail.append(button('변경 전후 미리보기','button compact outline',act(async()=>{for(const before of [true,false]){detail.append(element('h4','',before?'변경 전':'변경 후'));const url=await api.bankMaintenancePreview({id:j.id,questionId:i.questionId,before});if(!url){detail.append(element('p','','보존된 미리보기 없음'));continue;}const img=element('img');img.src=url;img.alt=before?'처리 전 문항':'처리 후 문항';img.style.maxWidth='100%';detail.append(img);}})));box.append(detail);}root.append(box);
  }
 }
 async function local(){
  const s=await read(true),root=shell('2. 등록할 문항 확인','local');if(!state.project){root.append(element('p','','먼저 시험지와 문항을 여세요.'));return;}
  const projectId=state.project.id,list=s.items.filter(i=>i.projectId===projectId),checks=[];
  if(selectionState?.projectId!==projectId)selectionState={projectId,ids:null};if(selectionState.ids===null)selectionState.ids=new Set(list.map(i=>i.questionId));
  root.append(element('p','review-notice','업로드 완료·문항 검토 완료와 AI 추천 결과는 별도입니다. 전체 문항이 기본 선택됩니다. 특정 문항만 올릴 때는 아래 전체 선택 해제를 누르세요. 문제보기에서 수식·그림·정답·풀이를 확인할 수 있습니다.'));
  const sync=()=>{selectionState.ids=new Set(checks.filter(x=>x.checked).map(x=>x.value));next.textContent=`다음 · ${selectionState.ids.size}문항 업로드`;};
  const selectedItems=()=>list.filter(i=>selectionState.ids.has(i.questionId));
  const actions=element('div','bank-actions');actions.append(button('전체 선택','button outline',()=>{checks.forEach(c=>c.checked=true);sync();}),button('전체 선택 해제','button outline',()=>{checks.forEach(c=>c.checked=false);sync();}),button('선택 문항 태그·난이도 수정','button outline',act(()=>edit(selectedItems().map(i=>i.id)))));root.append(actions);
  for(const item of list){const row=element('div','bank-list-row'),label=element('label','bank-item-label'),check=element('input');check.type='checkbox';check.value=item.questionId;check.checked=selectionState.ids.has(item.questionId);checks.push(check);check.addEventListener('change',sync);
   const p=state.project.problems.find(p=>p.id===item.problemId),q=[p?.original,...(p?.variants||[])].find(q=>q?.id===item.questionId);label.append(check,element('span','',`${q?.kind==='variant'?'유사문제':'원문'} · ${describe(item)}\n${statusText(item.status)}${item.metadata.analysis?.error?' · AI 추천 실패: '+recommendationFailure(item,q):''}`));if(q&&p){const peek=element('details','bank-native-preview');peek.append(element('summary','','수식·도형 미리보기'));peek.open=true;peek.append(await renderQuestion(p,q));row.append(peek);}row.append(label,button('문제보기','button compact outline',act(()=>preview(p,q,item))));root.append(row);
  }
  const label=element('label','bank-check'),auto=element('input');auto.type='checkbox';auto.checked=true;auto.id='bankRecommend';label.append(auto,document.createTextNode('저장된 최초 분석·캐시 반영 (추가 AI 호출 없음)'));root.append(label,element('p','editor-hint','추천은 확정값과 구분해 저장합니다. 세부 유형이 갖춰진 문항을 업로드합니다. 추천 실패 시 원본은 PC에 보존됩니다.'));
  const analyze=async(automatic=false)=>{if(analyzing)throw Error('추천이 진행 중입니다.');if(!selectionState.ids.size)throw Error('문항을 선택하세요.');beginProgress('recommend',projectId,selectionState.ids.size);analyzing=true;for(const c of checks)c.disabled=true;root.querySelectorAll('[role=tab]').forEach(b=>b.disabled=true);try{$('bankMessage').textContent='기존 문제·풀이로 소단원·난이도를 추천하고 있습니다…';let result;for(let attempt=0;attempt<3;attempt++){let current=await read();while(current.analysisRunning){activity.waitingForBackground=true;renderProgress();await new Promise(resolve=>setTimeout(resolve,600));current=await read();}activity.waitingForBackground=false;renderProgress();try{result=await api.bankAnalyze({projectId,questionIds:[...selectionState.ids],provider:getProvider(),automatic});break;}catch(e){if(attempt<2&&/추천을 진행 중입니다/.test(e.message))continue;throw e;}}await read(true);return result;}catch(e){activity.error=e.message;renderProgress();throw e;}finally{analyzing=false;for(const c of checks)c.disabled=false;root.querySelectorAll('[role=tab]').forEach(b=>b.disabled=false);}};
  root.append(button('선택 문항 AI 분석 · 추가 요청','button outline',act(async()=>{const r=await analyze();await local();$('bankMessage').textContent=r.waiting?`서비스 문제로 ${r.waitingIds.length}문항을 대기시켰습니다. 복구 후 선택 문항 AI 분석을 다시 실행하세요. 추가 요청은 중지되어 있습니다.`:`추천 ${r.analyzed}건 · 재사용 ${r.reused}건 · 실패 ${r.errors.length}건. 세부 유형을 확인한 문항을 업로드할 수 있습니다.`;})));
  const next=button('다음 · 선택 문항 업로드','button primary',act(async()=>{if(state.project?.id!==projectId)throw Error('작업이 바뀌었습니다.');if(!selectionState.ids.size)throw Error('문항을 선택하세요.');const ids=[...selectionState.ids];let failed=0;if(auto.checked){try{const r=await analyze(true);failed=r.errors.length;}catch(e){failed=ids.length;toast('자동 추천 실패: '+e.message,true);}}beginProgress('upload',projectId,ids.length);try{const selections={};for(const target of await api.bankTargets({projectId,questionIds:ids})){if(!target.required){if(target.target)selections[target.questionId]={questionId:target.target.question_id,revisionId:target.target.revision_id};continue;}const options=target.candidates.filter(c=>c.writable);const answer=window.prompt('원본 번호 또는 기존 대상 확인이 필요합니다. 기존 문항을 갱신하려면 번호를 입력하세요. 신규 문항임을 직접 확인했다면 신규를 입력하세요.\n'+options.map((c,i)=>(i+1)+'. '+[c.metadata.source.school,c.metadata.source.academicYear,c.metadata.source.grade,c.metadata.source.semester,c.metadata.source.exam,c.metadata.source.originalNumber].join(' · ')).join('\n'));if(answer===null)throw Error('대상 선택을 취소했습니다.');if(answer.trim()==='신규')selections[target.questionId]='new';else{const chosen=options[Number(answer)-1];if(!chosen)throw Error('목록의 번호를 선택하세요.');selections[target.questionId]={questionId:chosen.question_id,revisionId:chosen.revision_id};}}const saved=await api.bankSave({projectId,questionIds:ids,selections});activity.itemIds=ids.map(id=>saved.items.find(i=>i.projectId===projectId&&i.questionId===id)?.id).filter(Boolean);activity.enqueueing=false;snapshot=saved;renderProgress();await jobs();if(failed)$('bankMessage').textContent=`${failed}문항은 AI 추천을 완료하지 못했습니다. 문항 원본 업로드는 계속 진행합니다. 현재 문항 탭에서 다시 추천할 수 있습니다.`;}catch(e){activity.error=e.message;renderProgress();throw e;}}));next.id='bankUploadSelected';sync();const footer=element('div','bank-registration-footer');footer.append(next);root.append(footer);
 }
 async function edit(ids){if(!ids.length)throw Error('문항을 선택하세요.');const s=await read(),item=s.items.find(i=>i.id===ids[0]),root=shell(ids.length===1?'문항 기본 정보':'선택 문항 일괄 수정');if(!item)throw Error('로컬 문항이 없습니다.');root.append(element('p','','일괄 수정은 입력한 필드만 적용합니다. 입력란을 변경하지 않으면 기존 값이 유지됩니다.'));
  const m=item.metadata,inputs={tags:field(root,'자유 태그 (쉼표로 구분)',ids.length===1?m.management.tags.join(', '):''),primaryUnit:field(root,'대표 단원',ids.length===1?m.classification.primaryUnit?.name||'':''),type:field(root,'출제유형 수동 지정',ids.length===1?fineTypeLabel(item):''),userScore:field(root,'내 평가 제안 (소수점 한 자리, 미평가는 빈칸)',ids.length===1?m.difficulty.userScore||'':''),targetScore:field(root,'유사문제 생성 목표 난이도',ids.length===1?m.difficulty.targetScore||'':''),note:field(root,'사용자 메모',ids.length===1?m.management.note:'','textarea')};const touched=new Set();for(const [k,input] of Object.entries(inputs))input.addEventListener('input',()=>touched.add(k));
  attachTypes(inputs.type,s.typeCatalog);const recommended=m.classification.types||[];inputs.type.placeholder=recommended.map(t=>typeof t==='string'?t:t.coreTask?.name||t.name||t.label||t.id).join(' · ');root.append(element('p','editor-hint','출제유형 추천: '+(inputs.type.placeholder||m.classification.typeRecommendation?.reason||'추천 전')+' · 핵심 풀이 구조가 같은 세부 유형을 재사용합니다. 첫 번째 유형을 중복 최소화에 사용합니다.'));
  root.append(element('p','editor-hint','난이도 대표 기준: 하 3.0 / 중 5.0 / 상 8.0 이상. 구간을 자동 배정하지 않습니다. AI가 제안한 점수와 교사의 평가는 별도로 보존됩니다.'));
  const ref=field(root,'별도 기준문항으로 지정',null,'checkbox');ref.checked=ids.length===1&&m.difficulty.isReference;ref.addEventListener('change',()=>touched.add('isReference'));
  root.append(element('p','editor-hint','아래 난이도는 개인 평가입니다. 공동 목록의 평가 저장에서 보정 표본에 함께 반영합니다. 개인 메모는 공동 문항 파일에 포함하지 않습니다.'));const details=element('details');details.append(element('summary','','문항별 출처 예외 · 원문 번호'));const sourceInputs={};for(const [key,label] of [['school','학교'],['region','지역'],['materialTitle','자료명'],['academicYear','출제 학년도'],['grade','학년'],['semester','학기'],['exam','시험 구분'],['originalNumber','원문 문제번호'],['originalPoints','원문 배점']]){sourceInputs[key]=field(details,label,ids.length===1?m.source[key]||'':'');sourceInputs[key].addEventListener('input',()=>touched.add('source.'+key));}root.append(details);
  root.append(button('기본 정보 저장','button primary',act(async()=>{const patch={};for(const key of touched)if(key==='isReference')patch[key]=ref.checked;else if(key.startsWith('source.')){patch.source||={};patch.source[key.slice(7)]=sourceInputs[key.slice(7)].value;}else patch[key]=key==='tags'?inputs[key].value.split(','):inputs[key].value;await api.bankEdit({ids,patch});await local();})));if(ids.length===1){root.append(button('기존 HWP·PDF 첨부','button outline',act(async()=>{await api.bankAttach({id:item.id});await edit(ids);})),element('p','editor-hint','선택한 파일만 별도 첨부합니다. 외부 편집 내용이 문항 원본에 반영되지는 않습니다. '+(item.attachments||[]).map(f=>f.name).join(', ')));}if(item.folderId&&s.auth.kind!=='shared')root.append(button('Drive 문항 위치 열기','button outline',act(()=>api.bankOpenFolder({id:item.folderId}))));
 }
 async function common({questionIds=null}={}){
  if(questionIds&&state.project)selectionState={projectId:state.project.id,ids:new Set(questionIds)};
  const s=await read(true);if(!s.auth.connected)return settings();const root=shell('1. 시험지 공통 정보','common');
  if(!state.project){root.append(element('p','','먼저 원본 파일을 불러오세요.'));return;}
  const projectId=state.project.id,selectedItems=questionIds?s.items.filter(i=>i.projectId===projectId&&questionIds.includes(i.questionId)):[];
  const sources=s.sources.filter(source=>!questionIds||selectedItems.some(i=>i.sourceId===source.bankSourceId));
  if(!sources.length)throw Error('등록할 문항의 원본 파일을 확인하세요.');
  root.append(element('p','review-notice',questionIds?`선택한 ${questionIds.length}문항 · ${sources.length}개 원본 파일의 정보를 확인하세요. 빈칸이 있어도 등록할 수 있습니다.`:'파일별로 한 번 확인하면 같은 시험지의 문항에 함께 적용됩니다. 모르는 정보는 빈칸으로 두세요.'));
  root.append(element('p','editor-hint','파일명에 명확하게 적힌 정보만 미리 채웠습니다. 잘못된 값은 수정하거나 지우세요. 추가 AI 호출은 하지 않습니다.'));
  const select=element('select');select.setAttribute('aria-label','정보를 확인할 원본 파일');for(const source of sources){const o=element('option','',source.name);o.value=source.id;select.append(o);}select.value=sources.some(source=>source.id===state.activeSourceId)?state.activeSourceId:sources[0].id;root.append(select);
  const drafts=new Map(sources.map(source=>[source.id,{...source.metadata}])),form=element('div','bank-form');root.append(form);
  const draw=()=>{
   form.replaceChildren();const source=sources.find(source=>source.id===select.value),m=drafts.get(source.id);
   const origin=element('p','editor-hint',source.suggested?'파일명에서 가져온 제안값입니다. 등록할 때 확정됩니다.':'이전에 저장한 정보입니다. 직접 수정한 값과 빈칸은 유지됩니다.');origin.style.gridColumn='1 / -1';form.append(origin);
   const kindLabel=element('label','bank-field'),kind=element('select');kindLabel.append(element('span','','자료 종류'),kind);for(const name of ['학교기출','교재','기타자료','자체제작','원문변형','AI생성']){const o=element('option','',name);o.value=name;kind.append(o);}kind.value=m.kind;kind.addEventListener('change',()=>m.kind=kind.value);form.append(kindLabel);
   for(const [key,label,example] of [['materialTitle','자료명','원본 파일명'],['school','학교명','예: 광희중'],['academicYear','출제 학년도','예: 2026'],['grade','학년','예: 중2'],['semester','학기','예: 2학기'],['exam','시험 구분','예: 중간고사'],['region','지역 (선택)','동명이교 구분이 필요할 때']]){const input=field(form,label,m[key]||'');input.placeholder=example;input.addEventListener('input',()=>m[key]=input.value.trim()||null);}
   const n=m.numbering||{};for(const [key,label]of [['total','원본 전체 문항 수'],['objectiveCount','객관식 전체 문항 수'],['writtenCount','서술형 전체 문항 수 (없으면 0)']]){const input=field(form,label,n[key]??'','number');input.min=key==='writtenCount'?0:1;input.max=2000;input.addEventListener('input',()=>{m.numbering={...n,...m.numbering,[key]:input.value===''?null:Number(input.value),evidence:'사용자가 시험지 공통 정보에서 입력',confirmed:true};});}form.append(element('p','editor-hint','부분 인식한 개수나 마지막 번호를 전체 수로 입력하지 마세요. 서술형 번호가 1부터 다시 시작하면 객관식과 별도로 합산합니다.'));
  };select.addEventListener('change',draw);draw();
  const help=element('details');help.append(element('summary','','모르는 항목은 어떻게 하나요?'),element('p','','학교·학년도·단원·난이도를 몰라도 등록됩니다. 학교 식별값은 동명이교 구분용 내부 코드, 분류기준표 버전은 단원·유형 목록의 관리 번호입니다. 직접 입력할 필요가 없어 기본 화면에서 제외했습니다. 기존 값은 보존합니다.'));root.append(help);
  if(!s.auth.connected&&questionIds)root.append(element('p','review-notice','현재 문제은행에 연결되지 않았습니다. 위 ‘연결 설정’에서 본인 Google 계정으로 로그인한 뒤 등록하세요.'));
  const next=button('다음 · 문항 확인','button primary',act(async()=>{
   if(state.project?.id!==projectId)throw Error('작업이 바뀌었습니다. 등록할 문항을 다시 선택하세요.');
   for(const source of sources)await api.bankSource({projectId,sourceId:source.id,metadata:drafts.get(source.id)});
   await local();
  }));next.id='bankConfirmRegistration';const footer=element('div','bank-registration-footer');footer.append(next);root.append(footer);
 }
 async function remote(){if((await read()).auth.kind==='shared')return sharedRemote();const s=await read(),root=shell('공동 저장 문항 목록'),search=field(root,'불러온 목록에서 검색 · 출처 / 원문번호 / 학년 / 단원 / 태그',''),list=element('div');const render=()=>{list.replaceChildren();for(const item of Object.values(s.cached).filter(i=>JSON.stringify(i.metadata||{}).toLowerCase().includes(search.value.toLowerCase()))){const row=element('div','bank-list-row'),info=element('div');info.append(element('strong','',describe(item)),element('p','editor-hint',`${statusText(item.status||'complete')} · ${item.revisionId||'완료 기록 확인 필요'} · ${item.completedAt||''} · 등록자 ${item.author?.email||'확인 전'}${item.error?' · '+item.error:''}`));row.append(info);if(item.revisionId)row.append(button('이 버전 다시 열기','button primary compact',act(async()=>{if(blocked())throw Error('현재 작업이 끝난 후 불러오세요.');if(state.editor&&!window.confirm('저장하지 않은 편집을 닫고 저장 문항을 불러올까요?'))return;$('bankMessage').textContent='다운로드·무결성 확인·문항 복원 중…';const result=await api.bankRestore({revisionId:item.revisionId});$('mainDialog').close();await loadProject(result.project);await workflowUI.scopeRefresh();state.view=item.metadata?.relations?.originalQuestionId?'variants':'original';renderAll();})));list.append(row);}if(!list.children.length)list.append(element('p','','저장 완료 문항이 없거나 아직 목록을 읽지 않았습니다.'));};search.addEventListener('input',render);root.append(button('원격 목록 새로 읽기','button outline',act(async()=>{await api.bankRefresh({});await remote();})));if(s.nextPageToken)root.append(button('다음 100개 읽기','button outline',act(async()=>{await api.bankRefresh({next:true});await remote();})));root.append(button('캐시 초기화 후 재조회','button quiet',act(async()=>{await api.bankRefresh({rescan:true});await remote();})),list);render();}
 async function sharedRemote(filters={},start=0){const s=await read(),root=shell('공동 문항 검색·선택','remote'),form=element('div','bank-form'),inputs={};for(const [k,label] of [['text','검색어'],['school','학교'],['academicYear','출제 학년도'],['grade','학년'],['semester','학기'],['unit','단원'],['type','유형'],['owner','등록자 이메일'],['min','공동 확정 난이도 최소'],['max','공동 확정 난이도 최대']])inputs[k]=field(form,label,filters[k]||'');root.append(form,button('검색','button primary',act(()=>sharedRemote(Object.fromEntries(Object.entries(inputs).filter(([k,v])=>v.value.trim()).map(([k,v])=>[k,v.value.trim()])),0))),button('웹 선택 목록 가져오기','button outline',act(async()=>{const p=await api.bankImportSelection();if(p){$('mainDialog').close();await loadProject(p);renderAll();}})),button('백업에서 로컬 복원','button outline',act(async()=>{const r=await api.bankRestoreBackup();if(r?.project){$('mainDialog').close();await loadProject(r.project);renderAll();toast(r.versions+'개 버전을 별도 로컬 작업으로 복원했습니다.');}})));
 const rows=await api.bankSearch({filters,start}),chosen=[];for(const c of rows){const row=element('div','bank-list-row'),check=element('input');check.type='checkbox';check.addEventListener('change',()=>{const n=chosen.indexOf(c);if(check.checked&&n<0)chosen.push(c);else if(n>=0)chosen.splice(n,1);});row.append(check,element('span','',describe({metadata:c.metadata})+'\n'+({approved:'공동 검수 완료',shared_pending:'공동 미검수',private:'이전 비공개 자료'}[c.visibility])+' · '+(c.confirmed?.difficulty?c.confirmed.difficulty+'점 공동 확정':'공동 난이도 미평가')+' · '+c.owner_email),button('상세·검수','button compact outline',act(()=>sharedDetail(c,s))),button('같은 시험지 원래 순서로 불러오기','button compact outline',act(async()=>{if(blocked())throw Error('현재 작업이 끝난 후 불러오세요.');const p=await api.bankImportExam({revisionId:c.revision_id});$('mainDialog').close();await loadProject(p);renderAll();toast('현재 접근 가능한 원문 '+p.problems.length+'문항을 원래 순서로 불러왔습니다.');})));const f=c.files.find(f=>f.role==='preview');if(f)row.append(button('미리보기','button compact quiet',act(async()=>{const img=element('img');img.src=await api.bankPreview({id:f.id});img.style.maxWidth='100%';row.append(img);})));root.append(row);}
 root.append(button('원문 순서로 불러오기','button primary',act(async()=>{const p=await api.bankImportSelection({order:'source',items:chosen.map(c=>({questionId:c.question_id,revisionId:c.revision_id}))});if(p){$('mainDialog').close();await loadProject(p);renderAll();}})),button('선택 문항 파일 내려받기','button outline',act(async()=>{if(!chosen.length)throw Error('문항을 선택하세요.');const r=await api.bankBackup({revisionIds:chosen.map(c=>c.revision_id)});if(r)toast(r.versions+'개 버전 저장: '+r.directory);})));if(start)root.append(button('이전 50개','button outline',act(()=>sharedRemote(filters,Math.max(0,start-50)))));if(rows.length===50)root.append(button('다음 50개','button outline',act(()=>sharedRemote(filters,start+50))));
 }
 async function sharedDetail(c,s){const full=(await api.bankCatalog({revisionId:c.revision_id}))[0];if(!full)throw Error('현재 접근할 수 없는 문항입니다.');const root=shell('공동 문항 상세·검수');root.append(element('p','',full.content.body||''),element('p','',(full.content.choices||[]).join('\n')),element('p','','정답: '+(full.content.answer||'미확인')),element('p','',full.content.solution||''));const tags=field(root,'태그',(full.confirmed.tags||[]).join(', ')),unit=field(root,'대표 단원',full.confirmed.primaryUnit||''),type=field(root,'출제유형',fineTypeLabel(full)),score=field(root,'내 평가 점수 (10점 만점)','','number');const patch=()=>({tags:tags.value.split(',').map(x=>x.trim()).filter(Boolean),primaryUnit:unit.value,type:type.value});attachTypes(type,s.typeCatalog);let version=c.review_version,savedPatch=JSON.stringify(patch());root.append(button('평가 저장','button outline',act(async()=>{if(!score.value.trim())throw Error('점수를 입력하세요.');await api.bankRateSave({revisionId:c.revision_id,value:Number(score.value)});toast('내 평가와 공동 보정 표본을 저장했습니다.');})),button('검수 저장','button primary',act(async()=>{const snapshot=patch(),prior=JSON.parse(savedPatch),changes=Object.fromEntries(Object.entries(snapshot).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(prior[key])));const saved=await api.bankReviewSave({revisionId:c.revision_id,patch:changes,expected:version});version=saved.version;savedPatch=JSON.stringify(snapshot);toast('검수 내용을 저장했습니다. 완료 후에도 수정할 수 있습니다.');})));}
 function jobDescription(j,s){const item=s.items.find(i=>i.id===j.questionId);return `${item?describe(item):'등록 문항'}\n${statusText(j.status)}${j.superseded?' · 더 나중에 등록한 작업이 있어 이 이전 실패본은 재시도하지 않습니다.':j.error?' · '+j.error:j.status==='paused'?' · 다시 시작을 누르면 이어서 업로드합니다.':''}`;}
 function jobSummary(s){return `전체 ${s.jobs.length}건 · 업로드 완료 ${s.jobs.filter(j=>j.status==='complete').length}건 · 진행/대기 ${s.jobs.filter(j=>['queued','preparing','uploading'].includes(j.status)).length}건 · 확인 필요 ${s.jobs.filter(j=>!['complete','queued','preparing','uploading'].includes(j.status)).length}건`;}
 async function jobs(){const s=await read(),root=shell('3. 문제은행 업로드 작업','jobs'),summary=element('p','review-notice',jobSummary(s));summary.id='bankUploadSummary';root.append(summary,element('p','editor-hint','업로드 완료 = 파일과 문항 데이터가 저장되었습니다. 공동 검수 대기 = 저장된 문항을 관리자·검수자가 확인하는 단계입니다. 공통정보의 빈칸 때문에 검수가 대기하는 것은 아닙니다.'),button('상태 새로고침','button outline',act(jobs)));const timedOut=s.jobs.filter(j=>!j.committed&&!j.superseded&&['failed','paused'].includes(j.status)&&/statement timeout|DB 타임아웃/i.test(j.error||''));if(timedOut.length){const actions=element('div','bank-actions');actions.append(button('타임아웃 1건 먼저 재시도','button outline',act(async()=>{await api.bankRetryTimedOut({limit:1});await jobs();})),button(`타임아웃 ${timedOut.length}건 모두 재시도`,'button outline',act(async()=>{if(!window.confirm('타임아웃으로 실패·보류된 작업을 순서대로 다시 시도합니다. 같은 DB 타임아웃이 발생하면 남은 작업은 자동 보류됩니다. 진행할까요?'))return;await api.bankRetryTimedOut({limit:'all'});await jobs();})));root.append(element('p','editor-hint',`DB 타임아웃 ${timedOut.length}건 · 먼저 한 건을 재시도해 저장 완료를 확인하세요.`),actions);}for(const j of [...s.jobs].reverse()){const row=element('div','bank-list-row');row.dataset.bankJob=j.id;row.append(element('span','',jobDescription(j,s)));const details=element('details');details.append(element('summary','','저장 상세'),element('p','editor-hint',`버전 ${j.revisionId} · 미리보기 ${j.previewStatus==='complete'?'생성 완료':j.previewStatus==='pending'?'생성 대기':'없음 (문항 원본 저장과 별도)'}`));row.append(details);if(!j.committed&&!j.superseded&&!['complete','uploading','preparing'].includes(j.status))row.append(button(j.status==='paused'?'다시 시작':'재시도','button compact outline',act(async()=>{await api.bankRetry({id:j.id});await jobs();})));if(['queued','uploading','preparing'].includes(j.status))row.append(button('일시정지','button compact quiet',act(async()=>{await api.bankPause({id:j.id});await jobs();})));root.append(row);}root.append(button('저장된 문항 확인','button primary',act(remote)));if(!s.jobs.length)root.append(element('p','','업로드 대기 작업이 없습니다.'));}
 function refreshCards(){renderProgress();if(analyzing&&snapshot&&$('bankMessage')){const p=snapshot.analysisProgress;$('bankMessage').textContent=p?.projectId===selectionState?.projectId?`소단원·난이도 추천 중 · 처리 ${p.completed}/${p.total}문항 · 실패 ${p.failed}문항`:'소단원·난이도 추천을 준비 중입니다.';}const summary=$('bankUploadSummary');if(summary&&snapshot)summary.textContent=jobSummary(snapshot);for(const row of document.querySelectorAll('[data-bank-job]')){const job=snapshot?.jobs.find(j=>j.id===row.dataset.bankJob);if(!job)continue;row.querySelector('span').textContent=jobDescription(job,snapshot);if(job.status==='complete'||job.committed)for(const b of row.querySelectorAll('button'))b.hidden=true;}for(const node of document.querySelectorAll('[data-bank-status]')){const item=snapshot?.items.find(i=>i.projectId===state.project?.id&&i.questionId===node.dataset.bankStatus);node.textContent=item?statusText(item.status)+' · '+score(item):'내 PC에 저장됨 · 미평가';}}
 function mount(card,p,q){const row=element('div','bank-question-actions'),status=element('span','editor-hint');status.dataset.bankStatus=q.id;status.textContent='내 PC에 저장됨';row.append(button('문제은행에 저장','button compact outline',act(async()=>{if(blocked())throw Error('문항 작업이 끝난 후 저장하세요.');await entry([q.id]);})),button('태그·난이도','button compact quiet',act(async()=>{const s=await read(true);await edit([s.items.find(i=>i.projectId===state.project.id&&i.questionId===q.id).id]);})),status);card.append(row);queueMicrotask(refreshCards);}
 const controls=element('div','bank-sidebar');controls.append(button('문제은행 연결 설정','button outline',act(settings)));document.querySelector('.ai-sidebar-footer').before(controls);
 const upload=button('공동 문제은행에 등록','button primary bank-bottom-upload',act(()=>entry()));upload.id='bankUploadMain';const attachUpload=()=>{const slot=document.querySelector('#bankUploadSlot');if(!slot)return false;slot.append(upload);return true;};if(!attachUpload())document.addEventListener('bank-toolbar-ready',attachUpload,{once:true});

 api.onEvent(event=>{if(event.type==='bank-updated'){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>read().catch(()=>{}),250);}});void read().catch(()=>{});
 return {mount,settings,local,remote};
}
