'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http');
const EXPECTED_EMAIL='animochoi@gmail.com';
const SCOPES=['openid','email','https://www.googleapis.com/auth/drive.file'];
class BankError extends Error{constructor(message,code='failed',retryable=false){super(message);Object.assign(this,{code,retryable});}}
class GoogleBankAuth{
 constructor({directory,safeStorage,openExternal,fetchImpl=fetch}){Object.assign(this,{safeStorage,openExternal,fetch:fetchImpl});this.file=path.join(directory,'google-auth.enc');this.error=null;this.session=null;this.epoch=0;}
 read(){if(!fs.existsSync(this.file))return {};try{if(!this.safeStorage.isEncryptionAvailable())throw Error();return JSON.parse(this.safeStorage.decryptString(fs.readFileSync(this.file)));}catch{throw new BankError('이 PC에서 인증정보를 해독할 수 없습니다. OAuth 설정을 다시 불러오고 연결하세요.','auth');}}
 write(value){if(!this.safeStorage.isEncryptionAvailable()||this.safeStorage.getSelectedStorageBackend?.()==='basic_text')throw new BankError('운영체제 보안 저장소를 사용할 수 없어 인증정보를 저장하지 않았습니다.','auth');fs.mkdirSync(path.dirname(this.file),{recursive:true});const temp=this.file+'.tmp';fs.writeFileSync(temp,this.safeStorage.encryptString(JSON.stringify(value)));fs.renameSync(temp,this.file);}
 configure(json){if(this.session)throw Error('진행 중인 로그인을 먼저 취소하세요.');const c=json?.installed;if(!c||!/^[-\w.]+\.apps\.googleusercontent\.com$/.test(c.client_id)||typeof c.client_secret!=='string')throw Error('Google Cloud의 데스크톱 앱 OAuth 클라이언트 JSON이 필요합니다.');this.epoch++;this.write({client:{client_id:c.client_id,client_secret:c.client_secret}});this.error=null;return this.status();}
 status(){try{const value=this.read();return {configured:!!value.client,connected:!!value.tokens?.refresh_token&&value.account?.email===EXPECTED_EMAIL&&!this.error,account:value.account?{email:value.account.email}:null,expectedEmail:EXPECTED_EMAIL,error:this.error,connecting:!!this.session};}catch(e){return{configured:false,connected:false,expectedEmail:EXPECTED_EMAIL,error:e.message,connecting:false};}}
 async tokenRequest(fields){let response;try{response=await this.fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields),signal:AbortSignal.timeout(30000)});}catch{throw new BankError('Google 인증 서버에 연결하지 못했습니다. 인터넷 연결을 확인하세요.','network',true);}const value=await response.json();if(!response.ok){const reconnect=['invalid_grant','invalid_client','unauthorized_client'].includes(value.error);throw new BankError(reconnect?'Google 인증이 만료·철회되었거나 OAuth 설정이 변경되었습니다. 다시 연결하세요.':'Google 인증 요청을 완료하지 못했습니다.',reconnect?'auth':'failed',response.status>=500);}return value;}
 async verify(accessToken){let response;try{response=await this.fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+accessToken},signal:AbortSignal.timeout(30000)});}catch{throw new BankError('Google 계정을 확인할 수 없습니다. 인터넷 연결을 확인하세요.','network',true);}if(!response.ok)throw new BankError('Google 계정을 다시 인증해 주세요.','auth');const user=await response.json();if(user.email_verified!==true||String(user.email).toLowerCase()!==EXPECTED_EMAIL||!user.sub)throw new BankError('저장 계정은 '+EXPECTED_EMAIL+'입니다. 다른 계정으로는 업로드할 수 없습니다.','auth');return{email:EXPECTED_EMAIL,sub:user.sub};}
 async accept(tokens,previous,epoch=this.epoch){const account=await this.verify(tokens.access_token);if(epoch!==this.epoch)throw new BankError('취소되거나 변경된 Google 연결입니다.','auth');if(tokens.scope&&!SCOPES.every(s=>tokens.scope.split(' ').includes(s)||s==='email'&&tokens.scope.includes('userinfo.email')))throw new BankError('필요한 Drive 파일 권한이 승인되지 않았습니다. 다시 연결하세요.','auth');if(!tokens.refresh_token&&!previous.tokens?.refresh_token)throw new BankError('재연결용 인증정보가 없습니다. 다시 연결하여 권한을 승인하세요.','auth');this.write({...previous,account,tokens:{...previous.tokens,...tokens,expiresAt:Date.now()+(tokens.expires_in||3600)*1000}});this.error=null;return this.status();}
 async token(){if(this.refreshing)return this.refreshing;this.refreshing=this.getToken().finally(()=>this.refreshing=null);return this.refreshing;}
 async getToken(){const epoch=this.epoch;try{if(this.error)throw new BankError(this.error,'auth');const v=this.read();if(!v.client||!v.tokens?.refresh_token||v.account?.email!==EXPECTED_EMAIL)throw new BankError('문제은행 Google 계정을 연결하세요.','auth');if(v.tokens.access_token&&v.tokens.expiresAt>Date.now()+60000)return v.tokens.access_token;const t=await this.tokenRequest({...v.client,grant_type:'refresh_token',refresh_token:v.tokens.refresh_token});await this.accept(t,v,epoch);return t.access_token;}catch(e){if(e.code==='auth')this.error=e.message;throw e;}}
 invalidate(){const v=this.read();if(v.tokens){v.tokens.expiresAt=0;this.write(v);}}
 async connect(){if(this.session)throw Error('Google 로그인 창에서 연결을 완료하거나 취소하세요.');const v=this.read();if(!v.client)throw Error('먼저 데스크톱 OAuth 설정 JSON을 불러오세요.');const verifier=crypto.randomBytes(48).toString('base64url'),state=crypto.randomBytes(32).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url');const epoch=++this.epoch;let finish,consumed=false,settled=false;
  const completion=new Promise((resolve,reject)=>{finish=(error,value)=>{if(settled)return;settled=true;if(error)this.epoch++;error?reject(error):resolve(value);};});completion.catch(()=>{});
  const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname!=='/oauth/callback'){res.writeHead(404).end();return;}if(req.method!=='GET'||url.searchParams.get('state')!==state){res.writeHead(400).end('Invalid OAuth state.');return;}if(consumed||settled){res.writeHead(409).end('OAuth callback already handled.');return;}consumed=true;res.setHeader('Content-Type','text/plain; charset=utf-8');res.setHeader('Cache-Control','no-store');if(url.searchParams.has('error')||!url.searchParams.get('code')){res.end('연결이 취소되었습니다. 문제공방으로 돌아가세요.');finish(new BankError('Google 연결 승인이 취소되었습니다.','auth'));return;}try{const tokens=await this.tokenRequest({...v.client,grant_type:'authorization_code',code:url.searchParams.get('code'),redirect_uri:redirect,code_verifier:verifier});const status=await this.accept(tokens,v,epoch);res.end('문제공방 Google Drive 연결을 완료했습니다. 이 창을 닫아도 됩니다.');finish(null,status);}catch(e){res.end('연결하지 못했습니다. 문제공방에서 오류 안내를 확인하세요.');finish(e);}});
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const redirect=`http://127.0.0.1:${server.address().port}/oauth/callback`;this.session={cancel:()=>finish(new BankError('Google 연결을 취소했습니다.','auth'))};const timer=setTimeout(()=>finish(new BankError('Google 연결 시간이 지났습니다. 다시 연결하세요.','auth')),300000);
  try{const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:v.client.client_id,redirect_uri:redirect,response_type:'code',scope:SCOPES.join(' '),access_type:'offline',prompt:'consent select_account',login_hint:EXPECTED_EMAIL,state,code_challenge:challenge,code_challenge_method:'S256'});await this.openExternal(url.href);return await completion;}catch(e){this.error=e.message;throw e;}finally{clearTimeout(timer);server.closeAllConnections();server.close();this.session=null;}
 }
 cancel(){this.session?.cancel();}
 disconnect(){this.epoch++;this.cancel();const v=this.read();this.write({client:v.client});this.error=null;return this.status();}
}
module.exports={GoogleBankAuth,BankError,EXPECTED_EMAIL,SCOPES};
