'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {atomicWrite}=require('./store.cjs'),{digest}=require('./bank-drive.cjs');
const absoluteFile=value=>/^[A-Za-z]:[\\/]/.test(value)||/^\\\\[^\\]+\\/.test(value)||value.startsWith('/');
const uuid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),clone=x=>structuredClone(x);
function score(value){if(value===null||value===undefined||value==='')return null;const text=String(value).trim();if(!/^-?\d+(?:\.\d)?$/.test(text)||!Number.isFinite(Number(text))||Number(text)>10||Number(text)<0)throw Error('난이도는 10점 이내, 소수점 한 자리까지 입력하세요. 미평가는 빈칸으로 둡니다.');return Number(text).toFixed(1);}
const sourceDefaults=()=>({kind:'기타자료',school:null,region:null,schoolId:null,materialTitle:null,academicYear:null,grade:null,semester:null,exam:null,curriculumId:null,taxonomyVersion:null,numbering:null});
function sourceMeta(value={}){const out=sourceDefaults();for(const k of Object.keys(out))if(k==='numbering'){out[k]=require('./source-inventory.cjs').normalize(value[k]);if(value[k]?.confirmed&&out[k]?.uncertain)throw Error('원본 전체 수와 객관식·서술형 수를 확인하세요.');}else if(k in value)out[k]=value[k]===null||value[k]===''?null:String(value[k]).slice(0,300);if(!['학교기출','교재','기타자료','자체제작','원문변형','AI생성'].includes(out.kind))throw Error('출처 종류를 확인하세요.');return out;}
function metadata(q,p,project){return {source:{...sourceDefaults(),originalNumber:require('./bank-source-order.cjs').printedNumber(q,p),originalPoints:q.originalPoints??p.recognition?.points??require('./structured-layout.js').sourcePoints(q)??null},classification:{primaryUnit:null,relatedUnits:[],types:[],assessmentConcepts:[],conditionConcepts:[],solutions:[],strategies:[],suggested:null,confirmed:null,status:'unclassified',existingDomains:clone(p.recognition?.domains||[]),taxonomyVersion:project.scope?.curriculum?.version||null},difficulty:{aiScore:null,userScore:null,targetScore:null,reason:null,scope:clone(project.scope||null),referenceIds:[],criteriaVersion:require('./difficulty-assessment.cjs').version,isReference:false,status:'unevaluated',burdens:null,legacyLabel:q.difficulty||null},management:{note:'',favorite:false,tags:[],customFields:{},disabled:false,disabledReason:null,usageNotes:null,review:q.kind==='variant'?'needs_user_review':q.approval?.status||'unreviewed'},content:{responseType:({single_choice:'선택형',single_value:'단답형',all_solutions:'단답형',proof:'서술형',written_response:'서술형'})[q.questionType]||((q.choices||[]).length?'선택형':null),responseDetail:null,printedAnswer:p.recognition?.printedAnswer??null,reviewedAnswer:q.answer||null,choices:(q.choices||[]).map(text=>({id:uuid(),text})),solutionConcepts:[],commonRelations:[],subquestionRelations:[],rubric:clone(q.grading||null),solutionGuide:clone(q.solutionGuide||null)},relations:{originalQuestionId:null,variantGroupId:null,method:q.provenance?.variant||null,generationConditions:clone(q.provenance||null),targetDifficultyLegacy:q.requestedDifficulty||null},reviews:{recognition:clone(p.recognition?{confirmed:p.recognition.confirmed,status:p.recognition.status}:null),answer:clone(q.checks?.ai||null),solution:clone(q.approval||null),diagram:clone(q.checks?.program||null),scope:clone(q.checks?.scope||null)}};}
function patchMetadata(current,patch){const next=clone(current);if(patch.source)next.source={...next.source,...sourceMeta({...next.source,...patch.source}),...Object.fromEntries(['originalNumber','originalPoints'].filter(k=>k in patch.source).map(k=>[k,patch.source[k]===null||patch.source[k]===''?null:String(patch.source[k]).slice(0,100)]))};if(patch.tags)next.management.tags=[...new Set(patch.tags.map(String).map(s=>s.trim()).filter(Boolean))].slice(0,100);if('note'in patch)next.management.note=String(patch.note).slice(0,10000);if('favorite'in patch)next.management.favorite=!!patch.favorite;
 if('userScore'in patch){next.difficulty.userScore=score(patch.userScore);next.difficulty.reassessmentRequired=false;next.difficulty.status=next.difficulty.userScore===null?'unevaluated':'user_confirmed';}if('targetScore'in patch)next.difficulty.targetScore=score(patch.targetScore);if('isReference'in patch)next.difficulty.isReference=!!patch.isReference;
 if('teacherBand'in patch){if(patch.teacherBand!==null&&!require('./difficulty-assessment.cjs').bands.includes(patch.teacherBand))throw Error('난이도 구간 오류');next.difficulty.teacherBand=patch.teacherBand;}
 if('primaryUnit'in patch){const label=String(patch.primaryUnit||'').trim();next.classification.primaryUnit=label?{id:next.classification.primaryUnit?.name===label?next.classification.primaryUnit.id:uuid(),name:label}:null;next.classification.status=label?'user_confirmed':'unclassified';next.classification.confirmed={...next.classification.confirmed,primaryUnit:next.classification.primaryUnit};}
 if('type'in patch){const types=require('./question-types.cjs').resolve(patch.type,{metadata:current});next.classification.confirmed={...next.classification.confirmed,types};}
 return next;}
function filename(text){return String(text||'미상').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,90);}
function folderSegments(meta,sourceId,created){const s=meta.source;if(['원문변형','AI생성','자체제작'].includes(s.kind))return ['03_유사문제·자체제작',/^\d{4}-/.test(s.generatedAt||'')?s.generatedAt.slice(0,4)+'년':'연도미상'];if(s.kind==='학교기출')return ['01_학교기출',s.academicYear?filename(s.academicYear)+'학년도':'연도미상',filename([s.region,s.school].filter(Boolean).join('_')||'출처미상'),filename([s.grade,s.semester,s.exam].filter(Boolean).join('_')||'시험미상')+'_'+sourceId.slice(0,8)];return ['02_교재·기타자료',filename(s.materialTitle||'출처미상')+'_'+sourceId.slice(0,8)];}
function safeLocal(root,rel){if(typeof rel!=='string'||rel.includes('\\')||rel.split('/').some(x=>!x||x==='.'||x==='..')||/[:\x00]/.test(rel))throw Error('문항 묶음의 파일 경로가 올바르지 않습니다.');const full=path.resolve(root,...rel.split('/'));if(!full.startsWith(path.resolve(root)+path.sep))throw Error('문항 묶음 경로 오류');return full;}
function portableSnapshot(project,problem,question,folder,{externalSource=null}={}){const allSources=project.sources||[{...project.source,id:'primary'}],ids=new Set(problem.regions.map(r=>r.sourceId||'primary'));const sources=allSources.filter(s=>ids.has(s.id));if(!sources.length)throw Error('문항의 원본 파일을 찾을 수 없습니다.');const p=clone(problem);delete p.losslessStorage;p.variants=question.kind==='variant'?p.variants.filter(q=>q.id===question.id):[];const primary=sources[0].id;if(primary!=='primary')for(const r of p.regions)if(r.sourceId===primary)r.sourceId='primary';const normalizedSources=clone(sources);normalizedSources[0].id='primary';const {id:unused,...source}=normalizedSources[0];const native={version:1,id:project.id,title:project.title,createdAt:project.createdAt,updatedAt:project.updatedAt,settings:clone(project.settings),scope:clone(project.scope||{}),sources:normalizedSources,source,problems:[p]};const refs=new Map(),sourcePaths=new Map(sources.map(s=>[path.resolve(s.path),s.id]));const root=fs.realpathSync(folder);
 function visit(value){if(typeof value==='string'&&absoluteFile(value)){const resolved=fs.realpathSync(value);if((!resolved.startsWith(root+path.sep)&&(!externalSource||resolved!==fs.realpathSync(externalSource)||!sourcePaths.has(path.resolve(value))))||!fs.statSync(resolved).isFile())throw Error('문항의 첨부 파일이 작업 폴더 밖에 있습니다.');const bytes=fs.readFileSync(resolved),sha256=digest(bytes),key=digest(Buffer.from(resolved.startsWith(root+path.sep)?resolved.slice(root.length):'queue-source:'+sha256)).slice(0,20),entry={key,name:path.basename(value),localPath:resolved,size:bytes.length,sha256,sourceLocalId:sourcePaths.get(path.resolve(value))||null,role:sourcePaths.has(path.resolve(value))?'source':'asset'};refs.set(key,entry);return 'bank-asset:'+key;}if(Array.isArray(value))return value.map(visit);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!/(?:access_token|refresh_token|client_secret|api[_-]?key|password|authorization)/i.test(k)).map(([k,v])=>[k,visit(v)]));return value;}
 return {native:visit(native),refs:[...refs.values()],targetId:question.id,sources};}
function restoreSnapshot(bundle,files,folder,{projectId=path.basename(folder),createdAt=now(),externalSources=null}={}){if(bundle.schemaVersion!==1||!bundle.native?.project||!Array.isArray(bundle.files))throw Error('지원하지 않는 문항 저장 규격입니다.');const native=clone(bundle.native.project),assetDir=path.join(folder,'assets');fs.mkdirSync(assetDir,{recursive:true});const refs=new Map();for(const entry of bundle.files.filter(f=>['source','asset'].includes(f.role))){const bytes=files.get(entry.key);if(!bytes||bytes.length!==entry.size||digest(bytes)!==entry.sha256)throw Error('문항 첨부 파일의 무결성 확인에 실패했습니다.');const base=path.basename(entry.name);if(base!==entry.name||/[\\/:\x00]/.test(base))throw Error('첨부 파일 이름 오류');const out=path.join(assetDir,base);if(fs.existsSync(out)&&digest(fs.readFileSync(out))!==entry.sha256)throw Error('첨부 파일 이름이 충돌합니다.');const external=entry.role==='source'&&externalSources?.get(entry.key);if(external){if(digest(fs.readFileSync(external))!==entry.sha256)throw Error('대기열 외부 원본 무결성 오류');refs.set(entry.key,external);}else{fs.writeFileSync(out,bytes);refs.set(entry.key,out);}}
 const visit=v=>typeof v==='string'&&absoluteFile(v)?(()=>{throw Error('복원 데이터에 로컬 절대경로가 있습니다.');})():typeof v==='string'&&v.startsWith('bank-asset:')?(refs.get(v.slice(11))||(()=>{throw Error('복원할 첨부 자료가 없습니다.');})()):Array.isArray(v)?v.map(visit):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,visit(x)])):v;
 const restored=visit(native);if(!Array.isArray(restored.problems)||restored.problems.length!==1||!Array.isArray(restored.sources)||!restored.sources.length||restored.sources[0].id!=='primary')throw Error('문항 네이티브 구조가 올바르지 않습니다.');const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(id);if(restored.sources.some(s=>!validId(s.id))||restored.problems.some(p=>!validId(p.id)||!Array.isArray(p.regions)||!Array.isArray(p.cropPaths)||!Array.isArray(p.variants)||[p.original,...p.variants].filter(Boolean).some(q=>!validId(q.id))))throw Error('문항 식별값 또는 영역 구조가 올바르지 않습니다.');restored.id=projectId;restored.createdAt=createdAt;restored.updatedAt=now();for(const p of restored.problems){p.threadId=null;p.geminiThreadId=null;for(const q of [p.original,...p.variants].filter(Boolean)){if(q.id!==bundle.native.targetQuestionId)q.include=false;if(q.questionOnlyExport)q.questionOnlyExport.sourceKey=JSON.stringify(p.cropPaths);}}
 return restored;}
module.exports={uuid,now,clone,score,metadata,patchMetadata,sourceMeta,folderSegments,filename,safeLocal,portableSnapshot,restoreSnapshot};
