'use strict';
const fs=require('node:fs'),path=require('node:path');
const {atomicWrite}=require('./store.cjs'),{BankError}=require('./bank-auth.cjs'),{digest,APP}=require('./bank-drive.cjs');
const M=require('./bank-model.cjs');
const ACTIVE=['queued','uploading','preparing'],COMPLETE=['complete'];
const payloadFrozen=job=>!job.committed&&/Revision payload frozen or retired/i.test(job.error||'');
class QuestionBank{
 constructor({directory,store,storage,auth,buildDocx,preview,appVersion,rendererVersion=null,losslessUploads=false,onEvent=()=>{}}){Object.assign(this,{store,storage,auth,buildDocx,preview,appVersion,rendererVersion,losslessUploads,onEvent});this.dir=path.join(directory,'question-bank');this.file=path.join(this.dir,'state.json');fs.mkdirSync(this.dir,{recursive:true});const empty=()=>({version:1,auto:false,root:null,folders:{},sources:{},sourceMeta:{},items:{},bindings:{},jobs:[],cache:{},dirty:[]});try{this.state=fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):empty();if(this.state.version!==1||!Array.isArray(this.state.jobs)||!this.state.items||!Array.isArray(this.state.dirty))throw Error();this.state.bindings||={};}catch{this.state=empty();this.blockedError='문제은행 로컬 목록을 읽지 못했습니다. 기존 state.json을 보존했습니다. 백업에서 복원한 뒤 다시 실행하세요.';}for(const entry of [...Object.values(this.state.items),...Object.values(this.state.bindings)]){if(entry.sourcePath)entry.sourcePath=this.store.folders.rebase(entry.sourcePath);for(const a of entry.attachments||[])if(a.localPath)a.localPath=this.store.folders.rebase(a.localPath);}for(const job of this.state.jobs)if(ACTIVE.includes(job.status))job.status='queued';this.save();this.running=false;this.timer=null;}
 save(){if(this.blockedError)return;for(const item of Object.values(this.state.items))this.state.bindings[item.localKey]=M.clone(item);atomicWrite(this.file,this.state);this.onEvent({type:'bank-updated'});}
 status(){return {difficultyCriteriaVersion:require('./difficulty-assessment.cjs').version,error:this.blockedError||null,auth:this.auth.status(),root:this.state.root,automatic:this.state.auto,analysisProgress:this.state.analysisProgress||null,jobs:this.state.jobs.map(({id,questionId,revisionId,status,error,attempts,createdAt,previewStatus,committed,filesCompleted,filesTotal})=>({id,questionId,revisionId,status,error,attempts,createdAt,previewStatus,committed,filesCompleted,filesTotal,superseded:this.isSuperseded({id,questionId,revisionId})})),items:Object.values(this.state.items).map(i=>({...i,finalDifficulty:(()=>{const display=require('./desktop-difficulty.cjs').effective({metadata:i.metadata,revision_id:i.latestRevisionId||i.baseRevisionId});return {...display,numberSource:display.source};})(),sourcePath:undefined,attachments:(i.attachments||[]).map(({localPath,...f})=>f)})),cached:Object.values(this.state.cache),nextPageToken:this.state.nextPageToken||null};}
 async connect(options){await this.auth.connect(options);for(const j of this.state.jobs)if(j.status==='auth'){j.status='queued';j.error=null;j.nextAt=0;}this.save();this.wake();return this.status();}
 async root(id=null){if(this.running)throw Error('업로드가 끝난 뒤 저장 폴더를 변경하세요.');await this.auth.token();let root;if(this.storage.getRoot){root=await this.storage.getRoot();if(id&&id!==root.id)throw Error('공동 저장소 ID가 다릅니다.');}else if(id){root=await this.storage.checkRoot(id);}else{const found=await this.storage.find(digest(Buffer.from('root')));if(found.length>1)throw Error('앱이 만든 문제은행 폴더가 여러 개입니다. 폴더 ID를 지정하세요.');if(found.length)root=await this.storage.checkRoot(found[0].id);else{const same=await this.storage.list("trashed=false and mimeType='application/vnd.google-apps.folder' and name='문제은행' and 'root' in parents");if(same.files.length)throw Error('접근 가능한 같은 이름의 폴더가 있습니다. 사용할 폴더 ID를 지정하세요.');const rootId=await this.storage.folder({key:'root',name:'문제은행',registry:this.state.folders,save:()=>this.save()});root=await this.storage.checkRoot(rootId);}}
  if(this.state.root&&this.state.root.id!==root.id&&this.state.jobs.some(j=>!COMPLETE.includes(j.status)))throw Error('기존 폴더에 저장할 대기 작업을 완료한 뒤 폴더를 변경하세요.');this.state.root={id:root.id,name:root.name};this.save();this.wake();return this.status();}
 async setAuto(enabled){if(enabled){await this.auth.token();if(!this.state.root)throw Error('문제은행 저장 폴더를 먼저 연결하세요.');await this.storage.checkRoot(this.state.root.id);}this.state.auto=!!enabled;this.save();return this.status();}
 disconnect(){if(this.running)throw Error('진행 중인 업로드가 끝난 후 연결 해제하세요. 대기 작업은 먼저 보류할 수 있습니다.');this.state.auto=false;this.auth.disconnect();this.save();return this.status();}
 sourceId(projectId,source){const key=projectId+':file:'+(source.queueSourceId||path.basename(source.path));if(this.state.sources[key])return this.state.sources[key];const hash='sha256:'+digest(fs.readFileSync(source.path));return this.state.sources[key]=this.state.sources[hash]||(this.state.sources[hash]=M.uuid());}
 ensure(project,p,q){const key=project.id+':'+p.id+':'+q.id;let item=Object.values(this.state.items).find(i=>i.localKey===key);if(!item&&this.state.bindings[key]){item=M.clone(this.state.bindings[key]);this.state.items[item.id]=item;}if(!item){item={id:M.uuid(),localKey:key,projectId:project.id,problemId:p.id,questionId:q.id,createdAt:M.now(),metadata:M.metadata(q,p,project),overrides:{},baseRevisionId:null,latestRevisionId:null,status:'local'};this.state.items[item.id]=item;}
  const src=(project.sources||[{...project.source,id:'primary'}]).find(s=>s.id===(p.regions.find(r=>r.role!=='context')?.sourceId||'primary'));if(!src)throw Error('문항의 출처 파일을 찾을 수 없습니다.');item.sourceId=this.sourceId(project.id,src);const sourceDetails=require('./bank-source-order.cjs').sourceDetails(project,p,q,item.sourceId);item.metadata.source={...item.metadata.source,...sourceDetails,originalNumber:sourceDetails.originalNumber??item.metadata.source.originalNumber};const common=this.state.sourceMeta[item.sourceId]||{};item.metadata.source={...item.metadata.source,...common,...item.overrides};const numbering=sourceDetails.numbering;if(common.numbering||numbering)item.metadata.source.numbering={...numbering,...common.numbering,...item.overrides.numbering,section:item.overrides.numbering?.section||numbering?.section||require('./source-inventory.cjs').sourceNumber({originalNumber:sourceDetails.originalNumber}).section||'unknown'};
  if(item.metadata.source.originalPoints==null&&!Object.hasOwn(item.overrides,'originalPoints'))item.metadata.source.originalPoints=M.metadata(q,p,project).source.originalPoints;
  item.metadata.source.generatedAt||=q.createdAt||(p.runs||[]).find(r=>r.requestId===q.provenance?.requestId)?.startedAt||null;item.metadata.content.reviewedAnswer=q.answer||null;item.metadata.content.printedAnswer=p.recognition?.printedAnswer??null;item.metadata.content.responseType=M.metadata(q,p,project).content.responseType;item.metadata.content.rubric=M.clone(q.grading||null);item.metadata.content.solutionGuide=M.clone(q.solutionGuide||null);item.metadata.content.solutionConcepts=M.clone(q.checks?.ai?.usedConcepts||[]);item.metadata.reviews=M.metadata(q,p,project).reviews;item.metadata.relations.generationConditions=M.clone(q.provenance||null);
  item.metadata=require('./difficulty-assessment.cjs').currentOnly({metadata:item.metadata,revision_id:item.latestRevisionId||item.baseRevisionId}).metadata;
  require('./queue-classification.cjs').apply(item.metadata,q,p,project.scope);  require('./assessment-cache.cjs').importEmbedded(item.metadata,q,p,project.scope);const analysis=item.metadata.analysis;if(analysis?.basis===require('./bank-analysis.cjs').legacyBasis(q,p,project.scope))analysis.basis=require('./bank-analysis.cjs').basis(q,p,project.scope);if(analysis?.basis&&analysis.basis!==require('./bank-analysis.cjs').basis(q,p,project.scope)){delete item.metadata.difficulty.previousAssessment;analysis.status='stale';item.metadata.difficulty.reassessmentRequired=true;delete item.metadata.difficulty.calibratedScore;delete item.metadata.difficulty.calibration;item.metadata.difficulty.aiScore=null;item.metadata.difficulty.aiBand=null;item.metadata.difficulty.reason='문항 내용·도형·범위 변경으로 이전 분석을 사용할 수 없습니다.';if(!item.metadata.classification.confirmed){item.metadata.classification.primaryUnit=null;item.metadata.classification.status='unclassified';}item.metadata.classification.suggested=null;if(!item.metadata.classification.confirmed?.types?.length&&!item.metadata.classification.confirmed?.type){item.metadata.classification.types=[];item.metadata.classification.typeRecommendation={status:"stale",reason:"문항 변경 후 출제유형 재확인 필요"};}}
  item.metadata=require('./difficulty-assessment.cjs').currentOnly({metadata:item.metadata,revision_id:item.latestRevisionId||item.baseRevisionId}).metadata;
  const oldChoices=item.metadata.content.choices,used=new Set();item.metadata.content.choices=(q.choices||[]).map((text,index)=>{const previous=oldChoices.find(c=>c.text===text&&!used.has(c.id))||(!used.has(oldChoices[index]?.id)?oldChoices[index]:null),id=previous?.id||M.uuid();used.add(id);return{id,text};});
  if(q.kind==='variant'){const original=p.original?this.ensure(project,p,p.original):null;item.metadata.source.kind=q.provenance?'AI생성':'원문변형';item.metadata.relations.originalQuestionId=original?.id||null;item.metadata.relations.originalRevisionId=original?.latestRevisionId||original?.baseRevisionId||null;item.metadata.relations.variantGroupId=original?.id||null;item.metadata.management.review='needs_user_review';}else item.metadata.management.review=q.approval?.status||'unreviewed';return item;
 }
 catalog(projectId){if(!projectId)return this.status();const p=this.store.get(projectId);for(const problem of p.problems)for(const q of [problem.original,...problem.variants].filter(q=>q?.body))this.ensure(p,problem,q);this.save();const visible=new Set(p.problems.flatMap(problem=>[problem.original,...problem.variants].filter(q=>q?.body).map(q=>q.id)));return {...this.status(),items:this.status().items.filter(i=>i.projectId!==projectId||visible.has(i.questionId)),projectId,sources:(p.sources||[{...p.source,id:'primary'}]).map(s=>({id:s.id,name:s.name,bankSourceId:this.sourceId(p.id,s),metadata:this.state.sourceMeta[this.sourceId(p.id,s)]||M.sourceMeta(require('./bank-source-info.cjs').inferSourceInfo(s.name)),suggested:!this.state.sourceMeta[this.sourceId(p.id,s)]}))};}
 edit(ids,patch){this.state.taxonomy||={};if(patch.primaryUnit?.trim()&&!this.state.taxonomy[patch.primaryUnit.trim()])this.state.taxonomy[patch.primaryUnit.trim()]={id:M.uuid(),name:patch.primaryUnit.trim()};if(!Array.isArray(ids)||!ids.length)throw Error('수정할 문항을 선택하세요.');const entries=ids.map(id=>{const item=this.state.items[id];if(!item)throw Error('로컬 문항을 먼저 불러오세요.');return [item,M.patchMetadata(item.metadata,patch)];});for(const [item,meta] of entries){item.metadata=meta;if(patch.primaryUnit?.trim()){item.metadata.classification.primaryUnit=M.clone(this.state.taxonomy[patch.primaryUnit.trim()]);item.metadata.classification.confirmed={...item.metadata.classification.confirmed,primaryUnit:item.metadata.classification.primaryUnit};}item.hasLocalChanges=true;if(patch.source)item.overrides={...item.overrides,...patch.source};item.status='local';item.modifiedAt=M.now();if(this.state.auto)this.markDirty(item.projectId,item.questionId);}this.save();return this.status();}
 editSource(projectId,sourceLocalId,values){const project=this.store.get(projectId),source=(project.sources||[{...project.source,id:'primary'}]).find(s=>s.id===sourceLocalId);if(!source)throw Error('원본 파일을 선택하세요.');const sourceId=this.sourceId(projectId,source),metadata=M.sourceMeta(values);if(JSON.stringify(this.state.sourceMeta[sourceId])===JSON.stringify(metadata))return this.catalog(projectId);this.state.sourceMeta[sourceId]=metadata;for(const item of Object.values(this.state.items).filter(i=>i.sourceId===sourceId)){item.metadata.source={...item.metadata.source,...this.state.sourceMeta[sourceId],...item.overrides};item.status='local';item.hasLocalChanges=true;if(this.state.auto)this.markDirty(item.projectId,item.questionId);}this.save();return this.catalog(projectId);}
 attach(id,paths){const item=this.state.items[id];if(!item)throw Error('문항을 먼저 선택하세요.');for(const file of paths){const ext=path.extname(file).toLowerCase();if(!['.hwp','.pdf'].includes(ext)||!fs.statSync(file).isFile()||fs.statSync(file).size>300*1024*1024)throw Error('300MB 이하의 HWP·PDF 파일을 선택하세요.');const bytes=fs.readFileSync(file);if(!bytes.length)throw Error('빈 파일은 첨부할 수 없습니다.');const sha256=digest(bytes);item.attachments||=[];if(item.attachments.some(f=>f.sha256===sha256))continue;const key=M.uuid(),target=path.join(this.dir,'attachments',key+ext);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,bytes);item.attachments.push({key,name:path.basename(file),localPath:target,size:bytes.length,sha256,role:'attachment',externalEditedCopy:true});}item.status='local';item.hasLocalChanges=true;if(this.state.auto)this.markDirty(item.projectId,item.questionId);this.save();return this.status();}
 markDirty(projectId,questionId){if(this.store.get(projectId).queueSource)return;const pending=this.state.dirty.find(d=>d.projectId===projectId&&d.questionId===questionId);if(pending)pending.nonce=M.uuid();else this.state.dirty.push({projectId,questionId,nonce:M.uuid()});clearTimeout(this.debounce);this.debounce=setTimeout(()=>this.flushDirty(),1800);this.debounce.unref?.();}
 afterExport({projectId,originalsOnly=false}){if(!this.state.auto||this.blockedError)return;const project=this.store.get(projectId);for(const p of project.problems)for(const q of [p.original,...(originalsOnly?[]:p.variants)].filter(q=>q?.include&&q.body?.trim()))this.markDirty(projectId,q.id);this.save();}
 observe(project,previous){if(!previous||!this.state.auto&&!Object.values(this.state.bindings).some(i=>i.projectId===project.id))return;for(const p of project.problems){if((p.runs||[]).some(r=>r.status==='running'))continue;const old=previous.problems.find(x=>x.id===p.id);for(const q of [p.original,...p.variants].filter(q=>q?.body?.trim())){const before=[old?.original,...(old?.variants||[])].find(x=>x?.id===q.id);const changed=JSON.stringify(before)!==JSON.stringify(q)||JSON.stringify(old?.regions)!==JSON.stringify(p.regions)||JSON.stringify(old?.recognition)!==JSON.stringify(p.recognition)||JSON.stringify(previous.settings)!==JSON.stringify(project.settings)||JSON.stringify(previous.scope)!==JSON.stringify(project.scope)||(old?.runs||[]).some(r=>r.status==='running');if(!changed)continue;const key=project.id+':'+p.id+':'+q.id;const item=Object.values(this.state.items).find(i=>i.localKey===key)||this.state.bindings[key];if(item){item.status='local';item.hasLocalChanges=true;}if(this.state.auto)this.markDirty(project.id,q.id);}}this.save();}
 async flushDirty(){const dirty=M.clone(this.state.dirty);for(const d of dirty){try{await this.enqueue(d.projectId,[d.questionId]);this.state.dirty=this.state.dirty.filter(p=>!(p.projectId===d.projectId&&p.questionId===d.questionId&&p.nonce===d.nonce));}catch(e){const i=Object.values(this.state.items).find(i=>i.projectId===d.projectId&&i.questionId===d.questionId);if(i){i.status='failed';i.error=e.message;}}this.save();}}
 async targets(projectId,questionIds){const project=this.store.get(projectId),results=[];for(const questionId of questionIds){const p=project.problems.find(p=>[p.original,...p.variants].some(q=>q?.id===questionId)),q=p&&[p.original,...p.variants].find(q=>q?.id===questionId);if(!q)throw Error('대상 문항을 확인하세요.');results.push(await require('./bank-source-link.cjs').resolve(this,this.ensure(project,p,q),{preview:true}));}return results;}
  async enqueue(projectId,questionIds,selections={}){const project=this.store.get(projectId);if(!Array.isArray(questionIds)||!questionIds.length)throw Error('저장할 문항을 선택하세요.');for(const questionId of questionIds){const p=project.problems.find(p=>[p.original,...p.variants].some(q=>q?.id===questionId)),q=p&&[p.original,...p.variants].find(q=>q?.id===questionId);if(!q?.body?.trim())throw Error('완성된 문항 본문이 필요합니다.');if((p.runs||[]).some(r=>r.status==='running'))throw Error('문항 생성이 끝난 뒤 저장하세요.');const item=this.ensure(project,p,q);await require('./bank-source-link.cjs').resolve(this,item,{selection:selections[questionId]||null});let actorId=null;if(this.storage.prepareItem){const access=await this.storage.prepareItem(item);actorId=access.actorId;if(access.foreign){const oldId=item.id;delete this.state.items[oldId];item.id=M.uuid();item.metadata.relations.derivedFromQuestionId=oldId;item.metadata.relations.derivedFromRevisionId=item.baseRevisionId;item.baseRevisionId=null;item.latestRevisionId=null;item.folderId=null;item.createdAt=M.now();item.ownerId=actorId;this.state.items[item.id]=item;}item.ownerId=actorId;}await require('./bank-detailed-types.cjs').beforeUpload(this,item);const pack=M.portableSnapshot(project,p,q,this.store.projectDir(project.id),{externalSource:project.queueSource?this.store.externalSource?.(project.queueSource.queueId,project.id):null});if(item.metadata.processing)item.metadata.processing.nativeInput=require('./bank-maintenance-rules.cjs').nativeInput(pack);const fingerprint=digest(Buffer.from(JSON.stringify({q,p:{regions:p.regions,recognition:p.recognition},metadata:item.metadata,settings:project.settings,scope:project.scope,assets:[...pack.refs,...(item.attachments||[])].map(r=>[r.key,r.sha256])})));
   const frozen=this.state.jobs.find(j=>j.questionId===item.id&&payloadFrozen(j)&&(j.parentRevisionId===(item.baseRevisionId||null)||j.revisionId===item.latestRevisionId));
   if(frozen)throw new BankError('Revision payload frozen or retired: 기존 미완료 revision '+frozen.revisionId+'을 보존했습니다. 서버 차단 원인을 해결하기 전에는 새 업로드를 만들 수 없습니다.','conflict');
   if(this.state.jobs.some(j=>j.questionId===item.id&&j.fingerprint===fingerprint&&j.parentRevisionId===(item.baseRevisionId||null)&&!['failed','conflict'].includes(j.status)||j.questionId===item.id&&j.fingerprint===fingerprint&&j.revisionId===item.latestRevisionId&&!['failed','conflict'].includes(j.status)))continue;
   const revisionId=M.uuid(),dir=path.join(this.dir,'outbox',revisionId);fs.mkdirSync(dir,{recursive:true});const sourceRefs=[...pack.refs,...(item.attachments||[])].map(ref=>({...ref,sourceId:ref.role==='source'?this.sourceId(project.id,pack.sources.find(s=>s.id===ref.sourceLocalId)):null}));
   const previous=this.state.jobs.find(j=>j.revisionId===item.latestRevisionId&&j.projectId===projectId&&!['failed','conflict'].includes(j.status));const parentRevisionId=previous?.revisionId||item.baseRevisionId||null;
   const originalItem=q.kind==='variant'?this.state.items[item.metadata.relations.originalQuestionId]:null;const bundle={schemaVersion:1,questionId:item.id,sourceId:item.sourceId,revisionId,parentRevisionId,createdAt:item.createdAt,modifiedAt:M.now(),appVersion:this.appVersion,metadata:M.clone(item.metadata),relatedOriginal:originalItem?{id:originalItem.id,createdAt:originalItem.createdAt,revisionId:originalItem.latestRevisionId||originalItem.baseRevisionId,sourceId:originalItem.sourceId,metadata:M.clone(originalItem.metadata)}:null,native:{format:'examstudio-project-v1',project:pack.native,targetQuestionId:q.id},files:sourceRefs.map(({localPath,sourceLocalId,...r})=>r),definitions:{curriculum:project.scope?.curriculum||null,customFields:item.metadata.management.customFields,taxonomy:M.clone(this.state.taxonomy||{})}};
   if(this.storage.kind==='shared'){bundle.metadata.management.note='';bundle.metadata.management.favorite=false;if(bundle.relatedOriginal){bundle.relatedOriginal.metadata.management.note='';bundle.relatedOriginal.metadata.management.favorite=false;}}const captured=new Map(sourceRefs.map(r=>[r.key,fs.readFileSync(r.localPath)]));const snapshot=M.restoreSnapshot(bundle,captured,path.join(dir,'native'),{externalSources:project.queueSource?new Map(sourceRefs.filter(r=>r.role==='source').map(r=>[r.key,r.localPath])):null});for(const r of sourceRefs){if(r.role==='attachment'){const target=path.join(dir,'attachments',r.key+path.extname(r.name));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,captured.get(r.key));r.localPath=target;}else if(!(project.queueSource&&r.role==='source'))r.localPath=path.join(dir,'native','assets',r.name);}atomicWrite(path.join(dir,'question.json'),bundle);atomicWrite(path.join(dir,'local-input.json'),{project:snapshot,problemId:p.id,questionId:q.id,refs:sourceRefs,losslessSources:structuredClone(p.losslessStorage?.bindings||[])});
   this.state.jobs.push({actorId,id:revisionId,revisionId,questionId:item.id,sourceId:item.sourceId,projectId,questionFolderId:item.folderId||null,status:'queued',createdAt:M.now(),fingerprint,parentRevisionId,attempts:0,error:null,remote:{},rootId:this.state.root?.id||null,previewStatus:'pending',losslessPreview:this.losslessUploads,losslessUploads:this.losslessUploads});item.latestRevisionId=revisionId;item.hasLocalChanges=false;item.status='queued';this.save();
  }this.wake();return this.status();}
 wake(){if(this.closed||this.blockedError)return;clearTimeout(this.timer);this.timer=setTimeout(()=>this.pump().catch(e=>{this.lastError=e.message;}),50);this.timer.unref?.();}
 pause(id){const job=this.state.jobs.find(j=>j.id===id);if(!job)throw Error('업로드 작업을 찾을 수 없습니다.');if(this.activeId===id)job.pauseRequested=true;else job.status='paused';this.save();return this.status();}
 isSuperseded(job){const index=this.state.jobs.findIndex(j=>j.id===job.id);if(index<0)return false;const next=this.state.jobs.slice(index+1).find(j=>j.questionId===job.questionId);return !!next&&next.parentRevisionId!==job.revisionId;}
 retry(id){const job=this.state.jobs.find(j=>j.id===id);if(job?.status==='conflict'||job?.conflictBlocked)throw new BankError('수정 충돌 작업은 같은 기준으로 재시도할 수 없습니다. 최신 문항과 로컬 수정본을 비교한 뒤 새 버전으로 등록하세요.','conflict');if(!job||job.status==='complete'||job.committed)throw Error('재시도할 작업을 선택하세요.');if(this.isSuperseded(job))throw Error('이 문항에는 더 나중에 등록한 작업이 있습니다. 오래된 실패본 대신 최신 작업을 재시도하세요.');job.status='queued';job.error=null;job.attempts=0;job.nextAt=0;job.pauseRequested=false;this.save();this.wake();return this.status();}
 retryTimedOut(limit=1){if(this.running)throw Error('현재 업로드가 끝난 뒤 재시도하세요.');if(limit!==1&&limit!=='all')throw Error('재시도 범위를 확인하세요.');const candidates=this.state.jobs.filter(j=>!j.committed&&!this.isSuperseded(j)&&['failed','paused'].includes(j.status)&&/statement timeout|DB 타임아웃/i.test(j.error||''));const selected=limit===1?candidates.slice(0,1):candidates;for(const job of selected){job.status='queued';job.error=null;job.attempts=0;job.nextAt=0;job.pauseRequested=false;}if(selected.length){this.save();this.wake();}return{retried:selected.length,status:this.status()};}
 async pump(){if(this.running||this.closed||this.blockedError)return;this.running=true;try{for(const job of this.state.jobs){if(this.closed)break;if(job.queueManaged||job.status!=='queued'||job.nextAt>Date.now())continue;const dependency=this.state.jobs.find(j=>j.revisionId===job.parentRevisionId);if(dependency&&!dependency.committed){job.status='paused';job.error=dependency.status==='conflict'?'직전 버전이 수정 충돌로 완료되지 않았습니다. 최신 원격본과 비교해야 합니다.':'직전 버전의 업로드를 완료한 뒤 재시도하세요.';this.save();continue;}this.activeId=job.id;try{await this.process(job);}catch(e){job.error=e.message;if(e.code==='conflict')job.conflictBlocked=true;job.attempts++;job.status=e.code==='auth'?'auth':e.code==='conflict'?'conflict':e.code==='timeout'?'failed':e.retryable&&job.attempts<4?'queued':'failed';if(job.status==='queued')job.nextAt=Date.now()+Math.min(60000,2000*2**job.attempts);const item=this.state.items[job.questionId];if(item&&!item.hasLocalChanges&&item.latestRevisionId===job.revisionId){item.status=job.status;item.error=job.error;}if(e.code==='timeout'){for(const pending of this.state.jobs.filter(j=>j.status==='queued')){pending.status='paused';pending.error='DB 타임아웃으로 나머지 업로드를 보류했습니다. 서버 상태를 확인한 뒤 재시도하세요.';const pendingItem=this.state.items[pending.questionId];if(pendingItem&&!pendingItem.hasLocalChanges&&pendingItem.latestRevisionId===pending.revisionId){pendingItem.status='paused';pendingItem.error=pending.error;}}}this.save();}finally{this.activeId=null;}}}finally{this.running=false;const pending=this.state.jobs.filter(j=>j.status==='queued'&&!j.queueManaged);if(pending.length&&!this.closed&&this.autonomous!==false){clearTimeout(this.timer);this.timer=setTimeout(()=>this.pump(),Math.max(1000,Math.min(...pending.map(j=>(j.nextAt||0)-Date.now()))));this.timer.unref?.();}}}
 checkPause(job){if(job.pauseRequested||this.closed){job.status='paused';job.pauseRequested=false;this.save();return true;}return false;}
 async remoteHeads(questionId){let token=null;const all=[];do{const page=await this.storage.commits(this.state.root.id,questionId,token);for(const f of page.files)all.push(await this.readCommit(f));token=page.nextPageToken;}while(token);const parents=new Set(all.map(m=>m.parentRevisionId).filter(Boolean));return all.filter(m=>!parents.has(m.revisionId));}
 async process(job){const dir=path.join(this.dir,'outbox',job.id),bundle=JSON.parse(fs.readFileSync(path.join(dir,'question.json'),'utf8'));job.status='preparing';this.save();const input=JSON.parse(fs.readFileSync(path.join(dir,'local-input.json'),'utf8'));if(!job.prepared){const cache=require('./bank-render-cache.cjs');
   if(!cache.reuse(this,job,input,dir)){const document=path.join(dir,'question.docx');await this.buildDocx(input,document);try{if(this.preview){await this.preview(document,path.join(dir,'preview.png'));job.previewStatus='complete';}else job.previewStatus='unavailable';}catch{job.previewStatus='failed_optional';}}
   cache.record(job,dir);job.prepared=true;this.save();}
  if(job.losslessPreview&&job.previewStatus==='complete'&&!job.previewStorage){job.previewStorage=await require('./lossless-image.cjs').prepare(path.join(dir,'preview.png'),path.join(dir,'optimized'));this.save();}
  if(job.previewStorage&&require('./lossless-image.cjs').sha(fs.readFileSync(job.previewStorage.file))!==job.previewStorage.sha256)throw new BankError('Prepared preview bytes changed; original job retained.','conflict');
  if(job.losslessUploads)await require('./lossless-upload.cjs').prepareJob(this,job,bundle,input,dir);
  if(this.checkPause(job))return;await this.auth.token();if(!this.state.root)throw new BankError('문제은행 저장 폴더를 연결하세요.','auth');if(job.rootId&&job.rootId!==this.state.root.id)throw new BankError('이 작업은 다른 문제은행 폴더에서 시작했습니다. 기존 폴더를 다시 연결하세요.','conflict');job.rootId=this.state.root.id;await this.storage.checkRoot(job.rootId);if(this.storage.beginRevision)await this.storage.beginRevision(job);job.status='uploading';this.save();
  const heads=await this.remoteHeads(job.questionId);let conflict=heads.some(h=>h.revisionId!==job.parentRevisionId&&h.revisionId!==job.revisionId);
  if(conflict&&this.storage.kind==='shared')throw new BankError('수정 충돌: 원격 최신 버전 또는 기존 변경 갈래를 먼저 확인하세요. 로컬 수정본은 보존했습니다.','conflict');
  job.filesTotal=input.refs.length+3+(job.previewStatus==='complete'?1:0);job.filesCompleted=0;this.save();
  const folder=async(key,name,parent)=>this.storage.folder({key:job.rootId+':'+key,name,parent,registry:this.state.folders,save:()=>this.save()});
  let parent=job.rootId,questionFolder;
  if(job.questionFolderId){const existing=await this.storage.get(job.questionFolderId);if(existing.trashed||existing.mimeType!=='application/vnd.google-apps.folder')throw new BankError('문항 폴더를 확인하세요.','conflict');questionFolder=existing.id;const questions=await this.storage.get(existing.parents?.[0]);parent=questions.parents?.[0];if(!parent)throw new BankError('출처 폴더 연결을 확인하세요.','conflict');}
  else{const locationKey='source-location:'+job.rootId+':'+job.sourceId+':'+(['원문변형','AI생성','자체제작'].includes(bundle.metadata.source.kind)?'generated':'original');const savedLocation=this.state.folders[locationKey],segments=M.folderSegments(bundle.metadata,job.sourceId,job.createdAt);if(savedLocation){const f=await this.storage.get(savedLocation.id);if(f.trashed)throw new BankError('출처 폴더가 휴지통에 있습니다.','conflict');parent=f.id;}else{for(let i=0;i<segments.length;i++)parent=await folder('source-path:'+segments.slice(0,i+1).join('/'),segments[i],parent);this.state.folders[locationKey]={id:parent};this.save();}const questions=await folder('questions:'+parent+':'+job.sourceId,'문항',parent);questionFolder=await folder('question:'+job.questionId,`Q_${job.questionId}_${M.filename(bundle.metadata.source.originalNumber?'원문'+bundle.metadata.source.originalNumber:'번호미상')}`,questions);}
  const sourceFolder=await folder('originals:'+parent+':'+job.sourceId,'원본',parent),revisionFolder=await folder('revision:'+job.revisionId,'R_'+job.revisionId,questionFolder);
  job.folderId=questionFolder;const assets=await folder('assets:'+job.revisionId,'assets',revisionFolder);
  const upload=async(key,file,name,role,target)=>{let remote=job.remote[key];if(!remote){remote=job.remote[key]={id:await this.storage.generateId()};this.save();}await this.storage.put({file,id:remote.id,name,parent:target,properties:{questionId:job.questionId,revisionId:job.revisionId,role,rootId:job.rootId},session:remote.session,saveSession:v=>{remote.session=v;this.save();}});job.filesCompleted++;this.save();const bytes=fs.readFileSync(file);return {key,id:remote.id,name,role,size:bytes.length,sha256:digest(bytes)};};
  const descriptors=[];for(const ref of input.refs){if(this.checkPause(job))return;if(digest(fs.readFileSync(ref.localPath))!==ref.sha256)throw new BankError('저장 대기 중 원본 파일이 변경되었습니다. 문항을 다시 등록하세요.','conflict');if(ref.role==='source'){const key='source-file:'+ref.sourceId+':'+ref.sha256,registryKey=digest(Buffer.from(job.rootId+key));let shared=this.state.folders[registryKey];if(!shared){const query=await this.storage.list(`trashed=false and appProperties has { key='sourceKey' and value='${registryKey}' }`);if(query.files.length>1)throw new BankError('중복된 원본 파일이 있습니다.','conflict');shared=this.state.folders[registryKey]={id:query.files[0]?.id||await this.storage.generateId(),parentId:query.files[0]?.parents?.[0]||sourceFolder};this.save();}const sourceUpload=await this.storage.put({file:ref.localPath,id:shared.id,name:ref.name,parent:shared.parentId||sourceFolder,properties:{sourceKey:registryKey,role:'source',rootId:job.rootId},session:shared.session,saveSession:v=>{shared.session=v;this.save();}});job.filesCompleted++;this.save();if(sourceUpload?.id&&sourceUpload.id!==shared.id){shared.id=sourceUpload.id;shared.parentId=sourceUpload.parents?.[0]||shared.parentId;this.save();}descriptors.push({...bundle.files.find(f=>f.key===ref.key),id:shared.id});}else descriptors.push({...bundle.files.find(f=>f.key===ref.key),...await require('./lossless-upload.cjs').uploadAsset({bank:this,job,bundle,ref,assets,upload})});}
  descriptors.push(await upload('docx',path.join(dir,'question.docx'),'question.docx','docx',revisionFolder));if(job.previewStatus==='complete')descriptors.push(await upload('preview',job.previewStorage?.file||path.join(dir,'preview.png'),job.previewStorage?.name||'preview.png','preview',revisionFolder));
  bundle.files=descriptors;atomicWrite(path.join(dir,'question.json'),bundle);descriptors.push(await upload('data',path.join(dir,'question.json'),'question.json','data',revisionFolder));
  if(this.checkPause(job))return;const commit={schemaVersion:1,app:APP,rootId:job.rootId,questionId:job.questionId,sourceId:job.sourceId,revisionId:job.revisionId,parentRevisionId:job.parentRevisionId,completedAt:job.completedAt||(job.completedAt=M.now()),metadata:bundle.metadata,folderId:questionFolder,files:descriptors};atomicWrite(path.join(dir,'complete.json'),commit);this.save();await upload('commit',path.join(dir,'complete.json'),'complete.json','commit',revisionFolder);job.committed=true;this.save();
  const currentHeads=await this.remoteHeads(job.questionId);conflict=conflict||currentHeads.length>1;job.status=conflict?'conflict':'complete';job.error=conflict?'같은 기준 버전에서 갈라진 변경본이 있습니다. 저장 버전을 비교해 주세요.':null;const item=this.state.items[job.questionId];for(const bound of Object.values(this.state.bindings))if(bound.id===job.questionId&&bound.latestRevisionId===job.revisionId&&!bound.hasLocalChanges){bound.status=job.status;bound.baseRevisionId=job.revisionId;bound.folderId=questionFolder;bound.error=job.error;}if(item?.latestRevisionId===job.revisionId&&!item.hasLocalChanges){item.status=job.status;item.baseRevisionId=job.revisionId;item.folderId=questionFolder;item.error=job.error;}this.state.cache[job.revisionId]={...commit,author:currentHeads.find(h=>h.revisionId===job.revisionId)?.author||null,commitId:job.remote.commit.id,commitHash:digest(fs.readFileSync(path.join(dir,'complete.json'))),status:job.status};this.save();
 }
 async readCommit(file){if(Number(file.size)>5*1024*1024)throw Error('완료 기록이 너무 큽니다.');const bytes=await this.storage.download(file.id);if(file.md5Checksum&&digest(bytes,'md5')!==file.md5Checksum)throw new BankError('완료 기록 무결성 오류','conflict');if(bytes.length>5*1024*1024)throw Error('완료 기록이 너무 큽니다.');const value=JSON.parse(bytes);if(![value.questionId,value.revisionId,value.sourceId,...(value.parentRevisionId?[value.parentRevisionId]:[])].every(id=>typeof id==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(id))||value.schemaVersion!==1||value.app!==APP||value.rootId!==this.state.root.id||value.questionId!==file.appProperties?.questionId||value.revisionId!==file.appProperties?.revisionId||!Array.isArray(value.files)||!value.files.some(f=>f.role==='docx')||!value.files.some(f=>f.role==='data'))throw new BankError('문항 완료 기록을 검증하지 못했습니다.','conflict');if(new Set(value.files.map(f=>f.key)).size!==value.files.length||value.files.some(f=>!require('./bank-drive.cjs').validId(f.id)||typeof f.key!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(f.key)||!Number.isSafeInteger(f.size)||f.size<=0||f.size>350*1024*1024||!/^[a-f0-9]{64}$/.test(f.sha256)))throw new BankError('문항 파일 목록 검증에 실패했습니다.','conflict');return {...value,author:file.author||null,ownerId:file.ownerId||null,commitId:file.id,commitHash:digest(bytes)};}
 async refresh({next=false,rescan=false}={}){if(!this.state.root)throw Error('문제은행 폴더를 연결하세요.');await this.auth.token();if(rescan){this.state.cache={};this.state.nextPageToken=null;}const response=await this.storage.commits(this.state.root.id,null,next?this.state.nextPageToken:null);for(const file of response.files){try{const entry=await this.readCommit(file),old=this.state.cache[entry.revisionId];if(old?.commitHash&&old.commitHash!==entry.commitHash){old.status='conflict';old.error='완료 기록이 외부에서 변경되었습니다.';}else this.state.cache[entry.revisionId]={...entry,status:'complete'};}catch(e){this.state.cache['invalid-'+file.id]={commitId:file.id,status:'conflict',error:e.message};}}const entries=Object.values(this.state.cache);for(const id of new Set(entries.map(e=>e.questionId).filter(Boolean))){const versions=entries.filter(e=>e.questionId===id),parents=new Set(versions.map(e=>e.parentRevisionId)),heads=versions.filter(e=>!parents.has(e.revisionId));if(heads.length>1)for(const h of heads){h.status='conflict';h.error='여러 수정 갈래가 있습니다. 버전별 내용을 확인하세요.';}}this.state.nextPageToken=response.nextPageToken||null;this.save();return this.status();}
 async restore(revisionId){const cached=this.state.cache[revisionId];if(!cached)throw Error('저장 문항 목록을 새로 읽어 주세요.');const meta=await this.storage.get(cached.commitId),commit=await this.readCommit(meta);if(cached.commitHash&&cached.commitHash!==commit.commitHash)throw new BankError('Drive 완료 기록이 외부에서 변경되었습니다.','conflict');const data=commit.files.find(f=>f.role==='data'),bundle=JSON.parse(await this.storage.download(data.id,data));if(bundle.questionId!==commit.questionId||bundle.revisionId!==commit.revisionId||bundle.schemaVersion!==1)throw new BankError('문항 데이터와 완료 기록이 다릅니다.','conflict');if(JSON.stringify(bundle.files)!==JSON.stringify(commit.files.filter(f=>f.role!=='data')))throw new BankError('첨부 파일 관계가 변경되었습니다.','conflict');const files=new Map();for(const file of commit.files.filter(f=>['asset','source','docx','attachment'].includes(f.role)))files.set(file.key,await this.storage.download(file.id,file));
  const restoredMetadata=await require('./bank-detailed-types.cjs').restoredMetadata(this.storage,bundle);
  const projectId=M.uuid(),createdAt=M.now(),folder=this.store.reserveProjectFolder({id:projectId,title:bundle.native?.project?.title,createdAt});fs.mkdirSync(folder,{recursive:true});const project=await require('./lossless-restore.cjs').restore({bundle,files,folder,storage:this.storage,options:{projectId,createdAt}});const exports=path.join(folder,'exports');fs.mkdirSync(exports,{recursive:true});fs.writeFileSync(path.join(exports,'bank-original.docx'),files.get('docx'));const restoredAttachments=[];for(const f of commit.files.filter(f=>f.role==='attachment')){const target=path.join(exports,f.key+'_'+M.filename(f.name));fs.writeFileSync(target,files.get(f.key));restoredAttachments.push({...f,localPath:target});}
  this.store.write(project);this.state.taxonomy={...bundle.definitions?.taxonomy,...this.state.taxonomy};const problem=project.problems[0],question=[problem.original,...problem.variants].find(q=>q?.id===bundle.native.targetQuestionId);if(!question)throw Error('복원할 문항을 찾을 수 없습니다.');const item={ownerId:commit.ownerId||null,author:commit.author||null,id:bundle.questionId,localKey:projectId+':'+problem.id+':'+question.id,projectId,problemId:problem.id,questionId:question.id,createdAt:bundle.createdAt,sourceId:bundle.sourceId,metadata:restoredMetadata,overrides:Object.fromEntries(Object.entries(bundle.metadata.source).filter(([,v])=>v!==null&&v!=='')),baseRevisionId:bundle.revisionId,latestRevisionId:bundle.revisionId,status:'complete',folderId:commit.folderId,attachments:restoredAttachments};if(this.state.items[item.id])this.state.bindings[this.state.items[item.id].localKey]=M.clone(this.state.items[item.id]);this.state.items[item.id]=item;if(bundle.relatedOriginal&&problem.original?.id!==question.id){const base=bundle.relatedOriginal,oq=problem.original,originalBinding={id:base.id,localKey:projectId+':'+problem.id+':'+oq.id,projectId,problemId:problem.id,questionId:oq.id,createdAt:base.createdAt,sourceId:base.sourceId,metadata:base.metadata,overrides:Object.fromEntries(Object.entries(base.metadata.source).filter(([,v])=>v!==null&&v!=='')),baseRevisionId:base.revisionId,latestRevisionId:base.revisionId,status:base.revisionId?'complete':'local'};this.state.bindings[originalBinding.localKey]=originalBinding;}for(const s of project.sources)this.state.sources[projectId+':file:'+path.basename(s.path)]=bundle.files.find(f=>f.role==='source'&&path.basename(f.name)===path.basename(s.path))?.sourceId||bundle.sourceId;this.save();return {project,bank:this.status()};
 }
 close(){this.closed=true;clearTimeout(this.timer);clearTimeout(this.debounce);this.auth.cancel();this.save();}
}
module.exports={QuestionBank};
