'use strict';
const {questionSchema,diagramSchema,validateResult}=require('./codex.cjs');
const str={type:'string'},num={type:'number'},bool={type:'boolean'};
const arr=items=>({type:'array',items});
const obj=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const nullable=s=>({anyOf:[s,{type:'null'}]});
const en=(...values)=>({type:'string',enum:values});
const domains=arr(en('integer','algebra','geometry','combinatorics'));
const location=obj({regionIndex:nullable(num),description:str});
const origin=en('printed','handwritten','uncertain');
const xy=obj({x:num,y:num});
const lineMarks={
 shadedRegions:{...nullable(arr(obj({rings:arr(arr(xy)),color:str,origin:en('printed','constructed')}))),description:'Preserve printed shaded areas. Each ring is a closed boundary in diagram coordinates; sample curved boundaries densely (at least 48 samples for a full circle). Even-odd fill supports holes. Color is #RRGGBB; use original gray/color. Do not include handwriting. [] if none.'},
 equalAngleMarks:{...nullable(arr(obj({a:str,vertex:str,b:str,group:str,count:num,style:en('dot','arc'),origin:en('printed','constructed')}))),description:'Printed equal-angle or angle-bisector marks anchored inside angle a-vertex-b. Same group has same style/count (integer 1..3). Reproduce dots on equal-angle arcs with style=dot, not point names or floating text. Include both half-angles of an explicit bisector; never infer from appearance alone. [] if absent.'},
 lines:{...nullable(arr(obj({start:xy,end:xy,through:arr(str),label:str,dashed:bool,origin:en('printed','constructed')}))),description:'Visible portion of an infinite straight line, extending beyond named points on both sides. Preserve BC lines and lowercase l/ℓ labels; never substitute numeral 1. through references known named points only; [] for unnamed lines, using start/end without inventing named points. [] if absent.'},
 equalLengthMarks:{...nullable(arr(obj({from:str,to:str,group:str,count:num,position:nullable(num),origin:en('printed','constructed')}))),description:'Ticks anchored ON the segment from/to. Same group uses same count (integer 1..5); position is fraction 0.1..0.9 or null for midpoint. Preserve printed tick groups; exclude handwriting. Constructed figures also mark explicitly given equal sides, never equality inferred only from approximate coordinates. No floating text labels for ticks. [] if absent.'}
};
const dimensions={...nullable(arr(obj({from:nullable(str),to:nullable(str),start:nullable(xy),end:nullable(xy),label:str,origin,guideStyle:{...nullable(en('curved','straight')),description:'Default null or curved: outward curve touching the actual measured points directly, without straight extension lines or endpoint ticks. Use straight only if explicitly requested in additional redraw instructions.'},endpointStyle:en('tick','arrow','none')}))),description:'Printed length-range guides, separate from real edges. from/to are actual measured endpoints; start/end are approximate placement hints in the diagram coordinate system. For curved guides the renderer connects from/to directly and uses these hints only for the bulge direction; no straight extensions. preserve whole vs partial spans. Unknown endpoints remain null and require confirmation. No handwriting. Use [] if absent.'};
const angleLabelOverrides={...nullable(arr(obj({angleIndex:num,x:num,y:num,leader:bool}))),description:'Only for explicit additional redraw requests conflicting with default angle placement. Coordinates in diagram units, preserved by renderer; leader adds an arrow to the corresponding angle. Otherwise null. Never change an angle value to change its placement.'};
const condition=obj({text:str,source:en('body','diagram'),origin,location});
const observation=obj({kind:en('length_range','equal_length','angle','right_angle','parallel','point','other'),origin,text:str,targets:arr(str),start:nullable(str),end:nullable(str),group:nullable(str),span:en('whole','part','unknown'),location});
const observedDiagramSchema={...obj({...diagramSchema.properties,...lineMarks,dimensions,angleLabelOverrides,angleLabelLeaders:{...en('auto','always'),description:'Use auto. Keep angle number centers inside their angle and near the vertex. Slight overlap with diagram lines is explicitly allowed for angle labels. Unless an explicit additional redraw request is represented in angleLabelOverrides, never move them outside or add leaders/arrows. Legacy always values use the same inside-only policy.'},coordinateSystem:{...en('image_y_down','cartesian_y_up'),description:'Use image_y_down for source image positions: origin top left, x right, y down. Cartesian means y up. This is approximate drawing placement, not exact mathematical conditions.'}}),description:'Reproduce visible printed geometry as approximate positions and connections. Do not omit a visible diagram merely because exact mathematical coordinates were not solved. If unreadable, return null and explain in uncertainties.'};
const assessmentSchema=require('./difficulty-assessment.cjs').schema;
const recognition=obj({assessment:assessmentSchema,body:str,givens:arr(str),statementBox:arr(str),choices:arr(str),conditions:arr(condition),printedAnswer:str,printedSolution:str,domains,uncertainties:arr(obj({text:str,kind:en('reading','mathematical','mismatch'),location})),marks:arr(observation),observedDiagram:nullable(observedDiagramSchema)});
const layoutDocumentSchema=nullable(obj({version:{type:'integer',enum:[1]},features:arr(en(...require('./structured-layout.js').FEATURES)),nodes:arr(obj({id:str,parentId:nullable(str),type:en('paragraph','proofStep','box','figureGroup','figure','arrow'),origin,align:en('left','center','right'),widthRatio:num,figureId:nullable(str),diagram:nullable(observedDiagramSchema),inlines:arr(obj({kind:en('text','math','blank','reason'),text:{...str,description:'For kind=math, raw LaTeX only: no $ or $$ or parenthesis/bracket math delimiters. Normal JSON string escaping once. Math tokens are inline within the containing paragraph, including adjoining prose/particles. Center an entire proof row with node.align; do not make each formula a display block.'},label:str,border:en('none','box','underline'),widthEm:num,align:en('left','center','right'),origin}))}))}));
recognition.properties.layoutDocument={...layoutDocumentSchema,description:'null for ordinary questions. In the SAME recognition call detect multi-element boxes, inline blanks, multiple figures/arrows, text→figure→text, proof steps together. For compound layouts return ordered flat nodes; parentId records containment, array order records reading order, figureGroup uses relative widths. Paragraph inlines keep math and Korean particles together. Preserve printed content only; handwritten is excluded, uncertain remains flagged. Blank has empty text, original circled Korean label, real border, width in em, alignment; reason is a separate printed ①②③. A blank on a separate printed line belongs to its own paragraph/proofStep node; keep a sentence blank inline. An arrow node must carry its observed direction/symbol in text or math inlines; an empty arrow is incomplete and requires an uncertainty, never invent a direction. diagram reuses observed geometry, never a full proof crop. A necessary geometry-only source crop can reference materials by figureId=material:0 (zero-based materials index), or diagram for an explicitly selected sourceFigure; it remains a flagged original image, never a reconstructed proof. Do not infer obscured content.'};
recognition.required.push('layoutDocument');
recognition.properties.materials={...arr(obj({label:str,text:str,regionIndex:num,bounds:nullable(obj({x:num,y:num,width:num,height:num})),slot:str})),description:'Shared passage or independent method/process panels, NOT the target question diagram. Preserve each panel as a source crop. slot is before, after, or the exact body line:N/part:N slot where the source image occurs. line:N marks a single paragraph line break; legacy gap:N marks a blank-line break. Do not put every figure at the end. [] when absent.'};
recognition.properties.boxSlot={...str,description:'Placement of statementBox relative to body: before, after, or the exact body line:N/part:N slot. Keep the whole printed box and its internal item order. Use after only when the source really puts it there or position is unreadable.'};
recognition.properties.bodyBorder={...bool,description:'True only when a visible printed border surrounds the whole question, including its body, figures and choices. An inner statementBox is separate. False when there is no enclosing printed border.'};
recognition.properties.diagramSlot={...str,description:'Placement of the printed question diagram relative to body: before, after, or the exact body line:N/part:N slot. line:N counts single paragraph breaks; preserve prose before and after the image. Do not default every diagram to the bottom.'};
recognition.properties.choiceLayout={...en('auto','vertical'),description:'Printed answer choices: vertical when each choice occupies its own row, auto for multi-column or unknown. Preserve source choice order and text. This is layout only, never a mathematical condition.'};
recognition.properties.originalNumber={...nullable(str),description:'Exact printed source question number, e.g. 17, 서술형3, 3-(2). Preserve separately even when omitted from body. Do not use selection order or subquestion numbers. null if unreadable or absent.'};
recognition.properties.sourceNumbering=nullable(obj({section:en('objective','written','unknown'),total:nullable({type:'integer'}),objectiveCount:nullable({type:'integer'}),writtenCount:nullable({type:'integer'}),evidence:str,confirmed:bool,uncertain:bool}));
recognition.properties.sourceNumbering.description='Record the observed printed objective/written section and explicit exam total/section counts in this SAME request. Written questions can restart at 1: preserve their section. Never use work selection order or the last printed number as the exam total. A single crop cannot establish full-exam counts: use null unless an explicit printed total/header is visible. Quote that evidence; missing/covered/ambiguous numbering is uncertain, never guessed. confirmed must be false: only the teacher can confirm totals in source settings.';
recognition.required.push('sourceNumbering');
recognition.required.push('materials','boxSlot','bodyBorder','diagramSlot','choiceLayout','originalNumber');
const validation=obj({status:en('passed','failed','unverified'),evidence:arr(str),forwardSolution:str,crossCheck:str,independentCheck:bool,unverified:arr(str),scopeStatus:en('compatible','incompatible','unverified'),usedConcepts:arr(str),correctChoiceIndices:arr(num),rubric:nullable(obj({total:num,steps:arr(obj({description:str,points:num,criteria:str,partialCredit:str})),alternatives:str}))});
validation.properties.rubric.description='Six-point step grading only for proof or written_response questions where steps can be assessed. For single_choice, short answers and true/false selection use null. Still provide detailed explanation of every incorrect option. Do not fail a question for not having a rubric when it is not a written-response question.';
const constructedDimension=obj({...dimensions.anyOf[0].items.properties,origin:en('constructed','printed')});
const generatedDiagramSchema=obj({...diagramSchema.properties,...lineMarks,dimensions:{...nullable(arr(constructedDimension)),description:'Length guides for the new problem. Use origin=constructed, never claim these coordinates were observed in the source. [] if absent.'},angleLabelOverrides,angleLabelLeaders:en('auto','always'),coordinateSystem:en('cartesian_y_up')});
const solutionGuideSchema=require('./solution-guide-schema.cjs')(generatedDiagramSchema);
const generatedQuestionSchema=obj({...questionSchema.properties,solutionGuide:solutionGuideSchema,layoutDocument:layoutDocumentSchema,statementBox:arr(str),diagram:nullable(generatedDiagramSchema)});
const generated=obj({assessment:assessmentSchema,question:generatedQuestionSchema,questionType:en('single_value','all_solutions','proof','single_choice','multiple_choice','written_response','other'),difficulty:en('하','중하','중','중상','상'),changes:arr(str),validation});
const diagramRepairSchema=obj({reply:str,diagram:generatedDiagramSchema,validation,holdReason:str});
const schemas={
 solve:obj({assessment:assessmentSchema,reply:str,answer:str,solution:str,solutionGuide:solutionGuideSchema,questionType:generated.properties.questionType,validation,holdReason:str}),
 recognition:obj({reply:str,recognition}),
 generation:obj({reply:str,items:arr(generated),holdReason:str}),
 revision:obj({reply:str,correction:{type:'null'},item:nullable(generated),changes:arr(str),holdReason:str}),
 validation:obj({reply:str,reviews:arr(obj({targetId:str,validation})),holdReason:str})
};
const correctionSchema=obj({reply:str,correction:recognition,item:{type:'null'},changes:arr(str),holdReason:str});
const recoverySchema=obj({...schemas.solve.properties,recognitionCorrection:nullable(recognition),correctionEvidence:arr(str),notes:arr(str)});
const partialRecognitionSchemas={
 diagram:obj({reply:str,observedDiagram:nullable(observedDiagramSchema),uncertainties:recognition.properties.uncertainties}),
 text:obj({reply:str,originalNumber:recognition.properties.originalNumber,body:str,givens:arr(str),statementBox:arr(str),boxSlot:str,bodyBorder:bool,diagramSlot:str,choices:arr(str),conditions:arr(obj({...condition.properties,source:en('body')})),printedAnswer:str,printedSolution:str,uncertainties:recognition.properties.uncertainties})
};
const SCHEMA_VERSION='task-v9-stepwise-solution-guide';
function check(task,result,schema=schemas[task]){for(const holder of [result,...(result?.items||[]),result?.item,result?.recognition,result?.correction,result?.recognitionCorrection].filter(Boolean)){if(holder===result&&!schema.properties.assessment)continue;if(holder.assessment===undefined)holder.assessment=null;if(holder.assessment!==null){try{validateResult(holder.assessment,assessmentSchema);}catch(e){Object.defineProperty(holder,'assessmentIssue',{value:holder.assessment,enumerable:false,configurable:true});holder.assessment=null;}}} for(const q of [...(result?.items||[]).map(i=>i.question),result?.item?.question].filter(Boolean))if(q.layoutDocument===undefined)q.layoutDocument=null;for(const r of [result?.recognition,result?.correction,result?.recognitionCorrection])if(r){if(r.layoutDocument===undefined)r.layoutDocument=null;if(r.sourceNumbering===undefined)r.sourceNumbering=null;if(r.originalNumber===undefined)r.originalNumber=null;if(r.boxSlot===undefined)r.boxSlot='after';if(r.bodyBorder===undefined)r.bodyBorder=false;if(r.diagramSlot===undefined)r.diagramSlot='after';for(const m of r.materials||[])if(m.slot===undefined)m.slot='after';}if(schema===partialRecognitionSchemas.text){if(result.originalNumber===undefined)result.originalNumber=null;if(result.boxSlot===undefined)result.boxSlot='after';if(result.bodyBorder===undefined)result.bodyBorder=false;if(result.diagramSlot===undefined)result.diagramSlot='after';}if(schema.properties.solutionGuide&&result.solutionGuide===undefined)result.solutionGuide=null;for(const q of [...(result?.items||[]).map(i=>i.question),result?.item?.question].filter(Boolean))if(q.solutionGuide===undefined)q.solutionGuide=null;return validateResult(result,schema);}
module.exports={generatedDiagramSchema,diagramRepairSchema,partialRecognitionSchemas,schemas,correctionSchema,recoverySchema,SCHEMA_VERSION,check};
