import sourceReview from './source-review.cjs';
import {schoolSources} from './school-sources.js';
import {imageMime} from './bank-image.js';
import {paperFormSettings} from './paper-form-settings.js';
import {homeLayout,decorateDifficulty,recentSource,icon} from './home-view.js';
import searchModel from '../app/bank-search-filters.cjs';
import inventoryTools from '../app/source-inventory.cjs';
import examModel from '../app/bank-exam-model.cjs';
import {difficultyPanel,loadCompositionCandidates} from './composition-summary.js';
import D from '../app/difficulty-assessment.cjs';
import {difficultyStatistics} from './difficulty-statistics.js';
import {reviewEditor} from './review-editor.js';
import {leaveEdits,setEditGuard} from './edit-guard.js';
import {setQuestionSequence,navigationButtons} from './question-navigation.js';
import {scopeReview} from './scope-review.js';
import {attachScoreSlider} from './score-control.js';
import {createClient} from '@supabase/supabase-js';
import renderMathInElement from 'katex/contrib/auto-render';
import {sourceInfo,score,previewText,formatSourcePoints,originalNumberText} from './presentation.js';
import {createQuestionReader} from './question-renderer.js';
import {examEditor} from './exam-editor.js';
import {originalExams,cancelOriginalExams,restoreOriginalExam} from './original-exams.js';
import {createAccountPopoverController} from './account-popover.js';
import {loadSourceDifficulty} from './source-difficulty.js';
import {examLibrary} from './exam-library.js';
import {mockExams} from './mock-exams.js';
import {renderUsagePanel} from './usage-panel.js';
import calibration from '../app/bank-calibration.cjs';
import curriculum from '../app/curriculum.js';
import {captureInvitation,pendingInvitation,forgetInvitation,showInviteWelcome,showMemberManager} from './invitations.js';
const accountPopover=createAccountPopoverController();
const $=id=>document.getElementById(id),node=(tag,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;n.className=className;return n;};
let ratingSamples=[],ratingSamplesReady=false,reader,client,config,member,user,view,offset=0,filters={},chosen=[],previews=new Map();
const message=(text,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'';};
const action=(text,fn,primary=false)=>{const b=node('button',text,primary?'primary':'');b.addEventListener('click',async()=>{if(b.getAttribute('role')!=='tab')b.disabled=true;try{await fn();}catch(e){message(e.message||String(e),true);}finally{b.disabled=false;}});return b;};
const field=(parent,label,value='',type='text')=>{const wrap=node('label'),input=node(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;if(type==='checkbox')wrap.classList.add('checkbox-field');input.value=value??'';wrap.append(node('span',label),input);parent.append(wrap);return input;};
function taxonomySelect(parent,label,items,value){const wrap=node('label'),input=node('select');wrap.append(node('span',label),input);const blank=node('option','목록에서 선택 또는 아래에 직접 입력');blank.value='';input.append(blank);for(const item of items){const o=node('option',item.label);o.value=item.id;input.append(o);}input.value=value||'';parent.append(wrap);return input;}
async function rpc(name,args,{signal}={}){let query=client.rpc(name,args);if(signal)query=query.abortSignal(signal);const {data,error}=await query;if(error){const failure=Error(error.message);failure.code=error.code;failure.status=error.status;throw failure;}return data;}
async function rows(table,filters,{signal}={}){let query=client.from(table).select('*');if(signal)query=query.abortSignal(signal);for(const[k,v]of Object.entries(filters))query=query.eq(k,v);const{data,error}=await query;if(error)throw Error(error.message);return data;}
function clear(title){cancelOriginalExams($('view'));setEditGuard(null);screen++;for(const d of document.querySelectorAll('dialog'))d.close();for(const url of previews.values())URL.revokeObjectURL(url);previews.clear();view=$('view');view.className='';document.body.classList.toggle('home-route',tab==='home');if(['mine','members','admin'].includes(tab)){view.setAttribute('role','tabpanel');view.setAttribute('aria-labelledby','account-tab-'+tab);}else{view.removeAttribute('role');view.removeAttribute('aria-labelledby');}view.replaceChildren(...(title?[node('h2',title)]:[]));return view;}
const status=x=>({approved:'공동 검수 완료',shared_pending:'공동 미검수',private:'이전 비공개 자료'})[x]||x;
async function preview(file,parent){if(!file)return;const {data,error}=await client.from('bank_entries').select('*').eq('id',file.id).single();if(error)throw Error(error.message);if(!data.verified||data.size>12*1024*1024)throw Error('미리보기 크기 또는 상태를 확인하세요.');const chunks=[];for(let i=0;i<data.chunks;i++){const r=await client.storage.from('question-bank').download(`${config.spaceId}/${file.id}/${String(i).padStart(3,'0')}`);if(r.error)throw Error(r.error.message);chunks.push(r.data);}const bytes=await new Blob(chunks).arrayBuffer(),blob=new Blob([bytes],{type:imageMime(bytes)}),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==data.sha256||blob.size!==data.size)throw Error('미리보기 무결성 오류');if(!parent.isConnected)return;if(previews.has(file.id))URL.revokeObjectURL(previews.get(file.id));const url=URL.createObjectURL(blob);previews.set(file.id,url);const img=node('img');img.src=url;img.alt='문항 미리보기';parent.append(img);}
let tab='home',screen=0,dashboardCache=null,searchFilters={};
const tabs=[['home','홈','⌂'],['search','문항찾기','⌕'],['exam','시험지','▤'],['review','검수함','✓'],['schools','학교·시험지','▧']];
function math(parent){renderMathInElement(parent,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false},{left:'\\[',right:'\\]',display:true}],throwOnError:false,trust:false,strict:'ignore',maxExpand:100,maxSize:15});}
function renderText(parent,text,className='body'){const el=node('div',typeof text==='string'?text:JSON.stringify(text??''),className);parent.append(el);math(el);return el;}
function saveUi(){if(!user)return;sessionStorage.setItem('bank-ui:'+user.id,JSON.stringify({chosen,searchFilters,offset,tab,scroll:scrollY}));history.replaceState({...history.state,bank:true,offset,searchFilters,scroll:scrollY},'',location.href);}
async function navigate(next,{replace=false,restore=null}={}){if(!await leaveEdits()){if(restore)history.pushState({bank:true},'','#'+tab);return;}accountPopover.close();cancelOriginalExams($('view'));if(!restore)saveUi();tab=next;offset=restore?.offset||0;if(restore?.searchFilters)searchFilters=restore.searchFilters;if(!restore)history[replace?'replaceState':'pushState']({bank:true,offset:0},'','#'+next);nav();message('');screen++;await route(next);requestAnimationFrame(()=>scrollTo(0,restore?.scroll||0));}
async function route(next){if(next==='mock-exams'||next.startsWith('mock-exams/'))return mockExams({root:clear('실전모의고사 출제하기'),mockId:next.split('/')[1],user,config,rpc,reader,node,action,field,navigate,message,applyCalibration});if(next==='paper-forms'||next==='paper-forms/edit')return paperFormSettings({root:clear('시험지 폼 설정'),config,user,node,action,field,message,navigate,fromExam:next.endsWith('/edit')});if(next.startsWith('question/'))return detail(next.slice(9),true);if(next.startsWith('source/'))return sourceQuestions(decodeURIComponent(next.slice(7)));if(next.startsWith('exam-source/'))return selection('new',false,decodeURIComponent(next.slice(12)));if(next.startsWith('exam/'))return selection(next.split('/')[1],next.endsWith('/download'));return next==='home'?home():next==='exam'?examList():next==='originals'?originalsPage():next==='schools-name'?schools('name'):next==='schools'?schools('recent'):next==='register'?register():next==='members'?membersPage():next==='admin'?admin():listing();}
addEventListener('popstate',()=>{if(user&&member)navigate(location.hash.slice(1)||'home',{restore:history.state||{}}).catch(e=>message(e.message,true));});
addEventListener('pagehide',saveUi);
async function schools(order='recent'){const root=clear('학교·원본 시험지'),epoch=screen;difficultyStatistics({root,rpc,config,node,action});root.append(node('p','원본 자료별 등록 수와 검수 수입니다. 일부 등록을 전체 등록 완료로 간주하지 않습니다.','hint'));await schoolSources({root,rpc,config,node,action,sourceCard,order,isCurrent:()=>screen===epoch});}
async function originalsPage(){const root=clear('기출문제 복원하기'),epoch=screen;await originalExams({root,config,rpc,navigate,node,action,isCurrent:()=>screen===epoch&&tab==='originals'});}
function sourceCard(e,{difficulty=false,registration=false}={}){const s=e.source||{},row=action('',()=>navigate('source/'+encodeURIComponent(e.source_id)));row.className='recent-row';const text=node('div'),heading=node('strong',s.school||s.materialTitle||'출처 미입력');heading.append(node('small',' '+inventoryTools.sourceCountLabel(e),'source-count'));text.append(heading,node('span',[s.region,s.academicYear&&s.academicYear+'학년도',s.grade,s.semester,s.exam].filter(Boolean).join(' · ')),node('span',`등록 ${e.question_count}${e.progress?.expected_count?'/'+e.progress.expected_count:''}문항 · 검수 ${e.reviewed_count}문항 · ${{unknown:'완료 여부 미확인',partial:'일부 등록',in_progress:'등록 진행 중',complete:'등록 완료 (사용자 확인)'}[e.progress?.status]||'완료 여부 미확인'}`),node('small',`${(e.contributors||[]).join(', ')} · ${registration?(e.last_registered_at?new Date(e.last_registered_at).toLocaleDateString('ko-KR')+' 등록':'등록 시각 미확인'):new Date(e.updated_at).toLocaleDateString('ko-KR')+' 수정'}`));row.append(text);if(difficulty)loadSourceDifficulty(rpc,config.spaceId,e.source_id,e.difficulty).then(value=>{if(row.isConnected)heading.append(node('small',' ('+value+')','source-difficulty'));}).catch(()=>{if(row.isConnected)heading.append(node('small',' (난이도 조회 실패)','source-difficulty'));});return row;}
async function sourceQuestions(id){const ratingEpoch=screen;await ensureRatingSamples();if(ratingEpoch!==screen)return;const root=clear('원본 시험지 문항'),epoch=screen;root.prepend(action('학교·시험지 목록',()=>navigate('schools')));const progress=await rpc('bank_source_progress_get',{s:config.spaceId,k:id});const form=node('details','','panel');form.append(node('summary','시험지 등록 진행 상태'));const total=field(form,'원본 전체 문항 수 (모르면 빈칸)',progress.expected_count??'','number'),stateInput=node('select');for(const [value,label]of [['unknown','완료 여부 미확인'],['partial','일부 등록'],['in_progress','등록 진행 중'],['complete','등록 완료 (직접 확인)']]){const o=node('option',label);o.value=value;stateInput.append(o);}stateInput.value=progress.status||'unknown';form.append(stateInput,action('진행 상태 저장',async()=>{await rpc('bank_source_progress_save',{s:config.spaceId,k:id,n:total.value?Number(total.value):null,st:stateInput.value,expected:progress.version||0});await sourceQuestions(id);}));root.append(form);let start=0;const list=node('div','','cards');root.append(list);const more=action('다음 문항',load);more.hidden=true;root.append(more);const ordered=await sourceReview.loadSourceReview(rpc,config.spaceId,id,()=>epoch===screen);if(!ordered)return;setQuestionSequence(ordered);function load(){if(epoch!==screen)return;const data=ordered.slice(start,start+50);for(const c of data)list.append(questionCard(c));start+=data.length;more.hidden=start>=ordered.length;}load();}
const iconSvg=icon;
function mainTab(){if(tab.startsWith('paper-forms'))return 'home';return tab.startsWith('exam/')||tab.startsWith('exam-source/')?'exam':tab.startsWith('source/')||(tab==='originals'||tab==='schools-name')?'schools':tab.startsWith('question/')?'search':tab;}
function nav(){for(const b of document.querySelectorAll('[data-account-tab]')){const selected=b.dataset.accountTab===tab;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;}const first=document.querySelector('[data-account-tab]');if(first&&!document.querySelector('[data-account-tab][aria-selected="true"]'))first.tabIndex=0;const n=$('nav');n.setAttribute('aria-label','주 메뉴');n.replaceChildren();for(const [id,label,icon]of tabs){const b=action(label,()=>navigate(id));const glyph=node('span','','nav-icon');glyph.append(iconSvg(id));b.prepend(glyph);b.setAttribute('aria-label',label);b.setAttribute('aria-current',mainTab()===id?'page':'false');n.append(b);}}
function sectionTitle(root,title,subtitle){root.append(node('h3',title,'section-title'));if(subtitle)root.append(node('p',subtitle,'hint'));}
async function home(){const root=clear(''),epoch=screen;root.classList.add('home');
 const {statNodes,statsPanel,difficulty,recent}=homeLayout({root,node,action,navigate});
 try{const value=await rpc('bank_home_summary',{s:config.spaceId});if(epoch!==screen)return;
 const dash=value.dashboard,summary=dash?.difficulty;
 if(dash?.summaryVersion!=='stored-web-v1'||!summary||!Number.isSafeInteger(summary.total)||summary.total!==dash.questions||Object.values(summary.counts).reduce((a,b)=>a+b,0)!==summary.total||!Number.isSafeInteger(summary.killerCount)||summary.killerCount<0||summary.killerCount>summary.counts.high)throw Error('저장 집계 응답을 확인할 수 없습니다.');
 for(const [key,card]of Object.entries(statNodes)){if(!Number.isSafeInteger(dash[key])||dash[key]<0)throw Error('저장 집계 응답을 확인할 수 없습니다.');card.querySelector('strong').textContent=dash[key].toLocaleString('ko-KR');}
 const panel=difficultyPanel(node,[],'난이도별 등록 문항',key=>{searchFilters.search={compositionBand:key};return navigate('search');},summary);decorateDifficulty(panel,summary,node,key=>{searchFilters.search={compositionBand:key};return navigate('search');});difficulty.replaceChildren(panel);
 const names=value.recentSchools,line=node('small',names.join(' · '),'recent-school-names');line.title=names.join(' · ');statNodes.schools.append(line);recent.replaceChildren();for(const e of value.recentSources)recent.append(recentSource(e,{node,action,navigate,rpc,spaceId:config.spaceId}));if(!value.recentSources.length)recent.append(node('p','등록된 원본 시험지가 없습니다.','hint'));
 }catch(e){if(epoch===screen){for(const card of Object.values(statNodes))card.querySelector('strong').textContent='—';statsPanel.append(node('p','운영 현황을 불러오지 못했습니다. '+e.message,'hint'));difficulty.replaceChildren(node('p','난이도 현황 조회 실패: '+e.message,'error'));recent.replaceChildren(node('p','최근 시험지 조회 실패: '+e.message,'error'));}}
}
// Refresh the home read model when the user returns to this window after an upload.
addEventListener('focus',()=>{if(user&&member&&tab==='home'&&!document.hidden)home().catch(e=>message(e.message,true));});

function register(){const root=clear('문항 등록');root.append(node('p','문제공방 PC 앱에서 편집한 문항을 공동 문제은행에 등록합니다.','lead'));const list=node('ol','','steps');for(const text of ['PC에서 문제공방을 열고 문항을 인식·편집합니다.','문제은행 저장에서 공통 출처 정보를 확인합니다. 모르는 정보는 비워 둘 수 있습니다.','등록할 문항을 선택한 뒤 공동 저장합니다. 업로드 완료 상태를 확인하세요.','이 사이트의 내문항에서 같은 계정으로 등록 결과를 확인합니다.'])list.append(node('li',text));root.append(list,node('p','웹에서 검색·선택·검수하고 시험지를 구성하여 HWPX·DOCX·PDF로 내려받을 수 있습니다.','hint'),action('내문항에서 등록 확인',()=>navigate('mine'),true));}
function toggleChosen(c){queueMicrotask(saveUi);const i=chosen.findIndex(x=>x.revisionId===c.revision_id);if(i>=0){chosen.splice(i,1);return false;}if(chosen.some(x=>x.questionId===c.question_id))throw Error('같은 문항은 한 버전만 담을 수 있습니다. 시험지 탭에서 기존 버전을 제외해 주세요.');const s=sourceInfo(c);chosen.push({questionId:c.question_id,revisionId:c.revision_id,label:[s.school||'문항',s.number&&originalNumberText(s.number)].filter(Boolean).join(' · ')});return true;}
async function previewDialog(c){const dialog=node('dialog','','preview-dialog'),header=node('div','','dialog-heading');header.append(node('h2','문제 미리보기'),action('닫기',()=>dialog.close()));dialog.append(header);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();const loading=node('p','미리보기를 불러오는 중입니다.');dialog.append(loading);try{const rendered=await reader.render(c.revision_id);dialog.append(rendered.element);loading.remove();}catch(e){loading.textContent='미리보기 실패: '+e.message;}}
async function ensureRatingSamples(){if(ratingSamplesReady)return;const accountId=user?.id,spaceId=config.spaceId;try{const samples=await rpc('bank_rating_samples',{s:spaceId});if(user?.id===accountId&&config.spaceId===spaceId){ratingSamples=samples;ratingSamplesReady=true;}}catch{if(user?.id===accountId&&config.spaceId===spaceId)ratingSamples=[];}}
function applyCalibration(c){const m=c.metadata||{},d=m.difficulty||{},ai=D.currentAI(c);if(!ai)return;const result=calibration.calibrate({rawScore:ai.score,confirmedScore:c.confirmed?.difficulty??d.userScore,model:ai.provenance?.model||m.analysis?.model,criteriaVersion:ai.criteriaVersion,grade:m.source?.grade,scopeKey:d.scope,type:m.content?.responseType},ratingSamples);if(result.families){d.calibrationSuggestion=result;}}
function questionCard(c){applyCalibration(c);const src=sourceInfo(c),card=node('article','','card');card.append(node('span',status(c.visibility),'badge '+c.visibility),node('h3',src.school||'출처 미확인'),node('p',[src.year&&src.year+'학년도',src.grade,src.term,src.exam,src.number&&originalNumberText(src.number)].filter(Boolean).join(' · ')||'출처 정보를 아직 입력하지 않았습니다.','source-line'));
 const peek=node('div','','question-peek');renderText(peek,previewText(c.content?.body),'math-snippet');for(const invalid of peek.querySelectorAll('.katex-error'))invalid.replaceWith(node('span','[수식은 미리보기에서 확인]')); if(c.revision_conflict)card.append(node('p','서로 갈라진 수정본이 있습니다. 최신본을 비교하기 전에는 자동 구성에서 제외합니다.','error'));card.append(peek);const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();reader.render(c.revision_id).then(r=>{if(peek.isConnected){peek.replaceChildren(r.element);const expand=action('전체 펼치기',()=>{peek.classList.toggle('expanded');expand.textContent=peek.classList.contains('expanded')?'접기':'전체 펼치기';});peek.after(expand);}}).catch(e=>{if(peek.isConnected)peek.append(node('p','그림·전체 내용 확인 실패: '+e.message,'hint'));});},{rootMargin:'100px'});observer.observe(peek);
 const meta=node('dl','','question-meta');for(const [label,value]of [['단원',src.unit||'미분류'],['출제유형',src.types.length?src.types.map(t=>t.displayName).join(' · ')+(src.typeStatus==='suggested'?' · 추천':''):'미확인'],['응답 형식',c.metadata?.content?.responseType||'미확인'],['원문 배점',src.points==null?'미확인':src.points+'점'],['난이도',score(c)],['등록자',c.owner_email||'미확인']])meta.append(node('dt',label),node('dd',value));card.append(meta);if(src.tags.length)card.append(node('p',src.tags.slice(0,5).join(' · '),'tags'));
 if(src.typeReason||src.types.some(t=>t.evidence)){const why=node('details');why.append(node('summary','출제유형 추천 근거'),node('p',[src.typeReason,...src.types.map(t=>t.evidence)].filter(Boolean).join(' · '),'hint'));card.append(why);}
 if(c.visibility!=='approved'){const reasons=['문항 내용을 확인하고 검수 저장을 눌러 주세요.'];const optional=[];if(!src.number)optional.push('원문 번호 미확인');if(!src.unit)optional.push('소단원 미분류');if(!c.confirmed?.scopeEvidence)optional.push('범위 자동 출제용 풀이 개념 미확인');if(c.metadata?.reviews?.diagram?.status==='partial')optional.push('도형 일부 미확인');const why=node('details');why.append(node('summary','공동 검수에 필요한 확인'),node('p',reasons.join(' · '),'hint'));if(optional.length)why.append(node('p','추가 확인 권장: '+optional.join(' · '),'hint'));card.append(why);}
 const assessment=D.currentAI(c),reason=assessment?.reason||(!assessment?'새 기준 난이도 평가가 필요합니다.':null);if(reason){const why=node('details');why.append(node('summary',assessment?'새 기준 난이도 근거':c.metadata.difficulty.aiScore==null?'난이도가 미평가인 이유':'AI 난이도 추천 근거'),node('p',reason,'hint'));card.append(why);}
 const buttons=node('div','','card-actions'),add=action(chosen.some(x=>x.revisionId===c.revision_id)?'담기 취소':'시험지에 담기',()=>{const added=toggleChosen(c);add.textContent=added?'담기 취소':'시험지에 담기';add.setAttribute('aria-pressed',String(added));message(`시험지에 ${chosen.length}문항을 담았습니다.`);},true);add.setAttribute('aria-pressed',String(chosen.some(x=>x.revisionId===c.revision_id)));buttons.append(action('상세 보기',()=>detail(c.revision_id)),action('미리보기',()=>previewDialog(c)),add);card.append(buttons);return card;}
async function listing(reset=false){const ratingEpoch=screen;await ensureRatingSamples();if(ratingEpoch!==screen)return;if(reset)offset=0;const mode=tab,root=clear(mode==='review'?'검수함':mode==='mine'?'내문항':'문항 찾기'),epoch=screen;const effective=searchModel.clean(searchFilters[mode]);searchFilters[mode]={...effective};if(mode==='mine')effective.owner=user.email;if(mode==='review')effective.status='shared_pending';root.append(node('p',mode==='review'?(member.role==='teacher'?'내가 등록한 미검수 문항과 검수 요청 상태를 확인합니다. 공동 문항의 승인 권한은 검수자에게 있습니다.':'공동 검수를 기다리는 문항입니다. 상세보기에서 내용을 확인하고 승인하세요.'):mode==='mine'?'현재 계정으로 등록한 문항입니다. 공동 미검수·검수 완료 상태를 확인하세요.':'동료가 공유한 문항을 검색하고 시험지에 담으세요.','lead'));
 if(mode==='review')root.querySelector('.lead').textContent='공동 미검수 문항입니다. 문항을 확인하고 검수 저장을 누르면 완료됩니다. 완료 후에도 다시 수정할 수 있습니다.';
 const form=node('form','','search-form'),top=node('div','','search-top'),query=field(top,'검색어',effective.text||'');query.placeholder='학교, 단원, 문제 내용 검색';const submit=node('button','검색','primary');submit.type='submit';submit.disabled=true;top.append(submit);form.append(top);const advanced=node('details','','advanced'),summary=node('summary','상세 필터');advanced.open=true;advanced.append(summary);form.setAttribute('aria-busy','true');
 const inputs={text:query},fields=node('div','','filters');for(const[k,label]of searchModel.fields){inputs[k]=taxonomySelect(fields,label,[],effective[k]);inputs[k].firstChild.textContent='전체';inputs[k].setAttribute('aria-label',label);inputs[k].disabled=true;}
 inputs.compositionBand=taxonomySelect(fields,'상·중·하 분류',Object.entries(searchModel.difficultyLabels).map(([id,label])=>({id,label})),effective.compositionBand);inputs.compositionBand.firstChild.textContent='전체';inputs.compositionBand.setAttribute('aria-label','상·중·하 분류');
 if(effective.compositionBand){advanced.open=true;root.append(node('p',searchModel.difficultyLabels[effective.compositionBand]+' 문항만 표시 · 최종 점수 기준','hint'),action('난이도 필터 해제',()=>{delete searchFilters[mode].compositionBand;return listing(true);}),action('홈으로',()=>navigate('home')));}
 const sw=node('label'),select=node('select');select.setAttribute('aria-label','검수 상태');for(const[v,label]of [['','검수 상태 전체'],['approved','공동 검수 완료'],['shared_pending','공동 미검수']]){const o=node('option',label);o.value=v;select.append(o);}select.value=effective.status||'';select.disabled=mode==='review';sw.append(node('span','검수 상태'),select);fields.append(sw);advanced.append(fields);form.append(advanced);form.addEventListener('submit',e=>{e.preventDefault();const next={};for(const[k,input]of Object.entries(inputs))if(input.value.trim())next[k]=input.value.trim();if(select.value&&mode!=='review')next.status=select.value;searchFilters[mode]=next;listing(true).catch(e=>message(e.message,true));});inputs.compositionBand.addEventListener('change',()=>form.requestSubmit());root.append(form,action('목록·필터 새로고침',()=>listing()));
 let all;try{all=await loadCompositionCandidates(rpc,config.spaceId);}catch(e){if(epoch===screen){form.setAttribute('aria-busy','false');root.append(node('p','필터·문항 조회 실패: '+e.message+' · 목록·필터 새로고침으로 다시 확인하세요.','error'));}return;}if(epoch!==screen)return;
 const available=searchModel.options(all),removed=[];for(const[k,label]of searchModel.fields){if(effective[k]&&!available[k].includes(String(effective[k]))){removed.push(label);delete effective[k];delete searchFilters[mode][k];}const input=inputs[k];input.replaceChildren();const whole=node('option','전체');whole.value='';input.append(whole);for(const value of available[k]){const option=node('option',value);option.value=value;input.append(option);}input.value=effective[k]||'';input.disabled=false;}submit.disabled=false;form.setAttribute('aria-busy','false');if(removed.length)root.append(node('p','현재 접근 가능한 자료에 없는 필터를 전체로 해제했습니다: '+removed.join(', '),'hint'));
 const results=node('div','','results'),cards=node('div','','cards');results.append(node('p','문항을 불러오는 중입니다.','hint'));root.append(results);const searched=effective.text?await loadCompositionCandidates((name,args)=>rpc(name,{...args,filters:{text:effective.text}}),config.spaceId):all;
 const matched=sourceReview.orderReviewGroups(searched.filter(c=>searchModel.matches(c,effective))),data=matched.slice(offset,offset+50);if(epoch!==screen)return;setQuestionSequence([],async()=>matched);results.replaceChildren(node('p',`${matched?'전체 '+matched.length+'문항 · ':''}${offset?offset+1+'번째부터 · ':''}${data.length}개 표시 · 시험지 ${chosen.length}문항`,'hint'));for(const c of data)cards.append(questionCard(c));results.append(cards);if(!data.length)results.append(node('div','조건에 맞는 문항이 없습니다. 검색 조건이나 현재 계정을 확인하세요.','empty'));const pager=node('div','','actions');if(offset)pager.append(action('이전 50개',()=>{offset=Math.max(0,offset-50);return listing();}));if(matched?offset+data.length<matched.length:data.length===50)pager.append(action('다음 50개',()=>{offset+=50;return listing();}));results.append(pager);}

async function detail(id,routed=false){if(!routed)return navigate('question/'+id);const ratingEpoch=screen;await ensureRatingSamples();if(ratingEpoch!==screen)return;const epoch=screen;const list=await rows('bank_catalog',{revision_id:id});if(epoch!==screen)return;if(!list[0])throw Error('문항 접근 권한이 없습니다.');const c=list[0];applyCalibration(c);const r=(await rows('bank_revisions',{id}))[0];if(epoch!==screen)return;const root=clear('문항 상세'),detailScreen=screen,isCurrent=()=>screen===detailScreen,content=c.content||{};const scoreSummary=node('p',score(c));root.append(node('span',status(r.visibility),'badge'),scoreSummary);root.prepend(action('뒤로 · 목록',()=>history.state?.bank&&history.length>1?history.back():navigate('search',{replace:true})));const source=sourceInfo(c);root.querySelector('h2').after(node('p',[source.school,source.year,source.grade,source.term,source.number&&originalNumberText(source.number),source.unit].filter(Boolean).join(' · '),'hint'));try{const rendered=await reader.render(id,{answers:true});if(isCurrent())root.append(rendered.element);}catch(e){if(!isCurrent())return;root.append(node('p','원본 표시 실패: '+e.message,'error'));renderText(root,content.body);}if(!isCurrent())return;
 root.append(node('p','원문 배점: '+formatSourcePoints(source.points)+' · 난이도 점수와 별개입니다.','hint source-points-summary'));
 root.append(node('p',`앱에서 저장한 검수 기록: ${c.metadata?.management?.review||'미확인'} · 인식 확인: ${c.metadata?.reviews?.recognition?.confirmed===true?'완료':'미확인'}. 공동 검수 상태와 별도로 보존됩니다.`,'hint'));
 if(r.reviewer_id){try{root.append(node('p','공동 검수자: '+(await rpc('bank_review_identity',{r:id})||'확인 필요'),'hint'));}catch{root.append(node('p','공동 검수자 ID: '+r.reviewer_id,'hint'));}}
 if(!isCurrent())return;const scopeControl=scopeReview({catalog:c,content,root,node,field,action,rpc,onSaved:async()=>message('개념·풀이 검수를 저장했습니다.')});
 await reviewEditor({root,c,r,user,node,field,action,rows,rpc,message,scopeControl,isCurrent,onEvidenceSaved:patch=>{c.confirmed={...c.confirmed,...patch};scoreSummary.textContent=score(c);const points=root.querySelector('.source-points-summary');if(points)points.textContent='원문 배점: '+formatSourcePoints(sourceInfo(c).points)+' · 난이도 점수와 별개입니다.';},ratingsChanged:async()=>{ratingSamples=await rpc('bank_rating_samples',{s:config.spaceId});applyCalibration(c);}});
 if(!isCurrent())return;const questionNav=await navigationButtons({id,parent:root,node,action,isCurrent,open:next=>navigate('question/'+next.revision_id)});if(!isCurrent())return;if(questionNav){questionNav.classList.add('question-navigation-fixed');root.classList.add('has-question-navigation');}
 if(member.role==='owner')root.append(action('문항 실제 삭제',async()=>{
  if(!await leaveEdits())return;
  const plan=await rpc('bank_question_delete_plan',{q:c.question_id});
  if(plan.blocked)throw Error(plan.reason);
  const target=[source.school,source.number&&originalNumberText(source.number)].filter(Boolean).join(' · ')||'선택한 문항';
  if(!confirm(target+'\n이 문항을 삭제하시겠습니까?\n문항과 해당 버전이 삭제됩니다. 공유 원본 파일은 보존됩니다.'))return;
  const {data,error}=await client.functions.invoke('bank-delete-question',{body:{questionId:c.question_id,token:plan.token}});if(error)throw Error(error.message);if(!data?.complete)throw Error(data?.error||'삭제가 끝나지 않았습니다. 다시 확인하세요.');reader.clear();await navigate('search');message('문항과 전용 파일을 삭제했습니다.');
 }));
}
function download(name,value){const a=node('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function examList(){const root=clear('내 시험지');await examLibrary({root,user,config,rpc,preview,navigate,message,node,action});}
async function selection(examId,downloadFocus=false,sourceExam=null){const root=clear(sourceExam?'기출 시험지 구성':'시험지 만들기'),epoch=screen;const context={root,examId,downloadFocus,sourceExam,chosen,reader,rpc,rows,config,user,applyCalibration,save:saveUi,navigate,message,node,action,field};if(sourceExam){root.dataset.sourceExam=sourceExam;await restoreOriginalExam({root,node,action,rpc,rows,reader,isCurrent:()=>screen===epoch&&tab==='exam-source/'+encodeURIComponent(sourceExam)},loading=>examEditor({...context,...loading}));}else await examEditor(context);}
async function admin(){if(member.role!=='owner')throw Error('관리자 전용입니다.');const root=clear('회원·사용량 관리'),form=node('div','','form'),email=field(form,'승인할 Google 이메일');form.append(action('사용 승인',async()=>{if(!confirm(email.value+' 계정의 공동 은행 참여를 승인할까요?'))return;await rpc('bank_invite',{s:config.spaceId,email_address:email.value.trim(),enabled_value:true});await admin();}));root.append(form,action('멤버 관리',()=>navigate('members')),action('문항 관리 → 일괄 업데이트',maintenanceAdmin));for(const m of await rows('bank_members',{space_id:config.spaceId})){const row=node('div','','row');row.append(node('span',`${m.email} · ${m.role} · ${m.enabled?'승인':'차단'}`));if(m.role!=='owner'){row.append(action(m.enabled?'차단':'승인',async()=>{if(!confirm('이 회원의 접근 권한을 변경할까요?'))return;await rpc('bank_invite',{s:config.spaceId,email_address:m.email,enabled_value:!m.enabled});await admin();}),action(m.role==='reviewer'?'일반 교사로':'검수자로 지정',async()=>{if(!confirm('검수자는 공동 값 승인 권한을 갖습니다. 역할을 변경할까요?'))return;await rpc('bank_set_role',{s:config.spaceId,email_address:m.email,new_role:m.role==='reviewer'?'teacher':'reviewer'});await admin();}));}root.append(row);}
 await renderUsagePanel({root,rpc,node,action,config});
}
async function membersPage(){return showMemberManager({client,config,member,clear,node,field,action,rpc,rows,message,navigate});}

async function maintenanceAdmin(){
 if(member.role!=='owner')throw Error('관리자 전용입니다.');const root=clear('문항 관리 → 일괄 업데이트');
 root.append(node('p','처리는 관리자 PC의 문제공방 앱에서 실행합니다. 앱의 문제은행 연결 설정 → 문항 관리 → 일괄 업데이트에서 대상을 선택하고 샘플을 확인하세요. 앱을 닫으면 멈추며 작업을 만든 PC에서 재개할 수 있습니다.','hint'),action('작업 기록 새로고침',maintenanceAdmin),action('관리 화면',admin));
 const {data:jobs,error}=await client.from('bank_maintenance_jobs').select('*').eq('space_id',config.spaceId).order('created_at',{ascending:false}).limit(50);if(error)throw Error(error.message);
 for(const j of jobs.sort((a,b)=>b.created_at.localeCompare(a.created_at))){const box=node('section','','panel');box.append(node('h3',(j.spec.undoOf?'되돌리기':'일괄 업데이트')+' · '+j.status),node('p',new Date(j.created_at).toLocaleString()+' · '+JSON.stringify(j.progress.counts||{})),node('p',(j.spec.rules||[]).map(r=>r.title+' ('+r.version+')').join(' / '),'hint'));for(const i of j.progress.items||[])if(i.error)box.append(node('p',i.questionId+' · '+i.error,'error'));const records=await rows('bank_maintenance_items',{job_id:j.id});for(const item of records){const detail=node('details');detail.append(node('summary',item.question_id+' · '+item.status),node('p','기준 '+item.base_id+' → 결과 '+item.result_id),node('pre',JSON.stringify(item.report,null,2)));box.append(detail);}root.append(box);}if(!jobs.length)root.append(node('p','아직 저장된 일괄 작업이 없습니다.'));
}
async function session(){
 cancelOriginalExams($('view'));captureInvitation();const {data,error}=await client.auth.getSession();if(error)throw error;const previous=user?.id;user=data.session?.user;member=null;if(previous!==user?.id){reader?.clear();chosen=[];dashboardCache=null;searchFilters={};if(user){try{const saved=JSON.parse(sessionStorage.getItem('bank-ui:'+user.id)||'{}');chosen=saved.chosen||[];searchFilters=saved.searchFilters||{};}catch{}}} accountPopover.detach();$('account').replaceChildren();$('workspace').hidden=true;$('welcome').hidden=true;$('welcome').replaceChildren();
 const login=async()=>{const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{prompt:'select_account'}}});if(error)throw error;};
 const logout=async()=>{await client.auth.signOut({scope:'local'});await session();};
 if(!user){screen++;$('view').replaceChildren();if(pendingInvitation()){showInviteWelcome({node,action,login,logout,client,rpc,session,message,user});message('초대를 확인하려면 본인 Google 계정으로 로그인하세요.');}else{$('account').append(action('Google로 로그인',login,true));message('관리자가 승인한 본인 Google 계정으로 로그인하세요.');}return;}
 const profile=node('details','','profile'),summary=node('summary','내 계정'),menu=node('div','','profile-menu');summary.setAttribute('aria-label','내 계정 메뉴');profile.append(summary,menu);menu.append(node('strong','연결된 계정'),node('p',user.email),action('로그아웃',async()=>{await client.auth.signOut({scope:'local'});chosen=[];dashboardCache=null;await session();}));$('account').append(profile);accountPopover.attach(profile);
 try{member=await rpc('bank_join',{s:config.spaceId});}catch(e){screen++;$('view').replaceChildren();if(pendingInvitation()){showInviteWelcome({node,action,login,logout,client,rpc,session,message,user});message('초대를 수락하거나 관리자 승인을 기다려 주세요.');}else message('로그인은 되었지만 공동 문제은행 이용 승인이 필요합니다. 관리자에게 이 이메일을 알려 주세요.\n'+e.message,true);return;}
 if(pendingInvitation()){forgetInvitation();message('이미 문제은행 회원입니다. 초대 없이 이용할 수 있습니다.');}
 menu.append(action('내문항',()=>{return navigate('mine');}));menu.prepend(node('span',({owner:'관리자',reviewer:'검수자',teacher:'일반 교사'})[member.role]||'교사','badge'));if(member.role==='owner'){menu.append(action('멤버 관리',()=>{return navigate('members');}));menu.append(action('관리',()=>{return navigate('admin');}));}const accountTabs=node('div','','account-tabs');accountTabs.setAttribute('role','tablist');accountTabs.setAttribute('aria-label','계정 하위 메뉴');for(const b of [...menu.querySelectorAll('button')]){if(b.textContent==='로그아웃'){b.classList.add('account-logout');continue;}b.setAttribute('role','tab');const id={'내문항':'mine','멤버 관리':'members','관리':'admin'}[b.textContent];b.dataset.accountTab=id;b.id='account-tab-'+id;b.setAttribute('aria-controls','view');accountTabs.append(b);}menu.append(accountTabs,menu.querySelector('.account-logout'));$('view').setAttribute('tabindex','-1');accountTabs.addEventListener('keydown',async e=>{const buttons=[...accountTabs.children];let index=buttons.indexOf(document.activeElement);if(index<0)return;if(e.key==='ArrowRight')index=(index+1)%buttons.length;else if(e.key==='ArrowLeft')index=(index+buttons.length-1)%buttons.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=buttons.length-1;else return;e.preventDefault();await navigate(buttons[index].dataset.accountTab);(profile.open?buttons[index]:summary).focus();});$('workspace').hidden=false;ratingSamples=[];ratingSamplesReady=false;const target=location.hash.slice(1);await navigate(/^(home|paper-forms(?:\/edit)?|search|exam|exam\/new|exam\/[a-f0-9-]{36}(?:\/download)?|review|mine|members|admin|schools|schools-name|originals|exam-source\/[^/]+|source\/[^/]+|question\/[a-f0-9-]+)$/.test(target)?target:'home',{replace:true,restore:history.state||{}});
}
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(member&&user)navigate('home').catch(e=>message(e.message,true));});
try{config=await(await fetch('config.json',{cache:'no-store'})).json();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(config.url)||!config.publishableKey)throw Error('공개 연결 설정이 필요합니다.');client=createClient(config.url,config.publishableKey,{auth:{flowType:'pkce',storage:sessionStorage,persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});reader=createQuestionReader(client,config);await session();client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'||event==='SIGNED_IN'&&!user)setTimeout(()=>session().catch(e=>message(e.message,true)),0);});}catch(e){message('연결을 시작하지 못했습니다. '+e.message,true);}
