import {questionArticle} from './print-question.js';
import {questionFragmenter} from './question-fragments.js';
import {formLoader,beginFormEdit,savedPaperForm} from './paper-form-settings.js';
import formModel from './exam-form-model.cjs';
import {fitFormTitles,isMock,formClass,formHeader,formIntro,formFooter,measureForm,answerHeader,measureAnswer} from './exam-form.js';
import {difficultyMapping,countsText,loadCompositionCandidates,compositionFailureText,paperComposition,paperCompositionText} from './composition-summary.js';
import {generationProgress,waitForGeneration} from './generation-progress.js';
import {composeInWorker} from './exam-composition-task.js';
import {bodyFontRange,validateBodyFont} from './exam-typography.js';
import {examSession} from './exam-session.js';
import {setEditGuard} from './edit-guard.js';
import inventoryTools from '../app/source-inventory.cjs';
import originalQuestion from './original-question.cjs';
import model from '../app/bank-exam-model.cjs';
import curriculum from '../app/curriculum.js';
import searchFilters from '../app/bank-search-filters.cjs';
import {mathText} from './question-renderer.js';
import {appendSolutionPages} from './solution-flow.js';
import {scopeTree} from './scope-tree.js';
import {matchingSourceSchools} from './exam-scope-schools.js';
import {sourceLabel,sourceInfo,formatSourcePoints} from './presentation.js';
import {examPageHeader,pageContentHeight} from './standard-form.js';
export {examPageHeader,pageContentHeight} from './standard-form.js';
import textTools from '../app/question-text.cjs';
const MM=96/25.4;
import {figureScalePercent,scaleQuestionFigures} from './figure-scale.js';
export {figureScalePercent,scaleQuestionFigures} from './figure-scale.js';

export async function examEditor(ctx){
 const {root,examId,downloadFocus,sourceExam,chosen,reader,rpc,rows,config,user,applyCalibration,save,navigate,message,node,action,field}=ctx;
 root.classList.add('exam-editor');
 const defaultPrint={paper:'A4',columns:2,marginsMm:{top:20,right:15,bottom:18,left:15}};
 const localKey=id=>'bank-exam-draft:'+user.id+':'+id,newKey='bank-exam-new:'+user.id;
 const parseLocal=key=>examSession.read(user.id,key===newKey?'new':key.slice(localKey('').length));
 let draft,initialLocal=null,staleLocal=false;
  if(examId==='new'){
   const sourceWorking=sourceExam?parseLocal(newKey):null;
   initialLocal=sourceExam?(sourceWorking?.originalExam?.sourceId===sourceExam?sourceWorking:null):parseLocal(newKey)||parseLocal('bank-exam:'+user.id);
  // An older release kept its last saved paper under the generic key. A new
  // paper must never silently write back to that existing server revision.
  if(initialLocal?.version>0)initialLocal={...initialLocal,id:crypto.randomUUID(),version:0,status:'draft',copiedFrom:{id:initialLocal.id,version:initialLocal.version}};
  draft=initialLocal||{id:crypto.randomUUID(),version:0,title:'수학 시험지',answerMode:'quick',status:'draft',rules:{},items:[]};
  if(!initialLocal){try{const saved=savedPaperForm(config,user);if(saved)draft.paperForm=structuredClone(saved);}catch(e){message('저장한 폼을 읽지 못했습니다. '+e.message,true);}}
   if(sourceExam){const sourceItems=[];for(let start=0;;start+=50){const page=await rpc('bank_source_questions',{s:config.spaceId,source_key:sourceExam,start_at:start});sourceItems.push(...page.filter(c=>!c.metadata?.relations?.originalQuestionId));if(page.length<50)break;}
    if(!sourceItems.length)throw Error('이 원본 시험지에 접근 가능한 문항이 없습니다.');const s=sourceInfo(sourceItems[0]);draft.title=[s.school,s.year&&s.year+'학년도',s.grade,s.term,s.exam].filter(Boolean).join(' ')||'기출 시험지';
    const priorItems=new Map(draft.items.map(i=>[i.questionId,i]));
    draft.items=originalQuestion.restoreItems(sourceItems,initialLocal?.originalExam?.sourceId===sourceExam?draft.items:null,c=>({questionId:c.question_id,revisionId:c.revision_id,workspaceMm:priorItems.get(c.question_id)?.workspaceMm??0,breakBefore:priorItems.get(c.question_id)?.breakBefore??null,originalNumber:originalQuestion.printedNumber(c),numbering:c.metadata?.source?.numbering||null,originalPoints:sourceInfo(c).points??null,sourceCaption:sourceLabel(c)}));
    const progress=await rpc('bank_source_progress_get',{s:config.spaceId,k:sourceExam});
    draft.originalExam={sourceId:sourceExam,questionCount:sourceItems.length,registeredComplete:progress?.status==='complete',expectedCount:progress?.expected_count??null,missingNumbers:draft.items.filter(i=>!i.originalNumber).length,missingPoints:draft.items.filter(i=>i.originalPoints==null).length,...inventoryTools.sourceProgress(sourceItems[0].metadata?.source,progress||{})};draft.preserveOriginalOrder=true;
   }else{for(const c of chosen)if(!draft.items.some(i=>i.questionId===c.questionId))draft.items.push({...c,workspaceMm:15,breakBefore:null});chosen.splice(0);save();}
 }else{
  initialLocal=parseLocal(localKey(examId));let server;
  try{server=await rpc('bank_exam_get',{s:config.spaceId,e:examId});}catch(e){if(!initialLocal||initialLocal.version!==0)throw e;}
  staleLocal=Boolean(initialLocal&&server&&initialLocal.version!==server.version);
  draft=initialLocal||{...server.document,id:server.id,version:server.version};
 }
 draft.print={...defaultPrint,...draft.print,marginsMm:{...defaultPrint.marginsMm,...draft.print?.marginsMm}};
  draft.items||=[];draft.rules||={};delete draft.rules.status;delete draft.rules.avoidSameType;draft.status||='draft';draft.version||=0;draft.showOriginalPoints??=!!draft.preserveOriginalOrder;draft.figureScalePercent=figureScalePercent(draft.figureScalePercent);
  const sourceWarning=draft.originalExam?node('p','','hint'):null;
  const updateSourceWarning=()=>{if(!sourceWarning)return;const completeness=inventoryTools.inventory(draft.items.map(i=>({questionId:i.questionId,originalNumber:i.originalNumber,numbering:i.numbering})),draft.originalExam);draft.originalExam.missingNumbers=completeness.unknown.length;const heading=root.querySelector('h2');if(heading)heading.textContent=draft.title+' · '+completeness.included+'/'+(completeness.expectedTotal??'?')+'문항';draft.originalExam.missingPoints=draft.items.filter(i=>i.originalPoints===null||i.originalPoints===undefined||i.originalPoints==='').length;sourceWarning.textContent=`포함 ${completeness.included}/${completeness.expectedTotal??'?'}문항 · 누락 원본 번호: ${completeness.missing.map(inventoryTools.label).join(', ')||(completeness.complete?'없음':'전체 번호 범위 확인 필요')} · 중복: ${completeness.duplicates.map(inventoryTools.label).join(', ')||'없음'} · 번호 미확인 ${completeness.unknown.length}개 · 배점 미확인 ${draft.originalExam.missingPoints}개.`;};
  if(sourceWarning){updateSourceWarning();root.append(sourceWarning);}
 const controls=node('div','','panel'),syncState=node('p','','exam-sync-state'),syncActions=node('div','','actions');root.append(controls,syncState,syncActions);
 let timer=null,inFlight=null,change=0,committed=0,conflict=staleLocal,lastSerialized=JSON.stringify(draft);
 const showState=(kind,detail='')=>{syncState.className='exam-sync-state '+(kind==='conflict'||kind==='local'?'error':'hint');syncState.textContent=({local:'편집 중 · 저장 버튼으로 확인한 뒤 다른 기기에서 열 수 있습니다.',saving:'서버 저장 중…',saved:'서버 저장 완료 · 다른 기기에서 이어 편집할 수 있습니다.',conflict:'수정 충돌 · 다른 기기의 최신 작업을 덮어쓰지 않았습니다.'})[kind]+(detail?' '+detail:'');syncActions.hidden=kind!=='conflict';};
 const profileResult=node('p','','hint');
 const cache=()=>{examSession.write(user.id,draft.version===0?'new':draft.id,draft);save();};
 async function saveExplicit(){const nextStatus=draft.items.length&&lastLayout&&!lastLayout.overflows.length&&loaded.length===draft.items.length?'completed':draft.status;if(!confirm(`‘${draft.title}’ ${draft.items.length}문항을 ${nextStatus==='completed'?'완성본':'초안'}으로 내 시험지에 저장할까요?`))return false;if(nextStatus!==draft.status){draft.status=nextStatus;persist({keepCompleted:true});}return flush();}
 const persist=({derived=false,keepCompleted=false}={})=>{if(!derived&&!keepCompleted&&draft.status==='completed')draft.status='draft';const serialized=JSON.stringify(draft);if(serialized===lastSerialized)return;lastSerialized=serialized;change++;cache();showState(conflict?'conflict':'local');};
 async function flush(){clearTimeout(timer);if(conflict){showState('conflict');return false;}if(inFlight)return inFlight;if(change===committed&&draft.version>0)return true;
  const savedChange=change,snapshot=structuredClone(draft),oldId=snapshot.id;showState('saving');inFlight=(async()=>{try{const result=await rpc('bank_exam_save',{s:config.spaceId,e:oldId,expected:snapshot.version,doc:snapshot});if(draft.id!==oldId)return false;draft.version=result.version;committed=savedChange;lastSerialized=JSON.stringify(draft);if(root.isConnected&&location.hash!=='#exam/'+oldId)history.replaceState({...history.state,bank:true},'','#exam/'+oldId);examSession.clear(user.id,'new');if(change===savedChange){examSession.clear(user.id,oldId);showState('saved',new Date(result.updatedAt||Date.now()).toLocaleString('ko-KR'));}else{cache();showState('local');}return true;}
   catch(e){if(e.code==='PT409'||e.status===409||/다른 기기에서 시험지를 수정|시험지 버전이 없습니다/.test(e.message)){conflict=true;showState('conflict');}else{showState('local','저장 실패: '+e.message+' · 재연결 후 다시 저장하세요.');}cache();return false;}finally{inFlight=null;}})();return inFlight;}
 const title=field(controls,'시험지 제목',draft.title);title.oninput=()=>{draft.title=title.value;persist();};title.onchange=()=>render();
 formLoader({controls,getDraft:()=>draft,node,action,user,config,persist,render,message,onChange:form=>{scoreNote.value=form.scoreNote??'객관식 1개당 4점.';},edit:async()=>{beginFormEdit({config,user,draft,returnRoute:'exam/'+(draft.version===0?'new':draft.id)});await navigate('paper-forms/edit');}});
 const scoreNote=field(controls,'배점 안내 문구',draft.paperForm.scoreNote??'객관식 1개당 4점.');scoreNote.oninput=()=>{draft.paperForm.scoreNote=scoreNote.value;persist();};scoreNote.onchange=()=>render();
 const bodySize=field(controls,'본문 글자 크기 (7~15pt)',draft.bodyFontSize??bodyFontRange.default,'number');bodySize.min=bodyFontRange.min;bodySize.max=bodyFontRange.max;bodySize.step=0.5;
 const fontHint=node('p','','hint');controls.append(fontHint);const updateFontHint=()=>{fontHint.textContent=Number(draft.bodyFontSize)>15?'이 시험지는 기존 '+draft.bodyFontSize+'pt 설정을 유지하고 있습니다. 글자 크기를 새로 입력할 때는 7~15pt에서 선택하세요.':'';};updateFontHint();
 bodySize.onchange=()=>{try{draft.bodyFontSize=validateBodyFont(bodySize.value);bodySize.setCustomValidity('');updateFontHint();persist();render();}catch(e){bodySize.value=draft.bodyFontSize??bodyFontRange.default;message(e.message,true);bodySize.setCustomValidity(e.message);bodySize.reportValidity();}};bodySize.oninput=()=>bodySize.setCustomValidity('');
 const figureLabel=node('label'),figureHeading=node('span','그림 크기'),figureValue=node('output',draft.figureScalePercent+'%'),figureSlider=node('input');figureSlider.type='range';figureSlider.min=50;figureSlider.max=150;figureSlider.step=1;figureSlider.value=draft.figureScalePercent;figureSlider.setAttribute('aria-label','그림 크기');figureHeading.append(document.createTextNode(' · '),figureValue);figureLabel.append(figureHeading,figureSlider);controls.insertBefore(figureLabel,fontHint);controls.insertBefore(node('p','50~150%. 단 너비를 넘는 그림은 비율을 유지해 단 너비에 맞춥니다.','hint'),fontHint);
 figureSlider.oninput=()=>{draft.figureScalePercent=figureScalePercent(figureSlider.value);figureValue.textContent=draft.figureScalePercent+'%';figureSlider.setAttribute('aria-valuetext',draft.figureScalePercent+'%');persist();void render();};
  const answerLabel=node('label','정답·해설'),mode=node('select');mode.setAttribute('aria-label','정답·해설');for(const [value,text]of [['quick','빠른 정답만'],['detailed','빠른 정답 + 상세 풀이']]){const o=node('option',text);o.value=value;mode.append(o);}mode.value=draft.answerMode;mode.onchange=()=>{draft.answerMode=mode.value;persist();render();};answerLabel.append(mode);controls.append(answerLabel);
  const sourceToggle=field(controls,'혼합 시험지에 원문 출처 표시 · 미리보기와 출력에 반영','','checkbox');sourceToggle.checked=!!draft.showSourceOnPaper;sourceToggle.onchange=()=>{draft.showSourceOnPaper=sourceToggle.checked;persist();render();};
  const pointsToggle=field(controls,'원래 배점 표시 · 확인된 배점만 미리보기와 출력에 반영','','checkbox');pointsToggle.checked=!!draft.showOriginalPoints;pointsToggle.onchange=()=>{draft.showOriginalPoints=pointsToggle.checked;persist();render();};
 controls.append(node('p','인쇄 설정 · A4 · 2단. 선택한 폼에 맞춰 여백과 첫 페이지 안내문 공간을 계산합니다. 모바일에서도 같은 용지 배치를 축소해 보여줍니다.','hint'));
 const restoring=Boolean(sourceExam||draft.originalExam);
 if(!restoring)controls.append(action('문항 더 찾기',()=>navigate('search')));
 if(!restoring&&chosen.length)controls.append(action(`선택한 ${chosen.length}문항 추가`,()=>{for(const c of chosen)if(!draft.items.some(i=>i.questionId===c.questionId))draft.items.push({...c,workspaceMm:15,breakBefore:null});chosen.splice(0);persist();render();}));
 syncActions.append(action('최신 서버본 불러오기',async()=>{if(!confirm('이 기기의 미저장 변경을 버리고 서버의 최신본을 열까요?'))return;examSession.clear(user.id,draft.id);examSession.clear(user.id,'new');setEditGuard(null);await navigate('exam/'+draft.id,{replace:true});}),action('별도 사본으로 저장',async()=>{if(!confirm('현재 변경을 별도 시험지로 저장할까요?'))return;const previous=draft.id,previousVersion=draft.version;draft={...structuredClone(draft),id:crypto.randomUUID(),version:0,status:'draft',copiedFrom:{id:previous,version:previousVersion}};conflict=false;committed=0;change++;cache();if(await flush())await navigate('exam/'+draft.id,{replace:true});}));syncActions.hidden=true;

 if(staleLocal)showState('conflict','이 기기의 미저장 변경과 서버 버전이 다릅니다.');else if(initialLocal){change=1;showState('local');}else if(draft.version>0)showState('saved');else{change=1;cache();showState('local');}
 setEditGuard({dirty:()=>change!==committed,save:saveExplicit,discard:()=>{examSession.clear(user.id,draft.version===0?'new':draft.id);}});
 let composing=false,generationPopup=null,preparedPreview=null,cancelGeneration=()=>{};
 // Restoration keeps the original selection and metadata. Do not construct
 // generation controls or issue their candidate/school/exclusion queries.
 if(!restoring){
  const scopePanel=node('details','','panel exam-scope-panel');scopePanel.open=true;scopePanel.append(node('summary','1. 시험범위 설정'),node('p','학년과 상위 단원을 펼쳐 세부 단원을 선택하세요. 상위 체크박스는 하위를 모두 선택합니다. 이전 과정의 선수개념 허용 규칙은 그대로 적용됩니다.','hint'));
  const selected=new Set(draft.rules.units||[]),forbidden=new Set(draft.rules.forbidden||[]),denyBox=node('details','','forbidden-picker');denyBox.append(node('summary','금지 개념 설정 · 선수개념보다 우선'));
  let scheduleSchoolFilter=()=>{};
  const renderForbidden=()=>{const visibleGrades=[...new Set(curriculum.leaves.filter(u=>selected.has(u.id)||forbidden.has(u.id)).map(u=>curriculum.tree.find(g=>g.title===u.grade)?.id).filter(Boolean))];const previous=denyBox.open;denyBox.replaceChildren(node('summary','금지 개념 설정 · 선수개념보다 우선'),scopeTree({node,selected:forbidden,label:'금지 개념',gradeFilter:visibleGrades.length?visibleGrades:null}).element);denyBox.open=previous;};
  const unitTree=scopeTree({node,selected,label:'시험범위',onChange:()=>{renderForbidden();scheduleSchoolFilter();}});scopePanel.append(unitTree.element,denyBox);renderForbidden();root.append(scopePanel);
  const condition=node('details','','panel');condition.open=true;condition.append(node('summary','2. 조건 입력 · 자동 구성'));const f=node('div','','filters'),count=field(f,'총 문항 수',draft.rules.count||10,'number');
  const selectedSchools=new Set(draft.rules.schools||[]),schoolPicker=node('details','','school-picker'),schoolList=node('div','','school-options'),schoolSummary=node('summary');schoolPicker.append(schoolSummary,node('p','미선택이면 전체 학교에서 찾습니다. 목록을 접어도 선택은 유지됩니다.','hint'),schoolList);f.append(schoolPicker);
  const generationFilters={};for(const [key,label]of [['unit','단원'],['type','유형']]){const wrapper=node('label',label),select=node('select');select.setAttribute('aria-label',label);generationFilters[key]=select;wrapper.append(select);f.append(wrapper);select.onchange=()=>{draft.rules={...draft.rules,unit:generationFilters.unit.value,type:generationFilters.type.value};persist();};}
  const updateGenerationFilters=all=>{const options=searchFilters.options(all);for(const [key,select]of Object.entries(generationFilters)){const value=select.options.length?select.value:draft.rules[key]||'',values=options[key]||[];select.replaceChildren();const any=node('option',key==='unit'?'전체 단원':'전체 유형');any.value='';select.append(any);for(const v of [...new Set([...values,...(value?[value]:[])])]){const option=node('option',v);option.value=v;select.append(option);}select.value=value;}};updateGenerationFilters([]);
 const typeInputs={};for(const label of ['선택형','단답형','서술형'])typeInputs[label]=field(f,label+' 개수 (빈칸: 자동)',draft.rules.types?.[label]??'','number');condition.append(f,node('p','입력한 유형은 정확히 그 개수로 고정합니다. 빈칸 유형으로 나머지를 자동 충원하고, 0은 해당 유형을 제외합니다.','hint'),node('p','자동 생성 순서: 비서술형 먼저 → 서술형 마지막. 각 묶음에서 난이도 0.5점 구간 순으로, 비슷한 난이도는 그림·보기·수식을 포함한 실제 높이가 짧은 문항부터 배치합니다. 원문 복원과 수동 이동 순서는 유지합니다.','hint'));
  let compositionEpoch=0,generationAbort=null;
  const profileBox=node('div','','filters'),profile=draft.rules.profile||{low:30,middle:50,high:20,targetAverage:5.0};condition.append(node('h4','난이도 구성 추천'),node('p',difficultyMapping+' 비율을 바꾸면 예상 목표가 갱신되고, 목표를 직접 입력하면 비율을 추천합니다. 마지막으로 직접 고친 입력이 기준입니다.','hint'));
  const ratioControl=node('div','','ratio-control'),ratioBar=node('div','','ratio-bar'),lowSegment=node('span','하','ratio-low'),middleSegment=node('span','중','ratio-middle'),highSegment=node('span','상','ratio-high'),lowHandle=node('input'),middleHandle=node('input');
  for(const handle of [lowHandle,middleHandle]){handle.type='range';handle.min=0;handle.max=100;handle.step=1;handle.className='ratio-handle';}
  lowHandle.setAttribute('aria-label','하와 중의 경계');middleHandle.setAttribute('aria-label','중과 상의 경계');ratioBar.append(lowSegment,middleSegment,highSegment,lowHandle,middleHandle);ratioControl.append(node('p','막대의 경계를 움직여 하·중·상 비율을 정하세요. 합계는 항상 100%입니다.','hint'),ratioBar);condition.append(ratioControl,profileBox);
  const lowRatio=field(profileBox,'하 비율 (%)',profile.low,'number'),middleRatio=field(profileBox,'중 비율 (%)',profile.middle,'number'),highRatio=field(profileBox,'상 비율 (%)',profile.high,'number'),targetAverage=field(profileBox,'목표 문항 난이도 평균',profile.targetAverage,'number');for(const input of [lowRatio,middleRatio,highRatio]){input.min=0;input.max=100;}targetAverage.min=0;targetAverage.max=10;targetAverage.step='0.01';const ratioEstimate=node('p','','hint');ratioEstimate.setAttribute('role','status');condition.append(ratioEstimate,profileResult);
  const clampPercent=value=>Math.max(0,Math.min(100,Math.round(Number(value)||0)));
  const syncRatioBar=()=>{const low=clampPercent(lowRatio.value),middle=clampPercent(middleRatio.value),high=100-low-middle;lowHandle.value=String(low);middleHandle.value=String(low+middle);ratioBar.style.setProperty('--low-end',low+'%');ratioBar.style.setProperty('--middle-end',(low+middle)+'%');lowSegment.textContent=`하 ${low}%`;middleSegment.textContent=`중 ${middle}%`;highSegment.textContent=`상 ${Math.max(0,high)}%`;};
  let profileDriver=draft.rules.profile?.driver||'ratio',profileTouched=!!draft.rules.profile;
  const updateEstimate=()=>{const p={low:Number(lowRatio.value),middle:Number(middleRatio.value),high:Number(highRatio.value)},estimate=model.profileAverage(p);try{const n=model.profileCounts(Number(count.value),p);ratioEstimate.textContent=`예상 목표 평균 ${estimate.toFixed(2)} (대표점 3·5·8의 비율 가중평균) · 하 ${n.low} / 중 ${n.middle} / 상 ${n.high}문항 · ${profileDriver==='target'?'직접 입력한 목표를 기준으로 비율 추천':'비율을 기준으로 예상 목표 갱신'}. 실제 선택 문항 평균은 생성 후 별도로 표시합니다.`;}catch{ratioEstimate.textContent='비율 합계와 총 문항 수를 확인하세요.';}return estimate;};
  const setRatios=(low,middle,high,{fromTarget=false}={})=>{profileTouched=true;if(composing)cancelGeneration();lowRatio.value=String(low);middleRatio.value=String(middle);highRatio.value=String(high);profileDriver=fromTarget?'target':'ratio';syncRatioBar();const estimate=updateEstimate();if(!fromTarget)targetAverage.value=estimate.toFixed(2);};
  targetAverage.oninput=()=>{if(targetAverage.value.trim()==='')return;try{const p=model.profileForTarget(targetAverage.value);setRatios(p.low,p.middle,p.high,{fromTarget:true});if(Number(targetAverage.value)<3||Number(targetAverage.value)>8)ratioEstimate.textContent+=' 입력 목표는 대표점 범위 밖이므로 가장 가까운 비율을 제안합니다.';}catch(e){ratioEstimate.textContent=e.message;}};
  count.addEventListener('input',updateEstimate);
  lowHandle.oninput=()=>{const high=clampPercent(highRatio.value),low=Math.min(clampPercent(lowHandle.value),100-high);setRatios(low,100-low-high,high);};
  middleHandle.oninput=()=>{const low=clampPercent(lowRatio.value),end=Math.max(low,clampPercent(middleHandle.value));setRatios(low,end-low,100-end);};
  lowRatio.onchange=()=>{const high=clampPercent(highRatio.value),low=Math.min(clampPercent(lowRatio.value),100-high);setRatios(low,100-low-high,high);};
  middleRatio.onchange=()=>{const low=clampPercent(lowRatio.value),middle=Math.min(clampPercent(middleRatio.value),100-low);setRatios(low,middle,100-low-middle);};
  highRatio.onchange=()=>{const low=clampPercent(lowRatio.value),high=Math.min(clampPercent(highRatio.value),100-low);setRatios(low,100-low-high,high);};
  if(clampPercent(profile.low)+clampPercent(profile.middle)+clampPercent(profile.high)!==100)setRatios(clampPercent(profile.low),100-clampPercent(profile.low)-Math.min(clampPercent(profile.high),100-clampPercent(profile.low)),Math.min(clampPercent(profile.high),100-clampPercent(profile.low)));else {syncRatioBar();const estimate=updateEstimate();if(profileDriver!=='target')targetAverage.value=estimate.toFixed(2);}
 const exclusionGroups=new Map(Object.entries(draft.rules.exclusionGroups||{})),excludedIds=new Set(draft.rules.excludeIds||[]),syncExcluded=()=>{excludedIds.clear();for(const ids of exclusionGroups.values())for(const id of ids)excludedIds.add(id);},excludeBox=node('details');excludeBox.append(node('summary','기존 시험지에 사용한 문항 제외'));condition.append(excludeBox);
 const custom=await rows('bank_exam_drafts',{space_id:config.spaceId,owner_id:user.id});for(const exam of custom){const label=node('label'),check=node('input');check.type='checkbox';check.checked=exclusionGroups.has('exam:'+exam.id);check.onchange=()=>{if(check.checked)exclusionGroups.set('exam:'+exam.id,exam.document.items.map(i=>i.questionId));else exclusionGroups.delete('exam:'+exam.id);syncExcluded();};label.append(check,document.createTextNode('내 시험지 · '+exam.title));excludeBox.append(label);}
  const originals=[];for(let start=0;;start+=50){const found=await rpc('bank_source_exams',{s:config.spaceId,start_at:start});originals.push(...found);if(found.length<50)break;}
  const questionsBySource=new Map(),schoolFilterState={generation:0,timer:null};
  const loadSourceQuestions=source=>{if(questionsBySource.has(source.source_id))return questionsBySource.get(source.source_id);const pending=(async()=>{const results=[];for(let start=0;;start+=50){const page=await rpc('bank_source_questions',{s:config.spaceId,source_key:source.source_id,start_at:start});results.push(...page);if(page.length<50)break;}return results;})();questionsBySource.set(source.source_id,pending);pending.catch(()=>questionsBySource.delete(source.source_id));return pending;};
  const showSchoolSummary=()=>{schoolSummary.textContent=selectedSchools.size?`학교 선택 · 선택한 학교 ${selectedSchools.size}개 (${[...selectedSchools].join(', ')})`:'학교 선택 · 전체 학교';};showSchoolSummary();
  schoolPicker.append(action('전체 학교로 변경',()=>{selectedSchools.clear();for(const check of schoolList.querySelectorAll('input'))check.checked=false;showSchoolSummary();}));
  const updateSchools=async()=>{const generation=++schoolFilterState.generation,chosenScope=new Set(selected);showSchoolSummary();schoolList.replaceChildren(node('p',chosenScope.size?'해당 범위의 학교·시험지를 확인하는 중…':'학교 목록을 보려면 시험범위를 선택하세요. 현재 학교 선택은 유지됩니다.','hint'));if(!chosenScope.size)return;
   try{let cursor=0;const loaded=new Map();await Promise.all(Array.from({length:Math.min(4,originals.length)},async()=>{while(cursor<originals.length){const source=originals[cursor++];loaded.set(source.source_id,await loadSourceQuestions(source));}}));if(generation!==schoolFilterState.generation||!root.isConnected)return;
    const matching=matchingSourceSchools(originals,loaded,chosenScope),names=new Set(matching.map(x=>x.school));for(const school of selectedSchools)if(!names.has(school))matching.push({school,examCount:0,questionCount:0});
    schoolList.replaceChildren();for(const info of matching){const label=node('label'),check=node('input');check.type='checkbox';check.checked=selectedSchools.has(info.school);check.onchange=()=>{check.checked?selectedSchools.add(info.school):selectedSchools.delete(info.school);showSchoolSummary();};label.append(check,document.createTextNode(`${info.school} · 관련 시험지 ${info.examCount}개 · 문항 ${info.questionCount}개`));schoolList.append(label);}showSchoolSummary();if(!matching.length)schoolList.append(node('p','선택한 범위와 연결된 학교 시험지가 없습니다. 미분류 문항은 임의로 포함하지 않습니다.','hint'));
   }catch(e){if(generation===schoolFilterState.generation){schoolList.replaceChildren(node('p','학교 목록 확인 실패: '+e.message+' · 학교 선택은 변경하지 않았습니다.','error'));showSchoolSummary();}}};
  scheduleSchoolFilter=()=>{clearTimeout(schoolFilterState.timer);schoolFilterState.timer=setTimeout(updateSchools,180);};void updateSchools();
  for(const source of originals){const label=node('label'),check=node('input');check.type='checkbox';check.checked=exclusionGroups.has('source:'+source.source_id);check.onchange=async()=>{check.disabled=true;try{const ids=[];for(let start=0;;start+=50){const data=await rpc('bank_source_questions',{s:config.spaceId,source_key:source.source_id,start_at:start});for(const c of data)ids.push(c.question_id);if(data.length<50)break;}if(check.checked)exclusionGroups.set('source:'+source.source_id,ids);else exclusionGroups.delete('source:'+source.source_id);syncExcluded();}catch(e){message(e.message,true);}finally{check.disabled=false;}};label.append(check,document.createTextNode('원본 · '+[source.source?.school,source.source?.academicYear,source.source?.exam].filter(Boolean).join(' ')));excludeBox.append(label);}
  condition.append(node('p','검수·미검수 모두 출제 후보입니다. 가능한 서로 다른 출제유형을 먼저 선택하며, 수량 확보에 필요한 반복과 유형 미상은 결과에 표시합니다.','hint'));
  const availability=node('div','','composition-availability');condition.append(availability);let candidateCache=null,candidatePending=null,availabilityGeneration=0,availabilityTimer=null,lastAvailability=null;
  const candidates=async(force=false,progress={})=>{if(force){const all=await loadCompositionCandidates(rpc,config.spaceId,progress);if(progress.isValid?.()!==false)candidateCache=all;return all;}if(candidateCache)return candidateCache;if(!candidatePending)candidatePending=loadCompositionCandidates(rpc,config.spaceId).then(rows=>(candidateCache=rows)).finally(()=>{candidatePending=null;});return candidatePending;};
  const availabilityRules=()=>({unit:generationFilters.unit.value,type:generationFilters.type.value,schools:[...selectedSchools],units:[...selected],forbidden:[...forbidden],excludeIds:[...excludedIds],types:Object.fromEntries(Object.entries(typeInputs).filter(([,v])=>v.value!=='').map(([k,v])=>[k,Number(v.value)]))});
  function useAvailable(){if(!lastAvailability)return;const c=lastAvailability.counts,total=c.low+c.middle+c.high;if(!total)return;const ratios=model.profileCounts(100,{low:c.low/total*100,middle:c.middle/total*100,high:c.high/total*100});setRatios(ratios.low,ratios.middle,ratios.high);profileTouched=true;}
  async function updateAvailability(){const gen=++availabilityGeneration;try{const all=await candidates();if(gen!==availabilityGeneration||!root.isConnected)return;updateGenerationFilters(all);if(!selected.size){availability.replaceChildren(node('p','학교·범위를 정하면 가용 난이도별 문항 수를 표시합니다. 전체 등록 '+all.length+'문항 · 검수 여부와 무관합니다.','hint'));return;}const checked=model.inspectCandidates(all,availabilityRules()),d=checked.diagnostics;lastAvailability=d.eligibleDifficulty;availability.replaceChildren(node('h4','현재 조건의 가용 문항'),node('p','학교·범위: '+countsText(d.schoolScopeDifficulty)),node('p','형식·중복 제외 적용 후: '+countsText(lastAvailability)),node('p','범위 분류 미상 '+d.scopeUnknown+'개 · 세부 개념 근거 일부 없음 '+d.limitedEvidence+'개 (저장된 추천 단원으로 포함)','hint'),node('p',difficultyMapping,'hint'),action('가용 문항 비율 적용',()=>{useAvailable();message('가용 문항 분포로 비율을 입력했습니다. 시험지 생성을 눌러 적용하세요.');}));if(!profileTouched&&!draft.items.length)useAvailable();}catch(e){if(gen===availabilityGeneration)availability.replaceChildren(node('p','가용 문항 조회 실패: '+e.message,'error'));}}
  const scheduleAvailability=()=>{clearTimeout(availabilityTimer);availabilityTimer=setTimeout(updateAvailability,120);};
  for(const input of [lowRatio,middleRatio,highRatio,lowHandle,middleHandle])input.addEventListener('input',()=>{profileTouched=true;});
  condition.addEventListener('change',scheduleAvailability);scopePanel.addEventListener('change',scheduleAvailability);schoolPicker.querySelector('button').addEventListener('click',scheduleAvailability);void updateAvailability();
  const diagnostics=node('div','','composition-diagnostics');diagnostics.setAttribute('role','status');diagnostics.setAttribute('aria-live','polite');condition.append(diagnostics);
  function showDiagnostics(result,rules){
   diagnostics.replaceChildren(node('h4',result.complete?'조건에 맞는 문항 구성 완료':'조건에 맞는 문항을 구성하지 못했습니다.'));
   if(!result.complete){diagnostics.append(node('p',compositionFailureText(result),'error'));if(result.constraintConflict)for(const [band,counts]of Object.entries(result.crossCounts||{}))diagnostics.append(node('p',`${({low:'하',middle:'중',high:'상',all:'전체'})[band]||'난이도 구간 '+(Number(band)+1)}: `+Object.entries(counts).map(([format,n])=>`${format} ${n}개`).join(' · ')));}
   if(rules.scopeDistribution){for(const g of result.scopeAllocation?.groups||result.diagnostics.scopeInventory||[])diagnostics.append(node('p',`${g.title}: 범위 ${g.selected}/${g.total} · 가중 목표 ${(g.target||0).toFixed(2)}개${result.complete&&g.count!=null?' → 선정 '+g.count+'개':g.roundedTarget==null?'':' · 정수 배분 목표 '+g.roundedTarget+'개'} · 현재 조건 가용 ${g.available}개 · 서술형 가용 ${g.writtenAvailable}개${result.complete&&g.writtenCount!=null?' → 선정 '+g.writtenCount+'개':g.roundedWrittenTarget==null?'':' · 정수 배분 목표 '+g.roundedWrittenTarget+'개'}`));if(result.diagnostics.scopeAmbiguous)diagnostics.append(node('p',`대단원 분류가 하나로 확정되지 않는 후보 ${result.diagnostics.scopeAmbiguous}개. 특정 단원의 가중치로 임의 분류하지 않았습니다.`,'hint'));}
   if(result.scopeAllocation?.searchLimitReached)diagnostics.append(node('p','범위 배분 탐색 한도 안에서 찾은 근사값입니다. 요청 수량과 모든 기존 조건은 지켰으며, 최적 비율은 확정하지 못했습니다.','hint'));
   diagnostics.append(node('p',`접근 가능한 최신 문항 ${result.diagnostics.total}개 → 모든 후보 조건을 만족하는 문항 ${result.eligible}개 / 요청 ${rules.count}개`));
   if(!result.diagnostics.total)diagnostics.append(node('p','현재 계정에서 접근 가능한 최신 문항이 없습니다. 문항 등록·공유 상태와 계정을 확인하세요.'));
   const list=node('ul');for(const check of result.diagnostics.checks)if(check.failed)list.append(node('li',`${check.label}: 통과 ${check.passed}개 · 제외 ${check.failed}개`));
   for(const [reason,n]of Object.entries(result.reasons))list.append(node('li',`${reason} · ${n}개`));diagnostics.append(list,node('p','각 조건은 독립적으로 점검하므로 같은 문항이 여러 제외 이유에 포함될 수 있습니다. 조건이나 접근 권한을 자동으로 완화하지 않습니다.','hint'));
   if(!result.complete&&draft.items.length)diagnostics.append(node('p','기존 시험지 구성은 유지했습니다.','hint'));
  }
  cancelGeneration=()=>{if(composing&&!generationAbort?.signal.aborted){compositionEpoch++;generationAbort?.abort();generationPopup?.finish('cancelled','생성을 취소했습니다. 기존 시험지는 유지합니다.');message('시험지 생성을 취소했습니다. 기존 시험지는 유지합니다.');}};
  const cancelButton=action('생성 취소',cancelGeneration);cancelButton.hidden=true;
  condition.addEventListener('input',cancelGeneration);condition.addEventListener('change',cancelGeneration);
  const generateButton=action('시험지 생성',async()=>{if(composing)return;composing=true;generateButton.disabled=true;generationAbort=new AbortController();const signal=generationAbort.signal,ticket=++compositionEpoch,current=()=>ticket===compositionEpoch&&controls.isConnected&&!signal.aborted,wait=p=>waitForGeneration(p,signal);cancelButton.hidden=false;let previousDraft=null,appliedDraft=null;
   generationPopup?.close();const popup=generationProgress({node,action,onCancel:cancelGeneration,returnFocus:generateButton});generationPopup=popup;
   const stage=(text,done=null,total=null)=>{if(current())popup.stage(text,done,total);},fail=text=>{if(current()){popup.finish('error',text);message(text,true);}};
   try{if(targetAverage.value.trim()==='')throw Error('목표 문항 난이도 평균을 입력하세요.');const rules={scopeDistribution:!sourceExam&&!draft.originalExam&&!draft.preserveOriginalOrder,count:Number(count.value),unit:generationFilters.unit.value,type:generationFilters.type.value,schools:[...selectedSchools],types:Object.fromEntries(Object.entries(typeInputs).filter(([k,v])=>v.value!=='').map(([k,v])=>[k,Number(v.value)])),profile:{low:Number(lowRatio.value),middle:Number(middleRatio.value),high:Number(highRatio.value),targetAverage:Number(targetAverage.value),driver:profileDriver},units:[...selected],forbidden:[...forbidden],scopeSnapshot:selected.size?curriculum.build([...selected],{extraForbidden:curriculum.leaves.filter(u=>forbidden.has(u.id)).map(u=>u.title)}):null,excludeIds:[...excludedIds],exclusionGroups:Object.fromEntries(exclusionGroups)};
  model.validateRules(rules);if(!selected.size)throw Error('시험범위를 선택하세요.');
  stage('후보 검색 중입니다.');message('후보를 확인하는 중입니다.');const all=await wait(candidates(true,{isValid:current,onProgress:n=>stage('접근 가능한 최신 후보를 검색하고 있습니다.',n)}));if(!current())return;await wait(updateAvailability());if(!current())return;
  stage('학교·범위·난이도·유형 조건에 맞춰 문항을 구성하고 있습니다.');await wait(new Promise(requestAnimationFrame));if(!current())return;
  const result=rules.scopeDistribution?await wait(composeInWorker(all,rules,{signal})):model.selectQuestions(all,rules);if(!current())return;showDiagnostics(result,rules);if(!result.complete){const reason=compositionFailureText(result);message(reason,true);popup.finish('error',reason+'\n'+diagnostics.innerText);return;}
   stage('문항 데이터와 그림을 준비하고 있습니다.',0,result.items.length);
   const ready=new Map();for(const [i,c]of result.items.entries()){try{const rendered=await wait(reader.render(c.revision_id));if(rendered.element.dataset.incomplete)throw Error('그림이 누락되었습니다.');await wait(Promise.all([...rendered.element.querySelectorAll('img')].map(img=>img.decode())));if(!current())return;ready.set(c.revision_id,rendered);stage('문항 데이터와 그림을 준비하고 있습니다.',i+1,result.items.length);}catch(e){if(!current())return;diagnostics.querySelector('h4').textContent='후보 선택 완료 · 미리보기 준비 실패';diagnostics.append(node('p',`후보 선택은 완료했으나 선택한 ${i+1}번째 문항의 미리보기 원본을 읽지 못했습니다: ${e.message}. 기존 시험지는 유지했습니다. 다시 시도할 수 있습니다.`,'error'));fail('미리보기 준비 실패: '+e.message+' · 기존 시험지는 유지했습니다.');return;}}preparedPreview=ready;
   if(result.diversity)diagnostics.append(node('p',`출제유형 ${result.diversity.knownTypes}종 · 저장된 유형 반복 ${result.diversity.repeated}문항 · 유형 미상 ${result.diversity.unknownTypes}문항 · 세부 유형 키 없음 ${result.diversity.coarseTypeCount||0}문항. ${result.diversity.searchLimitReached?'탐색 한도 안에서 찾은 구성으로 최소 반복 여부는 미확정입니다. ':''}${result.diversity.unknownTypes||result.diversity.coarseTypeCount?'일부 문항은 핵심 풀이 방식의 중복 여부를 확정할 수 없습니다. ':''}${result.diversity.repeated?'조건과 수량을 유지한 구성에 유형 반복이 남아 있습니다.':''}`,'diversity-result'));
   const summary=result.profileSummary;profileResult.textContent=summary?`추천 배치: 하 ${summary.requested.low}문항 · 중 ${summary.requested.middle}문항 · 상 ${summary.requested.high}문항 · 실제 평균 ${summary.actualAverage?.toFixed(2)??'점수 없는 문항 포함'} / 목표 ${summary.targetAverage.toFixed(1)}`:'';
   if(!current())return;previousDraft=structuredClone(draft);draft={...draft,preserveOriginalOrder:false,rules,items:result.items.map(c=>({questionId:c.question_id,revisionId:c.revision_id,responseType:model.responseType(c.metadata),selectedSolutionId:c.selectedSolutionId,solutionSnapshot:c.selectedSolution||null,workspaceMm:15,scoreSnapshot:model.numericScore(c),profileSlot:summary.assignment[c.question_id]}))};appliedDraft=draft;items.inert=true;controls.inert=true;toolbar.inert=true;
   stage('글꼴·문항 크기를 확인하고 페이지에 배치하고 있습니다.',0,draft.items.length);
   const rendered=await render({persistLayout:false,isValid:current,sortAutomatic:true,onProgress:stage,awaitPending:wait});if(!current())return;if(!rendered){const failure=status.textContent;diagnostics.querySelector('h4').textContent='후보 선택 완료 · 미리보기 배치 실패';draft=previousDraft;previousDraft=null;await render();if(!current())return;diagnostics.append(node('p',failure+' · 기존 시험지를 유지했습니다.','error'));fail(failure+' · 기존 시험지를 유지했습니다.');return;}
   persist();previousDraft=null;message('배치 완료 · '+draft.items.length+'문항');popup.finish('success',`${draft.items.length}문항의 선택·데이터 로딩·미리보기 배치와 정답 연결 확인이 끝났습니다.`);
   }catch(e){if(current()){diagnostics.replaceChildren(node('p','시험지 생성 실패: '+e.message,'error'));fail('시험지 생성 실패: '+e.message);}}
   finally{if(previousDraft&&draft===appliedDraft&&controls.isConnected){draft=previousDraft;await render();}items.inert=false;controls.inert=false;toolbar.inert=false;cancelButton.hidden=true;composing=false;generateButton.disabled=false;if(!controls.isConnected)popup.close();else if(!popup.isOpen())generateButton.focus();}
  },true);condition.append(generateButton,cancelButton);root.append(condition);
  const workActions=node('div','','exam-control-actions exam-flow-actions');for(const button of [...controls.querySelectorAll(':scope > button')])workActions.append(button);
  condition.after(node('h3','3. 문항 직접 추가·수정'),workActions);
 }
 const toolbar=node('div','','panel exam-output-controls');
 const controlGroup=label=>{const group=node('section','','exam-control-group');group.setAttribute('aria-label',label);group.append(node('h4',label));toolbar.append(group);return group;};
 const previewControls=controlGroup('미리보기 조절'),zoom=field(previewControls,'미리보기 확대 (%)',Math.max(25,Math.min(100,Math.floor((innerWidth-48)/(210*MM)*100))),'number');zoom.min=10;zoom.max=150;
 const saveGroup=controlGroup('서버 저장'),saveActions=node('div','','exam-control-actions');saveGroup.append(node('p','문항 미리보기가 준비되면 완성본으로 저장합니다. 아직 준비되지 않은 초안도 저장할 수 있습니다. 저장은 파일 출력이나 공개를 시작하지 않습니다.','hint'),saveActions);saveActions.append(action('지금 서버에 저장',async()=>{if(await saveExplicit())message('내 시험지에 저장했습니다.');},true));
 const outputGroup=controlGroup('문서 출력'),outputActions=node('div','','exam-control-actions');outputGroup.append(outputActions);const versionGroup=controlGroup('문항 버전 관리'),versionActions=node('div','','exam-control-actions');versionGroup.append(versionActions);
  const status=node('p','','hint'),items=node('div','','exam-item-tools'),toolGroup=node('details','','panel exam-layout-tools'),previewShell=node('div','','exam-preview-shell'),viewport=node('div','','exam-viewport'),pages=node('div','','exam-pages'),scrollbar=node('div','','exam-scrollbar'),thumb=node('div','','exam-scroll-thumb');toolGroup.append(node('summary','풀이공간 및 문제배치'),items);const pageSurface=node('div','','exam-page-surface');pageSurface.style.position='relative';pages.style.position='absolute';pageSurface.append(pages);viewport.append(pageSurface);scrollbar.append(thumb);scrollbar.setAttribute('role','scrollbar');scrollbar.setAttribute('aria-label','시험지 미리보기 세로 이동');scrollbar.setAttribute('aria-orientation','vertical');scrollbar.tabIndex=0;previewShell.append(viewport,scrollbar);root.append(status,toolGroup,node('h3','4. 배치 결과 확인'),previewShell,node('h3','5. 저장 및 출력'));previewShell.after(node('p','인쇄 페이지를 확인한 뒤 아래에서 저장하거나 파일을 만드세요. 오른쪽 스크롤바로 페이지를 이동할 수 있습니다.','hint'));root.append(toolbar);
  const updateScrollbar=()=>{const total=Math.max(0,viewport.scrollHeight-viewport.clientHeight),track=scrollbar.clientHeight;scrollbar.setAttribute('aria-valuemin','0');scrollbar.setAttribute('aria-valuemax',String(Math.round(total)));scrollbar.setAttribute('aria-valuenow',String(Math.round(viewport.scrollTop)));const height=total?Math.max(36,Math.min(track,track*viewport.clientHeight/viewport.scrollHeight)):track;thumb.style.height=Math.max(0,height)+'px';thumb.style.top=(total&&track>height?viewport.scrollTop/total*(track-height):0)+'px';scrollbar.classList.toggle('inactive',total<2);};
  const scrollFromPointer=e=>{const box=scrollbar.getBoundingClientRect(),height=thumb.getBoundingClientRect().height,available=Math.max(1,box.height-height),top=Math.max(0,Math.min(available,e.clientY-box.top-height/2));viewport.scrollTop=top/available*Math.max(0,viewport.scrollHeight-viewport.clientHeight);};
  scrollbar.onpointerdown=e=>{e.preventDefault();scrollbar.setPointerCapture(e.pointerId);scrollFromPointer(e);};scrollbar.onpointermove=e=>{if(scrollbar.hasPointerCapture(e.pointerId))scrollFromPointer(e);};scrollbar.onkeydown=e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End'].includes(e.key)){e.preventDefault();viewport.scrollTop=e.key==='Home'?0:e.key==='End'?viewport.scrollHeight:viewport.scrollTop+(e.key==='ArrowDown'?80:e.key==='ArrowUp'?-80:e.key==='PageDown'?viewport.clientHeight:-viewport.clientHeight);}};
  const zoomTools=node('div','','exam-layout-zoom'),zoomValue=node('output','','exam-layout-zoom-value');
  zoomTools.setAttribute('aria-label','배치 미리보기 확대·축소');
  let zoomChosen=false,zoomReady=false;
  const applyPreviewZoom=()=>{
   if(!zoomReady&&pages.querySelector('.exam-page')){
    if(matchMedia('(min-width:761px)').matches){const css=getComputedStyle(viewport),width=viewport.clientWidth-parseFloat(css.paddingLeft)-parseFloat(css.paddingRight),height=viewport.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom);zoom.value=String(Math.max(10,Math.min(100,Math.floor(100*Math.min(width/(210*MM),height/(297*MM))))));}
    zoomReady=true;
   }
   const percent=Math.max(10,Math.min(150,Number(zoom.value)||10)),scale=percent/100;zoom.value=String(percent);zoomValue.value=percent+'%';
   pages.style.transform=`scale(${scale})`;pageSurface.style.width=(210*MM*scale)+'px';pageSurface.style.height=(pages.scrollHeight*scale)+'px';
   zoomOut.disabled=percent<=10;zoomIn.disabled=percent>=150;requestAnimationFrame(updateScrollbar);
  };
  zoom.oninput=()=>{zoomChosen=true;zoomReady=true;applyPreviewZoom();};
  const changeZoom=delta=>{zoom.value=String(Number(zoom.value)+delta);zoom.oninput();};
  const zoomOut=action('−',()=>changeZoom(-10)),zoomIn=action('+',()=>changeZoom(10));
  zoomOut.setAttribute('aria-label','배치 미리보기 축소');zoomIn.setAttribute('aria-label','배치 미리보기 확대');
  zoomTools.append(zoomOut,zoomValue,zoomIn);previewShell.before(zoomTools);
  viewport.addEventListener('scroll',updateScrollbar);
  const previewResize=new ResizeObserver(()=>{if(!zoomChosen)zoomReady=false;applyPreviewZoom();});previewResize.observe(viewport);applyPreviewZoom();
  const paperCatalogs=new Map(),compositionBox=node('section','','panel exam-current-composition'),compositionValue=node('p');compositionBox.setAttribute('aria-label','현재 시험지 구성');compositionValue.setAttribute('role','status');compositionValue.setAttribute('aria-live','polite');compositionBox.append(node('h4','현재 시험지 구성'),compositionValue);[...root.children].find(e=>e.tagName==='H3'&&e.textContent==='5. 저장 및 출력').before(compositionBox);
  const updatePaperComposition=()=>{compositionValue.textContent=paperCompositionText(paperComposition(draft.items,paperCatalogs));};
  let generation=0,lastLayout=null,loaded=[],fontReflowTimer=null;
 const reflowAfterLoad=event=>{if(event.type==='load'&&event.target instanceof HTMLImageElement&&(!event.target.closest('.print-question')||event.target.dataset.measuredSize===`${event.target.naturalWidth}x${event.target.naturalHeight}`))return;if(!controls.isConnected||composing||exporting||!lastLayout)return;clearTimeout(fontReflowTimer);fontReflowTimer=setTimeout(()=>{if(controls.isConnected&&!composing&&!exporting)void render();},40);};
 const loadEvents=new AbortController();document.fonts.addEventListener('loadingdone',reflowAfterLoad,{signal:loadEvents.signal});pages.addEventListener('load',reflowAfterLoad,{capture:true,signal:loadEvents.signal});
  const lifecycle=new MutationObserver(()=>{if(!controls.isConnected){cancelGeneration();generationPopup?.close();loadEvents.abort();previewResize.disconnect();clearTimeout(fontReflowTimer);lifecycle.disconnect();}});lifecycle.observe(root,{childList:true});
  let exporting=false,rendering=false,previewCurrent=false,moveQueue=Promise.resolve();
  async function runDownload(label,task){
   if(exporting)return;
   exporting=true;const dialog=node('dialog','','preview-dialog export-progress-dialog'),heading=node('h2',label+' 준비 중'),detail=node('p','출력 배치를 확인 중입니다. 내 시험지 저장은 저장 버튼으로 진행합니다.','export-progress-detail'),close=action('닫기',()=>dialog.close());close.hidden=true;dialog.append(heading,detail,close);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();
   try{if(rendering||!previewCurrent)throw Error('현재 문항 배치가 준비되지 않았습니다. 표시된 배치 오류를 확인한 뒤 다시 시도하세요.');if(!draft.items.length)throw Error('문항을 추가한 뒤 출력하세요.');if(!lastLayout||lastLayout.overflows.length)throw Error('문항 로딩 또는 넘침을 먼저 해결하세요.');await task(detail);heading.textContent=label+' 파일 생성 완료';detail.textContent='파일 생성이 끝나 다운로드를 시작했습니다. 브라우저의 다운로드 목록에서 저장 결과를 확인하세요.';}
   catch(e){heading.textContent=label+' 생성 실패';detail.textContent=e.message;status.textContent=label+' 생성 실패: '+e.message;}
   finally{exporting=false;close.hidden=false;}
  }
  outputActions.append(action('DOCX 다운로드',()=>runDownload('DOCX',async detail=>{detail.textContent='문항·그림을 문서에 담는 중입니다.';const {exportDocx}=await import('./web-export.js');await exportDocx({draft,loaded,layout:lastLayout,pages,reader,status:detail});})),action('PDF 다운로드',()=>runDownload('PDF',async detail=>{detail.textContent='글꼴·그림을 확인하는 중입니다.';const {exportPdf}=await import('./web-export.js');await exportPdf(pages,draft.title,detail);})),action('HWPX 다운로드',()=>runDownload('HWPX',async detail=>{const {exportHwpx}=await import('./web-export.js');await exportHwpx({draft,loaded,layout:lastLayout,pages,status:detail});})));
 versionActions.append(action('최신 문항 버전 확인·적용',async()=>{const updates=[];for(const item of draft.items){const latest=await rpc('bank_exam_latest',{s:config.spaceId,q:item.questionId});if(latest&&latest!==item.revisionId)updates.push({item,latest});}if(!updates.length){message('모든 문항이 현재 확인 가능한 최신 버전입니다.');return;}if(!confirm(`${updates.length}문항의 최신 버전이 있습니다. 편집 중인 시험지에 최신 버전을 적용할까요? 적용 후 저장 버튼으로 저장하세요.`))return;for(const {item,latest} of updates){item.revisionId=latest;item.selectedSolutionId=null;item.solutionSnapshot=null;delete item.scoreSnapshot;delete item.responseType;}persist();await render();message(`${updates.length}문항을 최신 버전으로 바꿨습니다. 출력 전에 내용을 확인하세요.`); }));
  async function render({persistLayout=true,isValid=()=>true,sortAutomatic=false,onProgress=()=>{},awaitPending=p=>p}={}){const gen=++generation,expandedTools=new Set([...items.querySelectorAll('details[open]')].map(x=>x.dataset.questionId)),previousScroll=viewport.scrollTop;rendering=true;previewCurrent=false;let nextLayout=null;const nextItems=document.createDocumentFragment(),nextPages=node('div','','exam-pages');nextPages.style.cssText='position:fixed;left:-20000px;top:0;visibility:hidden';root.append(nextPages);status.textContent='문항·수식·도형 크기 확인 중…';updatePaperComposition();const renderLoaded=[];
  const measure=node('div','','exam-measure'+(isMock(draft)?' mock-measure':''));root.append(measure);try{
   const measured=[];for(const [i,item] of draft.items.entries()){
    const r=preparedPreview?.get(item.revisionId)||await awaitPending(reader.render(item.revisionId,{printedNumber:draft.preserveOriginalOrder?item.originalNumber:null}));if(gen!==generation||!isValid()||!controls.isConnected)return false;if(item.selectedSolutionId){const solution=item.solutionSnapshot||r.catalog.confirmed?.scopeEvidence?.solutions?.find(s=>(s.id||s.label)===item.selectedSolutionId&&s.verified&&s.complete);if(!solution?.text)throw Error('선택한 허용 풀이 원문이 없습니다.');r.question={...r.question,solution:solution.text};}if(item.scoreSnapshot===undefined){const catalog=structuredClone(r.catalog);applyCalibration?.(catalog);item.scoreSnapshot=model.numericScore(catalog);}paperCatalogs.set(item.revisionId,r.catalog);updatePaperComposition();renderLoaded.push(r);
     if(item.originalPoints===null||item.originalPoints===undefined||item.originalPoints==='')item.originalPoints=sourceInfo(r.catalog).points??textTools.sourcePoints(r.question)??null;
     const printed=draft.preserveOriginalOrder?originalQuestion.printedTitle(item.originalNumber):String(i+1);const q=questionArticle(r.element,{index:i,number:printed,fontSize:draft.bodyFontSize??10,points:draft.showOriginalPoints&&item.originalPoints!=null?formatSourcePoints(item.originalPoints):null,source:draft.showSourceOnPaper?(item.sourceCaption||sourceLabel(r.catalog)):null});measure.append(q);
    q.dataset.questionId=item.questionId;
    await awaitPending(document.fonts.ready);await awaitPending(Promise.all([...q.querySelectorAll('img')].map(async img=>{await img.decode();img.dataset.measuredSize=`${img.naturalWidth}x${img.naturalHeight}`;})));if(gen!==generation||!isValid()||!controls.isConnected)return false;scaleQuestionFigures(r.element,draft.figureScalePercent);
    if(r.element.dataset.incomplete)throw Error(`${i+1}번 그림이 누락되어 출력을 중지합니다.`);
    measured.push({...item,responseType:model.responseType(r.catalog.metadata),height:q.getBoundingClientRect().height,element:q});onProgress('문항 크기를 확인하고 배치하고 있습니다.',i+1,draft.items.length);
    const tool=node('details','','exam-item-tool'),row=node('div','','exam-item-fields'),space=field(row,`${i+1}번 풀이공간(mm)`,item.workspaceMm||0,'number');tool.dataset.questionId=item.questionId;tool.open=expandedTools.has(item.questionId);tool.append(node('summary',`${i+1}번 · 풀이공간 ${item.workspaceMm||0}mm · ${item.breakBefore==='page'?'다음 페이지':item.breakBefore==='column'?'다음 단':'자동 배치'}`));space.min=0;space.max=200;space.onchange=()=>{item.workspaceMm=Math.max(0,Math.min(200,Number(space.value)||0));persist();render();};
    const br=node('select');for(const [value,label]of [['','자동 배치'],['column','다음 단'],['page','다음 페이지']]){const o=node('option',label);o.value=value;br.append(o);}br.value=item.breakBefore||'';br.onchange=()=>{item.breakBefore=br.value||null;persist();render();};row.append(br);
    for(const [label,d]of [['위로',-1],['아래로',1]])row.append(action(label,()=>move(i,Math.max(0,Math.min(draft.items.length-1,i+d)))));
    row.append(action('제외',()=>{draft.items.splice(i,1);persist();render();}));tool.append(row);nextItems.append(tool);
   }
   if(gen!==generation||!isValid()||!controls.isConnected)return false;
   if(sortAutomatic&&!draft.preserveOriginalOrder){const ordered=model.sortMeasured(measured),ids=ordered.map(x=>x.questionId);draft.orderPolicy='non-written-then-written-half-point-height-v2';if(ids.some((id,i)=>id!==draft.items[i].questionId)){const byId=new Map(draft.items.map(x=>[x.questionId,x]));draft.items=ids.map(id=>byId.get(id));preparedPreview=new Map(renderLoaded.map(r=>[r.catalog.revision_id,r]));return await render({persistLayout,isValid,onProgress,awaitPending});}}
   const contentHeight=pageContentHeight(),geometry=isMock(draft)?await measureForm(node,draft):null;
   if(gen!==generation||!isValid()||!controls.isConnected)return false;
   const fragmenters=[];
   try{for(const [i,item]of measured.entries())if(item.height>(geometry?.height??contentHeight)){
    const r=renderLoaded[i],q={...r.question,originalPoints:draft.showOriginalPoints?draft.items[i].originalPoints:null,sourceCaption:draft.showSourceOnPaper?(draft.items[i].sourceCaption||sourceLabel(r.catalog)):null};
    item.fragmenter=questionFragmenter({question:q,figures:r.figures,article:item.element,measure,workspacePx:(item.workspaceMm||0)*MM});fragmenters.push(item.fragmenter);
   }
   nextLayout=geometry?formModel.paginateForm(measured,geometry):model.paginateQuadrants(measured,contentHeight);
   }finally{fragmenters.forEach(f=>f.dispose());}
    updateSourceWarning();for(const [pi,p]of nextLayout.pages.entries()){const page=node('section','','exam-page'+formClass(draft)),header=geometry?formHeader(node,draft,pi):examPageHeader(node,draft.title,pi);page.append(header,geometry?formFooter(node,pi,nextLayout.pages.length):node('span',String(pi+1),'page-number'));const cols=node('div','','exam-columns');if(geometry)cols.style.height=(pi===0?geometry.firstHeight:geometry.height)+'px';
    p.columns.forEach((col,ci)=>{const column=node('div','','exam-column');column.dataset.page=pi;column.dataset.column=ci;if(geometry&&pi===0&&ci===0)column.append(formIntro(node,draft));for(const item of col){const q=item.element;q.style.position='absolute';q.style.top=item.top+'px';q.style.left='0';q.style.right='0';q.style.marginBottom='0';column.append(q);q.draggable=matchMedia('(pointer:fine)').matches;q.ondragstart=e=>e.dataTransfer.setData('text/plain',q.dataset.index);q.ondragover=e=>{e.preventDefault();q.classList.add('drop-target');};q.ondragleave=()=>q.classList.remove('drop-target');q.ondrop=e=>{e.preventDefault();move(Number(e.dataTransfer.getData('text/plain')),Number(q.dataset.index));};
     const handle=node('button','끌어서 이동','drag-handle');handle.onpointerdown=e=>{e.preventDefault();q.draggable=false;handle.setPointerCapture(e.pointerId);handle.classList.add('dragging');};handle.onpointermove=e=>{if(!handle.hasPointerCapture(e.pointerId))return;for(const t of pages.querySelectorAll('.drop-target'))t.classList.remove('drop-target');const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.print-question,.exam-column');if(target&&target!==q)target.classList.add('drop-target');};handle.onpointercancel=()=>{q.draggable=matchMedia('(pointer:fine)').matches;handle.classList.remove('dragging');for(const t of pages.querySelectorAll('.drop-target'))t.classList.remove('drop-target');};handle.onpointerup=e=>{q.draggable=matchMedia('(pointer:fine)').matches;handle.classList.remove('dragging');for(const t of pages.querySelectorAll('.drop-target'))t.classList.remove('drop-target');const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.print-question,.exam-column');if(!target||target===q)return;if(target.classList.contains('print-question'))move(Number(q.dataset.index),Number(target.dataset.index));else{const at=Number(q.dataset.index),first=target.querySelector('.print-question');move(at,first?Number(first.dataset.index):draft.items.length-1,target.dataset.column==='0'?'page':'column');}};q.prepend(handle);}
     column.ondragover=e=>e.preventDefault();column.ondrop=e=>{if(e.target!==column)return;e.preventDefault();const at=Number(e.dataTransfer.getData('text/plain')),item=draft.items[at];if(!item)return;const before=col[0]?draft.items.findIndex(i=>i.questionId===col[0].questionId):draft.items.length-1;move(at,before,ci===0?'page':'column');};cols.append(column);});page.append(cols);nextPages.append(page);fitFormTitles(page);
   }
    const answerGeometry=draft.items.length?await measureAnswer(node,draft.title):null;
    if(gen!==generation||!isValid()||!controls.isConnected)return false;
    if(draft.items.length&&draft.answerMode==='detailed'){if(!await awaitPending(appendSolutionPages({pages:nextPages,title:draft.title,loaded:renderLoaded,items:draft.items.map((item,i)=>({...item,originalNumber:draft.preserveOriginalOrder?item.originalNumber:String(i+1)})),node,mathText,height:answerGeometry.height,paddingTop:answerGeometry.paddingTop,isValid:()=>gen===generation&&isValid()&&controls.isConnected})))return false;}
    else if(draft.items.length){const answers=[],answerMeasure=node('div','','exam-measure answer-page');measure.append(answerMeasure);let answerGap=0,answerTop=0,answerBottom=0;for(const [i,r]of renderLoaded.entries()){const block=node('article');block.style.fontSize='9pt';const number=originalQuestion.answerTitle(draft.preserveOriginalOrder&&draft.items[i].originalNumber||String(i+1));block.append(mathText(`${number}. ${r.question.answer||'정답 미작성'}`));answerMeasure.append(block);await awaitPending(document.fonts.ready);if(gen!==generation||!isValid()||!controls.isConnected)return false;const style=getComputedStyle(block),top=parseFloat(style.marginTop)||0,bottom=parseFloat(style.marginBottom)||0;answerGap=Math.max(answerGap,top,bottom);answerTop=Math.max(answerTop,top);answerBottom=Math.max(answerBottom,bottom);answers.push({questionId:'answer-'+i,height:block.getBoundingClientRect().height,element:block});onProgress('정답·해설 연결과 페이지 배치를 확인하고 있습니다.',i+1,draft.items.length);}
    const answerLayout=model.paginate(answers,answerGeometry.height-answerTop-answerBottom,answerGap);nextLayout.overflows.push(...answerLayout.overflows);
    for(const p of answerLayout.pages){const answer=node('section','','exam-page answer-page');answer.style.paddingTop=answerGeometry.paddingTop+'px';answer.append(answerHeader(node,draft.title));const cols=node('div','','exam-columns');for(const col of p.columns){const column=node('div','','exam-column');for(const b of col)column.append(b.element);cols.append(column);}answer.append(cols);nextPages.append(answer);fitFormTitles(answer);}
   }
   status.textContent=`문제 ${draft.items.length}문항 · 문제 페이지 ${nextLayout.pages.length}쪽${nextLayout.overflows.length?' · 한 단을 넘는 문항: '+nextLayout.overflows.map(id=>String(id).startsWith('answer-')?'해설 '+(Number(id.slice(7))+1):draft.items.findIndex(i=>i.questionId===id)+1).join(', ')+'번. 공간 또는 글자·그림 크기를 조정하세요.':''}`;
   if(draft.rules.profile){const scores=draft.items.filter(i=>i.scoreSnapshot!==null&&i.scoreSnapshot!==undefined&&i.scoreSnapshot!=='').map(i=>Number(i.scoreSnapshot)).filter(Number.isFinite),slots={low:0,middle:0,high:0,manual:0};for(const item of draft.items)slots[item.profileSlot]!==undefined?slots[item.profileSlot]++:slots.manual++;profileResult.textContent=`현재 배치 ${draft.items.length}문항 · 하 ${slots.low} · 중 ${slots.middle} · 상 ${slots.high} · 직접 추가/미지정 ${slots.manual} · 실제 문항 난이도 평균 ${scores.length===draft.items.length&&scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(2):'미평가 포함'} / 생성 당시 목표 ${Number(draft.rules.profile.targetAverage).toFixed(2)}`;}
   if(draft.rules.count){const check=model.selectQuestions(renderLoaded.map(r=>{const c=structuredClone(r.catalog);applyCalibration?.(c);return c;}),{...draft.rules,scopeDistribution:false});if(!check.complete||draft.items.length!==draft.rules.count)status.textContent+=' · 수동 구성 결과가 저장된 조건과 다릅니다. 문항은 자동 변경하지 않았습니다.';}
     if(gen!==generation||!isValid()||!controls.isConnected)return false;loaded=renderLoaded;lastLayout=nextLayout;pages.replaceChildren(...nextPages.childNodes);items.replaceChildren(nextItems);previewCurrent=true;applyPreviewZoom();viewport.scrollTop=previousScroll;requestAnimationFrame(updateScrollbar);draft.layout=nextLayout.pages.map(p=>({columns:p.columns.map(col=>col.map(x=>x.questionId))}));if(persistLayout&&(change>committed||draft.version===0))persist({derived:true});return !nextLayout.overflows.length;
  }catch(e){if(gen===generation&&controls.isConnected){status.textContent='배치 실패: '+e.message;nextLayout=null;}return false;}finally{if(gen===generation){preparedPreview=null;rendering=false;}measure.remove();nextPages.remove();}
 }
 function move(from,to,breakBefore){
  if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0)return Promise.resolve(false);
  // The displayed indices remain unchanged while a new preview is loading.
  // Capture identities before queuing; a second gesture must not move another
  // question just because the first gesture has changed the draft indices.
  const source=pages.querySelector(`.print-question[data-index="${from}"]`)?.dataset.questionId;
  const target=pages.querySelector(`.print-question[data-index="${to}"]`)?.dataset.questionId;
  if(!source||!target||source===target)return Promise.resolve(false);
  const task=moveQueue.then(()=>moveQuestion(source,target,breakBefore));
  moveQueue=task.catch(()=>false);return task;
 }
 async function moveQuestion(source,target,breakBefore){
  const from=draft.items.findIndex(q=>q.questionId===source),to=draft.items.findIndex(q=>q.questionId===target);
  if(from<0||to<0)return false;
  const previous=structuredClone(draft.items),wasCurrent=previewCurrent;const next=draft.items.slice(),[item]=next.splice(from,1);
  next.splice(to,0,breakBefore?{...item,breakBefore}:item);draft.items=next;
  const expected=generation+1,ok=await render({persistLayout:false});
  if(expected!==generation)return false;
  if(!previewCurrent){draft.items=previous;previewCurrent=wasCurrent;updatePaperComposition();updateSourceWarning();return false;}
  persist();return ok;
 }
 const initialRendered=await render(ctx.initialLoad);if(downloadFocus)toolbar.scrollIntoView({block:'start'});return initialRendered;
}
export function blobDownload(name,blob){
 const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.textContent=name+' 다시 내려받기';
 let tray=document.getElementById('generated-downloads');if(!tray){tray=document.createElement('div');tray.id='generated-downloads';tray.className='panel';tray.setAttribute('aria-label','생성된 파일');document.getElementById('view').append(tray);}
 tray.append(a,document.createElement('br'));a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.removeAttribute('href');a.textContent=name+' · 다시 생성해 주세요';},600000);
}
