import mock from './mock-exam-model.cjs';
import model from '../app/bank-exam-model.cjs';
import curriculum from '../app/curriculum.js';
import {scopeTree} from './scope-tree.js';
import {formLoader,savedPaperForm} from './paper-form-settings.js';
import {formControls} from './exam-form.js';
import {examEditor} from './exam-editor.js';
import {composeInWorker} from './exam-composition-task.js';
import {compositionFailureText,difficultyMapping} from './composition-summary.js';
import {mathText} from './math-text.js';
import {sourceLabel} from './presentation.js';
import {setEditGuard} from './edit-guard.js';

export async function mockExams(ctx){
 const {root,user,config,rpc,node,action,field,navigate,message,reader}=ctx;
 root.classList.add('mock-exams-page');
 const key='bank-mock-work:'+config.spaceId+':'+user.id;
 let doc,baseline='',busy=false,abort=null,handle=null;
 const route=ctx.mockId||'list';
 async function listAll(){const all=[];for(let offset=0;;offset+=30){const page=await rpc('bank_mock_list',{s:config.spaceId,start_at:offset});all.push(...page);if(page.length<30)return all;}}
 if(route==='list'){
  root.append(action('새 실전모의고사 출제하기',()=>navigate('mock-exams/new'),true));
  const working=sessionStorage.getItem(key);if(working)root.append(action('작성 중인 모의고사 이어 열기',()=>navigate('mock-exams/work')));
  const list=node('div','','exam-library');root.append(list);
  const notice=popup('저장된 모의고사');notice.body.append(node('p','목록을 불러오는 중입니다.','hint'));let exams,listFailed=false;try{exams=await listAll();notice.body.replaceChildren(node('p',exams.length+'개의 저장된 모의고사를 불러왔습니다.'));}catch(e){notice.body.replaceChildren(node('p','불러오기 실패: '+e.message,'error'));exams=[];listFailed=true;}notice.footer.append(action('확인',()=>notice.d.close(),true));for(const e of exams){const card=node('article','','panel');card.append(node('strong',e.title),node('p',`${e.variant_count}개 유형 · ${new Date(e.updated_at).toLocaleString('ko-KR')} 저장`,'hint'),action('불러오기',()=>navigate('mock-exams/'+e.id)));list.append(card);}if(!exams.length&&!listFailed)list.append(node('p','저장된 모의고사가 없습니다.'));return;
 }
 if(route==='new'){doc=mock.create(crypto.randomUUID());doc.paperForm=savedPaperForm(config,user);mock.addVariant(doc,'A',crypto.randomUUID());}
 else if(route==='work'){doc=JSON.parse(sessionStorage.getItem(key)||'null');if(!doc)throw Error('작성 중인 모의고사가 없습니다.');}
 else{const loading=popup('모의고사 불러오기');loading.body.append(node('p','저장한 시험지를 불러오는 중입니다.'));try{const saved=await rpc('bank_mock_get',{s:config.spaceId,e:route});doc={...saved.document,version:saved.version};baseline=JSON.stringify(doc);loading.d.close();}catch(e){loading.body.replaceChildren(node('p','불러오기 실패: '+e.message,'error'));loading.footer.append(action('닫기',()=>loading.d.close()));return;}}
 doc=mock.normalize(doc);if(baseline)baseline=JSON.stringify(doc);
 const controls=node('div','','mock-settings'),cards=node('div','','mock-variants'),status=node('p','','hint'),result=node('div','','mock-result'),buttons=node('div','','actions mock-main-actions'),papers=node('section','','mock-papers');papers.hidden=true;root.append(controls,cards,buttons,status,result,papers);let viewerGeneration=0;
 const persist=()=>{try{sessionStorage.setItem(key,JSON.stringify(doc));status.textContent='편집 중 · 저장 버튼으로 모의고사 전체를 저장하세요.';}catch{status.textContent='이 기기의 임시 저장 공간이 부족합니다. 현재 편집 내용은 화면에 유지됩니다. 모의고사 저장 버튼으로 서버에 저장하세요.';}};
 async function save(){const {d,body,footer}=popup('모의고사 저장');body.append(node('p','모의고사를 저장하고 있습니다.','hint'));let ok=false;try{if(busy)throw Error('출제가 끝난 뒤 저장하세요.');if(!doc.title.trim())throw Error('시험지 이름을 입력하세요.');const savedDoc=structuredClone(doc),response=await rpc('bank_mock_save',{s:config.spaceId,e:doc.id,expected:doc.version,doc:savedDoc});doc.version=response.version;baseline=JSON.stringify({...savedDoc,version:response.version});try{sessionStorage.setItem(key,JSON.stringify(doc));}catch{}status.textContent=JSON.stringify(doc)===baseline?'모의고사 서버 저장 완료':'서버 저장 이후 변경 내용이 있습니다.';body.replaceChildren(node('p','저장 완료','mock-success'),node('strong',savedDoc.title),node('p',savedDoc.variants.length+'개 유형을 저장했습니다. 저장된 모의고사에서 다시 열 수 있습니다.','hint'));ok=true;}catch(e){body.replaceChildren(node('p','저장 실패: '+e.message,'error'));}footer.append(action('확인',()=>d.close(),true));return ok;}
 const guard=()=>setEditGuard({dirty:()=>JSON.stringify(doc)!==baseline,save,discard:()=>sessionStorage.removeItem(key)});guard();
 function popup(title,wide=false){const d=node('dialog','',wide?'mock-dialog mock-layout-dialog':'mock-dialog'),heading=node('h2',title),body=node('div','','mock-dialog-body'),footer=node('div','','actions mock-dialog-footer');d.setAttribute('aria-label',title);d.append(heading,body,footer);root.append(d);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return {d,body,footer};}
 function editForm(){const {d,body,footer}=popup('현재 모의고사 시험지 폼');const draft={paperForm:structuredClone(doc.paperForm),title:doc.title,rules:{units:[]}};formControls({controls:body,getDraft:()=>draft,node,action,field,user,config,persist:()=>{},render:()=>{},message});footer.append(action('적용',()=>{doc.paperForm=structuredClone(draft.paperForm);persist();d.close();renderControls();}),action('취소',()=>d.close()));}
 function scopePopup(id){const v=doc.variants.find(v=>v.id===id),{d,body,footer}=popup(v.label+' 시험범위');const selected=new Set(v.units);body.append(scopeTree({node,selected}).element);footer.append(action('범위 적용',()=>{v.units=[...selected];persist();renderCards();d.close();}),action('취소',()=>d.close()));}
 async function schoolPopup(){const {d,body,footer}=popup('출처 학교 선택');body.append(node('p','선택 학교의 기출문제를 우선 사용합니다. 부족할 때 직접 선택한 대체 후보만 추가할 수 있습니다.','hint'));const schools=await rpc('bank_mock_schools',{s:config.spaceId});if(!d.isConnected)return;const selected=new Set(doc.schools),search=field(body,'학교 검색'),list=node('div','','mock-picker');body.append(list);const entries=[];for(const school of [...new Set([...schools,...doc.schools])].sort()){const row=node('label'),check=node('input');check.type='checkbox';check.checked=selected.has(school);check.onchange=()=>check.checked?selected.add(school):selected.delete(school);row.append(check,document.createTextNode(school));list.append(row);entries.push([school,row]);}search.oninput=()=>entries.forEach(([name,row])=>row.hidden=!name.includes(search.value.trim()));footer.append(action('학교 적용',()=>{doc.schools=[...selected];persist();renderControls();d.close();}),action('취소',()=>d.close()));}
 async function excludePopup(){const {d,body,footer}=popup('중복 제외할 모의고사 선택'),selected=new Set(doc.excludeExamIds);body.append(node('p','선택한 모의고사의 모든 유형에서 사용한 문항을 제외합니다. 현재 모의고사 안의 공유는 허용합니다.','hint'));const exams=await listAll();if(!d.isConnected)return;for(const e of exams.filter(e=>e.id!==doc.id)){const row=node('label'),check=node('input');check.type='checkbox';check.checked=selected.has(e.id);check.onchange=()=>check.checked?selected.add(e.id):selected.delete(e.id);row.append(check,document.createTextNode(e.title));body.append(row);}footer.append(action('제외 대상 적용',()=>{doc.excludeExamIds=[...selected];persist();renderControls();d.close();}),action('취소',()=>d.close()));}
 function renderControls(){controls.replaceChildren();formLoader({controls,getDraft:()=>doc,node,action,config,user,persist,render:()=>{},message,edit:editForm});const title=field(controls,'시험지 이름',doc.title);title.oninput=()=>{mock.rename(doc,title.value);persist();};
  const countBox=node('div','','mock-counts');controls.append(node('h3','유형별 문항 구성'),countBox);
  for(const kind of Object.keys(doc.counts)){const row=node('div','','mock-count-row');row.append(node('strong',kind+'형'));for(const [k,label]of [['choice','객관식'],['written','서술형']]){const n=field(row,kind+'형 '+label,doc.counts[kind][k]??'','number');n.min=0;n.max=100;n.step=1;n.inputMode='numeric';n.onchange=()=>{doc.counts[kind][k]=n.value===''?null:Number(n.value);persist();renderCards();};}countBox.append(row);}
  controls.append(action('문항 구성 형 추가',()=>{mock.addKind(doc);persist();renderControls();renderCards();}));
  controls.append(node('h3','모든 유형에 적용할 공통 난이도'));
  const targetBox=node('div','','mock-target'),target=field(targetBox,'목표 난이도 (점)',doc.profile.targetAverage??'','number'),auto=node('span','','hint');target.min=0;target.max=10;target.step=.01;target.placeholder='자동 계산';target.inputMode='decimal';targetBox.append(auto);controls.append(targetBox);
  const ratios=node('div','','mock-ratios'),inputs={};controls.append(ratios);
  const refresh=()=>{for(const k of Object.keys(inputs))inputs[k].value=doc.profile[k];auto.textContent=doc.profile.targetAverage==null?'자동 계산: '+Number(model.profileAverage(doc.profile).toFixed(2))+'점':'빈칸이면 비중에 따라 자동 계산';};
  target.onchange=()=>{const value=target.value===''?null:Number(target.value);if(value!==null&&(!Number.isFinite(value)||value<0||value>10)){target.value=doc.profile.targetAverage??'';message('목표 난이도는 0~10점으로 입력하세요.',true);return;}doc.profile.targetAverage=value;refresh();persist();renderCards();};
  for(const [k,label]of [['high','상'],['middle','중'],['low','하']]){const input=field(ratios,label+' 비중 (%)',doc.profile[k],'number');input.min=0;input.max=100;input.step=1;input.inputMode='numeric';input.classList.add('mock-ratio-'+k);inputs[k]=input;input.onchange=()=>{const value=Math.round(Math.max(0,Math.min(100,Number(input.value)||0))),other=k==='low'?'high':'low',remaining=k==='middle'?'high':'middle';doc.profile[k]=value;doc.profile[other]=Math.min(doc.profile[other],100-value);doc.profile[remaining]=100-value-doc.profile[other];refresh();persist();renderCards();};}refresh();
  const details=node('details','','hint');details.append(node('summary','난이도 기준 보기'),node('p',difficultyMapping));controls.append(details);
  const picks=node('div','','mock-picks'),schoolRow=node('div','','mock-pick-row'),excludeRow=node('div','','mock-pick-row'),schoolButton=action('출처 학교 선택',schoolPopup,true);schoolButton.classList.add('mock-school-button');schoolRow.append(schoolButton,node('span',doc.schools.join(', ')||'선택한 학교 없음','mock-pick-value'));excludeRow.append(action('중복 제외할 모의고사 선택',excludePopup),node('span',doc.excludeExamIds.length+'개 선택','mock-pick-value'));picks.append(schoolRow,excludeRow);controls.append(picks,node('p','설정 변경은 다음 출제에 적용됩니다. 생성된 유형은 재출제 버튼을 누를 때까지 문항·배치를 유지합니다.','hint'));
  let section;for(const child of [...controls.childNodes]){if(!section||child.tagName==='H3'){section=node('section','','mock-settings-section');controls.append(section);}section.append(child);}
 }

 function renderCards(){cards.replaceChildren(node('h3','개별 유형'));for(const v of doc.variants){const card=node('section','','panel mock-variant');card.dataset.variantId=v.id;const names=curriculum.leaves.filter(u=>v.units.includes(u.id)).map(u=>u.title);let detail='범위 미설정';if(names.length)detail=names.slice(0,4).join(', ')+(names.length>4?` 외 ${names.length-4}개 세부 단원`:'');card.append(node('strong',v.label),node('span',detail),node('span',v.paper?`${v.paper.items.length}문항 생성됨`:'미출제'));const actions=node('div','','actions');actions.append(action('시험범위 설정',()=>scopePopup(v.id)),action(v.paper?'이 유형 재출제':'이 유형 출제',()=>generate([v.id])));if(v.paper)actions.append(action('시험지 보기',()=>showPapers(v.id)),action('배치·출력',()=>layoutPopup(v.id)));if(v.supplementIds?.length)actions.append(action('추가 후보 '+v.supplementIds.length+'개 초기화',()=>{v.supplementIds=[];persist();renderCards();}));actions.append(action('유형 삭제',()=>{doc.variants=doc.variants.filter(x=>x.id!==v.id);persist();renderCards();}));card.append(actions);if(v.paper){let current;try{current=mock.rulesFor(doc,v,v.paper.rules.excludeIds);}catch{}if(!current||JSON.stringify(current)!==JSON.stringify(v.paper.rules))card.append(node('p','설정이 변경되었습니다. 생성된 시험지는 이전 조건을 유지하고 있습니다.','hint'));}cards.append(card);}
  const add=node('div','','actions');for(const kind of Object.keys(doc.counts))add.append(action(kind+'형 추가',()=>{mock.addVariant(doc,kind,crypto.randomUUID());persist();renderCards();}));cards.append(add);const start=action('출제 시작',()=>generate(doc.variants.map(v=>v.id)),true);start.classList.add('mock-start');cards.append(start);
 }
 async function openEditor(body,paper,onChange,{sortAutomatic=false}={}){let localHandle;await examEditor({...ctx,root:body,examId:'new',chosen:[],rows:async()=>[],save:()=>{},initialLoad:{sortAutomatic},embedded:{draft:paper,onChange,setHandle:h=>localHandle=h}});return localHandle;}
 async function layoutPopup(id){const v=doc.variants.find(v=>v.id===id),{d,body,footer}=popup(v.label+' 배치·출력',true);let next={...structuredClone(v.paper),title:mock.paperTitle(doc,v)};handle=await openEditor(body,next,p=>next=p);const h=handle;footer.append(action('배치 적용',()=>{if(!h?.ready())throw Error('현재 배치 준비가 끝난 뒤 적용하세요.');const paper=h.getDraft();if(paper.items.length!==v.paper.items.length||paper.items.some(i=>!v.paper.items.some(old=>old.questionId===i.questionId&&old.revisionId===i.revisionId)))throw Error('문항 구성이 바뀌어 배치를 적용하지 않았습니다.');v.paper=paper;persist();d.close();renderCards();}),action('닫기',()=>d.close()));}
 function showSettings(){viewerGeneration++;papers.replaceChildren();papers.hidden=true;for(const el of [controls,cards,buttons,status,result])el.hidden=false;controls.scrollIntoView({block:'start'});}
 async function showPapers(id,notice=''){
  const generated=doc.variants.filter(v=>v.paper);if(!generated.length)return;
  const epoch=++viewerGeneration;for(const el of [controls,cards,buttons,status,result])el.hidden=true;papers.hidden=false;papers.replaceChildren();
  const bar=node('div','','mock-paper-heading'),tabs=node('div','','mock-paper-tabs'),editor=node('div','','mock-paper-editor');bar.append(node('h3',doc.title),action('출제 설정으로 돌아가기',showSettings));papers.append(bar);
  const messageText=notice||'제작한 시험지를 확인하고 배치·출력할 수 있습니다.';papers.append(node('p',messageText,'mock-success'));const totals=node('div','','mock-paper-stats');for(const [value,label]of [[generated.length,'유형'],[generated.reduce((n,v)=>n+v.paper.items.length,0),'배치 문항'],[new Set(generated.flatMap(v=>v.paper.items.map(i=>i.questionId))).size,'서로 다른 문항']]){const cell=node('div');cell.append(node('strong',String(value)),node('span',label));totals.append(cell);}papers.append(totals);
  const selected=generated.find(v=>v.id===id)||generated[0];tabs.setAttribute('aria-label','시험지 유형 선택');for(const v of generated){const b=action(v.label,()=>showPapers(v.id));b.setAttribute('aria-pressed',String(v.id===selected.id));tabs.append(b);}papers.append(tabs,node('p','배치 변경은 작성 중인 모의고사에 유지됩니다. 다른 기기에서 보려면 모의고사를 저장하세요.','hint'),action('모의고사 저장',save,true),editor);papers.scrollIntoView({block:'start'});
  const loading=node('p',selected.label+' 시험지를 준비하고 있습니다.','hint');editor.append(loading);
  try{const h=await openEditor(editor,structuredClone(selected.paper),paper=>{if(epoch!==viewerGeneration)return;selected.paper=paper;persist();});loading.remove();if(epoch===viewerGeneration){const settings=editor.querySelector(':scope > .panel');if(settings){const details=node('details','','mock-paper-options');details.append(node('summary','시험지 표시 설정'));settings.before(details);details.append(settings);}for(const heading of editor.querySelectorAll(':scope > h3')){heading.textContent=heading.textContent.replace(/^4\. 배치 결과 확인$/,'시험지 미리보기').replace(/^5\. 저장 및 출력$/,'파일 다운로드');}}if(epoch===viewerGeneration&&!h?.ready())editor.prepend(node('p','시험지 배치를 완료하지 못했습니다. 아래 오류를 확인하세요.','error'));}catch(e){if(epoch===viewerGeneration)loading.textContent='시험지 열기 실패: '+e.message;}
 }
 async function recommendations(targetIds,previewOnly){
  const {d,body,footer}=popup('부족 문항 추가 선택'),controller=new AbortController();d.classList.add('mock-recommendations');d.addEventListener('close',()=>controller.abort(),{once:true});body.append(node('p','전체 문항에서 범위·문항 유형·난이도를 확인하고 있습니다.','hint'));footer.append(action('취소',()=>d.close()));
  try{
   const start=JSON.stringify(doc),snapshot=await rpc('bank_mock_recommendation_snapshot',{s:config.spaceId,exclude_exams:doc.excludeExamIds},{signal:controller.signal});
   const groups=await composeInWorker(null,null,{signal:controller.signal,request:{recommend:true,document:structuredClone(doc),snapshot,targetIds}});if(!d.isConnected)return;
   body.replaceChildren(node('p','필요한 문항 유형·단원·난이도를 고려한 추천입니다. 중복 제외 모의고사의 문항은 제외했습니다. 선택한 문항을 추가 후보로 사용해 모든 조건을 다시 검사합니다.','hint'));
   const selections=new Map(),summary=node('p','','mock-selection-summary');body.append(summary);const refresh=()=>summary.textContent=[...selections].map(([id,set])=>doc.variants.find(v=>v.id===id).label+' '+set.size+'개').join(' · ');
   for(const group of groups){if(!group.failure)continue;const section=node('section','','mock-recommend-group'),selected=new Set();selections.set(group.id,selected);section.append(node('h3',group.label+' 추가 후보'),node('p',compositionFailureText(group.failure),'hint'));if(!group.complete)section.append(node('p','전체 문항에서도 현재 조건을 모두 충족하지 못합니다. 선택 후 부족 항목을 다시 확인하거나 범위를 조정하세요.','hint'));if(!group.candidates.length)section.append(node('p','범위·유형·중복 제외 조건에 맞는 추가 후보가 없습니다.','error'));
    const list=node('div','','mock-recommend-list');section.append(list);body.append(section);let shown=0;const more=action('후보 더 보기',()=>append());
    function append(){for(const c of group.candidates.slice(shown,shown+20)){const card=node('article','','mock-recommend-card'),check=node('input'),label=node('label'),cl=c.metadata?.classification||{},unit=cl.confirmed?.primaryUnit||cl.primaryUnit||cl.suggested?.primaryUnit,unitText=curriculum.leaves.find(u=>u.id===(unit?.id||unit))?.title||unit?.name||'범위 적합',preferred=group.suggestedIds.includes(c.question_id);check.type='checkbox';check.setAttribute('aria-label',group.label+' '+c.question_id+' 추가');check.onchange=()=>{check.checked?selected.add(c.question_id):selected.delete(c.question_id);refresh();};label.append(check,node('span',(preferred?'추천 · ':'')+(model.responseType(c.metadata)==='선택형'?'객관식':model.responseType(c.metadata))+' · '+unitText+' · '+model.numericScore(c)+'점'));card.append(label,node('p',sourceLabel(c)||c.metadata?.source?.school||'등록 문항','hint'));const snippet=mathText(c.content?.body||'문항 미리보기로 내용을 확인하세요.');snippet.classList.add('mock-recommend-snippet');card.append(snippet,action('문항 미리보기',async()=>{const peek=popup('대체 문항 미리보기');peek.body.append(node('p','문항을 불러오는 중입니다.','hint'));peek.footer.append(action('닫기',()=>peek.d.close()));try{const r=await reader.render(c.revision_id,{catalogSnapshot:c});if(peek.d.isConnected)peek.body.replaceChildren(r.element);}catch(e){peek.body.replaceChildren(node('p','미리보기 실패: '+e.message,'error'));}}));list.append(card);}shown+=20;more.hidden=shown>=group.candidates.length;}
    section.append(more);append();
   }refresh();
   const error=node('p','','error');error.hidden=true;body.append(error);footer.prepend(action('선택한 후보로 다시 출제',async()=>{const count=[...selections.values()].reduce((n,x)=>n+x.size,0);if(!count){error.hidden=false;error.textContent='추가할 문항을 선택하세요.';return;}if(JSON.stringify(doc)!==start){error.hidden=false;error.textContent='출제 설정이 변경되었습니다. 추천을 다시 열어주세요.';return;}for(const [id,ids]of selections){const v=doc.variants.find(v=>v.id===id);v.supplementIds=[...new Set([...(v.supplementIds||[]),...ids])];}persist();renderCards();d.close();await generate(targetIds,{previewOnly});},true));
  }catch(e){if(e.name!=='AbortError')body.replaceChildren(node('p','추천을 불러오지 못했습니다: '+e.message,'error'));}
 }
 async function generate(targetIds,{previewOnly=false}={}){
  if(busy)return;
  busy=true;abort=new AbortController();const controller=abort,{d,body,footer}=popup(previewOnly?'후보 구성 확인':'모의고사 출제 진행');d.classList.add('mock-progress');d.dataset.state='running';
  const progress=node('p','입력한 설정을 확인하고 있습니다.','mock-progress-status'),meter=node('progress'),steps=node('ol','','mock-progress-steps'),variantList=node('ul','','mock-progress-variants');progress.setAttribute('role','status');progress.setAttribute('aria-live','polite');meter.setAttribute('aria-label','출제 진행');meter.max=targetIds.length+3;meter.value=0;
  const labels=previewOnly?['설정 확인','후보 불러오기','전체 조건·공통문항 계산']:['설정 확인','후보 불러오기','전체 조건·공통문항 계산','유형별 시험지 준비'],stepNodes=labels.map(t=>node('li',t));steps.append(...stepNodes);const rows=new Map();for(const id of targetIds){const v=doc.variants.find(v=>v.id===id),row=node('li',(v?.label||id)+' · 대기');rows.set(id,row);variantList.append(row);}body.append(progress,meter,steps,variantList);
  const phase=(n,text)=>{stepNodes.forEach((el,i)=>{el.dataset.state=i<n?'done':i===n?'current':'waiting';el.setAttribute('aria-current',i===n?'step':'false');});progress.textContent=text;};
  let finished=false;const close=action('취소',()=>{if(finished)d.close();else{controller.abort();progress.textContent='출제를 취소하고 있습니다. 기존 결과는 유지됩니다.';}});footer.append(close);d.addEventListener('cancel',e=>{if(!finished){e.preventDefault();controller.abort();}});d.addEventListener('close',()=>{if(!finished)controller.abort();},{once:true});
  const finish=(state,text)=>{finished=true;d.dataset.state=state;progress.textContent=text;close.textContent='닫기';meter.value=state==='complete'?meter.max:Number(meter.value);meter.hidden=true;steps.hidden=true;if(state==='failed')variantList.hidden=true;if(state==='complete')stepNodes.forEach(el=>el.dataset.state='done');};
  try{
   if(!targetIds.length)throw Error('출제할 유형을 추가하세요.');if(!doc.title.trim())throw Error('시험지 이름을 입력하세요.');
   const issues=[];for(const id of targetIds){try{mock.rulesFor(doc,doc.variants.find(v=>v.id===id));}catch(e){issues.push(e.message);}}if(issues.length)throw Error([...new Set(issues)].join('\n'));
   const start=JSON.stringify(doc),requestDoc=structuredClone(doc);phase(1,'같은 시점의 문항과 중복 제외 대상을 읽는 중입니다.');meter.value=1;
   const expanded=requestDoc.variants.some(v=>targetIds.includes(v.id)&&v.supplementIds?.length);const snapshot=await rpc(expanded?'bank_mock_recommendation_snapshot':'bank_mock_snapshot',{s:config.spaceId,...(expanded?{}:{schools:requestDoc.schools}),exclude_exams:requestDoc.excludeExamIds},{signal:controller.signal});
   if(controller.signal.aborted)return;phase(2,`${snapshot.candidates.length}개 후보에서 ${targetIds.length}개 유형의 범위·문항 구성·난이도·공통문항을 함께 계산 중입니다.`);meter.removeAttribute('value');for(const row of rows.values())row.textContent=row.textContent.replace('대기','공동 구성 계산 중');
   const selection=await composeInWorker(null,null,{signal:controller.signal,request:{document:requestDoc,snapshot,targetIds}});
   if(!selection.complete){const failure=node('div');failure.append(node('h3','출제 조건 확인'));for(const f of selection.failures){rows.get(f.id).textContent=f.label+' · 조건 확인 필요';failure.append(node('h4',f.label),node('p',compositionFailureText(f),'error'));if(f.crossCounts){const table=node('table'),head=node('tr');for(const text of ['난이도','객관식 후보','서술형 후보'])head.append(node('th',text));table.append(head);for(const [band,counts]of Object.entries(f.crossCounts)){const row=node('tr');for(const text of [({low:'하',middle:'중',high:'상'})[band]||band,counts['선택형']||0,counts['서술형']||0])row.append(node('td',String(text)));table.append(row);}failure.append(table);}if(f.scopeAllocation)for(const group of f.scopeAllocation.groups)failure.append(node('p',`${group.title}: 목표 ${group.roundedTarget} / 후보 ${group.available} · 서술형 목표 ${group.roundedWrittenTarget??0} / 후보 ${group.writtenAvailable}`,'hint'));}for(const [id,row]of rows)if(!selection.failures.some(f=>f.id===id))row.textContent=requestDoc.variants.find(v=>v.id===id).label+' · 반영 보류';body.append(failure);result.replaceChildren(failure.cloneNode(true),action('다른 학교 추가',schoolPopup));finish('failed','문항이 부족하거나 출제 조건을 충족하지 못했습니다.');const ask=node('div','','mock-shortage-prompt');ask.append(node('h3','문제를 추가 선택하시겠습니까?'),node('p','전체 문항에서 대체 후보를 추천합니다. 중복 제외 조건은 그대로 적용합니다.','hint'));body.insertBefore(ask,failure);footer.prepend(action('네 · 대체 문제 추천',()=>{d.close();return recommendations(targetIds,previewOnly);},true));close.textContent='아니요 · 닫기';return;}
   meter.value=3;
   if(previewOnly){const text=`현재 후보에서 ${targetIds.length}개 유형 구성이 가능합니다. 서로 다른 문항 ${selection.sharing.distinct}개. 실제 출제 시 새 스냅샷으로 다시 검사합니다.`;for(const [id,row]of rows)row.textContent=requestDoc.variants.find(v=>v.id===id).label+' · 구성 가능';result.replaceChildren(node('p',text));finish('complete',text);return;}
   for(const [i,update]of selection.updates.entries()){
    if(controller.signal.aborted)return;const label=requestDoc.variants.find(v=>v.id===update.id).label;phase(3,`${label} 문항·수식·그림·배치 준비 (${i+1}/${selection.updates.length})`);rows.get(update.id).textContent=label+' · 시험지 준비 중';
    const stage=node('div','','mock-staging');root.append(stage);try{const h=await openEditor(stage,update.paper,()=>{},{sortAutomatic:true});if(controller.signal.aborted)return;if(!h?.ready())throw Error(label+' 문항 또는 그림·배치 준비에 실패했습니다.');update.paper=h.getDraft();rows.get(update.id).textContent=label+' · 준비 완료';meter.value=i+4;}finally{stage.replaceChildren();stage.remove();}
   }
   if(controller.signal.aborted||!root.isConnected)return;if(JSON.stringify(doc)!==start)throw Error('설정이 변경되어 출제 결과를 적용하지 않았습니다.');const next=mock.apply(doc,selection);sessionStorage.setItem(key,JSON.stringify(next));doc=next;persist();renderCards();const s=selection.sharing,text=`${targetIds.length}개 유형 출제 완료 · 총 ${s.total}문항 배치 · 서로 다른 문항 ${s.distinct}개`;result.replaceChildren(node('p',text));for(const [id,row]of rows)row.textContent=doc.variants.find(v=>v.id===id).label+' · 출제 완료';finish('complete',text);d.close();await showPapers(targetIds[0],text);
  }catch(e){if(e.name!=='AbortError'){const text='출제 실패: '+e.message+'\n기존 시험지는 유지했습니다.';result.replaceChildren(node('p',text,'error'));finish('failed',text);}}
  finally{if(controller.signal.aborted&&!finished)finish('cancelled','출제를 취소했습니다. 기존 시험지는 유지했습니다.');busy=false;abort=null;}
 }

 renderControls();renderCards();buttons.append(action('추가 유형 출제',()=>generate(doc.variants.filter(v=>!v.paper).map(v=>v.id))),action('전체 재출제',()=>generate(doc.variants.map(v=>v.id))),action('후보 구성 확인',()=>generate(doc.variants.map(v=>v.id),{previewOnly:true})),action('모의고사 저장',save,true),action('저장된 모의고사',()=>navigate('mock-exams')));if(!baseline)persist();else if(doc.variants.some(v=>v.paper))await showPapers();
 const observer=new MutationObserver(()=>{if(!root.isConnected||!controls.isConnected){abort?.abort();observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});
}
