import mock from './mock-exam-model.cjs';
import model from '../app/bank-exam-model.cjs';
import curriculum from '../app/curriculum.js';
import {scopeTree} from './scope-tree.js';
import {formLoader,savedPaperForm} from './paper-form-settings.js';
import {formControls} from './exam-form.js';
import {examEditor} from './exam-editor.js';
import {composeInWorker} from './exam-composition-task.js';
import {compositionFailureText,difficultyMapping} from './composition-summary.js';
import {setEditGuard} from './edit-guard.js';

export async function mockExams(ctx){
 const {root,user,config,rpc,node,action,field,navigate,message,reader}=ctx;
 const key='bank-mock-work:'+config.spaceId+':'+user.id;
 let doc,baseline='',busy=false,abort=null,handle=null;
 const route=ctx.mockId||'list';
 async function listAll(){const all=[];for(let offset=0;;offset+=30){const page=await rpc('bank_mock_list',{s:config.spaceId,start_at:offset});all.push(...page);if(page.length<30)return all;}}
 if(route==='list'){
  root.append(action('새 실전모의고사 출제하기',()=>navigate('mock-exams/new'),true));
  const working=sessionStorage.getItem(key);if(working)root.append(action('작성 중인 모의고사 이어 열기',()=>navigate('mock-exams/work')));
  const list=node('div','','exam-library');root.append(list);
  const exams=await listAll();for(const e of exams){const card=node('article','','panel');card.append(node('strong',e.title),node('p',`${e.variant_count}개 유형 · ${new Date(e.updated_at).toLocaleString('ko-KR')} 저장`,'hint'),action('불러오기',()=>navigate('mock-exams/'+e.id)));list.append(card);}if(!exams.length)list.append(node('p','저장된 모의고사가 없습니다.'));return;
 }
 if(route==='new'){doc=mock.create(crypto.randomUUID());doc.paperForm=savedPaperForm(config,user);mock.addVariant(doc,'A',crypto.randomUUID());}
 else if(route==='work'){doc=JSON.parse(sessionStorage.getItem(key)||'null');if(!doc)throw Error('작성 중인 모의고사가 없습니다.');}
 else{const saved=await rpc('bank_mock_get',{s:config.spaceId,e:route});doc={...saved.document,version:saved.version};baseline=JSON.stringify(doc);}
 const controls=node('div','','mock-settings'),cards=node('div','','mock-variants'),status=node('p','','hint'),result=node('div','','mock-result'),buttons=node('div','','actions');root.append(controls,cards,buttons,status,result);
 const persist=()=>{try{sessionStorage.setItem(key,JSON.stringify(doc));status.textContent='편집 중 · 저장 버튼으로 모의고사 전체를 저장하세요.';}catch{status.textContent='이 기기의 임시 저장 공간이 부족합니다. 현재 편집 내용은 화면에 유지됩니다. 모의고사 저장 버튼으로 서버에 저장하세요.';}};
 async function save(){if(busy)throw Error('출제가 끝난 뒤 저장하세요.');if(!doc.title.trim())throw Error('시험지 이름을 입력하세요.');const savedDoc=structuredClone(doc),response=await rpc('bank_mock_save',{s:config.spaceId,e:doc.id,expected:doc.version,doc:savedDoc});doc.version=response.version;baseline=JSON.stringify({...savedDoc,version:response.version});try{sessionStorage.setItem(key,JSON.stringify(doc));}catch{}status.textContent=JSON.stringify(doc)===baseline?'모의고사 서버 저장 완료':'서버 저장 이후 변경 내용이 있습니다.';return true;}
 const guard=()=>setEditGuard({dirty:()=>JSON.stringify(doc)!==baseline,save,discard:()=>sessionStorage.removeItem(key)});guard();
 function popup(title,wide=false){const d=node('dialog','',wide?'mock-dialog mock-layout-dialog':'mock-dialog'),heading=node('h2',title),body=node('div'),footer=node('div','','actions');d.setAttribute('aria-label',title);d.append(heading,body,footer);root.append(d);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return {d,body,footer};}
 function editForm(){const {d,body,footer}=popup('현재 모의고사 시험지 폼');const draft={paperForm:structuredClone(doc.paperForm),title:doc.title,rules:{units:[]}};formControls({controls:body,getDraft:()=>draft,node,action,field,user,config,persist:()=>{},render:()=>{},message});footer.append(action('적용',()=>{doc.paperForm=structuredClone(draft.paperForm);persist();d.close();renderControls();}),action('취소',()=>d.close()));}
 function scopePopup(id){const v=doc.variants.find(v=>v.id===id),{d,body,footer}=popup(v.label+' 시험범위');const selected=new Set(v.units);body.append(scopeTree({node,selected}).element);footer.append(action('범위 적용',()=>{v.units=[...selected];persist();renderCards();d.close();}),action('취소',()=>d.close()));}
 async function schoolPopup(){const {d,body,footer}=popup('출처 학교 선택');body.append(node('p','선택 학교의 기출문제만 사용합니다. 학교를 추가해도 기존 시험지는 그대로 유지됩니다.','hint'));const schools=await rpc('bank_mock_schools',{s:config.spaceId});if(!d.isConnected)return;const selected=new Set(doc.schools),search=field(body,'학교 검색'),list=node('div','','mock-picker');body.append(list);const entries=[];for(const school of [...new Set([...schools,...doc.schools])].sort()){const row=node('label'),check=node('input');check.type='checkbox';check.checked=selected.has(school);check.onchange=()=>check.checked?selected.add(school):selected.delete(school);row.append(check,document.createTextNode(school));list.append(row);entries.push([school,row]);}search.oninput=()=>entries.forEach(([name,row])=>row.hidden=!name.includes(search.value.trim()));footer.append(action('학교 적용',()=>{doc.schools=[...selected];persist();renderControls();d.close();}),action('취소',()=>d.close()));}
 async function excludePopup(){const {d,body,footer}=popup('중복 제외할 모의고사 선택'),selected=new Set(doc.excludeExamIds);body.append(node('p','선택한 모의고사의 모든 유형에서 사용한 문항을 제외합니다. 현재 모의고사 안의 공유는 허용합니다.','hint'));const exams=await listAll();if(!d.isConnected)return;for(const e of exams.filter(e=>e.id!==doc.id)){const row=node('label'),check=node('input');check.type='checkbox';check.checked=selected.has(e.id);check.onchange=()=>check.checked?selected.add(e.id):selected.delete(e.id);row.append(check,document.createTextNode(e.title));body.append(row);}footer.append(action('제외 대상 적용',()=>{doc.excludeExamIds=[...selected];persist();renderControls();d.close();}),action('취소',()=>d.close()));}
 function renderControls(){controls.replaceChildren();formLoader({controls,getDraft:()=>doc,node,action,config,user,persist,render:()=>{},message,edit:editForm});const title=field(controls,'시험지 이름',doc.title);title.oninput=()=>{doc.title=title.value;persist();};
  const countBox=node('div','','filters');controls.append(node('h3','A형·B형 문항 구성'),countBox);for(const [kind,k,label]of [['A','choice','A형 객관식'],['B','choice','B형 객관식'],['B','written','B형 서술형']]){const n=field(countBox,label,doc.counts[kind][k],'number');n.min=1;n.max=100;n.onchange=()=>{doc.counts[kind][k]=Number(n.value);persist();renderCards();};}
  controls.append(node('h3','모든 유형에 적용할 공통 난이도'),node('p',difficultyMapping,'hint'));const ratios=node('div','','filters'),inputs={};controls.append(ratios);for(const [k,label]of [['low','하 비율 (%)'],['middle','중 비율 (%)'],['high','상 비율 (%)'],['targetAverage','목표 문항 난이도 평균']]){const input=field(ratios,label,doc.profile[k],'number');input.min=0;input.max=k==='targetAverage'?10:100;input.step=k==='targetAverage'?0.01:1;inputs[k]=input;input.onchange=()=>{if(k==='targetAverage'){const p=model.profileForTarget(Number(input.value));doc.profile={...p,targetAverage:Number(input.value)};}else{const low=Math.max(0,Math.min(100,Number(inputs.low.value)||0)),high=Math.max(0,Math.min(100-low,Number(inputs.high.value)||0)),middle=Math.max(0,Math.min(100-low,Number(inputs.middle.value)||0));doc.profile=k==='middle'?{low,middle,high:100-low-middle}:{low,middle:100-low-high,high};doc.profile.targetAverage=model.profileAverage(doc.profile);}for(const key of Object.keys(inputs))inputs[key].value=doc.profile[key];persist();renderCards();};}
  const picks=node('div','','actions');picks.append(action('출처 학교 선택',schoolPopup),node('span',doc.schools.join(', ')||'선택한 학교 없음'),action('중복 제외할 모의고사 선택',excludePopup),node('span',doc.excludeExamIds.length+'개 선택'));controls.append(picks,node('p','설정 변경은 다음 출제에 적용됩니다. 생성된 유형은 재출제 버튼을 누를 때까지 문항·배치를 유지합니다.','hint'));
 }
 function renderCards(){cards.replaceChildren(node('h3','개별 유형'));for(const v of doc.variants){const card=node('section','','panel mock-variant');card.dataset.variantId=v.id;const names=curriculum.leaves.filter(u=>v.units.includes(u.id)).map(u=>u.title);let detail='범위 미설정';if(names.length)detail=names.slice(0,4).join(', ')+(names.length>4?` 외 ${names.length-4}개 세부 단원`:'');card.append(node('strong',v.label),node('span',detail),node('span',v.paper?`${v.paper.items.length}문항 생성됨`:'미출제'));const actions=node('div','','actions');actions.append(action('시험범위 설정',()=>scopePopup(v.id)),action(v.paper?'이 유형 재출제':'이 유형 출제',()=>generate([v.id])));if(v.paper)actions.append(action('배치·출력',()=>layoutPopup(v.id)));actions.append(action('유형 삭제',()=>{doc.variants=doc.variants.filter(x=>x.id!==v.id);persist();renderCards();}));card.append(actions);if(v.paper){let current;try{current=mock.rulesFor(doc,v,v.paper.rules.excludeIds);}catch{}if(!current||JSON.stringify(current)!==JSON.stringify(v.paper.rules))card.append(node('p','설정이 변경되었습니다. 생성된 시험지는 이전 조건을 유지하고 있습니다.','hint'));}cards.append(card);}
  const add=node('div','','actions');for(const kind of ['A','B'])add.append(action(kind+'형 추가',()=>{mock.addVariant(doc,kind,crypto.randomUUID());persist();renderCards();}));cards.append(add);
 }
 async function openEditor(body,paper,onChange,{sortAutomatic=false}={}){let localHandle;await examEditor({...ctx,root:body,examId:'new',chosen:[],rows:async()=>[],save:()=>{},initialLoad:{sortAutomatic},embedded:{draft:paper,onChange,setHandle:h=>localHandle=h}});return localHandle;}
 async function layoutPopup(id){const v=doc.variants.find(v=>v.id===id),{d,body,footer}=popup(v.label+' 배치·출력',true);let next=structuredClone(v.paper);handle=await openEditor(body,next,p=>next=p);const h=handle;footer.append(action('배치 적용',()=>{if(!h?.ready())throw Error('현재 배치 준비가 끝난 뒤 적용하세요.');const paper=h.getDraft();if(paper.items.length!==v.paper.items.length||paper.items.some(i=>!v.paper.items.some(old=>old.questionId===i.questionId&&old.revisionId===i.revisionId)))throw Error('문항 구성이 바뀌어 배치를 적용하지 않았습니다.');v.paper=paper;persist();d.close();renderCards();}),action('닫기',()=>d.close()));}
 async function generate(targetIds,{previewOnly=false}={}){
  if(busy)return;if(!targetIds.length)throw Error('출제할 유형을 추가하세요.');if(!doc.title.trim())throw Error('시험지 이름을 입력하세요.');targetIds.forEach(id=>mock.rulesFor(doc,doc.variants.find(v=>v.id===id)));
  busy=true;abort=new AbortController();const controller=abort,start=JSON.stringify(doc),requestDoc=structuredClone(doc),{d,body,footer}=popup(previewOnly?'후보 구성 확인':'모의고사 출제 중');const progress=node('p','같은 시점의 문항과 제외 대상을 읽는 중입니다.');body.append(progress);const cancel=action('취소',()=>{controller.abort();d.close();});footer.append(cancel);d.addEventListener('close',()=>controller.abort(),{once:true});
  try{
   const snapshot=await rpc('bank_mock_snapshot',{s:config.spaceId,schools:requestDoc.schools,exclude_exams:requestDoc.excludeExamIds},{signal:controller.signal});
   if(controller.signal.aborted)return;progress.textContent=`${snapshot.candidates.length}개 후보에서 유형별 조건과 공유 조합을 계산 중입니다.`;
   const selection=await composeInWorker(null,null,{signal:controller.signal,request:{document:requestDoc,snapshot,targetIds}});
   if(!selection.complete){result.replaceChildren(node('h3','출제 조건 확인'));for(const f of selection.failures){result.append(node('h4',f.label),node('p',compositionFailureText(f),'error'));if(f.crossCounts){const table=node('table'),head=node('tr');for(const text of ['난이도','객관식 후보','서술형 후보'])head.append(node('th',text));table.append(head);for(const [band,counts]of Object.entries(f.crossCounts)){const row=node('tr');for(const text of [({low:'하',middle:'중',high:'상'})[band]||band,counts['선택형']||0,counts['서술형']||0])row.append(node('td',String(text)));table.append(row);}result.append(table);}if(f.scopeAllocation)for(const group of f.scopeAllocation.groups)result.append(node('p',`${group.title}: 목표 ${group.roundedTarget} / 후보 ${group.available} · 서술형 목표 ${group.roundedWrittenTarget??0} / 후보 ${group.writtenAvailable}`,'hint'));}result.append(action('다른 학교 추가',schoolPopup));d.close();return;}
   if(previewOnly){result.replaceChildren(node('p',`현재 후보에서 ${targetIds.length}개 유형 구성이 가능합니다. 서로 다른 문항 ${selection.sharing.distinct}개. 실제 출제 시 새 스냅샷으로 같은 기준을 다시 검사합니다.`));d.close();return;}
   // Prepare every targeted paper before one atomic replacement. Old papers
   // stay untouched even when a later question/image/layout fails.
   for(const [i,update]of selection.updates.entries()){
    if(controller.signal.aborted)return;progress.textContent=`${requestDoc.variants.find(v=>v.id===update.id).label} 문항·수식·그림·배치 준비 (${i+1}/${selection.updates.length})`;
    const stage=node('div','','mock-staging');root.append(stage);try{const h=await openEditor(stage,update.paper,()=>{},{sortAutomatic:true});if(controller.signal.aborted)return;if(!h?.ready())throw Error('문항 또는 그림·배치 준비에 실패했습니다. 기존 결과는 유지했습니다.');update.paper=h.getDraft();}finally{stage.replaceChildren();stage.remove();}
   }
   if(controller.signal.aborted||!root.isConnected)return;if(JSON.stringify(doc)!==start)throw Error('설정이 변경되어 출제 결과를 적용하지 않았습니다.');const next=mock.apply(doc,selection);sessionStorage.setItem(key,JSON.stringify(next));doc=next;persist();renderCards();const s=selection.sharing;result.replaceChildren(node('p',`총 ${s.total}문항 배치 · 서로 다른 문항 ${s.distinct}개 · ${s.optimal?'작은 후보 집합의 최대 공유 확인':'조건 내 공유 개선 (최대 공유 보장 아님)'}`));d.close();
  }catch(e){if(e.name!=='AbortError'){progress.textContent=e.message;result.replaceChildren(node('p','출제 실패: '+e.message+' 기존 시험지는 유지했습니다.','error'));cancel.textContent='닫기';}}
  finally{busy=false;abort=null;}
 }
 renderControls();renderCards();buttons.append(action('추가 유형 출제',()=>generate(doc.variants.filter(v=>!v.paper).map(v=>v.id)),true),action('전체 재출제',()=>generate(doc.variants.map(v=>v.id))),action('후보 구성 확인',()=>generate(doc.variants.map(v=>v.id),{previewOnly:true})),action('모의고사 저장',save,true),action('저장된 모의고사',()=>navigate('mock-exams')));if(!baseline)persist();
 const observer=new MutationObserver(()=>{if(!root.isConnected||!controls.isConnected){abort?.abort();observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});
}
